### ISSUE TITLE
Parser: Unify "special" tag(s) logic to work more like the rest of the parser base

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#100]
Right now we special case a whole bunch of tags such as `"script", "text", "<!--", "<!*", "<?"` etc. and they drastically affect the state of the parser.  Due to their impact I've had to create some pretty ugly code to get "tag blocks" working in Razor.  We should revamping this part of the state machine to be more consistent.

**Comment by Eilon** [comment]
Let's look at this as part of the rewrite work.

**Comment by rynowak** [comment]
Moving this out as we're largely not messing with the parser.
