### ISSUE TITLE
C# Variables in Razor Style Blocks Break Intellisense

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Razor#1004]
## Issue
In a Razor page, using a variable inside a `<style>` block breaks intellisense.

## Example 
```
@{ var border = "1px solid #000"; }

<style>
    .border-single { border: @border }
</style>
```
This will cause all intellisense to quit working within  `<style></style>`

### Note
I posted this before, but with the changes in the repo process I didn't want it to get lost. I think this is a critical usability bug.

**Comment by Eilon** [comment]
@NTaylorMullen does this seem like a Razor tooling thing that we own, or an issue in VS?

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Tooling#1006

**Comment by NTaylorMullen** [comment]
VS razor editor issue.
