### ISSUE TITLE
Fix single line Razor text to work with TagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#101]
With the new TagHelper's they require Markup blocks to be "more" than just strings of markup. Currently if you do:

```
@: <p>Hello World</p>
```

The parser doesn't accurately detect the HTML after the `@:` and therefore doesn't enable TagHelpers for the p tags within the line.

**Comment by rynowak** [comment]
Punting this forever unless we get strong feedback
