### ISSUE TITLE
Remove RazorIRVisitor<TResult>

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1021]
We haven't found a use for this yet, and it's adding boilerplate to all of our node classes.

It's likely we'll never use this because we're doing immutable data structures in the IR.

**Comment by reaction1989** [comment]
@rynowak Do you mean this class: RazorIRNodeVisitor<TResult>?

**Comment by rynowak** [comment]
No, I mean this class https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Evolution/Intermediate/RazorIRNodeVisitorOfT.cs#L6

**Comment by ajaybhargavb** [comment]
319c53522459af509e3c238739ef5997ca565531
