### ISSUE TITLE
"using System.Threading.Tasks" in generated C# can cause compilation errors

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/Razor#1028]
SDK 1.0.0-rc4-004771
Similar to https://forums.asp.net/t/2093143.aspx

If I have a model class named `Task` like this:
```c#
namespace WebApplication1.Models {
    public class Task {
    }
}
```

and then import my `Models` namespace in a view:
```
@using WebApplication1.Models
```

then I get the compilation error "The return type of an async method must be void, Task or Task<T>" near
```c#
public override async Task ExecuteAsync()
```

I understand that this occurs because the `Task` type name is not fully qualified in the generated code:
```c#
[Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
public Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }

#line hidden
#pragma warning disable 1998
public override async Task ExecuteAsync()
```

Hence the question: shouldn't the code generator always use fully-qualified names to avoid such situations?

**Comment by NTaylorMullen** [comment]
Yes it should. Thanks for the issue @AlekseyMartynov!

**Comment by ajaybhargavb** [comment]
This is fixed in `Microsoft.AspNetCore.Razor.Evolution`. https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Evolution/RazorEngine.cs#L95
