### ISSUE TITLE
Remove workaround for missing documentation in OOP host

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1032]
See https://github.com/dotnet/roslyn/issues/12770

There's not yet support for XML documentation in the OOP host so we're working around the problem by adding the documentation when the descriptors get back to VS. When documentation is available in OOP, then we can remove this workaround.

**Comment by rynowak** [comment]
This will be unblocked when we have some 15.3 builds to try.

**Comment by NTaylorMullen** [comment]
82323456ee7d8d39603254e14ea6c1523e331214
