### ISSUE TITLE
Unable to hit enter after @addTagHelper directive

### ISSUE THREAD

**Issue by NickCraver** [aspnet/Razor#1045]
This is a weird one. The editor basically acts as if the enter key doesn't work immediately following this helper.

VS 2017 Build: 15.0.0+26288.0
Repo: https://github.com/MiniProfiler/dotnet/
File: [samples/Samples.AspNetCore/Views/Shared/_Layout.cshtml](https://github.com/MiniProfiler/dotnet/blob/4270b7fb8756a4284702d6f63069e7089945a428/samples/Samples.AspNetCore/Views/Shared/_Layout.cshtml)

When adding a directive like this (no quotes):
```c#
@addTagHelper *, MiniProfiler.AspNetCore.Mvc
```
If your cursor is at the end of the line right after the `c`, the enter key just doesn't work. It has no effect, no new line is inserted. The key command goes into a black hole of an uncaring cosmos never to return.

#### Workarounds
- Add a space, then hit enter
- Use the quoted form: `@addTagHelper "*, MiniProfiler.AspNetCore.Mvc"`

Apologies if this is a duplicate, I couldn't find anything on it and just came across it today.

**Comment by NickCraver** [comment]
Doh, found the dupe thanks to @scottaddie: https://github.com/aspnet/Tooling/issues/945 Closing this and linking back, tooling is the more appropriate place it seems.

**Comment by pranavkm** [comment]
> The key command goes into a black hole of an uncaring cosmos never to return.

❤️ it

**Comment by NTaylorMullen** [comment]
Re-opening until we verify that this is only a tooling issue.

**Comment by rynowak** [comment]
Let's debug this and see if our code gets called

**Comment by ajaybhargavb** [comment]
This is being tracked here https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=369170&triage=true

**Comment by rynowak** [comment]
This has been fixed in on the non-OSS side. Please verify 👍
