### ISSUE TITLE
Change ported Razor tests that dynamically add a prefix to use @tagHelperPrefix

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1059]
We didn't use `@tagHelperPrefix` in test files in the past because the logic to understand `@tagHelperPrefix` wasn't in the core of Razor. Now that it is, we should make sure our tests properly verify that `@tagHelperPrefix` works as a part of a Razor file.

**Comment by rynowak** [comment]
a570139b080b1f9aef10fa79bf27ad12d0c00f0c
