### ISSUE TITLE
Razor compilation error w/ 1.0 tooling

### ISSUE THREAD

**Issue by TrexinanF14** [aspnet/Razor#1062]
I have two projects, both targeting net46. One project has all of the aspnet code, the other acts as a host for the first project (basically, the second calls the first's program main). Running the first project works as expected, running the second works fine except for razor compilation, which bails out with a CompilationFailedException which I've included below. 

### Details
The csproj file for the two projects are largely duplicates of each other, the only difference being the references. This scenario worked fine before I converted from project.json -> csproj.

```
2017-03-08 11:48:43.8796 http://localhost:5000/login HTTP: Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
fknf50n3.b5g(4,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
fknf50n3.b5g(5,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
fknf50n3.b5g(6,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
fknf50n3.b5g(9,36): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
fknf50n3.b5g(10,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
fknf50n3.b5g(12,45): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
fknf50n3.b5g(31,16): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
fknf50n3.b5g(31,16): error CS0518: Predefined type 'System.Object' is not defined or imported
fknf50n3.b5g(31,41): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
fknf50n3.b5g(31,110): error CS0518: Predefined type 'System.Void' is not defined or imported
fknf50n3.b5g(33,16): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
fknf50n3.b5g(33,16): error CS0518: Predefined type 'System.Object' is not defined or imported
fknf50n3.b5g(33,41): error CS0234: The type or namespace name 'IUrlHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
... 
```

### Reproduction
This should recreate the issue on v1.0.1 of the cli:
https://github.com/TrexinanF14/razor-compilation-error

**Comment by NTaylorMullen** [comment]
Hmm, I'm not getting your error when run from VS 2017: 
![image](https://cloud.githubusercontent.com/assets/2008729/23720009/41326df4-03f2-11e7-9de9-913af68b0cfa.png)

**Comment by TrexinanF14** [comment]
Just to double-check, you're running the second, host project?

**Comment by NTaylorMullen** [comment]
Ah, so the problem you're having is you're using another runnable applications startup bits to boot your `host` application. You can fix the issue by copying the tmp.deps.json to the host output folder or having the host project boot itself.

**Comment by TrexinanF14** [comment]
Sorry, just to avoid confusion:
With dotnet cli v1.0.1, I pull down the repo above, I restore and build the /tmp project and the /host project, then dotnet run /host. I can also replicate this behavior on a fresh copy of windows 10.

![untitled](https://cloud.githubusercontent.com/assets/7518016/23769208/a6b5c780-04dc-11e7-9cf4-4175754cf404.png)

**Comment by Eilon** [comment]
@TrexinanF14 have you tried using @NTaylorMullen 's solution? If that doesn't work, please let us know what happened and which commands you ran. Thanks!

**Comment by TrexinanF14** [comment]
Yes, that did it, thank you. This felt like a pretty arcane solution, are there docs around on how razor finds its dependencies? A quick googling and a glance around this repo didn't yield much.

**Comment by rynowak** [comment]
@TrexinanF14 sorry we never answered your last question here.

The short answer is that Razor doesn't look for your dependencies, MVC does. MVC will primarily look in the "compilation context" also known as the depsfile. This is produced by default for web applications, and tells us what set of assemblies the project is compiled against.
