### ISSUE TITLE
Decouple errors for TagHelpers from type name

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#1072]
From https://github.com/aspnet/Razor/pull/1054#discussion_r104775920

Since TagHelperDescriptors are no longer tied to type name, we need to use DisplayName instead of type name in all our error messages for TagHelperDescriptors.

@NTaylorMullen

**Comment by rynowak** [comment]
This could move out to 2.1.0 so it will.

**Comment by rynowak** [comment]
Pulling this in, I ended up needing to do it while decoupling the builders from types and property names

**Comment by rynowak** [comment]
This was fixed by 853b458893b01458ef3df1f2045c7c4dec35f5fc
