### ISSUE TITLE
Razor editor with new tag helpers extension blocks on the following scenario

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Razor#1083]
_From @javiercn on March 14, 2017 18:13_

Repro steps:
<input type="hidden" asp-for="value" ...
go to asp-for and type @ after the opening quotes.
asp-for="@ value"

The editor blocks and the error message says 
![image](https://cloud.githubusercontent.com/assets/6995051/23915725/231c8dd6-08a7-11e7-8ee2-8f46fdccf083.png)

_Copied from original issue: aspnet/Tooling#1018_

**Comment by NTaylorMullen** [comment]
Any context on this guy @mlorbetske? Was it investigated and found to be a Razor issue?

**Comment by rynowak** [comment]
@mlorbetske @NTaylorMullen did we ever resolve this?

**Comment by NTaylorMullen** [comment]
> @mlorbetske @NTaylorMullen did we ever resolve this?

I haven't heard anything.

**Comment by rynowak** [comment]
I'm pulling this into sprint 3 as an investigation. Please work with @javiercn to figure this out.

**Comment by NTaylorMullen** [comment]
Can't reproduce.
