### ISSUE TITLE
Escape @ in form tag returns empty.

### ISSUE THREAD

**Issue by alexandretperez** [aspnet/Razor#1090]
I'm working with VueJs in my .cshtml file.

The short syntax to attach an event in Vue is "@eventName". 
@ is also used by Razor, so I need to escape it using @@.

When I write:
`<div id="app" class="container" @@click="doSomething">`

The html is perfectly rendered as:
`<div id="app" class="container" @click="doSomething">`

But this seems not to work in a form tag.
When I write:
`<form action="/" method="post" @@click="doSomething">`

The html rendered is:
`<form action="/" method="post">`

@@click in this case is completly ignored.

This issue occurs only in .NET Core.

For now, I'm using an another syntax.

**Comment by NTaylorMullen** [comment]
@alexandretperez do you have TagHelpers applying to your page?

**Comment by alexandretperez** [comment]
Hi @NTaylorMullen,

No, I don't have any TagHelpers on my page.

Just a simple HTML.

**Comment by NTaylorMullen** [comment]
@alexandretperez it's working for me. Could you share a repro project?

**Comment by rynowak** [comment]
Closing due to response.
