### ISSUE TITLE
TagHelperBinding needs to include more information

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1092]
It would be great if `TagHelperBinding` included more information:

- What was the tag?
- What was the tag helper prefix?
- Maybe some info about the attributes?

**Comment by rynowak** [comment]
Also TagHelperBinding should not be in Legacy 👍

**Comment by rynowak** [comment]
It turns out that tooling uses this type directly. This is going to be a breaking change for them.

**Comment by NTaylorMullen** [comment]
As part of this also going to make `TagHelperDescriptorProvider` non-legacy. This'll involve renaming it to `TagHelperBinder`

**Comment by NTaylorMullen** [comment]
5504a4765bdcaaa02ec0fe54ca63cc077e404737
