### ISSUE TITLE
Fix FileSystemRazorProject to accurately handle absolute paths.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1106]
Today the [FileSystemRazorProject](https://github.com/aspnet/Razor/blob/6fbbd5d148b71b4329cd371aa7d28cc8ba4ea329/src/Microsoft.AspNetCore.Razor.Evolution/FileSystemRazorProject.cs) doesn't entirely fulfill the purpose of handling absolute pathed Razor projects. This is needed so tooling can create Razor projects that work in their absolute pathed world.

**Comment by ajaybhargavb** [comment]
Close?

**Comment by NTaylorMullen** [comment]
c07759996fae51563a07d8034d978583b030a410
