### ISSUE TITLE
Track recent breaking changes in `exceptions.net*.json` files

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#1107]
This repo contains untracked breaking changes. To find and address them
1. Revert 6fbbd5d
2. Run `.\build.cmd /t:Pack` in projects 6fbbd5d touched or `.\build.cmd /t:Package` in the repo root
3. Update `exceptions.net45.json` and `exceptions.netcore.json` to track the changes
4. If not already announced, suggest filing issues at https://github.com/aspnet/Announcements

**Comment by dougbu** [comment]
In addition the following projects lack baselines. The details below are reformatted from a recent Universe build on the CI. (Might make sense to disable API Check for these projects until they are released to the public.)
```
[Razor\src\Microsoft.AspNetCore.Mvc.Razor.Extensions\Microsoft.AspNetCore.Mvc.Razor.Extensions.csproj]
  No baseline file for net46 found in Microsoft.AspNetCore.Mvc.Razor.Extensions.
  No baseline file for netstandard1.3 found in Microsoft.AspNetCore.Mvc.Razor.Extensions.
[Razor\src\Microsoft.AspNetCore.Razor.Evolution\Microsoft.AspNetCore.Razor.Evolution.csproj]
  No baseline file for netstandard1.3 found in Microsoft.AspNetCore.Razor.Evolution.
[Razor\src\Microsoft.CodeAnalysis.Razor.Workspaces\Microsoft.CodeAnalysis.Razor.Workspaces.csproj]
  No baseline file for netstandard1.3 found in Microsoft.CodeAnalysis.Razor.Workspaces.
[Razor\src\Microsoft.CodeAnalysis.Razor\Microsoft.CodeAnalysis.Razor.csproj]
  No baseline file for netstandard1.3 found in Microsoft.CodeAnalysis.Razor.
[Razor\src\Microsoft.CodeAnalysis.Remote.Razor\Microsoft.CodeAnalysis.Remote.Razor.csproj]
  No baseline file for net46 found in Microsoft.CodeAnalysis.Remote.Razor.
[Razor\src\Microsoft.VisualStudio.LanguageServices.Razor\Microsoft.VisualStudio.LanguageServices.Razor.csproj]
  No baseline file for net46 found in Microsoft.VisualStudio.LanguageServices.Razor.
[Razor\src\RazorPageGenerator\RazorPageGenerator.csproj]
  No baseline file for netcoreapp1.0 found in RazorPageGenerator.
```

**Comment by dougbu** [comment]
If I'm wrong and any of those packages have shipped to NuGet, baselines should be created in relevant `rel/*` branch and checked into the `dev` branch.

**Comment by rynowak** [comment]
None of these projects have shipped before but we should do the needful here to remove this noise from the build.

**Comment by NTaylorMullen** [comment]
99ff9d44a340907d0fbf60e3f230708e7dd9e6bd
