### ISSUE TITLE
Implement TagHelperCompletionService

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1120]
The Razor editor currently has in-depth knowledge of how TagHelpers apply to an HTML element, its attributes and the overall document. We should abstract this knowledge into a service.

**Comment by rynowak** [comment]
I'd also recommend here that we use separate the completion apis into their own service.

**Comment by NTaylorMullen** [comment]
22c7c90b5a158e7b38210122c781e95d496542a4

Not closing because more bits will probably flow through this.

**Comment by rynowak** [comment]
We've implemented completion for HTML elements.

The remaining work here is to implement completion for attributes.

Moving the remaining work out of preview 1.

**Comment by NTaylorMullen** [comment]
22c7c90b5a158e7b38210122c781e95d496542a4
1795fc26c124d643fa24bcf0111c7112d0a84a92
