### ISSUE TITLE
Update Microsoft.AspNetCore.Mvc.Razor.Extensions.Test to use the Razor integration testing code

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1125]
`Microsoft.AspNetCore.Razor.Evolution.Test` has good infrastructure for integration testing. We should be using that in the `Microsoft.AspNetCore.Mvc.Razor.Extensions.Test` project instead of some one-off thing.

**Comment by ajaybhargavb** [comment]
Also, we currently have a duplicate `LineMappingSerializer` in Razor.Extensions.Test. We should share the type instead.

**Comment by ryanbrandenburg** [comment]
While I'm at it I should add an integration test for razorpages which doesn't use @model as per [this](https://github.com/aspnet/Razor/pull/1140#pullrequestreview-29893512)

**Comment by rynowak** [comment]
303636db13b9fa382f17abda7ad0eaf9a7b429d2
