### ISSUE TITLE
Add tests that target the latest version of Razor.Runtime

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#1133]
_From @ajaybhargavb on October 28, 2016 19:6_

From https://github.com/aspnet/RazorTooling/pull/108#discussion_r85584480

We changed the tool to target 1.0.0 version of razor runtime. We need tests that target both 1.0.0 and 1.1.0-\* versions of Razor.Runtime to make sure the tool works in both cases.

_Copied from original issue: aspnet/RazorTooling#109_

**Comment by rynowak** [comment]
RazorTooling is obsolete now. Is there anything good still tracked by this issue?

**Comment by Eilon** [comment]
@NTaylorMullen ? If nothing, close.
