### ISSUE TITLE
how can i use taghelper IntelliSense for a aspnet core library project?

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#1136]
_From @endink on July 18, 2016 2:43_

in the library project, I use this config in project.json:

``` json
"tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final"
  },
```

but it doesn't work, how to use InterlliSense for a RazorView in Library project?
something like: 

``` html
<a asp-for="XXX">, <form asp-for>
```

_Copied from original issue: aspnet/RazorTooling#91_

**Comment by Eilon** [comment]
@endink so you have a .NET Core class library project with some CSHTML files in it and you want tag helper IntelliSense?

@NTaylorMullen @DamianEdwards is this supposed to work?

**Comment by Eilon** [comment]
_From @NTaylorMullen on July 18, 2016 17:58_

This currently isn't supported in the VS side of things or in the Razor tooling side of things. As for the question for if this should work. We do support the ability for a user to embed Razor files in a library and then compile them at runtime assuming a user has a custom file provider; therefore, I'd say we should shoot to make this work eventually.

**Comment by Eilon** [comment]
_From @ByteNuts on October 27, 2016 16:0_

If you want intellisense you can give Re-Sharper a try, since it gives custom tags and attributes intellisense.
The only thing missing is the purple and bold aspect of taghelpers, which I kind of get used to...

Is this likely to be added in future releases?

Thanks!

**Comment by Eilon** [comment]
_From @NTaylorMullen on October 27, 2016 17:19_

> Is this likely to be added in future releases?

That's our goal 😄

**Comment by rynowak** [comment]
Work here is coordinate with WTE to make sure we get this working E2E.

**Comment by NTaylorMullen** [comment]
This was completed on the WTE side.

**Comment by rynowak** [comment]
👍 For anyone watching this issue, this means it will be fixed in VS 2017 Update 3 preview 2
