### ISSUE TITLE
TagHelperDescriptorSerializationTest failures on VS

### ISSUE THREAD

**Issue by jbagga** [aspnet/Razor#1139]
All 3 tests in [TagHelperDescriptorSerializationTest](https://github.com/aspnet/Razor/blob/dev/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/TagHelperDescriptorSerializationTest.cs) class are failing with the following error in Visual Studio but not at command line.

`System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

cc @NTaylorMullen @rynowak

**Comment by rynowak** [comment]
@pranavkm - is this a binding redirect issue? I know for a fact that the test infrastructure uses JSON.NET

**Comment by pranavkm** [comment]
Yeah, seems like it. Might need to force adding binding redirects on. See https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj#L22-L23

**Comment by NTaylorMullen** [comment]
> Yeah, seems like it. Might need to force adding binding redirects on.

I thought the tests in VS weren't run on desktop, no?

**Comment by NTaylorMullen** [comment]
> I thought the tests in VS weren't run on desktop, no?

Tested this out in VS, looks like it still runs tests in desktop. That fix also worked, i'll take care of this.

**Comment by NTaylorMullen** [comment]
e6d5e2b2a99f152f0bc28634157e98e0618afca6
