### ISSUE TITLE
Add code generation tests tests for @inherits directive in Razor.Extensions

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#1142]
Currently we don't have any code generation tests that use `@inherits` directive.

cc' @NTaylorMullen

**Comment by NTaylorMullen** [comment]
There's also a possible tooling impact issue here with `@inherits` and `TModel`. Our `ModelDirective` bits update the `@inherits` token which will break IntelliSense in the editor: https://github.com/aspnet/Razor/blob/56c2d76e0334f8e2d37b7a76f9ffe34e47b4f4af/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ModelDirective.cs#L77
