### ISSUE TITLE
Simplify CSharpCodeWriter code for generating fields

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#1165]
From https://github.com/aspnet/Razor/pull/1161#discussion_r109519089

@rynowak to add more context

**Comment by rynowak** [comment]
We have a bunch of convenience methods on `CSharpCodeWriter` that are targeted at generating correct C# code for things like properties, methods, etc. We should leverage these as much as possible rather than hardcoding details like spacing and formatting into the code generator.

**Comment by rynowak** [comment]
d3e37f20ce4c3503181f5036fdafaba28b617a1d
