### ISSUE TITLE
Rename Razor.Evolution

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1169]
We need to come up with an *ahem* professional-sounding name for `Microsoft.AspNetCore.Razor.Evolution`. 

Suggestions from the previous discussion thread:
`Microsoft.AspNetCore.Razor.Engine`
`Microsoft.AspNetCore.Razor.Parser`

My cool suggestions:
`Microsoft.AspNetCore.Razor.Compiler`
`Microsoft.AspNetCore.Razor.Language`

I'm hoping to still park most of the important types in the `Microsoft.AspNetCore.Razor` namespace. 

-------------------------------

Names we can't use
`Microsoft.AspNetCore.Razor` - there are runtime bits here
`Microsoft.CodeAnalysis.Razor` - we decided against this because we don't want to bring in other Roslyn dependencies at this level.

**Comment by rynowak** [comment]
This deserves every label we can throw at it.

**Comment by rynowak** [comment]
We decided on `Microsoft.AspNetCore.Razor.Language`

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/commit/0618bae3bd856eeb31f2c7b40a7be56076b63183
https://github.com/aspnet/Mvc/commit/36e272fdc2486342c341746600615213d2d7fd2f
https://github.com/aspnet/MvcPrecompilation/commit/885792e16ba6f51bd9f9f61aedbbee70a451469c
https://github.com/aspnet/Scaffolding/commit/b2bc822b219e1f246cb182e9a2a15944b385e978
https://github.com/aspnet/Coherence/commit/f6431072b283f51bb531cfd0725f407d021a5793
