### ISSUE TITLE
Modify existing Optimizers to understand TagHelperBlock's

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#117]
We have a `TagHelperParseTreeRewriter` that rewrites `MarkupBlock`'s into `TagHelperBlock`'s but our `ConditionalAttributeCollapser` and `WhiteSpaceRewriter` do not understand `TagHelperBlock`'s.  We need to change them to handle the `TagHelperBlock`'s correctly.

As an interim fix we'll run the `TagHelperParseTreeRewriter` after the other optimizers to avoid conflicts.

**Comment by Eilon** [comment]
Closing for now, but will revisit in vNever.
