### ISSUE TITLE
DirectiveTokenDescriptor should be (sealed or abstract) and immutable

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1172]

**Comment by Yves57** [comment]
Why not simply a struct to reduce pressure on the GC?

**Comment by rynowak** [comment]
We expect about 20 of these to exist ever..  a struct might be suitable or not depending on where the design ends up.

**Comment by rynowak** [comment]
b17e506ce83007bddd7838e9a71958bc002f7660
