### ISSUE TITLE
Implement error recovery for directive tokens

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1173]
We're not strict enough with error detection for directive tokens - for example
```
@custom global::Some_Namespace
```

If the `custom` directive expects a namespace, it will parse the `global` token, and then fail because the `::`Some_Namespace` token remains. If instead, another token was part of the directive that could consume this text, it was parse correctly.

So, that means that tokens are allowed to run together, and we don't prevent it today.

We also need to implement error recovery for tokens universally.

**Comment by NTaylorMullen** [comment]
This is blocked on https://github.com/aspnet/Razor/issues/1412 being completed.

**Comment by NTaylorMullen** [comment]
22060a15dc7f6eb37df3ee0b700b112b98b36fbe
