### ISSUE TITLE
Add TagHelper completions API to TagHelperFactService.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1181]
Today we expose several APIs that control the binding of TagHelpers to a given HTML element based on the tag name and presence of attributes; we should own the entire completion API.

**Comment by rynowak** [comment]
The title of this is jankified. This would be a new, completion-focused service.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/commit/a1cfd22a3273ed1b9aca8cb7a3639cb9edc8a32a
