### ISSUE TITLE
Add multi-targeting support to RazorTemplateEngineFactoryService

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1183]
When we create a RazorTemplateEngine it should a version of the Razor codegeneration support that matches the project's dependencies. We have the ability to generate ASP.NET Core 1.X code for 1.X proejcts and ASP.NET Core 2.X code for 2.X projects. 

This items tracks the following improvements:
- Create a template engine with the appropriate version targeted when a new document is opened
- Update the template engine with the appropriate version when project references change
- Treat newest version as the 'fallback', if the version is unknown we just assume latest

**Comment by rynowak** [comment]
This isn't needed in Preview2

**Comment by Eilon** [comment]
@rynowak - what milestone should this be in?

**Comment by rynowak** [comment]
This is 2.1

**Comment by ajaybhargavb** [comment]
Do we have a design for it already? If not, we should discuss tomorrow.
