### ISSUE TITLE
@inject scope

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Razor#1191]
I've start to use the @inject tag to allow razor views access to scoped items the have been registered with Dependency Injection, I'm finding that when using @inject in the _ViewImports that instance is not available from within partial views.

I would have thought that _ViewImports would be accessible from all view/partial views; is there a way to use @inject and apply a scope to the instance ? what is the impact on code generated ?

**Comment by NTaylorMullen** [comment]
@grahamehorner Is your partial view a sibling or a grandchild to where your `_ViewImports.cshtml` lives?

**Comment by rynowak** [comment]
Closing due to lack of response
