### ISSUE TITLE
Razor adding indentation after @ when typing '@using html.BeginForm()'

### ISSUE THREAD

**Issue by TheConservativeCoder** [aspnet/Razor#1199]
Hi,

I'm finding that razor is adding an indentation after the @ when typing ```@using Html.BeginForm()``` in a VB.NET MVC Web Application. This can be recreated by creating a new empty VB.NET Web Application with MVC references and then add a new controller and view and then type ```@using Html.BeginForm()``` into the new view and press enter and you will see it then indents after the @.

![razorbug2](https://cloud.githubusercontent.com/assets/264872/24865630/c2c1ca78-1dff-11e7-8412-e870aea14691.gif)

**Comment by boomtopper** [comment]
Have also posted this onto the visual studio developer community 
https://developercommunity.visualstudio.com/content/problem/42335/razor-adding-indentation-after.html

**Comment by rynowak** [comment]
If this is an issue with `.vbhtml` then VS feedback is the right place to track it. This repo is for ASP.NET Core Razor, which doesn't include `.vbhtml`
