### ISSUE TITLE
Razor should require directives appear at the start of the line

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#1201]
Right now, an occurence of `@page` (or any other directive for that matter) anywhere in the page causes it to be treated as a directive. e.g. 

```
@{
   var @using = "crowbar";
}

You cannot use an @using indoors.
```

The generated code looks like:

```C#
WriteLiteral("\r\nHello ");
using
```

**Comment by ajaybhargavb** [comment]
Shouldn't this change be in Mvc that uses the api added in https://github.com/aspnet/Razor/issues/1195?

**Comment by rynowak** [comment]
Both, MVC should use the new API, and this should be a parsing error.

**Comment by pranavkm** [comment]
We should check the devolution parser behavior, but I think it required directives to start at the start of a line. Right now, any token that looks like a directive anywhere in the page is treated as one which would be a breaking behavior change.

**Comment by NTaylorMullen** [comment]
0688cd3ef73ea50999e7a95aa53a12e7e03f3e93
3b53f045186b735d28955064cabd21717b0aee68

**Comment by NTaylorMullen** [comment]
@rynowak didn't see you moved this to preview3 until after merge. Let me know if you want me to back it out

**Comment by ajaybhargavb** [comment]
Looks like we missed re-enabling this test https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/PageDirectiveTest.cs#L48

**Comment by NTaylorMullen** [comment]
So one thing that's different about ^ test is that it expects the page directive to not be there. How we decided to fix this issue was to still let the page directive exist BUT file an error. 

Are we ok with `TryGetPageDirective` returning the page directive if it's in an invalid state? That means when a user access' the page they'll get the logged error.

**Comment by rynowak** [comment]
> Are we ok with TryGetPageDirective returning the page directive if it's in an invalid state? That means when a user access' the page they'll get the logged error.

We should decide how we want this to work at a Razor level, and then allow MVC to live in that world.

Reopening this because there's still a skipped test.

**Comment by NTaylorMullen** [comment]
I think we should detect the page directive, log an error and then be on our merry way (how it exists currently). With that approach a user will be able to see that they made a mistake when accessing the page.

**Comment by Eilon** [comment]
@rynowak please do the needful.

**Comment by rynowak** [comment]
@pranavkm - this is all cleaned up now right?

**Comment by pranavkm** [comment]
With the way it works now, we've introduced a breaking change for users using the term `@page` in their regular Mvc views. For instance, consider
```c#
@{
   var page = "User Page";
    ViewData["title] = page;
}

<ul class="nav-bar"><li>Home -> </li><li>@page</li></ul>
```
This results in a parser exception stating "The 'page` directive must appear at the start of the line.". IMO, the right fix would be to only treat it as a directive if it is at the start of a line rather than parse it regardless and warn \ error. If we do choose to keep this behavior, I think we need a separate breaking change announcement stating all directives are now non-contextual keywords.

**Comment by rynowak** [comment]
> all directives are now non-contextual keywords

We were always fine with this choice, and we were fine with choosing `@page` as a new non-contextual keyword.

**Comment by pranavkm** [comment]
Cool. In which case we can close this item. I think the keyword thing deserves an announcement.
