### ISSUE TITLE
Change inherits, section and functions to be addable components.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1203]
Today Razor's `CSharpCodeParser` has a default set of extensible directives that it lights up. These include, `inherits`, `functions` and `section`. We should repurpose these guys to look like other directive registrations. Aka in MVC we have a single class that encompasses all the functionality of `@model`.

**Comment by rynowak** [comment]
Parking this in the backlog for now, I don't think it's important for preview 1.

**Comment by rynowak** [comment]
Moving into preview 2

**Comment by rynowak** [comment]
2d52f2
