### ISSUE TITLE
Move TagHelperDescriptorProvider out of legacy

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1209]
It's the primary API to determine what are TagHelpers. We even use it in the TagHelperFactsService..

**Comment by rynowak** [comment]
This needs to be redesigned, and is already tracked elsewhere

**Comment by rynowak** [comment]
Not happening for preview 1

**Comment by rynowak** [comment]
There's no real tooling impact of this change, since tooling now uses a service to get tag helpers

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/issues/1289
