### ISSUE TITLE
Generated code is not marked as auto-generated.

### ISSUE THREAD

**Issue by JosefPihrt** [aspnet/Razor#1215]
Generated code in class such as `public class _Foo_cshtml : Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>` should be marked as auto-generated.

Otherwise it is exposed to roslyn analyzers which is not desirable.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/5957.
