### ISSUE TITLE
TModel placeholder at design time causes errors when @model isn't fully qualified

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1222]
For `@model LoginViewModel` we generate `using TModel = LoginViewModel`. This is invalid, the type has to be fully qualified in the using statement but not in the model statement. Instead we should have the `TModel` always use System.Object.

**Comment by rynowak** [comment]
Go ahead and fix this one 👍

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/commit/01bb6326de2b8d3ac1f91d98675ed283555af584
