### ISSUE TITLE
Razor does not correctly parse HTML attributes that have spaces surrounding the equals

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#123]
After playing around with the parse tree a bit I noticed that if you were to create HTML elements such as:
```
<div class   =     "foo"></div>
<div class   ="foo"></div>
<div class=    "foo"></div>
```

The Razor parser does not generate an accurate syntax tree (which is used to generate correct "dynamic" attribute code) that can pull the full attribute value out of the HTML output if the inner condition results to false.

Once this has been added we should also support this attribute syntax in Tag Helpers.

**Comment by yishaigalatzer** [comment]
Consider porting back to fix https://aspnetwebstack.codeplex.com/workitem/2149 when this gets fixed

**Comment by ChrisKlug** [comment]
According to the W3.org spec, you are not supposed to be allowed to have a space between the attribute name and = though. Should it still allow that? If it is just a matter of getting the HtmlMarkupParser to accept spaces before and after the = character, I might be able to help out with that if you want me to?

**Comment by NTaylorMullen** [comment]
@ChrisKlug the HTML5 spec allows it. See: http://www.w3.org/TR/html-markup/syntax.html#syntax-attr-double-quoted

>
A double-quoted attribute value is specified by providing the following parts in exactly the following order:
>
1. an attribute name
1. zero or more space characters
1. a single "=" character
1. zero or more space characters
1. a single """ character
1. an attribute value
1. a """ character

**Comment by ChrisKlug** [comment]
You are absolutely correct. I read the http://www.w3.org/html/wg/drafts/html/master/syntax.html#attribute-name-state state-handling wrong. I guess I should stop questioning things now... :)

**Comment by NTaylorMullen** [comment]
Note place for reaction: https://github.com/aspnet/Razor/commit/4c5f9c5360830b52f28aade2447a7e73e44ea39b#diff-58782e50bed88f4f2f70af4835346999R476

**Comment by ajaybhargavb** [comment]
08c8f9f7ba6f9b48d93a4c6ea407a698fb94e4d8
