### ISSUE TITLE
Consider not providing catch-all IntelliSense to existing completions.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1230]
Today our `DefaultTagHelperElementCompletionService` will mark every completion with a catch-all `TagHelper` if it exists. Aka you get a massive list of `TagHelper`ified elements:
![image](https://cloud.githubusercontent.com/assets/2008729/25054029/c7404c06-210f-11e7-9f7e-5fc6e0564913.png)

This is consistent with how `TagHelper` IntelliSense has worked in the past but it doesn't seem useful. It might be better to exclude catch-all based `TagHelper`s entirely from IntelliSense completion. This way a catch-all `TagHelper` that has required attributes will only light up when its required attributes have been satisfied. It also means we wont be polluting the completion lists with excess amounts of `TagHelper`s.

**Comment by rynowak** [comment]
@DamianEdwards - do you have an opinion on this behavior?

**Comment by DamianEdwards** [comment]
Agree with @NTaylorMullen. I'm assuming the attributes on said Tag Helpers **will** still show up though, yes?

**Comment by rynowak** [comment]
Ok. I'm going to slot this into preview-2. For preview-1 we're going to have the behavior Dev14 had here.

**Comment by NTaylorMullen** [comment]
> I'm assuming the attributes on said Tag Helpers will still show up though, yes?

Yes.

**Comment by NTaylorMullen** [comment]
e87011f77fb5d287cf7548c64c393115d94bb242
