### ISSUE TITLE
Razor cshtml view doesn't see new property on model

### ISSUE THREAD

**Issue by clement911** [aspnet/Razor#1236]
I just had a weird issue after deploying my asp.net core app to azure app service (on full .net 4.6.1).

One of my views Shell.cshtml is using a strongly typed model:
`@model NitroCharts.Web.AppModel`

And one of the deployed changes was the addition of a new property `IsProduction` to that model. It ran fine locally however when I deployed it to the azure service, the cshtml file couldn't 'see' the new property, which resulted in a compile error. This was a massive issue because no one could load the site anymore...

What can cause the cshtml view to somehow hang on to an old version of the deployed assembly??? I tried restarting the app service but that didn't help...
The weird thing is that the model and the cshtml are in the same project, the top level asp.net core project, so they must have been deployed...

Am I missing something here???

Shell.cshtml:
...
`@if (Model.IsProduction)`
...

```Error from Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred: One or more compilation failures occurred: /shopify/Shell.cshtml(26,16): error CS1061: ‘AppModel’ does not contain a definition for ‘IsProduction’ and no extension method ‘IsProduction’ accepting a first argument of type ‘AppModel’ could be found (are you missing a using directive or an assembly reference?)```

I use VS 2017 and use web deploy for deployment.
Any help would be much appreciated...
Here are the asp.net core packages:
```<PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="1.0.0-beta-000019" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
```

My csproj has `<PreserveCompilationContext>true</PreserveCompilationContext>`. What does this do?

**Comment by ajaybhargavb** [comment]
@pranavkm could this be an issue with precompilation?

**Comment by clement911** [comment]
FYI I tried another deploy and the same thing happened again.

**Comment by pranavkm** [comment]
@clement911 do you have `MvcCompileViewsOnPublish` in your application (you're not referencing the view compilation package which makes it seem unlikely)?

**Comment by clement911** [comment]
No. How does pre-compilation work? Is there a way to flush the cache?

Here is my entire web project .csproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>NitroCharts.Web2</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>NitroCharts.Web2</PackageId>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Include="App.config" />
    <None Update="wwwroot\**\*;_content\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <ProjectReference Include="..\NitroCharts.Domain\NitroCharts.Domain.csproj" />
    <ProjectReference Include="..\ShopifyLib\ShopifyLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DistributedLock" Version="1.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="1.0.0-beta-000019" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="1.3.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="1.3.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.1" />
    <PackageReference Include="Microsoft.Net.Http" Version="2.2.29" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
    <PackageReference Include="Sendgrid" Version="6.3.4" />
    <PackageReference Include="ShopifySharp" Version="3.6.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.3.0" />
    <PackageReference Include="System.Interactive" Version="3.1.1" />
    <PackageReference Include="System.Interactive.Async" Version="3.1.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.1" />
    <PackageReference Include="System.Reactive.Linq" Version="3.1.1" />
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
    <PackageReference Include="System.ValueTuple" Version="4.3.0" />
    <PackageReference Include="TimeZoneConverter" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="_misc/prePublish.bat" />
  </Target>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

</Project>
```

**Comment by pranavkm** [comment]
@clement911 - precompilation is enabled by referencing the package and setting the property I listed earlier so that's clearly not the case here. Mvc in AspNetCore caches the result of compilation in memory so once you restart your app, there really isn't any cache to flush.

Is there a way for you to determine if the application's binary (presumably NitroCharts.Web2.dll) got updated as part of deployment (For instance via Kudu - https://blogs.msdn.microsoft.com/benjaminperkins/2014/04/01/get-azure-website-deployment-logs-from-kudu/)?

**Comment by clement911** [comment]
I know it has been updated because the logs are showing messages that didn't exist before.
In other words, it's like the dll was deployed, but the old one is still being picked by Razor...

**Comment by clement911** [comment]
It's actually NitroCharts.Web2.exe because how asp.net creates an .exe and not a dll...

**Comment by pranavkm** [comment]
@davidebbo have you seen other reports of an error like this? I can't think of a reason the views would continue to be compiling against stale binaries.

**Comment by davidebbo** [comment]
@pranavkm I'm guessing you didn't mean me?

**Comment by pranavkm** [comment]
I did mean you 😄. The issue apparently occured as part of deploying a desktop targeting Mvc application to Azure App Services. We don't have any disk caching for view compilation in AspNetCore, so I can't think of a good reason why the app's executable might have updated (per @clement911), but it ends up being stale when we do our runtime compilation. 

Just curious if you've seen other folks run in to similar issues with their AspNetCore applications on App Services.

**Comment by davidebbo** [comment]
That doesn't ring a bell. On App Service, we build the app using fairly standard dotnet commands, so usually issues that happen there can be reproed locally when using the same commands.

**Comment by pranavkm** [comment]
@clement911 - are you able to reproduce this issue locally (when publishing to a local folder)? There's not much for me to go by since I can't quite reproduce your issue.

**Comment by clement911** [comment]
So I am quite puzzled by this. I publish a new view this time (new controller, new cshtml file) and I had the same issue. 
The controller, which is new, ran and returned the view, but razor failed saying the model type didn't exist.
I deployed again by changing the model to be dynamic (@model dynamic) and the view rendered fine.
Somehow razor is not seeing the model types!
I tried to deploy to a local folder and configure the web site in IIS but all I get so far is "An error occurred while starting the application".

**Comment by clement911** [comment]
I just noticed that in the web deploy config screen there is a checkbox 'Remove additional files at destination', which is currently unchecked. Should I be checking this box?

**Comment by clement911** [comment]
I managed to run it locally and it works fine...
But how is this issue even possible? Does razor run in a different context with different loaded assemblies? At this point I have no choice but to type all my view models to dynamic with @model dynamic...

**Comment by clement911** [comment]
Ok so deploying with 'Remove additional files at destination' fixed the problem!
In the web deploy log I can see the a whole bunch of files were deleted, including a 'NitroCharts\refs\NitroCharts.Web2.exe' so my guess is that this is the one that razor was loading and it was probably old, where the app was loading the most recent one NitroCharts\NitroCharts.Web2.exe
I have no idea what that refs folder is but if someone can she some light that would be appreciated...

**Comment by rynowak** [comment]
The `refs` folder is the references that are used for compilation by Razor. Basically you are correct, Razor *is* in a different context. We need to preserve as much information as we can about the compilation environment so that we can compile the views later.

**Comment by clement911** [comment]
But is the issue I experienced a bug? Why were the 2 dlls out of sync?
I don't understand why Razor needs it own copy.

**Comment by rynowak** [comment]
If you had a mix of content from the `refs` folder from the current publish and from a previous one this would definitely cause issues. I'd recommend using the `Remove additional files at destination` option unless you are actually modifying assets on the server (which is kinda crazy).

The `ref` folder has the facades or reference assemblies from the BCL - these aren't another copy of the dlls, they only have the signatures. The dlls that get loaded when you run your app can be substantially different from what you compiled against (they can be broken up differently or have extra types and members). Using the `refs` makes the experience consistent between local development and compilation on the server.

**Comment by clement911** [comment]
To be honest, I didn't really get what you're saying. I guess things became more complicated recently in .net... but thanks for the explanation anyway.
Howver, note that the assembly that caused the issue and was in the ref folder was NOT from the BCL. It was my own project assembly
I don't recall checking 'Remove additional files at destination' off... I'm not sure if the default is on or off but it should probably be on by default...

**Comment by psulek** [comment]
@clement911 we experience same issue as you describe with `refs` folder. There was our own EXE from previous release (compiled for net core 1.0) and now when you upgrade to net core 1.1, bin folder has correct version of EXE but refs one has old version of EXE file. 
Should we clear 'refs' folder when deploying new version?

**Comment by pranavkm** [comment]
@psulek using the `Remove additional files at destination` option in the VS publish dialog should take care of this. If you're publishing from the cmdline, you can always `rm -r` the publish directory prior to publishing.

**Comment by psulek** [comment]
@pranavkm Thanks for suggestion. We added cmd line command to our TFS build process.
