### ISSUE TITLE
Investigate if AspNetCore.Razor.Runtime can be bumped down to a lower netstandard.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1238]
Today it targets netstandard1.5 but I'm not sure it needs to have that high of a netstandard TFM. We may be able to bump this down.

**Comment by rynowak** [comment]
This is not super relevant anymore

**Comment by AwsomeCode** [comment]
Hi @rynowak Older version of UWP does not support NETStandard 1.5
