### ISSUE TITLE
Consider making target extension interfaces public

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1245]
Today all of our specific target extension interfaces are internal, i.e. `IPreallocatedAttributeTargetExtension`. We should look over all the extensions we have and determine if we think they should stay internal or become public. This way, we can expose a well-defined code generation extension point for Razor.

**Comment by rynowak** [comment]
My opinion - preallocated attributes should stay internal. Some of the others like section should be public or even move into MVC entirely.

**Comment by rynowak** [comment]
There are 4 of these:
- Template
- Design Time Directives
- Preallocated Tag Helper Attributes
- Inject (MVC)

Of these, Template should be public, and it should not be on by default. The Template extension requires something like MVC's `HelperResult` which has no default implementation. 

I'm going to close this issue and track the changes to Template in https://github.com/aspnet/Razor/issues/952
