### ISSUE TITLE
ViewComponentTagHelper tooltips are ugly.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1251]
When looking at a tooltip for a ViewComponentTagHelper you see the generated TagHelpers name:
![image](https://cloud.githubusercontent.com/assets/2008729/25254059/7ff67258-25d8-11e7-87ac-f375197ddc54.png)

Instead we should come up with something nice for the view component taghelper tooltip.

**Comment by rynowak** [comment]
Is this tooltip coming from WTE or from the C# editor?

**Comment by NTaylorMullen** [comment]
> Is this tooltip coming from WTE or from the C# editor?

WTE consumes our `DisplayName` property on our `TagHelperDescriptor`

**Comment by rynowak** [comment]
Ok cool, this is easy to fix then.

**Comment by rynowak** [comment]
@ryanbrandenburg work with @DamianEdwards to figure out the right 'display name' for a VCTH

**Comment by NTaylorMullen** [comment]
So turns out we'll need editor fixes here. The editor is currently consuming `descriptor.Name` instead of `descriptor.DisplayName` everywhere. I'm going to fix this issue on our side and then file an external issue for the editor side.

**Comment by NTaylorMullen** [comment]
4c98b7f8f3a55648267aca5c727a1c017c7467f8

@alexgav You guys will need to move from `descriptor.Name` to `descriptor.DisplayName` in order to consume these changes.
