### ISSUE TITLE
Html.RenderPartialAsync("") shows an error in editor

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#1254]
Using VS2017 d15prerel (15.3 26423.1-Preview)

Add the following to a Razor file:
``` html
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}
```

You get a squigglie indicating the overload doesn't exist:
![image](https://cloud.githubusercontent.com/assets/249088/25365049/393f1edc-291b-11e7-9b82-04793c553390.png)

You can however "Go to definition" on the method and it finds it OK. Also, runtime works fine.

**Comment by DamianEdwards** [comment]
@NTaylorMullen @rynowak

**Comment by NTaylorMullen** [comment]
Super odd.... That extension methods exists in the same namespace as the base RenderPartialAsync method. I'll have to try it out once my VS updates.

**Comment by rynowak** [comment]
@NTaylorMullen - the error is on `RenderAsyncDelegate` in the generated code

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen - the error is on RenderAsyncDelegate in the generated code

Ooo i see. Ya gotta fix this guy.

**Comment by rynowak** [comment]
Can you figure out what the safe fix is for this for preview 1?

**Comment by NTaylorMullen** [comment]
Issue here is that our code generation is compatible with 1.0.0 Mvc but not 2.0.0 Mvc.

We render:
```C#
DefineSection("Foo", async (__razor_section_writer) => {
});
```

Which works in 1.0.0. However, in 2.0.0 our define section method looks like this:
```C#
public virtual void DefineSection(string name, RenderAsyncDelegate section)
```

Where `RenderAsyncDelegate` is:
```C#
public delegate Task RenderAsyncDelegate();
```

The most minimal fix for this for preview1 would be to create an overload to DefineSection in `RazorPage.cs` that took in a `Func<object, Task>` as its second parameter instead of `RenderAsyncDelegate`. If not, we'll have to tackle API targeting.

**Comment by DamianEdwards** [comment]
I'd vote for the minimal fix for preview1.

**Comment by rynowak** [comment]
> I'd vote for the minimal fix for preview1.

This guy right here.

Is this a pages-specific issue or do we need to fix this for pages and views?

**Comment by NTaylorMullen** [comment]
> Is this a pages-specific issue or do we need to fix this for pages and views?

Pages and Views

**Comment by rynowak** [comment]
So if I understand correctly, the fix here is to add a *dummy* `public virtual void DefineSection(string name, Func<TextWriter, Text> section)` to `RazorPageBase`. (Probably with `[EditorBrowsableNever]`)

This will be targeted by the design time codegen, but will have no purpose at runtime.

**Comment by NTaylorMullen** [comment]
> So if I understand correctly, the fix here is to add a dummy public virtual void DefineSection(string name, Func<TextWriter, Text> section) to RazorPageBase. (Probably with [EditorBrowsableNever])
> 
> This will be targeted by the design time codegen, but will have no purpose at runtime.

Exactly.

**Comment by NTaylorMullen** [comment]
IF we really wanted we could have the runtime impl do other stuff:
1. throw
2. call through to the primary DefineSection impl
3. Noop

**Comment by NTaylorMullen** [comment]
Went with option 2

**Comment by NTaylorMullen** [comment]
490f94d42553545f9cb980b8a018d141f897834c
e8c102adfbde049f758287e8f6189a916d2f8c10

**Comment by rynowak** [comment]
👍 🔥 🥈
