### ISSUE TITLE
Parameter info is not displayed automatically after typing opening parens of method invocation in Razor expression

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#1255]
When typing a Razor expression that invokes a method in the Razor editor, the parameter info is not being displayed automatically after the opening parenthesis is typed. The closing parenthesis is auto-completed however with the cursor placed inside. Manually invoking Parameter Info from the Edit menu (or KB shortcuts) shows it.

**Comment by DamianEdwards** [comment]
@NTaylorMullen @rynowak

**Comment by NTaylorMullen** [comment]
To note: This isn't a regression. The tooling has always been this way. There's a TFS issue somewhere in the deps of all the other tooling issues on this guy 😄

**Comment by DamianEdwards** [comment]
That sucks 😞 
We should dig it up and try to get it fixed.

**Comment by NTaylorMullen** [comment]
Totally still an issue, nuking the investigate label. Note: Re-typing the method invocation displays the method IntelliSense.

**Comment by rynowak** [comment]
Looking at this, it really seems odd that it's parked in 15.8. Do we know the actual cause of this? Seems worth figuring out at least what the fix would be.

**Comment by DamianEdwards** [comment]
Ya, this is still super annoying

**Comment by rynowak** [comment]
Taylor and I looked into this, and what's happening is that Roslyn starts preparing to show signature help, but then another edit gets applied, and the caret is moved **out** of the c# buffer.

This is the callstack that leads to the problem
```
>	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Retrigger() Line 140	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.OnTextViewBufferPostChanged(object sender, System.EventArgs args) Line 11	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(object sender, System.EventHandler eventHandlers)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BufferGroup.RaiseEvents()	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BufferGroup.FinishEdit()	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.SpanEdit.ReplaceSpans(int position, int spansToReplace, System.Collections.Generic.IList<object> spansToInsert, Microsoft.VisualStudio.Text.EditOptions options, object editTag)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.ReplaceSpans(int position, int spansToReplace, System.Collections.Generic.IList<object> spansToInsert, Microsoft.VisualStudio.Text.EditOptions options, object editTag)	Unknown
 	Microsoft.Html.Editor.dll!Microsoft.Html.Editor.Projection.ViewProjectionManager.UpdateViewBuffer(Microsoft.Html.Editor.Projection.LanguageProjectionManager langManager)	Unknown
 	Microsoft.Html.Editor.dll!Microsoft.Html.Editor.Projection.ViewProjectionManager.RemoveLanguageBuffer(Microsoft.Html.Editor.Projection.LanguageProjectionManager langManager)	Unknown
 	Microsoft.Html.Editor.dll!Microsoft.Html.Editor.Projection.LanguageProjectionManager.SetMappingsHelper(Microsoft.Html.Editor.Projection.ProjectionMapping[] mappings, string fullLangBufferText)	Unknown
 	Microsoft.Html.Editor.dll!Microsoft.Html.Editor.Projection.LanguageProjectionBuffer.SetTextAndMappings(string text, Microsoft.Html.Editor.Projection.ProjectionMapping[] mappings)	Unknown
 	Microsoft.VisualStudio.Web.Editors.Razor.4_0.dll!Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator.SetTextAndMappings(System.Collections.Generic.List<Microsoft.Html.Editor.ContainedLanguage.Razor.RazorRange> newCodeRanges)	Unknown
 	Microsoft.VisualStudio.Web.Editors.Razor.4_0.dll!Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator.OnDocumentStructureChanged.AnonymousMethod__0()	Unknown
 	Microsoft.Web.Editor.dll!Microsoft.Web.Editor.Utility.GuardedOperations.InvokeExtensionPoint(object errorSource, System.Action action)	Unknown
 	Microsoft.VisualStudio.Web.Editors.Razor.4_0.dll!Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator.OnDocumentStructureChanged(object sender, Microsoft.VisualStudio.Editor.Razor.DocumentStructureChangedEventArgs e)	Unknown
 	Microsoft.VisualStudio.Editor.Razor.dll!Microsoft.VisualStudio.Editor.Razor.DefaultVisualStudioRazorParser.OnDocumentStructureChanged(object state)	Unknown

```

This means that the partial parser isn't accepting the parentheses, and is causing a reparse, which will dirty the buffers.

A fix for this would be to update our edit handler code to accept parentheses immediately following a c# expression rather than triggering a reparse.

**Comment by rynowak** [comment]
We're getting some improvements on this feature for 15.7 but there will still be some problems. 

I have a partial fix that enables signature help in implicit expressions. 

Enabling signature help in explicit expressions and code blocks is more involved and will require more risky changes, so I'm splitting it out for now.

The editor doesn't properly colourize signature help in Razor: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/533660

**Comment by rynowak** [comment]
This is heavily dependent on https://github.com/aspnet/Razor/issues/2211

**Comment by NTaylorMullen** [comment]
af63afdae713f6eb4126eb1f2e70c7ff9061e7b4
