### ISSUE TITLE
Replace RazorEditorParser

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1259]
We should modernize the API for `RazorEditorParser`

We need to 'Roslyn-ize' this API and get rid of our janky `ITextBuffer` types and things like that.

Strawman:
```
    public abstract class RazorEditorWorker
    {
        public abstract State Current { get; }

        public abstract Task ParseAsync(TextChange change);

        public abstract class State
        {
            public abstract SourceText Text { get; }

            public abstract RazorSyntaxTree SyntaxTree { get; }

            public abstract RazorCSharpDocument CSharpDocument { get; }
        }
    }
```

**Comment by rynowak** [comment]
For preview2 the work item here is to move this and other `.Legacy` types into the `Microsoft.VisualStudio.LanguageServices.Razor` assembly

**Comment by rynowak** [comment]
5a1090f3240aa50bf1930a6f928d755047ef279e removes this component from 2.0.0. Don't worry! It's still there in the rel/15.3 branch. We'll bring it back in the next foundational update.

**Comment by NTaylorMullen** [comment]
f8d43853f89b7ebbc71d6e4d3b65b00126f768e2
