### ISSUE TITLE
Support Char properties better on Tag Helpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#126]
We want by default to be able to support char literals

``` html
    <foo bar="c" />
```

Currently you have to type

``` html
    <foo bar="'c'" />
```

With tag helpers we also need to be able to opt-out of the projected single quote's that characters imply in-case a user wants to provide a variable.

Example where the attribute `initial` is a character property.

``` C#
public class User
{
    public char Initial { get; set; }
}
```

```
@model User

@{
    var customUser = new User
    {
        Initial = 'J'
    };
    var userInitial = 'J';
}

<userTagHelper initial="J" />
<userTagHelper initial="@userInitial" />
```

In this example we're overloading the `initial` attribute to allow variable based values intead of being projected into single quotes.

The first input generates a value for the `initial` attribute value as follows:

``` C#
userTagHelper.Initial = 'J';
```

The second input generates a value for the 'for' attribute as follows:

``` C#
userTagHelper.Initial = userInitial;
```

Essentially it allows a user to opt out of the default single quotes.

**Comment by Eilon** [comment]
Zero demand for this, so closing.

cc @DamianEdwards FYI.
