### ISSUE TITLE
Roslyn-ize all of our VS MEF services

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1260]
We should make these into `ILanguageService`-based components. Most of the work here will be on the WTE side to flow the workspace through different components.

We will need to stage this:
1. Add new APIs
2. Push this to VS
3. Allow WTE to integrate these
4. Remove old APIs

**Comment by NTaylorMullen** [comment]
aa980fc67c72743694b004bc5dd29869c41281fd
