### ISSUE TITLE
[Question] Is there a way to disable text transformation for non-English characters?

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Razor#1285]
I have the part below inside my Razor view file which is being used by ASP.NET MVC Core:

```
<title>Yurtdışı</title>
```

This is in Turkish and has two weird characters: `ı` and `ş` and Razor renders this as below:

```
<title>Yurtd&#x131;&#x15F;&#x131;</title>
```

Not sure exactly what causes this (e.g. an encoding setting, etc.) but I am interested in the SEO impact of this. Any thoughts on the SEO impact and why Razor does this?

Also, is it possible to disable this behavior if I want to?

**Comment by rynowak** [comment]
Hi @tugberkugurlu - this is part of the HTML encoder which lives in dotnet/CoreFx, but we get through DI

I think the docs here https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting#customizing-the-encoders describe how to customize what characters will be encoded.

/cc @blowdart in case he wants to explain why we do this

**Comment by rynowak** [comment]
Closing this out since it was answered. Please let us know if you need anything else
