### ISSUE TITLE
Reduce the number of IR nodes related to TagHelpers

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1323]
Get rid of CreateTagHelperIRNode, InitializeTagHelperFields, ExecuteTagHelperIRNode

**Comment by ajaybhargavb** [comment]
1efcdafa450cdae1478de6695d6ee31957909152

**Comment by ajaybhargavb** [comment]
Related follow up https://github.com/aspnet/Razor/issues/1368
