### ISSUE TITLE
Review Properties on all public Tag Helper IR Nodes

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1329]
My notes from review of all of our IR:

**General**

- [x] Want to consider a rename from FooIRNode -> FooIntermediateNode
- [x] Can we get rid of `AccessModifier` where it appears?

**Preallocated Nodes** 

- [x] Move to .Extensions namespace (still internal)

**Using**
- [x] UsingStatement -> UsingDirective (a using statement is something else altogether)

**Tag Helper**
- [x] Should have tag helper descriptors

**Tag Helper Body**
- [x] Should have tag helper descriptors

**Set Tag Helper Property**
- [x] Needs lots of love
- [x] Should not have a type name
- [x] Can we get rid of property name (redundant)?
- [x] Can we get rid of attribute name?

**DeclareTagHelperFieldsIRNode**
- [x] Can we delete it?

**Checksum**
- [x] Can we delete it?

**AddTagHelperHtmlAttributeIRNode**
- [x] Better name?

**Comment by rynowak** [comment]
My notes from review of all of our IR:

**General**

Want to consider a rename from FooIRNode -> FooIntermediateNode
What things need a source besides tokens? where is it used?

Can we get rid of `AccessModifier` where it appears?

**Preallocated Nodes** 

Move to .Extensions namespace (still internal)

**Using**
- UsingStatement -> UsingDirective (a using statement is something else altogether)

**Tag Helper**
- Should have tag helper descriptors

**Tag Helper Body**
- Should have tag helper descriptors

**Set Tag Helper Property**
- Needs lots of love
- Should not have a type name
- Can we get rid of property name (redundant)?
- Can we get rid of attribute name?

**DirectiveIRToken**
- Can we get rid of it and use regular token?

**DeclareTagHelperFieldsIRNode**
- Can we delete it?

**Checksum**
- Can we delete it?

**AddTagHelperHtmlAttributeIRNode**
- Better name?

**Comment by rynowak** [comment]
@ajaybhargavb - let's divide and conquer to make these a reality.

**Comment by ajaybhargavb** [comment]
> What things need a source besides tokens? where is it used?

From a preliminary investigation, here is what I found. Note: this is not an exhaustive list.

Nodes | Reason
------|------
UsingDirectiveIRNode, CSharpExpressionIRNode, InjectIRNode, CSharpCodeIRNode,, CSharpCodeAttributeValueIRNode, CSharpExpressionAttributeValueIRNode and a few more I may have missed | Needs source to build line pragma
DirectiveIRNode | We use the FilePath from Source for some special stuff. Eg: namespace directive https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/NamespaceDirective.cs#L94
HtmlAttributeIRNode and HtmlAttributeValueIRNode | We use the source to write the prefix and suffix location for BeginWriteAttribute method Eg: `BeginWriteAttribute("class", " class=\"", 126, "\"", 142, 2);`Similarly for the value node.
