### ISSUE TITLE
ViewComponentTagHelperPass should use ExtensionIRNodes for code generation

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#1368]
The remaining work here is to implement a custom node (or reuse existing nodes) for the **generated ITagHelper** class that is created by the VCTH pass.

Right now this is just a blob of code and should be cleaned up.

**Comment by rynowak** [comment]
Stealing this.

**Comment by rynowak** [comment]
Moving this to 2.1, no public API impact.

**Comment by ajaybhargavb** [comment]
655a693e4a0566da4745d9a33dd0471c404f51b8
