### ISSUE TITLE
Support symbol data bound attributes in HTML

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#137]
Examples that we may need to support:

```HTML
<ul ng-repeat<="items">...</ul>
<button click+="doSomething()">Click Me</button>
<input value&="firstName">
<ul [ng-repeat|item]="items"></ul>
<button (click)="doSOmething()">Click Me</button>
```

These are just some, in general we should implement an attribute parsing approach that revolves around the '=' sign and less about the content around it.

Ultimately this showcases an issue with Razor where it expects attributes to be *exactly* in the form: `attributeName="attributeValue"` where the double quotes are optional.  Adding spaces or anything else around the = causes attribute parsing issues.  That specific issue is listed here: https://github.com/aspnet/Razor/issues/123

**Comment by Eilon** [comment]
Need to update this issue with the most recent Angular 2 syntax.

We would most likely treat the entire LHS as the "name" of an attribute in tag helper cases, e.g. `(click)` would be the attribute name.

In the more general Razor case the key goal is to just not have parser errors on these and to reliably echo the output into the HTML stream.

**Comment by NTaylorMullen** [comment]
After some research and testing. Here's the syntax angular 2 seems to enable:

```HTML
<ul [item]="items"></ul>
<ul [(item)]="items"></ul>
<button (click)="doSOmething()">Click Me</button>
<button (^click)="doSOmething()">Click Me</button>
<template *something="value"></template>
<div #local></div>
<div #local="value"></div>
```

Out of the supported syntaxes, the ones that currently aren't supported by Razor:

```HTML
<ul [item]="items"></ul>
<ul [(item)]="items"></ul>
<template *something="value"></template>
```

When working on this issue I'm going to investigate what it'll take to just get Razor allowing the full HTML5 spec of attribute names:
> Attribute names must consist of one or more characters other than the space characters, U+0000 NULL, """, "'", ">", "/", "=", the control characters, and any characters that are not defined by U

**Comment by NTaylorMullen** [comment]
7239eb015c708e3e03eecd3c6785c595b8b8d938
