### ISSUE TITLE
Improve tag helper runtime code generation

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#1371]
We now create the `TagHelperExecutionContext` using `TagHelperScopeManager.Begin(...)`. And we use that context to add attributes, initialize tag helpers etc. This make things complicated in terms of code generation and also makes it order dependent.
Instead we could have a `ExecutionContextBuilder` which can have multiple methods to add the tag helper body, attributes etc and this will all be a lot more flexible. Sample,
```c#
__InputTagHelper = CreateTagHelper<global::InputTagHelper>();
ecBuilder = `TagHelperExecutionContextBuilder.Create()`;
ecBuilder.AddBody(() => { });
ecBuilder.AddTagHelper(__InputTagHelper);
ecBuilder.AddHtmlAttribute(__tagHelperAttribute_0);
```

@NTaylorMullen, please add to this if I missed something.

**Comment by rynowak** [comment]
I don't feel like we have a strong reason to do this for 2.0.0 and it seems a little too speculative to really keep the workitem around.

I propose closing this as "good idea but nah". Any objections?

**Comment by ajaybhargavb** [comment]
I agree that it's a little too late to do this for 2.0.0 at this point but I don't think we should close the issue. We could backlog this and revisit later. Maybe future us won't find this as speculative. IMO, It'll just be completely forgotten if we close the issue.

**Comment by rynowak** [comment]
> Maybe future us won't find this as speculative. 

That's not enough reason to keep a bug around. We should have open issues for things that we definitely plan to do in the future (backlog) or are doing in the near future (current + next milestone). Anything else is noise.


> IMO, It'll just be completely forgotten if we close the issue.

I think it's fine if we forget this specific idea.

We're likely to revisit all of the codegen pieces again in the future, and when we do we'll come up with fresh ideas.
