### ISSUE TITLE
Update to latest Roslyn to support C# 7.1

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#1385]
Updated compiler packages are available for your consumption:
1. Find your favorite package in the [myget Roslyn gallery](https://dotnet.myget.org/gallery/roslyn), 
1. Pick a version that looks like 2.3.0-beta3-* (for example 2.3.0-beta3-61723-04).

Once we reach RTM, version 2.3 release packages will get published to nuget.org.

What’s new? 
In addition to bug fixes, the features included in the new compilers (C# 7.1, VB 15.3): 
- C#: async Main, “default” literal, inferred tuple names, pattern-matching with generics
- C# and VB: support emitting ref assemblies (MSBuild and IDE support will be after 15.3)
- VB: inferred tuple names

**Comment by rynowak** [comment]
8f299c5b113a61000414f1c58ed77a854c5d7aa7
