### ISSUE TITLE
We should lazy initialize annotations instead of having an empty ReadOnlyItemCollection

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#1390]
Right now we lazy initialize annotations for some nodes but not others like https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/Intermediate/CSharpStatementIRNode.cs#L19. We should just do this for all IR nodes.

**Comment by rynowak** [comment]
Generally the nodes that have lazy init are because they allocate. The nodes that dont' lazy-init don't support adding annotations and thus use a zero-alloc collection

**Comment by NTaylorMullen** [comment]
@rynowak Why wouldn't all of our nodes support annotations?

**Comment by rynowak** [comment]
There are some cases where we thought there was no scenario for it (tokens mostly). We can revisit.

**Comment by rynowak** [comment]
I'm putting this in the backlog unless one of you wants to fight for it. 🥊

**Comment by NTaylorMullen** [comment]
453ccd9649eec67f8f222785874e77010afe4c19
