### ISSUE TITLE
Discussion: Razor directives must appear at start of line.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1392]
Razor directives must now be written at the start of the line (whitespace insensitive).

The following are all still **valid**:
```HTML
@model Person
    @inject SignInManager Manager

<p>
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
</p>
```

However, these use-cases are now **invalid**:

```HTML 
@DateTime.Now @model Person
<p> @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
</p>
```

**Comment by wizarrc** [comment]
I'm a bit surprised it was allowed before. I like the change.

**Comment by MaximRouiller** [comment]
Wait... it was possible? 😆

**Comment by clarkis117** [comment]
I never got this working before now I can't do it, Sad! :shipit:

**Comment by scheshan** [comment]
@clarkis117 
Maybe this still works in ASP.NET MVC.
