### ISSUE TITLE
View appears to be modified while debugging

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Razor#1397]
Putting a breakpoint in some code that is triggered by a view, I double click on the View execution step in the stack trace, which opens the view.

At that point if I try to resume the stack (Continue/F5) then this message appears:

![image](https://cloud.githubusercontent.com/assets/1165805/26693833/591bc0ea-46ba-11e7-95b6-78954d49e3c8.png)

Clicking Edit won't let me continue either, but show an error message in the Error List : "Adding 'namespace' will prevent the debug session from continuing."

Closing the view from VS will let me continue the debugging session.

**Comment by NTaylorMullen** [comment]
Closing in favor of a more detailed repro issue (duplicate): https://github.com/aspnet/Razor/issues/1464
