### ISSUE TITLE
Invalid ViewComponent definition breaks tag helper discovery

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1399]
This code breaks tag helper discovery in 15.3

```
namespace WebApplication1.ViewComponents
{
    public class PriorityListViewComponent : ViewComponent
    {
        private readonly ToDoContext db;

        public PriorityListViewComponent(ToDoContext context)
        {
            db = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(
        int maxPriority, bool isDone)
        {
            var items = await GetItemsAsync(maxPriority, isDone);
            return View(items);
        }

        private Task<List<TodoItem>> GetItemsAsync(int maxPriority, bool isDone)
        {
            return db.ToDo.Where(x => x.IsDone == isDone &&
                                 x.Priority <= maxPriority).ToListAsync();
        }
    }
}
```

It's throwing an exception:
```
Microsoft.CodeAnalysis.Razor.ViewComponentTagHelperDescriptorFactory.GetInvokeMethodParameters(INamedTypeSymbol componentType)
   at Microsoft.CodeAnalysis.Razor.ViewComponentTagHelperDescriptorFactory.CreateDescriptor(INamedTypeSymbol type)
   at Microsoft.CodeAnalysis.Razor.DefaultTagHelperResolver.VisitViewComponents(Compilation compilation, IEnumerable`1 assemblyNameFilters, List`1 results)
   at Microsoft.CodeAnalysis.Razor.DefaultTagHelperResolver.GetTagHelpers(Compilation compilation, IEnumerable`1 assemblyNameFilters)
   at Microsoft.CodeAnalysis.Razor.TagHelperResolver.<GetTagHelpersAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.Razor.RazorLanguageService.<GetTagHelpersAsync>d__1.MoveNext()
```

This definition is not actually wrong:

```
public async Task<IViewComponentResult> InvokeAsync(int maxPriority, bool isDone)
```

So there are two bugs here.
1. We think this is wrong (already fixed in 2.0.0)
2. We throw exceptions (already fixed in 2.0.0)

**Comment by rynowak** [comment]
We need to fix this for the VS 15.3 release. 

Note that this is already fixed in `dev` and in `2.0.0/preview-2` https://github.com/aspnet/Razor/blob/rel/2.0.0-preview2/src/Microsoft.CodeAnalysis.Razor/ViewComponentTagHelperDescriptorFactory.cs

This is an error now, but doesn't throw an exception.

**Comment by DamianEdwards** [comment]
@rynowak is this the right milestone? Where does this work need to happen?

**Comment by rynowak** [comment]
This will happen in the `rel/15.3` branch along with the two other tooling bugs we fixed today 👍

**Comment by DamianEdwards** [comment]
OK, so which package version will it ship in, if any?

**Comment by rynowak** [comment]
None. This is a VS-only fix.

This code was rewritten during preview 2 and this bug was (unknowingly) fixed at that time. 

We branched for VS stabilization over a month ago so lots of things have been cleaned up and refactored since thing.

**Comment by DamianEdwards** [comment]
OK, I'll create a separate milestone for it then and put it in there.

**Comment by rynowak** [comment]
> We branched for VS stabilization over a month ago so lots of things have been cleaned up and refactored since thing.

Also, we all know this isn't an ideal situation... It's the reality to having two simultaneous ship cycles.

**Comment by NTaylorMullen** [comment]
f5ecb9ee60db0d042931a83539a289fd3f11d23a
