### ISSUE TITLE
Include currently selected attribute in TagHelper attribute completion results.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1401]
Today in our TagHelperCompletionService if you query for attribute completions we don't take into account what attribute the user currently has selected. For example if you have the following:

`<input |type="text" value="" />`

And you invoke IntelliSense at the pipe you will have the `type` attribute included in the attribute completion but not `value` because your cursor is on `type`. With TagHelpers this doesn't happen because we remove ALL already-present attributes from the completion list. 

Fixing this would involve adding a `AttributeCompletionContext` property to represent the currently selected attribute (allowing null). The WTE folks wont be consuming the attribute completion API in 15.3 so we can make this breaking change without worry of destabilizing them.

/cc @alexgav @ToddGrun

**Comment by ajaybhargavb** [comment]
fa6fde2b202e94f6daad198d156212d7efbca729
