### ISSUE TITLE
ArgumentException when using @inherits

### ISSUE THREAD

**Issue by pavel-b-novikov** [aspnet/Razor#1402]
### Functional impact
If you try to override base page class using ```@inherits``` directive then page rendering fails in run-time with Argument exception during HTML helper contextualization:

```
ArgumentException: Property 'ViewData' is of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[WebApplication1.TestViewModel, WebApplication1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]', but this method requires a value of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
Parameter name: viewContext
```

### Minimal repro steps

0. Create .NET MVC Core app from default template (VS2017, Community Edition)
1. Create base in app's root namespace as follows:
```
public abstract class MyPage<T> : Microsoft.AspNetCore.Mvc.Razor.RazorPage<T>
{
    
}
```
2. Open ```~/Views/Home/About.cshtml``` and prepend it with the following line: ```@inherits MyPage<int>```
3. Go to HomeController, in ```About``` action change ```return View();``` to ```return View(15);```
4. Launch application 
5. Navigate to ```/Home/About```

### Expected result
Page renders as usual, replacing ```@Model``` with ```15```

### Actual result
Exception from above

### Further technical details
The root cause is Razor compiler that handles ```@inject``` directive incorrectly, generating
```csharp
[RazorInject]
public IHtmlHelper<object> Html { get; private set; }
```

instead of

```csharp
[RazorInject]
public IHtmlHelper<int> Html { get; private set; }
```

Most likely, [```ModelDirective.GetModelType```](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ModelDirective.cs#L39) returns ```"object"``` when being called from [```InjectDirective.ExecuteCore```](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/InjectDirective.cs#L35). ModelDirective's visitor [collects](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ModelDirective.cs#L147) ```@inherits``` directives but does not use them within ```GetModelType```. I could fix, but do not have enough time and afraid of break something. Even cannot write test because ```dotnet restore``` fails on Razor project for some reason :(

UPD: Issue could be outdated since it is not possible to use ```@inherits``` along with ```@model``` in version ```1.1.2```, but in current "dev" branch I [see tests](https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/ModelDirectiveTest.cs#L54) with exactly such case.

### Workarond
For example given above: ```@inject IHtmlHelper<int> Html``` explicitly

---
```dotnet --version``` returns ```1.0.3```
```Microsoft.AspNetCore.Mvc.Razor``` version is ```1.1.2```

**Comment by pranavkm** [comment]
@pavel-b-novikov this is a dup of https://github.com/aspnet/Mvc/issues/6291. We'll use the other work item for tracking since it's older.

**Comment by pavel-b-novikov** [comment]
Sorry, master. Dobby googled too bad :)

**Comment by pranavkm** [comment]
@pavel-b-novikov, here's the suggested workarounds for now:

* https://github.com/aspnet/Mvc/issues/5397#issuecomment-253253761
* https://github.com/aspnet/Mvc/issues/5397#issuecomment-253271809
