### ISSUE TITLE
Custom Relative Path In Razor

### ISSUE THREAD

**Issue by OmidID** [aspnet/Razor#1426]
Is there any possibility to have a custom relative path same as example at below:
In Razor:

`<script src="%/scripts/theme.js" type="text/javascript"></script>`

And Result:

`<script src="/themes/default/scripts/theme.js" type="text/javascript"></script>`

https://stackoverflow.com/questions/44479154/custom-relative-path-in-asp-net-core-mvc

**Comment by NTaylorMullen** [comment]
@OmidID you can create a TagHelper to enable that functionality. Could have it only apply to script tags with a src attribute that starts with `%`. A lot like how [Mvc enables `~/`](https://github.com/aspnet/Mvc/blob/1c4b0fcdf38320b2f02c0bb7c31df5bd391ace07/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L47)

**Comment by OmidID** [comment]
@NTaylorMullen Thank you so much. I have another question to understand better
if i define a class same as example at below:

```
[HtmlTargetElement("link", Attributes = "[href^='%/']", TagStructure = TagStructure.WithoutEndTag)]
[HtmlTargetElement("script", Attributes = "[src^='%/']")]
....
public class ThemeUrlResolutionTagHelper : TagHelper
{
   /*Implement tag helper here*/
}
```

Then can I have %/ for the tags that i added them in attributes?

**Comment by OmidID** [comment]
@NTaylorMullen Thank you SO MUCH. IT"S WORKING NOW
