### ISSUE TITLE
Review RazorIRBuilder

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1432]
RazorIRReference does (better) a lot of the things the builder did. Should review the builder and make it more relevant.

**Comment by rynowak** [comment]
What I'd like to do here is to make `RazorIRBuilder` internal. All of the users outside of our main lowering code are pretty trivial.

@ajaybhargavb @NTaylorMullen any objections?

**Comment by NTaylorMullen** [comment]
> @ajaybhargavb @NTaylorMullen any objections?

Sounds good to me.

**Comment by ajaybhargavb** [comment]
5e57e9f2359149ec126ab595027b93de1ceaa902
