### ISSUE TITLE
Razor code background looks wrong with Dark Theme

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Razor#1436]
**Update**
Guess what, I switched back to Light theme and it looks like it does the same thing, so I assume this is by design ;) Feel free to close then if that is the case.

This is how it looks like in Dark Theme. You can notice the gray background of the font. In a standard C# editor the background of the font and the editor blend together, but not in HTML.

![image](https://user-images.githubusercontent.com/1165805/27142739-deb44c7e-50e0-11e7-8290-6c13858db9c1.png)

Looking at the color/font options we can see that the "Default" color is selected for the background for , like all other 

![image](https://user-images.githubusercontent.com/1165805/27142803-1b4456d4-50e1-11e7-9352-31fdd36f435f.png)

However this Default is rgb(80,80,80) whereas all others are rgb(30, 30, 30) like the Dark Theme background. Changing to a custom color works fine though.

It looks like this setting should take the value from the theme instead.

This is what it looks like when "fixed", much better IMO

![image](https://user-images.githubusercontent.com/1165805/27142935-774922d4-50e1-11e7-8f6d-77e0c25538e3.png)

**Comment by NTaylorMullen** [comment]
Hmm? In light theme it doesn't blend together:

![image](https://user-images.githubusercontent.com/2008729/27145068-1a20fa0c-50e9-11e7-86dd-432929c74999.png)
