### ISSUE TITLE
Is a hook available now to pre-process markup files prior to the Razor engine going to work?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Razor#1438]
I asked back in [Discussion: Razor.Evolution and the future of Razor extensibility](https://github.com/aspnet/Razor/issues/836) ...

> If Razor.Evolution has a feature where devs can get access to the whole View file ... do the minification (or whatever other mods they want to make at compile time) ... then Razor goes to work on it 

Just wondering given that Razor had so many updates: Does the latest release of Razor (on nightly perhaps) have a processing step to hook in order to process views (the static view file content) prior to the Razor engine getting to work on them? (I mean without having to replace the Razor engine as I was doing before.)

If not, it could perhaps be something that runs with a `BeforeTargets="Build"` where views in a *Views_Debug* folder are processed into the *Views* folder. Kind'a hacky, but I'm looking for ideas like that where custom view processing code could be run on the view files before Razor goes to work.

**Comment by ajaybhargavb** [comment]
I might have misunderstood your question, but would overriding https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/RazorTemplateEngine.cs#L140 help?

**Comment by GuardRex** [comment]
```c#
var source = RazorSourceDocument.ReadFrom(projectItem);
var imports = GetImports(projectItem);

return RazorCodeDocument.Create(source, imports);
```
Excellent! Let me see what I can do with that. Thanks @ajaybhargavb!

**Comment by GuardRex** [comment]
@ajaybhargavb May I ask if you would take a look at a hack for this? It's inelegant since it's not going to work with the `inputStream` directly but instead just throw the stream into a string, hack that, then shoot it back into a stream. I just want to make sure I'm headed in the right direction and if you think I'm missing anything.

For example, this is passing my `hackedInputStream` into the `ReadFrom` with the original page file's `projectItem.Path`, so I'm worried about something like a bad `Length` or some other property from the original file that isn't going to match what I end up providing in my `hackedInputStream`.

```csharp
public class CustomRazorTemplateEngine : RazorTemplateEngine
{
    public CustomRazorTemplateEngine(RazorEngine engine, RazorProject project) 
        : base(engine, project)
    {
        Options.ImportsFileName = "_ViewImports.cshtml";
    }

    public override RazorCodeDocument CreateCodeDocument(RazorProjectItem projectItem)
    {
        if (projectItem == null)
        {
            throw new ArgumentNullException($"{nameof(projectItem)} is null!");
        }

        if (!projectItem.Exists)
        {
            throw new InvalidOperationException($"{nameof(projectItem)} doesn't exist!");
        }

        using (var inputStream = projectItem.Read())
        {
            using (var reader = new StreamReader(inputStream))
            {
                var text = reader.ReadToEnd();

                // RexHacks here!
                text = text.Replace("</body>", "<h2>HACKED!</h2></body>");

                var byteArray = Encoding.UTF8.GetBytes(text);
                var hackedInputStream = new MemoryStream(byteArray);

                var source = RazorSourceDocument.ReadFrom(hackedInputStream, projectItem.Path);
                var imports = GetImports(projectItem);

                return RazorCodeDocument.Create(source, imports);
            }
        }
    }
}
```

![capture1](https://user-images.githubusercontent.com/1622880/29005088-4c73d20c-7a99-11e7-84af-ccf317d908b3.PNG)

![capture](https://user-images.githubusercontent.com/1622880/29004899-1c7a22ee-7a95-11e7-9cdb-88be807c30ff.PNG)

**Comment by Eilon** [comment]
@ajaybhargavb please take a look.

**Comment by ajaybhargavb** [comment]
Already on it 😄

**Comment by GuardRex** [comment]
Thanks guys!

**Comment by ajaybhargavb** [comment]
@GuardRex, looks like what you have should work for runtime. But we use the [line pragmas](https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Blocks_DesignTime.codegen.cs#L35) in our design time code for the debugger to know which line to break etc. So I assume those things will break. Let me try and find if there is a more elegant solution to this.

**Comment by GuardRex** [comment]
> for the debugger to know which line to break

That might be fine ... I mean lots of devs going down this road won't want the minfication when debugging.

I was more concerned about hacking the `inputStream` leaving the original `projectItem` alone (e.g., we know the `Length` will change after minifying the markup).

**Comment by ajaybhargavb** [comment]
That should be fine then. Another thing you could try is override https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/RazorTemplateEngine.cs#L124 and have it create a `CustomRazorProjectItem` which handles the underlying stream. But you probably won't need this for your scenario.

**Comment by GuardRex** [comment]
@ajaybhargavb Excellent. Thanks. If it does :boom: :cry: at some point, I'll just come back and drop an update for others attempting this hack.

The demo for this approach is here :point_right: https://github.com/GuardRex/RazorPagesMinification

**Comment by ajaybhargavb** [comment]
> If it does 💥 😢 at some point, I'll just come back and drop an update for others attempting this hack

Absolutely! 😄
