### ISSUE TITLE
Improve DesignTimeDirectivePass

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1440]
See https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/RazorDesignTimeIRPass.cs#L13

We want this pass to run later than it does today, so that passes have a chance to implement their own design time support by removing their directive.

If you leave your directive in, then it will have auto-generated design time support.

We should also merge this with the removal pass

**Comment by ajaybhargavb** [comment]
ff433f72b88e6bab61ec530b828bd70f459da79a
