### ISSUE TITLE
Question: are MVC view compiles deterministic ?

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#1446]
_From @davidglassborow on June 12, 2017 14:21_

Roslyn can do deterministic builds (https://github.com/dotnet/roslyn/issues/372), and I've recently added this to Visual F# (https://github.com/Microsoft/visualfsharp/pull/2954).

At my workplace, this means that the MVC view compilation is the only step left in our build processes that isn't deterministic. I was wondering if the new aspnetcore view compilation will be deterministic ?, or if that is a feature you would consider adding ?

_Copied from original issue: aspnet/MvcPrecompilation#141_

**Comment by Eilon** [comment]
_From @rynowak on June 12, 2017 19:22_

No, they are not
1. We don't pass `deterministic = true` to the `CSharpCompilerOptions` - this is easy to fix
2. Each tag helper usage gets a unique identifier assigned to it, right now this isn't deterministic

**Comment by Eilon** [comment]
_From @davidglassborow on June 13, 2017 7:24_

Is this something you would be happy to add ?  If so I'll have a look at a PR to do so (probably post core 2.0 release)

**Comment by Eilon** [comment]
_From @rynowak on June 14, 2017 0:0_

> Is this something you would be happy to add ? If so I'll have a look at a PR to do so (probably post core 2.0 release)

If it adds value for you, and you want to send us a PR then sure we'd be happy to take it for 2.1. We already have the capability to replace the 'id generator' for tests, we'd just have to figure out a way to generate stable ids.

**Comment by Eilon** [comment]
Moving to Backlog, but we'd be open to a contribution for this.

**Comment by Yves57** [comment]
@Eilon @rynowak 

> Each tag helper usage gets a unique identifier assigned to it, right now this isn't deterministic

Are you thinking about a new method `public abstract string CodeRenderingContext.GetUniqueId()`? And this method could be even used for other cases in the future.

And the default implementation could be something like:
```
var uniqueId = (string)Items[SuppressUniqueIds];
if (uniqueId != null)
{
   return uniqueId;
}
_nextId++;
return $"id_{_nextId}";
```

**Comment by rynowak** [comment]
We're doing work to make Razor compilation on build support determinism. When we're done this will 'just work'

**Comment by rynowak** [comment]
As of fbb73bccd055b31037c41557ca520909bc06d213 - build-time Razor will use your project's setting for determinism

**Comment by davidglassborow** [comment]
Brilliant, thanks !
