### ISSUE TITLE
@page should look at malformed directives and attempt to classify a document as a page.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1448]
With the new Razor error story we transform malformed `@page` directives into `MalformedDirectiveIRNode`s which in turn result in pages not being classified as Razor pages. This impacts the way Mvc routes to said pages; we should be smarter and also inspect malformed directives to determine our "pageness"

**Comment by rynowak** [comment]
@NTaylorMullen - done?

**Comment by NTaylorMullen** [comment]
@rynowak nope, waiting for your review on the PR.

**Comment by NTaylorMullen** [comment]
a78202e9379728494c409c5eff378ec966dbce5e
