### ISSUE TITLE
razor generated code should have the ubiquitous auto-generated in the comments

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1449]
_From @jimmymain on June 20, 2017 12:20_

The omitted `<auto-generated/>` in the comments for code files generated by the razor engine are causing [multiple issues](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2373#issuecomment-309723230) to be raised in [other projects](https://github.com/aspnet/Tooling/issues/498).

Please could we have `<auto-generated />` added as the first line of the comments in razor generated code files. 

This will **alleviate** the **huge volume of noise** being generated in code analysis when opening *.cshtml* files.

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2373
https://github.com/aspnet/Tooling/issues/498

Perhaps also consider including `#pragma warning suppress 1591` as well. Either that, or ensure that each generated comment is XML compliant.

https://github.com/dotnet/roslyn/issues/12702

_Copied from original issue: aspnet/Mvc#6414_

**Comment by rynowak** [comment]
/cc @sharwell

So I'm hearing the feedback loud and clear about `CS1591` and XML doc related warnings.

Is there anything we can do that will get stylecop to ignore a file?

**Comment by sharwell** [comment]
You should do two things:

1. Make sure the top of the file contains a comment which starts with `<auto-generated/>`. If you want to generate more detail, e.g. the version of the tool that generated the file or a message explaining that the code will be regenerated, I can show examples of standard cases.

2. Add a `#pragma` line to disable CS1591 with a comment explaining the meaning:

    ```csharp
    // Missing XML comment for publicly visible type or member '...'
    #pragma warning disable 1591
    ```

**Comment by rynowak** [comment]
@ajaybhargavb putting on your plate for the 2.0.0 runtime release. 

I will report back about whether or not we can fix for VS 15.3.

**Comment by rynowak** [comment]
Tracking this on TFS as well with 454556

**Comment by ajaybhargavb** [comment]
rel/15.3: 582cd877bb47862112610a43c59c536c423fc3f1
dev: d73ecf8b36ec865051b5f835026d00763d7b1865
