### ISSUE TITLE
Hitting <Enter> after "@page" in a Razor page indents unnecessarily

### ISSUE THREAD

**Issue by halter73** [aspnet/Razor#1461]
![image](https://user-images.githubusercontent.com/54385/27452348-1c515fce-5747-11e7-974b-eebd95717ce7.png)

The screenshot shows the editor immediately after `<Enter>`. `<Backspace>` once puts the cursor back at the beginning of the line.

**Comment by ajaybhargavb** [comment]
f41dc2aef94e873df96b3d72acdf1c8d50bf5119

**Comment by halter73** [comment]
Finally! But aren't you supposed to be on a 🏖 right now @ajaybhargavb?

**Comment by ajaybhargavb** [comment]
Haha! No I am back starting today.
