### ISSUE TITLE
Fix .cshml compilation issue with VB project

### ISSUE THREAD

**Issue by hishamco** [aspnet/Razor#1462]
I tried few days back to create an ASP.NET Core app using VB.NET, everything (models, controller .. etc) is working fine except the compilation and rendering the views, while `vbhtml` is not support yet, is there  a workaround to make the `cshtml` compiling without an issues

I don't wanna use another view engine - which will work fine - because I really like Razor

/cc @NTaylorMullen

**Comment by pranavkm** [comment]
> is working fine except the compilation and rendering the views

What happens when you attempt to render a cshtml view?

**Comment by hishamco** [comment]
![runtimeexception](https://user-images.githubusercontent.com/3237266/27496973-f1149fcc-5860-11e7-9bfd-1f33e2e0662d.png)

FYI I tried to set the `PreserveCompilationContext` to `true` with no luck 😞

**Comment by rynowak** [comment]
@ajaybhargavb can you take a look at this and see what's going on?

**Comment by ajaybhargavb** [comment]
@hishamco, could you share a sample repro project?

**Comment by hishamco** [comment]
Any updates on this?

**Comment by TheConservativeCoder** [comment]
I'd also love to see Razor come to ASPNET Core with VB.NET even if it it is the cshtml syntax!

**Comment by rynowak** [comment]
It unfortunately would be incredibly, incredibly expensive for us to add good support for using Razor in a VB project to tooling. The project system in VS for Razor intellisense is based on the idea that we can piggyback on your app's C# project for intellisense, references, and other settings.

We're also doing some work to make the build-time integration between the project and Razor much much sophisticated. This is also going to rely on the C# msbuild targets (like the VS support does).

For these reasons we have no plans to support Razor in VB projects. Our recommendation is factor your code into a C# app and VB class library. This way if you prefer VB you can write basically everything except `Program.Main` in VB (including startup, controllers, and models).

We have an example of this kind of factoring here: https://github.com/DamianEdwards/AspNetCoreVbHybrid

@DamianEdwards - do you want to add anything?

**Comment by hishamco** [comment]
Thanks, I saw that demo few weeks back it was cool, nothing but is there any future plan to abstract Razor to support multiple languages such as VB.NET & F#?

**Comment by rynowak** [comment]
> abstract Razor to support multiple languages such as VB.NET & F#

We're focused on making the experience with C# better and bringing up parity with the C# editor.
