### ISSUE TITLE
Html.Raw breaking charset?

### ISSUE THREAD

**Issue by rudolfdobias** [aspnet/Razor#1466]
Hello,
hope this is the right place to ask.

Example speaks for itself:

     
    @{
        var text = "<strong>Příšerně žluťoučký kúň úpěl ďábelské ódy.</strong>";
    }
    
    <p>@text</p>
    <p>@Html.Raw(text)</p>

Result:

    <strong>Příšerně žluťoučký kúň úpěl ďábelské ódy.</strong>
    
    PÅ™Ã­Å¡ernÄ› Å¾luÅ¥ouÄkÃ½ kÃºÅˆ ÃºpÄ›l ÄÃ¡belskÃ© Ã³dy. (...in bold)

---

(That thing is czech typographic testing sentence)

 - The source of the text does not matter. I could be written inline or drawn from DB.
 - The file is saved as UTF-8.
 - Output.Encoding is set to UTF8Encoding
 - meta encoding too

I'm doing something wrong? Or is there another way I'm missing?

Thanks ...

// PS: Opened [this at friday on SO](https://stackoverflow.com/questions/44723728/razor-html-raw-breaks-charset), no replies so far 
// Env: OSX 10.12 and Ubuntu 14, .NET Core 1.1, Microsoft.AspNetCore.Mvc 1.1.1

**Comment by rynowak** [comment]
I just tried this out (Chrome on Windows though) and this is working fine for me.

![image](https://user-images.githubusercontent.com/1430011/27566270-0b36e7f4-5a99-11e7-84e7-d91de749e857.png)


If I view source on the document I see the following:
```
<p>&lt;strong&gt;P&#x159;&#xED;&#x161;ern&#x11B; &#x17E;lu&#x165;ou&#x10D;k&#xFD; k&#xFA;&#x148; &#xFA;p&#x11B;l &#x10F;&#xE1;belsk&#xE9; &#xF3;dy.&lt;/strong&gt;</p>
<p><strong>Příšerně žluťoučký kúň úpěl ďábelské ódy.</strong></p>
```

This is what I would expect. When using `@Html.Raw` all of the characters are passed through verbatim to the response. 

When not using `@Html.Raw` the characters that aren't in the ASCII plan get encoded to HTML entities.

-- 

If you view source do you see the same thing? What browser is this?

I'll get a chance later tonight to try this on OSX.

**Comment by rudolfdobias** [comment]
Well, I reopened the code after while and thankfully found out that I'm just an idiot. It was a nifty frontend bug - the encoding breaks within an iframe with some specific cross-origin settings.
So sorry guys for false alarm and thanks.
