### ISSUE TITLE
Question: how to get razor error on build?

### ISSUE THREAD

**Issue by mhamri** [aspnet/Razor#1475]
I updated to vs2017 and now if I have some error in the razor, vs2017 doesn't show the error on build and build will pass successfully. I need to go to the page by page to see if there is an error or not, or open all the razor page then the ReSharper catch the error, not even the visual studio.

it's a heck of a burden on the development cycle. how to catch error on the build? 

this doesn't work anymore
```XML
<MvcBuildViews>false</MvcBuildViews>
```

adding `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design` to dependencies and `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools` to cliTools doesn't help

**Comment by NTaylorMullen** [comment]
Hi @mhamri. Sadly this is not something that Visual Studio currently offers on build.

However, you could choose to pre-compile your application by publishing it. This will result in all of your views being parsed/compiled. Ensure you have the following in your csproj:
```XML
<PropertyGroup>
  <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
</PropertyGroup>
```

And a package reference (directly or indirectly) to `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation`.

Once you have these you can run `dotnet publish` at the command line to verify everything is good.
