### ISSUE TITLE
Enhancements to TagHelperDescriptorBuilders

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1477]
- [ ] Convert lots of stuff to get/set properties 
- [x] Move TypeName and PropertyName to extension methods

**Comment by ajaybhargavb** [comment]
7c7bb627b96b8c06e84baeecae81de9606b47aad

**Comment by ajaybhargavb** [comment]
9c031e6fb571a616a69d9ddccd6abfa46260b5c0
