### ISSUE TITLE
Imported @page directive should log a diagnostic.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1503]
Today if you import an `@page` directive you end up with Razor thinking a view is a "page" but then MVC doesn't detect that. We should log a diagnostic indicating that imported `@page` directives are invalid.

**Comment by pranavkm** [comment]
Couldn't we make it so that `@page` does not get imported?

**Comment by NTaylorMullen** [comment]
@pranavkm You could but then you'd have silent errors in the system. I'd rather let it be imported and indicate that it's an error when a user attempts to use that imported view.

**Comment by NTaylorMullen** [comment]
d36838ed883a84d9f85c8637c1f994c4e835086b
