### ISSUE TITLE
Razor.Language API polish

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1510]
#### General
- [x] Make `DocumentClassifierPassBase.TargetExtensions` private. - @NTaylorMullen
- [x] `IRazorEngineBuilder.DesignTime` should be getter only. - @NTaylorMullen
- [x] ~`RazorCSharpDocument.GeneratedCode` should be renamed to `Code`.~ - @NTaylorMullen - Unimportant/too cross-cutting for repos.
- [x] Rename `RazorEngineFeatureBase.ThrowForMissingEngineDependency` to `ThrowForMissingFeatureDependency` - @NTaylorMullen
- [x] Rename `RazorEnginePhaseBase.ThrowForMissingEngineDependency` to `ThrowForMissingFeatureDependency` - @NTaylorMullen
- [x] Find all instances of base / path and rename them to FilePath / BasePath - @ajaybhargavb
- [x] Abstractify `ICodeTargetBuilder`. - @ajaybhargavb
- [x] `IntermediateNodeWalker` should be indexable - @ajaybhargavb
- [x] Do a pass on all `IntermediateNode`s and cross-check the verbosity of their properties. They should be consistent which may mean having more verbose properties. - @ajaybhargavb
- [x] Unnest `IntermediateToken.TokenKind` - @ajaybhargavb
- [x] Make `TagHelperIntermediateNode.TagHelpers` an IList - @ajaybhargavb

#### HtmlConventions.InvalidNonWhitespaceHtmlCharacters - @ajaybhargavb
- [x] Make internal.
- [x] Make non-hashset.

#### LineMapping - @NTaylorMullen
- [x] Rename to `SourceMapping`.
- [x] Remove `==` and `!=` operators.

#### RazorParserOptions - @NTaylorMullen
- [x] Add `CreateDesignTime` method 
- [x] Rename `ParseOnlyLeadingDirectives` => `ParseLeadingDirectives`

#### RazorParserOptionsBuilder - @NTaylorMullen
- [x] `DesignTime` should be getter only.
- [x] Rename `ParseOnlyLeadingDirectives` => `ParseLeadingDirectives`

#### TagHelperBinding - @NTaylorMullen
- [x] Attributes should be IReadOnlyList if it makes sense.
- [x] GetBoundRules should return IReadOnlyList if it makes sense.

#### TagHelper descriptors in general - @NTaylorMullen
- [x] See if `TagHelperDescriptor.AllowedChildTags` can be IReadOnlyList
- [x] See if `TagHelperDescriptor.BoundAttributes` can be IReadOnlyList
- [x] See if `TagHelperDescriptor.TagMatchingRules` can be IReadOnlyList
- [x] See if `TagMatchingRuleDescriptor.Attributes` can be IReadOnlyList
- [x] See if `TagMatchingRuleDescriptor.Attributes` can be IReadOnlyList

**Comment by NTaylorMullen** [comment]
When working on one of these lets put our name next to the items or item header so we don't duplicate work.

**Comment by NTaylorMullen** [comment]
afa61e708016f22cbdad5cf539d34add137af291

**Comment by ajaybhargavb** [comment]
11c5293862318091dd86d07b03ad57a531954116
