### ISSUE TITLE
Instrumentation lengths generated for ExpressionBlockChunks are not always accurate

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#153]
The following scenarios lead to incorrect lengths being calculated in `RenderRuntimeExpressionBlockChunk` for instrumentation
1. Expressions with inline comments (e.g. `@(a @* comment *@ b)`) - these have multiple code spans
2. Expressions with inline templates (e.g. `@Foo(@<p>Hello world</p>)`).

**Comment by rynowak** [comment]
I'm wondering if this was already fixed by some of the work we did. Let's try to figure this out.

**Comment by rynowak** [comment]
1705888721b25832fceac8fcacfe00018efd1c32
