### ISSUE TITLE
Implement Multitargeting for MVC codegen

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1535]
This is enabling us to have Mvc version x and x+1 in the box.

**Comment by NTaylorMullen** [comment]
We will need to conditionally render `RazorViewAttribute` when generating Razor code for a 1.0.0 application.

**Comment by NTaylorMullen** [comment]
Before starting this guy, going to wait for conversations surround proposed improvements in: https://github.com/aspnet/Razor/pull/1590#issue-246644259

**Comment by ajaybhargavb** [comment]
4fcad1548ee9b222fffc72fae8bd9b641ea19824

**Comment by ajaybhargavb** [comment]
dbcac41be7ca731d07ea296423758ccfbd3bf383
