### ISSUE TITLE
Implement brace smart indent completion.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1538]
Brace completion should not be part of the core Razor syntax tree contract. For example [this](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/EditorFeatures/Core/Implementation/AutomaticCompletion/BraceCompletionSessionProvider.cs) is how Roslyn does it for CSharp.

**Comment by NTaylorMullen** [comment]
After a significant amount of investigation, decoupling brace completion from the editing loop is not currently possible without more drastic editor changes. For the time being we should implement brace completion as part of our current VisualStudioRazorParser.

**Comment by NTaylorMullen** [comment]
This depends on https://github.com/aspnet/Razor/issues/1633

**Comment by rynowak** [comment]
This is moving out to a future 15.X release. Sticking it in 2.1 until we have that scoped out.

**Comment by NTaylorMullen** [comment]
31c16af40bbe10c9fb924be559bd42955aa4e246
