### ISSUE TITLE
Span nodes are not linked outside of tests.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1547]
This means that each `Span`'s Next member is always null.

**Comment by ajaybhargavb** [comment]
@NTaylorMullen, could you give me a little more context on this? I looked at `SyntaxTreeNode` and there is no `Next` property. Am I looking in the wrong place?

**Comment by NTaylorMullen** [comment]
Sorry, this issue is misleading. I was referring to `Span`'s `Next`/`Previous` properties.

**Comment by ajaybhargavb** [comment]
f4e9ddad22f78a704317dcfcfa655bedb6a35096
