### ISSUE TITLE
Using tilde does not resolve path in data-src

### ISSUE THREAD

**Issue by bogdandanielb** [aspnet/Razor#1554]
Hello,

I'm using .NET Core SDK 1.0.0-preview2-003131, NETCoreApp 1.0.1,  Microsoft.AspNetCore.Razor.Tools 1.0.0-preview2-final.
I have the following markup in my view:

`<img src="~/style/images/logo.png" alt="" data-src="~/style/images/logo.png"  />`

Data-src is not being resolved by the Razor engine, only src. Is this by design or an issue in this version?

Thanks,
Daniel

**Comment by rynowak** [comment]
/cc @NTaylorMullen 

I believe the answer is that we leave everything in a `data-` attribute alone. If you want a workaround, use `data-src="@Url.Content("~/...")"`

**Comment by NTaylorMullen** [comment]
> I believe the answer is that we leave everything in a data- attribute alone

Yup, 100% correct.

**Comment by rynowak** [comment]
Closing since this has been answered
