### ISSUE TITLE
addTagHelper is not in completion list

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1560]
Repro:
1. File->New->Web App
2. Go to Index.cshtml
3. Start typing `@add` - completion does not display
4. Press `ctrl+space` - completion would not have addTagHelper item
![image](https://user-images.githubusercontent.com/1697911/28379087-5169c00e-6c67-11e7-9b6f-6e27e7176195.png)

/cc @NTaylorMullen

**Comment by rynowak** [comment]
This is a planned feature for 15.5 - tracked by https://github.com/aspnet/Razor/issues/291
