### ISSUE TITLE
addTagHelper does not warn when using single quotes

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1561]
Repro:
1. File->New->Web App
2. Go to Index.cshtml
3. Add 
```
@addTagHelper 'WebApplication1.TagHelpers.MyTagHelper, WebApplication1'
```
4. `'WebApplication1.TagHelpers.MyTagHelper, WebApplication1'` is highlighted as a string, no warning/error is shown, no exception at runtime but tag helper is not applied

Additionally if you don't terminated single quote you'll get `Unterminated string literal. Strings that start with a quotation mark (") must be terminated before the end of the line. However, strings that start with @ and a quotation mark (@") can span multiple lines.` at runtime and in VS, so creates illusion that it should work but doesn't

/cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
We should at the very least be raising that the `WebApplication1'` assembly could not not be loaded for TagHelper discovery.

**Comment by pakrym** [comment]
Also, things like 
```
@addTagHelper "WebApplication1.TagHelpers.MyTagHelper, WebApplication" + "1"
```

do not show any errors and are even highlighted correctly in VS
![image](https://user-images.githubusercontent.com/1697911/28379767-b76352d8-6c69-11e7-88fc-80bc528a6350.png)

**Comment by NTaylorMullen** [comment]
lmao, ya we'll need to keep all this in mind when fixing https://github.com/aspnet/Razor/issues/945

**Comment by ajaybhargavb** [comment]
aa445ee9b45d780cb1a33e0ff0f153879e5a1a4a
