### ISSUE TITLE
Higlighting output.Content in debugger shows C# error

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1562]
1. Create tag helper add it to the page and set breakpoint 
2. Run and hightlight `output.Content` when debugger hits

![image](https://user-images.githubusercontent.com/1697911/28380911-d33ea454-6c6d-11e7-8aa2-08c848e94ec4.png)

/cc @NTaylorMullen

**Comment by rynowak** [comment]
lol

**Comment by pakrym** [comment]
![image](https://user-images.githubusercontent.com/1697911/28380962-085d19f4-6c6e-11e7-8c39-60f532edd45f.png)

**Comment by rynowak** [comment]
Fixed by ce689b0449db04a9fed4250c9465d4be7beb7cc5
