### ISSUE TITLE
Hitting Enter on tag helper attribute completion does not add =""

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1563]
Repro:
1. File->New->Web App
1. Create tag helper with attributes
1. Go to Index.cshtml
1. Start typing attribute name, completion will trigger
1. Press `Enter`

Expected:
`=""` would be inserted after attribute name

Actual:
Only attribute name is inserted

![](http://i.imgur.com/HfdYwVA.gif)

**Comment by NTaylorMullen** [comment]
Is that consistent with non-taghelper html attributes?

**Comment by pakrym** [comment]
No 
![http://i.imgur.com/9tVZpcg.gif](http://i.imgur.com/9tVZpcg.gif)

**Comment by rynowak** [comment]
@NTaylorMullen likely an HTML editor issue yes?

**Comment by NTaylorMullen** [comment]
Likely yes.

**Comment by NTaylorMullen** [comment]
https://developercommunity.visualstudio.com/content/problem/90996/hitting-enter-on-tag-helper-attribute-completion-d.html
