### ISSUE TITLE
Hitting undo after del-ing starting quote in bound atrribute adds two qoutes back

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1564]
![http://i.imgur.com/uXH3CtQ.gif](http://i.imgur.com/uXH3CtQ.gif)

**Comment by rynowak** [comment]
@NTaylorMullen - this is likely an HTML editor bug yes?

**Comment by NTaylorMullen** [comment]
Yes

**Comment by NTaylorMullen** [comment]
https://developercommunity.visualstudio.com/content/problem/90986/hitting-undo-after-del-ing-starting-quote-in-bound.html
