### ISSUE TITLE
Unhelpful additional error message for empty bound tag attribute

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1565]
Repro:
1. File->New->Web App
2. Go to Index.cshtml
3. Add tag helper with `int` attribute
4. Add attribute but keep value empty

![image](https://user-images.githubusercontent.com/1697911/28382224-4b120f4e-6c72-11e7-925f-d8a5ba825c04.png)

**Comment by rynowak** [comment]
@ajaybhargavb is there something we do here to prevent the invalid codegen in this case? Let's only fix this if it's straightforward

**Comment by ajaybhargavb** [comment]
After investigation and a hacky fix in https://github.com/aspnet/Razor/pull/1604, we decided that there is no easy way to fix this without breaking intellisense.
