### ISSUE TITLE
@model directive does not show error in VS when put after markup

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1568]
But fails at runtime with
```
The 'model' directive must exist prior to markup or code
```

**Comment by NTaylorMullen** [comment]
This will be resolved once VS consumes new Razor bits.

**Comment by pakrym** [comment]
Should we keep it open to verify or there is another issue tracking?

**Comment by NTaylorMullen** [comment]
Actually, this was reverted. In newer builds of CLI we should see this not fail at runtime. I'll reopen so we can re-verify.

**Comment by rynowak** [comment]
@NTaylorMullen please verify and close

**Comment by NTaylorMullen** [comment]
This is fixed as a dup of #1555
