### ISSUE TITLE
Unable to use nested tag helpers when prefix is enabled

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1572]
Consider following tag helpers:

``` c#
    [HtmlTargetElement("grid")]
    [OutputElementHint("table")]
    [RestrictChildren("cell")]
    public class GridTagHelper : TagHelper
    {
    }

    [HtmlTargetElement("cell", ParentTag = "grid")]
    public class CellTagHelper : TagHelper
    {
    }
```

When there is no tag helper prefix everything works fine:

![image](https://user-images.githubusercontent.com/1697911/28391536-466042ec-6c93-11e7-9a93-1dd815a2946c.png)

But if I add `@tagHelperPrefix T:` there is no way to use nested `cell` as tag helper anymore because `T:cell` is not allowed by `RestrictChildren` and `cell` is not recognized as tag helper:

![image](https://user-images.githubusercontent.com/1697911/28391593-7cd1e466-6c93-11e7-8971-bf114f0b05e2.png)

Should `RestrictChildren` be considering `tagHelperPrefix` while filtering?

**Comment by NTaylorMullen** [comment]
Great find, looks like we regressed this: https://github.com/aspnet/Razor/issues/532

**Comment by ajaybhargavb** [comment]
45732a5dd38d987acbf294b2df7aea6c0f5162c4
