### ISSUE TITLE
Runtime compilation error when two taghelpers target same elements and have attribute with the same name but different type

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1573]
Not sure how common/important this scenario is.

Tag helpers:
``` C#
    [HtmlTargetElement("img")]
    public class ImgTagHelper : TagHelper
    {
        public int Width { get; set; }
    }

    [HtmlTargetElement("img")]
    public class Img2TagHelper : TagHelper
    {
        public string Width { get; set; }
    }

```

Page.cshtml
``` html
   <img width="250" />
```

Expected: each tag helper is bound according to it's property type

Actual: runtime compilation error:
```
Cannot implicitly convert type 'int' to 'string'
78.            __WebApplication1_TagHelpers_Img2TagHelper.Width = __WebApplication1_TagHelpers_ImgTagHelper.Width;
```

**Comment by rynowak** [comment]
@NTaylorMullen thoughts? Should we throw a better error?

**Comment by NTaylorMullen** [comment]
This is a super rare case. When we first built `TagHelper`s we had a custom error for this case but decided to remove it prior to RTM. Given that this is the first occurrence of this complaint I'd say leave it with the runtime only error.

**Comment by NTaylorMullen** [comment]
Closing this for now since we haven't gotten a lot of feedback on this guy. Also because the error provided isn't completely arcane 😄.

Will re-open if we get more feedback saying the current experience is not sufficient.
