### ISSUE TITLE
DefaultTagHelperContent has incorrect DebuggerDisplayAttribute

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#1580]
![image](https://user-images.githubusercontent.com/174281/28536910-fad51cd4-705d-11e7-812b-ac92585f10c2.png)

The line in question: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Runtime/TagHelpers/DefaultTagHelperContent.cs#L17. One thing we could do is standardize on `nameof` in these strings. It looks uglier (https://github.com/aspnet/Mvc/blob/b796bc0f39d08bdbf0ce36279db3148ed9c9e888/src/Microsoft.AspNetCore.Mvc.RazorPages/PageActionDescriptor.cs#L10) since you cannot use string interpolation, but it guards against these values breaking during refactoring.

**Comment by ajaybhargavb** [comment]
ce689b0449db04a9fed4250c9465d4be7beb7cc5
