### ISSUE TITLE
Formatting adds extra lines on lambda expressions inside a code block

### ISSUE THREAD

**Issue by javiercn** [aspnet/Razor#1581]
Given a code block like the one below and the current cursor position represented by "|".
```
@{

    Reviews.Reviews.Where(r => { |})

}
```
When enter is pressed, an extra line is added
```
@{

    Reviews.Reviews.Where(r => {
        |
        
    })

}
```

**Comment by rynowak** [comment]
@NTaylorMullen please investigate

**Comment by NTaylorMullen** [comment]
@javiercn can you provide more of the file? I'm not seeing an extra new line get added.

**Comment by NTaylorMullen** [comment]
Talked offline and can no longer reproduce.
