### ISSUE TITLE
Autocompletion gets in the way

### ISSUE THREAD

**Issue by miloush** [aspnet/Razor#1586]
VS 15.3.0 Preview 6

1. You want to add `else` branch:
![untitled1](https://user-images.githubusercontent.com/10546952/28746942-44c0e490-748c-11e7-9119-d7eb26039338.png)
So you start typing `else`:
![untitled2](https://user-images.githubusercontent.com/10546952/28746951-712441da-748c-11e7-9944-2ac663d1e941.png)
And press Enter for new line:
![untitled3](https://user-images.githubusercontent.com/10546952/28746963-a38c4e4c-748c-11e7-8f09-d9a420b836d4.png)

2. You want to add `@foreach (...)`:
![untitled4](https://user-images.githubusercontent.com/10546952/28746982-f480a762-748c-11e7-8a31-49d5caef236c.png)
So you start typing `foreach`:
![untitled5](https://user-images.githubusercontent.com/10546952/28747002-3bb8e720-748d-11e7-975f-10a3bac21650.png)
And press space for the space before opening parenthesis:
![untitled6](https://user-images.githubusercontent.com/10546952/28747006-66ded3ba-748d-11e7-8b06-9d0a0a72a9dd.png)

**Comment by rynowak** [comment]
@NTaylorMullen can you try to reproduce this and figure out the issue?

**Comment by NTaylorMullen** [comment]
@miloush I'm unable to reproduce this in 15.3. Could you update your VisualStudio and try again?

**Comment by rynowak** [comment]
Closing due to lack of response. Please reopen if you can provide more information to help us reproduce the problem

**Comment by miloush** [comment]
I confirm I am unable to reproduce this in 15.4.0 Preview 3 anymore.
