### ISSUE TITLE
Intellisense/coloring for tag helpers does not get updated when the tag helper gets updated

### ISSUE THREAD

**Issue by javiercn** [aspnet/Razor#1587]
Create a tag helper
Use it on a view
Update the tag helper class to add a new property o change an existing one
Go back to the view
Expectation:
Intellisense/coloring etc is updated reflecting the changes.

Actual:
Intellisense reflects the previous version (before modifications)

Workaround:
Close and open the view.

**Comment by ajaybhargavb** [comment]
Wouldn't supporting this means triggering build for every file change? Do we want to support this scenario? @NTaylorMullen

**Comment by NTaylorMullen** [comment]
This is something we eventually want to accomplish. Lots of unknowns for getting this work item completed but there are some concrete things we know:

We won't need to build for every file change. Today we utilize Roslyn's APIs that are sufficient for unbuilt C# documents. Also, we'll use their workspace APIs to determine when a TagHelper has changed and then go forth and re-gen its TagHelperDescriptor equivalent.

**Comment by rynowak** [comment]
Today this is by design. We don't need an issue tracking this as it will be a massive undertaking to change, and we won't forget.
