### ISSUE TITLE
Allow attribute taghelpers without a value

### ISSUE THREAD

**Issue by javiercn** [aspnet/Razor#1588]
Currently attribute tag helpers require a value like
```html
<p my-tag-helper="true"></p>
```

It would be good if there was no need to provide a value as it reflect more closely HTML5 style and this is already supported for properties on a tag helper just when they are not the attribute that define the tag helper

```html
<p my-tag-helper></p>
```

**Comment by NTaylorMullen** [comment]
Dup of https://github.com/aspnet/Razor/issues/431
