### ISSUE TITLE
@model does not support the C# syntax for tuple

### ISSUE THREAD

**Issue by javiercn** [aspnet/Razor#1592]
I'd like to define the model below

```Razor
@model (id, playingOn)
```

so that I can do `@Model.id` and `@Model.playingOn`

This is very useful  to easily pack more than one parameter when rendering a partial.

**Comment by rynowak** [comment]
I would not expect that to work, I would imagine you would need to do `(int id, int playingOn)` - does that work?

**Comment by ajaybhargavb** [comment]
This is currently not supported. We don't consider tuples when we parse type names in directives https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpCodeParser.cs#L960.

**Comment by rynowak** [comment]
Cool beans, let's fix it.

**Comment by javiercn** [comment]
Yeah, I forgot to update the bug. I messed up when opening it, but it doesn't work (tried again with proper syntax)

**Comment by ajaybhargavb** [comment]
8d2a9e59291df7358b62fc9e51ea21d9cfd110f6
