### ISSUE TITLE
Value generated inside html tag is surrounded by "

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Razor#1611]
A code like this:

    @{ bool hasValue = true; string value = "myvalue"; }
    <input type="radio" @(hasValue ? "value=\""+value+"\"" : "") />

generates ``<input type="radio" value=""myvalue"" />``
And

    @{ bool hasValue = true; string value = "myvalue"; }
    <input type="radio" @(hasValue ? "value="+value : "") />

generates ``<input type="radio" value="myvalue" />``

I don't really understand this behavior. Is is "by design"?

**Comment by NTaylorMullen** [comment]
Yes, this is by design to prevent dynamic values from breaking HTML unexpectedly.
