### ISSUE TITLE
IRazorDirectiveFeature/IConfigureRazorParserOptionsFeature API weirdness

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Razor#1612]
Here, only the very first `IRazorDirectiveFeature` will win:

https://github.com/aspnet/Razor/blob/184ab74e68e89836ba2de4a1006f0a95217acebb/src/Microsoft.CodeAnalysis.Remote.Razor/RazorLanguageService.cs#L43-L50

And here, only the very first `IRazorTargetExtensionFeature` will win:

https://github.com/aspnet/Razor/blob/364fc1a55d6fa47dca795491189be4c6a354974c/src/Microsoft.AspNetCore.Razor.Language/DocumentClassifierPassBase.cs#L18-L22

But here, all of the `IConfigureRazorParserOptionsFeature`s are considered, and they can all add directives:

https://github.com/aspnet/Razor/blob/cb40da4e0fc1823805e9054c8f365df1f2dc70ff/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorParserOptionsFeature.cs#L18-L21

I don't know why `RazorParserOptions` has `Directives` but not `TargetExtensions`. It seems like it be either one of two things:

- `RazorParserOptions` has both `Directives` and `TargetExtensions`, and then both `IRazorDirectiveFeature` and `IRazorTargetExtensionFeature` go away, or
- `RazorParserOptions` loses the `Directives` property, and the appropriate places that use `IRazorDirectiveFeature` and `IRazorTargetExtensionFeature` are updated to consider multiple instances of the features.

**Comment by rynowak** [comment]
> Here, only the very first IRazorDirectiveFeature will win

There's only supposed to be one, and you should never need to write your own.

> I don't know why RazorParserOptions has Directives but not TargetExtensions

TargetExtensions have no role in parsing.

> I don't know why RazorParserOptions has Directives but not TargetExtensions. It seems like it be either one of two things:

`RazorParserOptions` is not intended to follow the ASP.NET Core options pattern. It's more like the equivalent things in Roslyn. `RazorParserOptions` has directives because they are needed to parse.
