### ISSUE TITLE
Replacement of RenderAsyncDelegate in asp net core 2.0

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Razor#1619]
![image](https://user-images.githubusercontent.com/12871379/29313828-e2646f1e-81bb-11e7-9fcb-952a779826d2.png)

It seems in asp net core 2.0, RenderAsyncDelegate lose its TextWriter

What is the replacement?

**Comment by Eilon** [comment]
@NTaylorMullen @rynowak - any thoughts on this?

**Comment by NTaylorMullen** [comment]
Inside your delegate you can now utilize `PushWriter(TextWriter writer)` and `PopWriter()` to render your content to something different.

If you'd like to shim your old delegate you can do something like this:

```
@using Microsoft.AspNetCore.Mvc.Razor
@using System.IO

@functions {
    RenderAsyncDelegate CreateOldDelegate(TextWriter writer, RenderAsyncDelegate oldDelegate)
    {
        RenderAsyncDelegate newDelegate = async () =>
        {
            PushWriter(writer);
            await oldDelegate();
            PopWriter();
        };

        return newDelegate;
    }
}

@{
    var temporaryWriter = new StringWriter();
    var oldDelegate = CreateOldDelegate(temporaryWriter, () =>
    {
        WriteLiteral("<p>Hello World</p>");

        return Task.CompletedTask;
    });
}
```

**Comment by Eilon** [comment]
Oh is this the change that @ajaybhargavb made?

**Comment by Eilon** [comment]
Did we have an announcement on it?

**Comment by ajaybhargavb** [comment]
Yes https://github.com/aspnet/Announcements/issues/242. But I missed adding this to the announcement because this change was done much earlier by @rynowak. I've now updated it.

**Comment by Eilon** [comment]
Thanks! Closing this bug. If there are still issues, please reactivate or log a new issue.

**Comment by andrew-vandenbrink** [comment]
Is this efficient? 
Now I have to create new StringWriter, previously I just need to pass it to single pipe of TextWriter

**Comment by andrew-vandenbrink** [comment]
https://github.com/aspnet/Razor/issues/702

```
public static void AppendSection(this RazorPage page, string key, Func<dynamic, dynamic> text)
        {
            if (!page.SectionWriters.ContainsKey(key))
            {
                page.SectionWriters.Add(key, async () =>
                {                    
                    using (var textWriter = new StringWriter())
                    {
                        await text("").WriteAction(textWriter);
                        page.WriteLiteral(textWriter.ToString());                        
                    }                    
                });
            }
            else
            {
                page.SectionWriters[key] += async () =>
                {
                    using (var textWriter = new StringWriter())
                    {                       
                        await text("").WriteAction(textWriter);
                        page.WriteLiteral(textWriter.ToString());                        
                    }                    
                };
            }
        }
```

Usage 

```
@{
    this.AppendSection("js",@<script>
//xxxxxx        
</script>
        );
    }
```

**Comment by NTaylorMullen** [comment]
> Now I have to create new StringWriter, previously I just need to pass it to single pipe of TextWriter

We take care of setting the appropriate writer for you. So assuming your text method returns something that can be written append section code could look like:

```C#
page.SectionWriters[key] += async () =>
{              
    page.Write(await text(""));
};
```

Much simpler 😄

**Comment by andrew-vandenbrink** [comment]
This is working, notice no await
```
page.SectionWriters.Add(key, async () => page.Write(text("")));
```


These are not working
```
page.SectionWriters.Add(key, async () => await page.Write(text(""))); // Exception thrown

page.SectionWriters.Add(key, () => page.Write(text(""))); // Exception thrown
```

While page.Write is working, it use async lambda without await
The Write also working without html encoding
Something is not right

**Comment by NTaylorMullen** [comment]
Your text method should definitely be awaitable. Razor in intrinsically async which means if you're not awaiting the underlying method or .Resulting it then something's going wrong.

**Comment by andrew-vandenbrink** [comment]
![image](https://user-images.githubusercontent.com/12871379/29446871-edfd7ac0-83ee-11e7-8910-a167325fa562.png)

![image](https://user-images.githubusercontent.com/12871379/29446881-02721646-83ef-11e7-8549-5b2d71daea96.png)

It doesn't work

**Comment by NTaylorMullen** [comment]
@andrew-vandenbrink my apologies. I re-looked over how you're establishing your text delegate and found I was incorrect.

Does the following work for you:
```C#
page.SectionWriters.Add(key, () => 
{
    page.Write(text(""));
    return Task.CompletedTask;
});
```

**Comment by andrew-vandenbrink** [comment]
While it works, the page.Write write not encoded html text.... where it should be right?
