### ISSUE TITLE
Provide a non @addtaghelper way to add TagHelper descriptors

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#162]
Right now you can do this by replacing the entire `TagHelperDescriptorResolver` which is obviously pretty heavy handed so we should put in an extensibility point to support this.

**Comment by Eilon** [comment]
@DamianEdwards @NTaylorMullen @rynowak is this a real thing? Who would use this?

**Comment by NTaylorMullen** [comment]
Orchard would use this for custom TagHelper types (shapes); however, when this issue was initially written it was to address problems like app-insights/glimpse needing to inject script tags in the body without using an `@addTagHelper`. 

I'd say it's still valuable even for us since we'd use it for VIewComponentTagHElpers (it's hacked together to make that work today).

**Comment by Eilon** [comment]
We have a different solution for Application Insights and Glimpse, which is to have a default head/body tag helper that they can inject content into: https://github.com/aspnet/Mvc/issues/5728

Is it a big chunk of design work to come up with something cleaner for VCTH's?

**Comment by NTaylorMullen** [comment]
> Is it a big chunk of design work to come up with something cleaner for VCTH's?

Ehh, not too much but not free. I can see this issue as open or closed; we've lived this long without a first class API. Can live a while longer 😄

**Comment by rynowak** [comment]
We should do this for 2.0.0 since the VCTH feature is currently hardcoded into Razor.

**Comment by DamianEdwards** [comment]
Do we have an idea how this would work?

**Comment by rynowak** [comment]
I think of this issue as tracking basically the support for VCTH and allowing 3rd party frameworks to do similar things (Orchard). 

Similar to adding a custom directive - it's something that frameworks can do - but you need to be aware of tooling-related concerns to do it.

--------

I don't think we should make this a user-space feature for 2.0.0. Things like `<head>` and `<body>` Tag Helpers fill a lot of the gaps that existed here in the past for libraries, and we have ideas for the future about users writing their own Tag Helpers via Razor.

**Comment by rynowak** [comment]
This is not critical for the 15.3 update, but we should try and solve it for 2.0.0 RTM

**Comment by rynowak** [comment]
ad294fb4baba598937db55510d37dfc4d16fa1f6
