### ISSUE TITLE
Tag helpers no longer work in VS 15.3

### ISSUE THREAD

**Issue by vaindil** [aspnet/Razor#1621]
I upgraded to the stable version of VS 15.3 a little while ago, and tag helpers no longer function. I did not install anything else and have not tried upgrading to .NET Core 2.0 (still on 1.1.2). Intellisense does not detect the tag helpers, and they are not rendered when the project is run. I changed no code at all, I only upgraded VS. I'm on Windows 10 Enterprise.

In `Views/_ViewImports.cshtml` I have this:

    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
    @addTagHelper "*, MyCompany.WebAdmin"

**Comment by NTaylorMullen** [comment]
@vaindil if you type out `@page` do you see it colored yellow?

**Comment by vaindil** [comment]
@NTaylorMullen No, it does not work. Intellisense tries to put something else (because it doesn't recognize `page` as valid).

**Comment by NTaylorMullen** [comment]
@vaindil Would you mind zipping up some Visual Studio installer logs for us to take a look at? To do that you could do the following:

- Go to `%temp%` in windows explorer
- In the windows explorer search box type `WebToolsExtensions`
- Copy/include in zip all `dd_setup_*` files (probably all of the search results)
- In the search box delete `WebToolsExtensions` and search for `RazorExtension`
- Copy/include in zip all `dd_setup_*` files (probably all of the search results)

Once you've gathered your logs you can fix your issue by repairing Visual Studio. We're hoping to resolve this problem but lacking logs for investigation 😄

**Comment by vaindil** [comment]
Here you go, I included all of the logs from today, haven't repaired yet so there shouldn't be any overlap. Thank you!
[VSLogs.zip](https://github.com/aspnet/Razor/files/1226039/VSLogs.zip)

**Comment by NTaylorMullen** [comment]
Thanks @vaindil! Feel free to re-open this issue if repairing does not solve your IntelliSense problems.
