### ISSUE TITLE
Opening Razor.sln in VisualStudio results in error unless Multitargeting sln was previously restored.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1624]
![image](https://user-images.githubusercontent.com/2008729/29346893-61b2cc16-81fd-11e7-928c-c2a861b0006e.png)

This is all due to the dependency on the 1_X project by VisualStudio.LanguageServices. May need to use some msbuild magic to force VS to restore the missing project in the sln.

**Comment by ajaybhargavb** [comment]
Discussed with @NTaylorMullen. There is no straightforward way of auto restoring projects that are not part of the solution. As a compromise, we are renaming 
`Razor.sln` -> `Razor.Slim.sln`
`Razor.Multitargeting.sln` -> `Razor.sln`

**Comment by ajaybhargavb** [comment]
bf6370454706a61d4e9ebc9e51b0e5ffb3014516
