### ISSUE TITLE
How to get section content?

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Razor#1625]
In previous version, I can do something like this
```
StringBuilder sb = new StringBuilder();
using (StringWriter writer = new StringWriter(sb))
{
  await page.SectionWriters[key](writer);
}

var x = sb.ToString(); // x is the content of section
```

Now that RenderAsyncDelegate have no TextWriter as I report here https://github.com/aspnet/Razor/issues/1619

**Comment by andrew-vandenbrink** [comment]
How to get the content of section?

**Comment by NTaylorMullen** [comment]
Sections make use of `PushWriter` and `PopWriter` which are protected on the `RazorPageBase`. If you wanted you could have a custom page base type that exposed these methods or you could utilize the public `ViewContext` and re-enact what Push/Pop writer [do](https://github.com/aspnet/Mvc/blob/5fee1cac83d5e41a3027a7f30d87764e18850c54/src/Microsoft.AspNetCore.Mvc.Razor/RazorPageBase.cs#L288):

```C#
var oldWriter = page.ViewContext.Writer;
var newWriter = new StringWriter();
page.ViewContext.Writer = newWriter;
page.SectionWriter[key]();
page.ViewContext.Writer = oldWriter;

var x = newWriter.ToString();
```

**Comment by andrew-vandenbrink** [comment]
Thanks it works
