### ISSUE TITLE
Manage VisualStudioRazorParser lifetime

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1630]
Today we rely on the WTE's RazorCodeGenerator to create and dispose our parser; instead, we should detect when a Razor document opens and create/dispose ourselves accordingly.

In order to accomplish this task we'll need to expose some extensibility points to enable VisualStudio to configure the Razor parser in the correct way.

**Comment by rynowak** [comment]
This will be done in a future 15.X release. Moving to 2.1 so we don't lose track of it.

**Comment by NTaylorMullen** [comment]
212d97e51170d1df49a6a7569e6a063e66a89c99
