### ISSUE TITLE
Change RazorDocumentTracker to track `ITextBuffer`s.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1632]
VisualStudio associates 1 Razor document->many text views (ITextBuffer->ITextView). Today we ignore the ITextBuffer when creating DocumentTrackers. Instead we track the `ITextViews` that are created which is misleading given that you can have many views of the same text buffer (which only has 1 parser today).

**Comment by rynowak** [comment]
d87e0f7
