### ISSUE TITLE
Flow ITextBuffer -> ITextView associations from RazorDocumentTracker to VisualStudioRazorParser

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1633]
This is dependent on https://github.com/aspnet/Razor/issues/1632

Once we're tracking the ITextView associations with our Razor documents we'll be able to properly use`Microsoft.VisualStudio.Language.Intellisense.ICompletionBroker`.

**Comment by rynowak** [comment]
I'll do this today if you haven't already started

**Comment by NTaylorMullen** [comment]
Go for it.

**Comment by rynowak** [comment]
This is happening in a future 15.X release. Sticking it in 2.1 so we don't lose track of it.

**Comment by NTaylorMullen** [comment]
@rynowak this is done with DocumentTracker correct?

**Comment by NTaylorMullen** [comment]
This information is available on the VisualStudioDocumentTracker
