### ISSUE TITLE
Whitespace between the taghelper directives and their value should not be metacode

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#1649]
It should instead be markup. This will make them consistent with all the other extensible directives.

![image](https://user-images.githubusercontent.com/1579269/29691885-047f8f3e-88e2-11e7-9c57-cfd9c3ebd02e.png)

Note: This is a minor issue and doesn't have any impact on the functionality.

**Comment by Eilon** [comment]
This has always bothered me 😄

**Comment by ajaybhargavb** [comment]
f3d121cacf5d4b98e1cb49c3e7cbbe04c98d2830
