### ISSUE TITLE
Investigate if we should cache `TagHelperDescriptor`s in the `TagHelperDescriptorFactory`

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#165]
Right now the `TagHelperDescriptorFactory` just creates `TagHelperDescriptor`s mindlessly and doesn't cache them even if it sees the same `Type` twice.  It may be worth investigating the performance impact of this and then potentially adding caching to the `TagHelperDescriptorFactory`.

**Comment by Eilon** [comment]
Close

**Comment by NTaylorMullen** [comment]
Investigated this and we now cache `TagHelperDesignTimeDescriptor`s. We're unable to cache the whole `TagHelperDescriptor`s due to other dependencies from tooling.
