### ISSUE TITLE
The StackOverflow exception is raised if Razor view contains a generic object that nests a heirarchy of generic types

### ISSUE THREAD

**Issue by maxerokh** [aspnet/Razor#1662]
Hi,

I've created the following hierarchy of generic classes:

```
public class Builder<TItem> : BuilderBaseEx<Builder<TItem>> {
	public Builder<TItem> SomeMethod(object arg) {
		return this;
	}
}

public class BuilderBaseEx<T> : BuilderBase<T> where T: BuilderBaseEx<T> { }

public class BuilderBase<T> : IHtmlContent where T : BuilderBase<T> {
	public void WriteTo(TextWriter writer, HtmlEncoder encoder) {
		writer.Write("Foo");
	}
}
```

When I call the SomeMethod method in a View of ASP.NET Core 2.0:
`@(new Builder<object>().SomeMethod(ViewBag.SomeProperty))`

the StackOverflowException is raised. Note that the exception occurs only when I send a dynamic type object to the SomeMethod. If I a send non-dynamic type object, no error occurs.

**Comment by NTaylorMullen** [comment]
This is a C# behavior, not Razor. I'd recommend filing your issue over in the https://github.com/dotnet/Roslyn repo to get more feedback.
