### ISSUE TITLE
Add token names and documentation to DirectiveTokenDescriptor

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1670]
In order to provide accurate design time IntelliSense for directive tokens we need to have a way to indicate a tokens name and its corresponding documentation. The name would be utilized when showing [how a directive is used](https://github.com/aspnet/Razor/issues/1657) and the documentation would be used when [snippet-completing](https://github.com/aspnet/Razor/issues/1658) a directive.

Example of how directive tokens are showed today and how a name could improve the default documentation:

![image](https://i.imgur.com/fUq86qu.gif)

**Comment by ajaybhargavb** [comment]
7002dbf20a841466a1e339f689db3d8411b6780e
