### ISSUE TITLE
IntelliSense not working in razor views in different output folders than "bin"

### ISSUE THREAD

**Issue by renatoleite** [aspnet/Razor#1700]
I have many projects in my solution, and to improve the build performance, I changed all output projects to a folder that I created. However, the IntelliSense from razor views stopped to work. I spent many hours to discovery the issue, and is because the IntelliSense only work with the output project setting to the "bin" folder. I would like to know if it a bug or if exists something to do in this case.

I'm using VS 2015.

**Comment by Eilon** [comment]
@renatoleite which version of ASP.NET are you using? ASP.NET Core is supported only in VS2017, and ASP.NET Core 2.0 requires VS2017 Update 3. VS2015 is not supported at all for ASP.NET Core.

**Comment by renatoleite** [comment]
.NET 4.6.2

**Comment by Eilon** [comment]
@renatoleite ah ok this repo is specifically for ASP.NET Core. For issues with previous versions of Razor please file a Visual Studio Feedback item using VS's built-in feedback system and it will get routed to the appropriate group.
