### ISSUE TITLE
Autocompletion removes code and does not commit on space

### ISSUE THREAD

**Issue by miloush** [aspnet/Razor#1704]
VS 15.4.0 Preview 3

Create a default ASP.NET Core app, and make one of the cshtml files contain the following:

```C#
@if (Model.HasText)
{
	@if (Model.Count < 1)
	{

	}
	else
	{
		if (Model.IsHappy)
		{
			<table>
			|
			</table>
		}
		else
		{
			<table>
			@foreach (var group in Model.SadGroups)
			{
				<tr><td>@group.Key</td></tr>
			}
			</table>
		}
	}

}
```

Inside the first `<table>`, type `@fore` and hit space so that `@foreach` is committed.

Expected:
```C#
...
		if (Model.IsHappy)
		{
			<table>
			@foreach |
			</table>
		}
...
```

Actual:
```C#
...
		if (Model.IsHappy)
		{
			<table>
			@fore  |
			</table>
			<table>
			@foreach (var group in Model.SadGroups)
			{
				<tr><td>@group.Key</td></tr>
			}
			</table>
		}
...
```

HTML spacing is set to tabs, C# spacing is set to spaces.

Note that this works as expected if the autocompletion is invoked manually using Ctrl+Space.

**Comment by Eilon** [comment]
@NTaylorMullen any ideas on this?

**Comment by NTaylorMullen** [comment]
I can reproduce this. This is definitely a Razor editor issue. I've filed a TFS bug for tracking: https://devdiv.visualstudio.com/DevDiv/_workitems?id=504119
