### ISSUE TITLE
Question - Razor Pages -  What is the CSS in Head?

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Razor#1707]
I created a default Razor Pages project. When I run the page, there are two style tags in the head.
`<style type="text/css">embed[Height="175"][Width="175"],... `, `<style type="text/css">.ggbox,...`. 
![image](https://user-images.githubusercontent.com/13967891/31093082-27f1360e-a776-11e7-8e72-684536d9de12.png)

I've stripped out everything I could from the app (the Analyzers are left) and all of file contents but they are still there. What are they?
![image](https://user-images.githubusercontent.com/13967891/31093036-0a7d8e6a-a776-11e7-8379-ca16e1561f42.png)

**Comment by Eilon** [comment]
Razor pages along with tag helper functionality have the ability to add additional content to certain tags, such as the `<head>` and `<body>` tags.

I'm guessing this is maybe injected by the Visual Studio Application Insights feature, which automatically lights up some diagnostic features when running locally in Visual Studio. A similar bit of functionality can be easily enabled when running on Azure Application Services.

But, without seeing more of the specific HTML or JS, it's hard to say for sure.

Does anything else within the content seem to indicate that it's somehow related to Application Insights?

**Comment by RandyBuchholz** [comment]
It's not a Razor thing. It looks like the browser or an ad blocker is putting that in there. I don't look in head that often, but since I was look at something new (Razor Pages) I was looking at everything. Slipped my mind that the browser is external and not part of the dev env... sry.

**Comment by Eilon** [comment]
Ah good to know! That CSS did look a bit odd to me! 😄
