### ISSUE TITLE
can razor pages update part of the webpage

### ISSUE THREAD

**Issue by kurtiswen** [aspnet/Razor#1708]
sorry, haven't been coding in asp.net for a long time. Recently started a new project and I'm now considering using asp.net core 2.0 with razor pages, which sames good for fast developing. But I'm confused about how could I make a complex web page to be only partial update, like using ajax. means I may only want to post a part of the web page bank to server, and make some update only in the part of the web page instead of refreshing the whole page. I wander if there is already a way to do this using razor pages in asp.net core 2.0.

**Comment by Eilon** [comment]
Hi @kurtiswen , thanks for checking out ASP.NET Core 2.0!

For doing straightforward substitutions of content with AJAX, you can choose from any of a variety of projects that make doing AJAX easier, such as jQuery. At that point it's just "normal" JavaScript / AJAX functionality where you can hook up a button to do an AJAX post and get more data/HTML/anything from the server.

If you're looking to do something a bit more advanced or a bit more structured than that, we have some very rich Single Page Application (SPA) project templates as well. Here are some of our documentation pages on this topic:
* Client-Side development in ASP.NET Core
  * https://docs.microsoft.com/en-us/aspnet/core/client-side/
* Using AngularJS for Single Page Applications (SPAs) with ASP.NET Core
   * https://docs.microsoft.com/en-us/aspnet/core/client-side/angular
* Using JavaScriptServices for Creating Single Page Applications with ASP.NET Core
   * https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services

**Comment by kurtiswen** [comment]
Hi @Eilon , thank you very much for this reply. Say, I want to start work based on asp.net core 2.0 angular template, but sames there is no build in authentication part in this template, like which in MVC template or the new Razor template. Is there a fast way to add this feature into the angular template?

**Comment by Eilon** [comment]
Hi @kurtiswen we're working on adding authentication options to those templates for the next release. In the meantime you could try creating two projects and "merging" them (though it's a bit tricky). You could create one project from the SPA template, and one project using a non-SPA template, but with your chosen auth option, and copy the code and settings from one to the other.
