### ISSUE TITLE
Meta-Issue: Improvements to Razor experience in class libraries

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1712]
Things to consider:
- [ ] Add Views and Controllers via Add New Item in a Net Standard library. [user feedback](https://github.com/aspnet/Home/issues/2135#issuecomment-330982068)

**Comment by rynowak** [comment]
@DamianEdwards @Eilon - I know there was more we wanted to do, what else goes on this list?

**Comment by Eilon** [comment]
cc @sebastienros for anything he might have run into w/ Orchard Core.

**Comment by mkArtakMSFT** [comment]
We're tracking multiple other improvements supporting this work, which all are tracked separately. @DamianEdwards, if there is something else you are looking for from this work, can you please provide more details.
