### ISSUE TITLE
Enable support for instrumentation (Page Inspector) for TagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#172]
In TagHelpers initial state they will not support page inspector (instrumentation).  They will however work around the pre-existing instrumentation.  Meaning pieces of a `TagHelper`s body (if not `ContentBehavior.Modify`) will still communicate with page inspector via instrumentation.  

We need to add support for page inspector in TagHelpers.  However; it's not as simple as just adding it, we need to decide how much page inspector integration we'll have with TagHelpers.

**Comment by danroth27** [comment]
From @jodavis 

Functional issue:
When content is generated by a tag helper (or even left unmodified by a tag helper), Browser Link can't map that element back to source.

Repro steps:
1. In a DNX website using MVC, add an IPageExecutionListenerFeature
2. Set a breakpoint in PageExecutionContext.BeginContext and EndContext
3. Run a Razor page that uses Tag Helpers.

Expected result:
BeginContext and EndContext are called for every range of the rendered page

Actual result:
BeginContext and EndContext are called for most of the rendered page, but not the parts rendered by Tag Helpers.

**Comment by NTaylorMullen** [comment]
ddbd603653b001fcd0985ccc4b166d013c7df854
