### ISSUE TITLE
Transition RazorTextViewConnectionListener to use ITextViewConnectionListener

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1735]
It currently depends on the WpfTextViewConnectionListener. This is windows specific; therefore, we should go with an interface that works in VS for mac.

**Comment by NTaylorMullen** [comment]
Blocked by WTE's addin being functional in VS for mac.

**Comment by rynowak** [comment]
How's this blocked? Doesn't it work in VS for windows?

**Comment by NTaylorMullen** [comment]
> How's this blocked? Doesn't it work in VS for windows?

Yes it works in windows; however, the original purpose of this issue was to have a text view connection listener that could work in both Windows and VS for mac. Given that the VS for mac side of the equation is blocked and will definitely influence the design of the shared connection listener i'd rather not do throw away work.

**Comment by NTaylorMullen** [comment]
182714c324331ddafd0d79d6f5bb6704010fe2ce
