### ISSUE TITLE
Optimize Expression Rewriter

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1738]
We need to test the cold startup performance of MVC+Razor without the expression rewriter. We think we can make a significant dent in the performance by not using it in debug. 

In our data the expression rewriter cost is about 900ms

**Comment by ajaybhargavb** [comment]
Here is a gist with a code to disable expression rewriting without having to change Mvc code https://gist.github.com/ajaybhargavb/6096c09ae64d11dc3f704dacfbdfcf28

**Comment by rynowak** [comment]
## Some preliminary results

### Before
![image](https://user-images.githubusercontent.com/1430011/32129313-96043dee-bb3a-11e7-94fe-911a1bc02a30.png)

### After
![image](https://user-images.githubusercontent.com/1430011/32129318-ab9c1d8e-bb3a-11e7-8ffb-c2c152f373b6.png)

**Comment by rynowak** [comment]
Closing this as we can plan to do it as part of #1739
