### ISSUE TITLE
Big Rock: Eliminate Roslyn from Inner Loop Startup

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1740]
## Razor 101

Razor is an HTML templating language. Your `.cshtml` files are code-generated to C# and then emitted into one more assemblies. The mapping is generally one `.cshtml` file -> one C# class. These assemblies are loaded by an application and used to render HTML.

You can include **Tag Helpers** which are .Net classes that perform dynamic HTML rendering. Tag Helpers are bound to HTML tags during code-generation. Creating a Tag Helper only requires the declaration of a .NET class, which could be declared in the project hosting Razor. The set of Tag Helpers, their bindings to HTML structure, and .Net Type must be known to correctly perform Razor code-generation.

You can include **Directives** via .Net code that extend the Razor engine to declare additional *reserved words* in the Razor language with arbitrary semantics - as an example, MVC provides `@inject <TypeName> <PropertyName>` to leverage DI. The set of Directives and their structure must be known to correctly parse Razor code. The Razor engine extensibility that processes custom directives must be known to correctly perform Razor code-generation.

You can also include **Imports** files that act like `#include ...` in C, but only for directives. The set of Imports must be known to correctly perform Razor code-generation.

---------------

Most of the user-facing experience that external people think of as Razor is actually delivered as extensibility by MVC. MVC is the one that provides a built-in set of Tag Helpers, many of the built-in Directives and hooks up Imports.

We are working towards delivering good tooling experiences that aren't hardcoded to MVC's flavor of Razor, but in practice that's what exists today. Any new tooling experiences that are coupled to MVC create more debt for us.

### Conclusions

A few conclusions you can draw from this that are important for any discussion about how Razor performs compilation:
1. Razor is not a simple single-file-generator
2. Razor is extensible and this extensibility is part of our primary use case (MVC)
3. Razor code-generation depends on the App as an input (Tag Helpers)

## Summary of issues
Using Roslyn in-process has an outsized impact on Razor's contribution to inner loop performance. We think that the minimum JIT/loader/warmup cost for doing in-process compilation with Razor is 2s. Performing actual 'Razor' tasks during code-generation/compilation have a trivial contribution to the performance.

The only way(s) to bypass this speed-of-light limitation are to:
1. Already have done compilation (duh)
2. Do compilation out-of-process using a persistent server

We plan to do both of these - but only at build-time. When a view changes during local development we will still run Roslyn in-process to compile it.

## Philosophy

Razor for .NET Core was very much build/designed from the point of view of a runtime component that does compilation - rather than a compiler as-a-service. The runtime model is primary - and much of our user-facing configuration and extensibility reflects the 'runtime first' approach.

The significant challenge in this area is we've given extenders a lot of freedom to do things at runtime that can't be dealt with by tools in a predictable fashion - we need to walk back from this, and do so in a way that will be OK for a minor release.

----

The escape hatch here is that if you turn off Razor view AOT compilation - you fall back to the previous behavior. It will be slow but you will be happy (and slow).

## Plan of record

This is a rough plan that I've sketched out along with @davidfowl and a few others that attempts to build the minimum complexity into our runtime behavior while re-using our existing assets.

Here are the primary pieces, which I'll break down in detail:
1. Make AOT compiled views updatable (Runtime Change)
2. Run Razor AOT compilation on build (MSBuild)
3. Pivot Razor AOT compilation to use a build server (Build Server)

We can make Razor AOT compilation fast by using a build server - that way it stays warm. Then we can turn it on for build (rather than publish) by default - then it was always happen before you start the app - this is great if it's fast. Then we need to make AOT compiled views updatable so that we can preserve our existing UX.

### Step 1: Make AOT compiled views updatable

Razor has support for AOT compilation (called precompilation) of views as well as runtime compilation. When rending AOT-compiled views we already avoid loading/JITing Roslyn 👍 

AOT compiled views have the limitation that we will not recompile them at runtime when the view files change. This is a simpliying assumption for technical reasons on our part - but we've come up with other (non-perf) scenarios where we want this to work.

#### Current state
The default for inner loop is runtime (in-process) compilation because AOT compilation does not support updates. The default for published apps (in 2.0) is AOT compilation - because we're willing to add the additional 2-3 seconds of time for publishing.

AOT compilation is done with a CLI tool that loads your app and uses its DI'ed services to drive the compilation process. Extensibility for AOT compilation is in-band and is extensible in the same ways that runtime compilation is extensible.

Today a view is **modal**. If we have an AOT compiled view we will **never** hook up to file change events or validate that the compiled view is *fresh* when we access it. It can never be invalidated. We never built updatability into AOT compiled views because it's been low on our priority list.

#### Desired state

When we perform AOT view compilation we need to stamp each view with a hash for each of its inputs:
- The app assembly's SHA
- The view source code SHA
- The SHA of each import source file

Using the App's SHA allows us to leverage what MSBuild is already doing for dirty-checking whether the App or any of its dependencies have changed. My expectation is that if the App had to rebuild due to a code change or dependency change we will also need to update. This is conservative but also very easy to implement.

These data need to be declared with attributes and code-generated by Razor in the output C# code.

The view engine will do a quick integrity check when it loads the view - if the SHAs of everything match then the AOT compiled view should be used. Otherwise we just treat it like a cache miss and do runtime compilation. In either case we will create a cache entry that can invalidate it when files change. There's a slight possibility of a race condition here that could lead to a source change getting ignored, but if you hit that scenario you can work around it by just saving again. If we care deeply about this we could solve that issue by double-checking after hooking up the file watchers.

-----------

Once we get here, we've now unified the UX and code path for all views (AOT or not). We need this step to make the sure we don't break the user experience when we make AOT view compilation the default.

### Step 2. Run Razor AOT compilation on build

This part is pretty easy. We already have the MSBuild glue written to gather everything we need and pass it to the AOT compilation tool.

We should use this opportunity to nail the design of the *Razor MSBuild* support. We're going to now be injecting MSBuild to every Razor-hosting application, so we should make the set of metadata we have richer and decouple the experience from MVC.

### Step 3.Pivot Razor AOT compilation to use a build server

We need to make Razor AOT compilation fast, but doing the initialization work once (Build Server). The cheapest way for us to do this is re-use the existing AOT compilation tool, but turn it into a server. The existing Razor AOT compilation tool is a dotnet CLI tool that is called by MSBuild and passed the list of files. We could fork most of the logic into a library and reuse it.

We could achieve this by placing each operation in its own `AssemblyLoadContext`. The 'main' load context would be responsible for loading Roslyn and most shared framework components so that these get JITed and warmed up a single time. 

When an operation comes in, we create a new `AssemblyLoadContext` with the App's dependency context and then perform the compilation there.

The only complicated thing is dealing with a version conflict of the shared components.

------------

Going all the way with this would mean that we plug into MSBuild. For instance we'd have a *loader* MSbuild `ITask` that acts has a host and can act as the coordinator.

Our team would love the opportunity to reuse MSBuild's server model. Put another way, we'd love to not own a server 😆 

------------

Long term we'd like to continue to pivot here to get out of the business of needing to `Load` in the .NET sense your App's code. This means transitioning more Razor configuration and extensibility to MSBuild. We need to do this when we're allowed to make breaking changes.

### Extensibility/Configuration of Razor

Today we allow you to configure and extend Razor by replacing services in the App's DI container. This is really unfriendly to tools as it requires us to load and start your App in order to reason about compilation.

### Differences between runtime and AOT compilation

Developers building so-called *modular* apps will get a different compilation experience with AOT compilation. Usually what happens here is that individual modules are developed in isolation, and the C# code is compiled when the module is built, but the Razor code is compiled at runtime, with access to the full dependency graph of the application. 

These users already have to work around these kinds of issues to some extent, but we need to validate that any changes we make are not a total blocker.

### Public APIs

If you want to make an omelet, you're going to have to break a few eggs. A lot of what we need to change on the runtime side will require breaking changes.

### Reliance on the SHA of the App assembly

If we include the SHA of the App assembly as one of the 'inputs' we hash, is this *good enough* for when dependencies of the App change? Does deterministic build break this?

### Updatable AOT compilation + 3rd party libraries + _ViewImports

We need to rationalize what the impact is of combining a global `_ViewImports.cshtml` with AOT compiled views in a 3rd party library. We can reasonably expect the App to have a different set of `_ViewImports` documents than the 3rd party library was compiled with, so we need to a design so that AOT compiled 3rd party views have the right invalidation logic.

**Comment by rynowak** [comment]
I'm putting this **design** item tentatively in 2.1.0

**Comment by rynowak** [comment]
# Apparator
Update here on the plans for this. I've done some prototyping of Razor as an MSBuild task (Rzc) + a build-server here: https://github.com/rynowak/Apparator/tree/master/src


## Next steps

The current focus of this is to measure the savings of using the MSBuild task (Rzc) using the MSBuild node-reuse server on desktop. This will allow us to collect some best case metrics and measure the impact of Rcz on the end-to-end.

**Comment by rynowak** [comment]
A small non-scientific data point here. This is a before/after running the `WebAppCore` scenario from https://github.com/mikeharder/dotnet-cli-perf using Rzc
Before:

                        Method | SdkVersion | Restore |    Mean | Error |
------------------------------ |----------- |-------- |--------:|------:|
 BuildIncrementalSourceChanged |      2.0.2 |   False | 3.183 s |    NA |
      BuildIncrementalNoChange |      2.0.2 |   False | 2.029 s |    NA |
                     BuildFull |      2.0.2 |   False | 5.459 s |    NA |
   RunIncrementalSourceChanged |      2.0.2 |   False | 5.876 s |    NA |
        RunIncrementalNoChange |      2.0.2 |   False | 4.579 s |    NA |
                       RunFull |      2.0.2 |   False | 8.076 s |    NA |
 BuildIncrementalSourceChanged |      2.0.2 |    True | 3.972 s |    NA |
      BuildIncrementalNoChange |      2.0.2 |    True | 2.740 s |    NA |
                     BuildFull |      2.0.2 |    True | 5.459 s |    NA |
   RunIncrementalSourceChanged |      2.0.2 |    True | 6.616 s |    NA |
        RunIncrementalNoChange |      2.0.2 |    True | 5.314 s |    NA |
                       RunFull |      2.0.2 |    True | 9.561 s |    NA |
 BuildIncrementalSourceChanged |      2.1.1 |   False | 2.725 s |    NA |
      BuildIncrementalNoChange |      2.1.1 |   False | 1.785 s |    NA |
                     BuildFull |      2.1.1 |   False | 4.974 s |    NA |
   RunIncrementalSourceChanged |      2.1.1 |   False | 5.236 s |    NA |
        RunIncrementalNoChange |      2.1.1 |   False | 4.163 s |    NA |
                       RunFull |      2.1.1 |   False | 7.040 s |    NA |
 BuildIncrementalSourceChanged |      2.1.1 |    True | 2.934 s |    NA |
      BuildIncrementalNoChange |      2.1.1 |    True | 1.925 s |    NA |
                     BuildFull |      2.1.1 |    True | 4.911 s |    NA |
   RunIncrementalSourceChanged |      2.1.1 |    True | 5.611 s |    NA |
        RunIncrementalNoChange |      2.1.1 |    True | 4.905 s |    NA |
                       RunFull |      2.1.1 |    True | 7.146 s |    NA |

Rzc in proc:

                        Method | SdkVersion | Restore |    Mean | Error |
------------------------------ |----------- |-------- |--------:|------:|
 BuildIncrementalSourceChanged |      2.0.2 |   False | 4.841 s |    NA |
      BuildIncrementalNoChange |      2.0.2 |   False | 2.047 s |    NA |
                     BuildFull |      2.0.2 |   False | 7.547 s |    NA |
   RunIncrementalSourceChanged |      2.0.2 |   False | 5.649 s |    NA |
        RunIncrementalNoChange |      2.0.2 |   False | 2.791 s |    NA |
                       RunFull |      2.0.2 |   False | 9.035 s |    NA |
 BuildIncrementalSourceChanged |      2.0.2 |    True | 5.584 s |    NA |
      BuildIncrementalNoChange |      2.0.2 |    True | 2.746 s |    NA |
                     BuildFull |      2.0.2 |    True | 7.494 s |    NA |
   RunIncrementalSourceChanged |      2.0.2 |    True | 6.488 s |    NA |
        RunIncrementalNoChange |      2.0.2 |    True | 3.564 s |    NA |
                       RunFull |      2.0.2 |    True | 8.525 s |    NA |


Apparator Server:

                        Method | SdkVersion | Restore |    Mean | Error |
------------------------------ |----------- |-------- |--------:|------:|
 BuildIncrementalSourceChanged |      2.0.2 |   False | 4.052 s |    NA |
      BuildIncrementalNoChange |      2.0.2 |   False | 2.021 s |    NA |
                     BuildFull |      2.0.2 |   False | 6.717 s |    NA |
   RunIncrementalSourceChanged |      2.0.2 |   False | 4.817 s |    NA |
        RunIncrementalNoChange |      2.0.2 |   False | 2.781 s |    NA |
                       RunFull |      2.0.2 |   False | 7.639 s |    NA |
 BuildIncrementalSourceChanged |      2.0.2 |    True | 4.811 s |    NA |
      BuildIncrementalNoChange |      2.0.2 |    True | 2.764 s |    NA |
                     BuildFull |      2.0.2 |    True | 6.766 s |    NA |
   RunIncrementalSourceChanged |      2.0.2 |    True | 5.603 s |    NA |
        RunIncrementalNoChange |      2.0.2 |    True | 3.564 s |    NA |
                       RunFull |      2.0.2 |    True | 8.046 s |    NA |
 BuildIncrementalSourceChanged |      2.1.1 |   False | 3.541 s |    NA |
      BuildIncrementalNoChange |      2.1.1 |   False | 1.655 s |    NA |
                     BuildFull |      2.1.1 |   False | 5.864 s |    NA |
   RunIncrementalSourceChanged |      2.1.1 |   False | 4.328 s |    NA |
        RunIncrementalNoChange |      2.1.1 |   False | 2.397 s |    NA |
                       RunFull |      2.1.1 |   False | 6.547 s |    NA |
 BuildIncrementalSourceChanged |      2.1.1 |    True | 3.820 s |    NA |
      BuildIncrementalNoChange |      2.1.1 |    True | 1.979 s |    NA |
                     BuildFull |      2.1.1 |    True | 5.801 s |    NA |
   RunIncrementalSourceChanged |      2.1.1 |    True | 4.621 s |    NA |
        RunIncrementalNoChange |      2.1.1 |    True | 2.717 s |    NA |
                       RunFull |      2.1.1 |    True | 6.559 s |    NA |

**Comment by davidfowl** [comment]
Formatting needs fixing (you need extra | on the right)

**Comment by rynowak** [comment]
Closing this item since we've collecting all of the data we need and are doing productization work. There are individual items labeled as `area: Build` that track the progress.
