### ISSUE TITLE
Auto-completing a Razor directive with space results in two spaces being added.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1743]
![](https://i.imgur.com/HtThKy3.gif)

**Comment by ajaybhargavb** [comment]
Looks like this applies to not just directives but any CSharp in Razor like `@DateTime` and such. I'm investigating.

**Comment by ajaybhargavb** [comment]
I investigated this and it looks like Razor doesn't do anything special to affect this behavior. Marking this as external and filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/539940.

**Comment by NTaylorMullen** [comment]
Marking this as working because consuming the new completion APIs fixes the problem.

**Comment by NTaylorMullen** [comment]
aec88e3eba339f91f75a4d1aa68ff7736aee34ee
