### ISSUE TITLE
Add Tag Helper Project System

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1744]
This item tracks us taking control of the Tag Helper discovery end-to-end in tooling

**Comment by ajaybhargavb** [comment]
9a2e3ceab64f04f933b3a4ab2886d7293f508eb3

**Comment by ajaybhargavb** [comment]
90120f6a3b713b08aac9c9abb442e17c80e36dfc
0a76ad70172f29721173b07ef2707bc558a4c367

**Comment by ajaybhargavb** [comment]
8abbaa46ccc28abf30d39f841a73a69df9b9a3bc
