### ISSUE TITLE
Make VisualStudioRazorParser dispatch document structure changed events on foreground thread.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1748]
There's a lot of ceremony that needs to go on when notifying listeners of a document structure changed event, lets own that.

**Comment by rynowak** [comment]
A good general rule for IDE code is that .NET `event`s are always raised on the UI thread. Do we have any other cases like this?

**Comment by NTaylorMullen** [comment]
> Do we have any other cases like this?

In practice no. However, there's a few classes were we don't assert the current thread prior to dispatching an event and we should:
- DefaultProjectSnapshotManager
- DefaultEditorSettingsManager
- DefaultVisualStudioDocumentTracker

**Comment by NTaylorMullen** [comment]
a2972ebf1ce0b7bde9da4444523503330f10898d
