### ISSUE TITLE
How can i use Razor in Console / NETStandard 1.4/2.0 project?

### ISSUE THREAD

**Issue by KalpeshChheda** [aspnet/Razor#1753]
Hi,
I am trying to add razor page to NETStandard Project. But i cant find option for that. If I manually add cshtml file it does not generate backing C# file. In Visual Studio I have installed web application feature as well.
I want to generate html form cshtml. Is CSHTML/Razor support on netstandard?
Thanks.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Home/issues/2270
