### ISSUE TITLE
model intellisense does not find model properties when model is IEnumerable

### ISSUE THREAD

**Issue by mjnorman** [aspnet/Razor#1755]
VS2017 netcoreapp2.0

v 15.4.2, although happened on previous patch also.

In razor page with @model directive as IEnumerable<Type> at top of page, the tag helper methods are not finding my Type properties, but instead finds IEnumerable methods.  Sometimes I can switch between documents in the project and I will see it, then it's gone again.

**Comment by NTaylorMullen** [comment]
Hi @mjnorman this is by design for right now. We plan to tackle features that will enable what you're looking for in the future though. Take a look at: https://github.com/aspnet/Razor/issues/788

**Comment by mjnorman** [comment]
Thanks for the reply.  However reading that enhancement looks like it is all about templates. Are you saying it's by design that intellisense will not pick up model properties on Innumerable models?  Sounds like more of a bug than a feature?

**Comment by NTaylorMullen** [comment]
> Are you saying it's by design that intellisense will not pick up model properties on Innumerable models?

IEnumerable models are treated no different than non-IEnumerable models.  Meaning if you have `@model IEnumerable<Person>` and you attempt to utilize it in a TagHelper:

```
<input asp-for="..." />
```

The `asp-for` expects an `IEnumerable<Person>` not `Person`. 

Therefore this **is** valid: `<input asp-for="@somePersonsArray" />`
And this is **not**: `<input asp-for="FirstName" />`

If i'm misunderstanding your use-case feel free to elaborate.

**Comment by mjnorman** [comment]
Ok, better with specifics for sure.

Given the following model:
```
    public partial class MOM
    {
        public int Id { get; set; }
        [Display(Name = "Message")]
        public int? MessageId { get; set; }
        [Display(Name = "UUI")]
        public int? UuiId { get; set; }
        [Display(Name = "Transfer Number")]
        public string Transfernumber { get; set; }
        [Display(Name = "Application")]
        public int? AppId { get; set; }
        [Display(Name = "Dialed Number")]
        public int DnisId { get; set; }

        public Applications App { get; set; }
        public Dnis Dnis { get; set; }
        public Message Message { get; set; }
        public Uui Uui { get; set; }
    }
```

The scaffolded cshtml page is created as below:

```
@model IEnumerable<ncotelecom.MOMCore.Data.Models.MOM>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Transfernumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dnis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Uui)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Transfernumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.App.Application)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dnis.Dialednumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message.Messagedetail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uui.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
```

Ok no issue so far, everything works fine.  You'll notice that in the table header section, the @Html.DisplayNameFor() method is taking <model.member> as input, and everything compiles and runs.  
However, if you attempt to use intellisense in the header section you get the IEnumerable methods, not the inner model.  So if I can pass model.member as a parameter, intellisense should be smart enough to see that.  Am I wrong?

**Comment by NTaylorMullen** [comment]
@mjnorman I see your issue now. I believe this is a Roslyn issue. The DisplayNameFor in your case has two possible overloads:
1. `string DisplayNameFor<TResult>(Expression<Func<TModel, TResult>> expression)`
2. `string DisplayNameFor<TModelItem, TResult>(this IHtmlHelper<IEnumerable<TModelItem>> htmlHelper, Expression<Func<TModelItem, TResult>> expression)`

It looks like the interaction between those two is borking the IntelliSense for you. I'd recommend filing an issue over at https://github.com/dotnet/Roslyn

**Comment by mjnorman** [comment]
Fabulous, thanks for the info!
