### ISSUE TITLE
Support for handler name Intellisense auto completion ?

### ISSUE THREAD

**Issue by pushqrdx** [aspnet/Razor#1765]
Well i noticed that the implementation for `asp-page-handler` takes in a string which results in Intellisense not recognizing the underlying `OnGet / OnPost` handler methods in Razor Pages so i rolled on my own implementation using `nameof()` plus some magic. So unless i am missing on something is there anyway to simply do `asp-page-handler(HandlerName)` with Intellisense auto completion enabled ?

**Comment by pushqrdx** [comment]
Anyone ?

**Comment by NTaylorMullen** [comment]
I'm assuming your referring to TagHelpers only. You're correct in your assumption that there's no great way to get auto-completed page handlers.

**Comment by Eilon** [comment]
Indeed, this does not exist, and there are no plans to add that feature at this time.
