### ISSUE TITLE
Targeted tag name cannot be null or whitespace.

### ISSUE THREAD

**Issue by thanhnntq** [aspnet/Razor#1766]
When i run in Debug mode it working fine. But when i publish it and run with dotnet via cmd it throw this exception:

> An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
> ...\TNHeThong\TNLoi\ChucNang\TNChucNang.QuanTriHeThong\Views\Home\Index.cshtml
> 
> Targeted tag name cannot be null or whitespace.

[TNHeThong.zip](https://github.com/aspnet/Razor/files/1464284/TNHeThong.zip)
Please change " apm.FeatureProviders.Prepend(new NhaCungCapUngDung());" to " apm.FeatureProviders.Add(new NhaCungCapUngDung());"
line 198 BoQuanLyChucNang.cs

It's working fine with .NET Core 1.1.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Mvc/issues/7029
