### ISSUE TITLE
Razor: standalone usage without the whole ASP.NET Core MVC

### ISSUE THREAD

**Issue by winseros** [aspnet/Razor#1767]
Hi, Is there a chance Razor could be used as a template engine without the MVC itself? 

If yes - then how? 
If no - then are there any plans for that?

Thanks

**Comment by NTaylorMullen** [comment]
@winseros yes you can absolutely use Razor without MVC. Here's an example of a command line application that does not depend on MVC that takes in a Razor view and spits out a C# file: https://github.com/aspnet/Razor/tree/dev/src/RazorPageGenerator

**Comment by snielsson** [comment]
Tried creating a copy of this console program and added the nuget Microsoft.AspNetCore.Razor.Language 2.1.0-preview1-final (also tried the latest stable 2.0.2), but some types seems to be missing:

RazorProjectEngine
RazorProjectEngineBuilder
RazorProjectFileSystem
RazorConfiguration

Please advice how to build a standalone .net core console app to process razor templates.

**Comment by NTaylorMullen** [comment]
@snielsson if you checkout the `2.1.0-preview1-final` tag you'll have a better idea of what the `2.1.0-preview1-final` version of the console app looks like.

**Comment by genifycom** [comment]
Still no clue on how to use these new classes. No sample code found for .NET Core 2.1

**Comment by NTaylorMullen** [comment]
@genifycom the latest [RazorPageGenerator](https://github.com/aspnet/Razor/blob/a06c2b243f5e446a04d9439a87d62f6794c6c1ff/src/RazorPageGenerator/RazorPageGenerator.csproj) is 2.1.

**Comment by andreibancioiu** [comment]
https://stackoverflow.com/a/48770461/1475331

**Comment by smourier** [comment]
I have provided some sample code here: https://stackoverflow.com/a/47756437/403671
