### ISSUE TITLE
Vue.JS Single @ Symbol Support Feature for Razor

### ISSUE THREAD

**Issue by deanilvincent** [aspnet/Razor#1785]
Good day everyone!

Using the "@" symbol does a really help in connecting with C# codes inside the cshtml page. I'm also implementing vue.js in my project and I got some issues in using single "@" symbol. In latest version of vue.js, "@" is the shortcut for defining an event in html property instead of "v-on:click." But when I'm trying to call the "@" symbol followed by the event name inside the razor page, I've got an error message that says
`
<input @click="submitSomething"
The name 'click' does not exist in the current context. Cannot resolve symbol 'click'"
`
I've found a solution instead of using single "@", "@@" will define the single @ symbol of vue.js but is there a way to avoid the conflict of @ from razor and @ from vue.? Or is there any visual studio plugin in supporting the @ of vue.js?

**Comment by Eilon** [comment]
Using `@@` to escape a regular `@` is the right thing to do. That's just how Razor works, because `@` is a reserved character with special meaning. There is no way to disable that behavior because otherwise Razor wouldn't work.

**Comment by deanilvincent** [comment]
Thank you @Eilon Have a good day! :)
