### ISSUE TITLE
Use windows VS error reporter instead of the default error reporter.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1795]
Right now the Windows RazorExtension is using the `DefaultErrorReporter` (does nothing on error). Instead we should be registering the VS windows specific one that logs information to the activity log.

**Comment by NTaylorMullen** [comment]
Biggest part of this item by the way will be verifying that errors work as we expect them to in VisualStudio since we haven't had the luxury of trying out the API we thought we were 😉

**Comment by ajaybhargavb** [comment]
6be80e7bede5f9a8e29690f29b96e577ece398b3
