### ISSUE TITLE
Consider adding default implementations of OS/VS specific features that throw nice errors.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1806]
This issue would be for polish purposes only.

Today we have a variety of abstractions that rely on being implemented at an OS/VS specific layer. We can utilize Roslyn's service layer metadata to provide a default implementation that will notify users that they require an OS/VS specific implementation of a specific API.

This would enable other tooling authors to more-easily create their own platform specific implementations of Razor tooling abstractions.

**Comment by rynowak** [comment]
I don't think this is a real thing

**Comment by mkArtakMSFT** [comment]
We have no plans to do this.
