### ISSUE TITLE
When razor page and folder have same name, the parameter is null

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Razor#1807]
This is a bit difficult to explain,
Here is the directory structures,

alpha/beta.cshtml
alpha.cshtml

Notice the alpha.cshtml and alpha folder
The content of the functions on alpha.cshtml and beta.cshtml is the same with difference in PageModel's name.

```
public class Parameter{
public string id{get;set;}
}

public IActionResult OnGetReadData([FromQuery] Parameter parameter){
...
}
```

when I call 
GET /alpha/ReadData?id=abc
It works fine as expected
```
public IActionResult OnGetReadData([FromQuery] Parameter parameter){
//parameter.id = "abc" 
}
```

but when I call
GET /alpha/beta/ReadData?id=abc

```
public IActionResult OnGetReadData([FromQuery] Parameter parameter){
//parameter.id is null here
}
```

Is this a bug ?

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Mvc#7118
