### ISSUE TITLE
Integration testing and Razor

### ISSUE THREAD

**Issue by bdovaz** [aspnet/Razor#1808]
I have the following error:

System.InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-x86.exe' file for package Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-x86.

I have already followed this steps:

https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/testing/TestingMVC

What problem can it be?

I should mention (if it's important) that for "UseStartup<>();" I'm using a class that inherits from the projects "Startup" class because I needed to override some services. This class is in my test project.

**Comment by NTaylorMullen** [comment]
@bdovaz are you saying that if you run the https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/testing/TestingMVC tests you end up with this error? 

If not, could you provide a repro?

**Comment by bdovaz** [comment]
In my project I got that error I mentioned but in that repo project I get another different one.

Here you have a repro project.

Check if you are able to successfully run the test project. The notable differences are that I'm targeting .NET 4.6.2 and using MSTest.

[TestingMVC.zip](https://github.com/aspnet/Razor/files/1552948/TestingMVC.zip)

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please have a look at this?

**Comment by javiercn** [comment]
@pranavkm Seems that this is caused by a reference to the `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation` package on full framework.

I had to re-target the repro to net461 (for some reason it didn't run with 4.6.2 complaining that it's not on my machine)

I also have to add the following references to the test project for views to compile.
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" PrivateAssets="All" />

**Can you take a look at this? seems related to pre-compilation**

**Comment by pranavkm** [comment]
We add a reference to view compilation binaries at build-time on desktop. This is meant to workaround mismatches between the tool version and the runtime version using binding redirects. The added reference shows up in the app's deps file \ refs directory but not in the test project's. Ideally we wouldn't have the reference in the deps file but it's not immediately obvious what the setting needs to be looking at the SDK's files.

A couple of alternatives until we [have build-time support](https://github.com/aspnet/MvcPrecompilation#note-this-repo-is-solely-for-maintenance-of-the-existing-mvc-precompilation-feature-future-work-on-razor-compilation-is-now-being-handled-in-the-razor-repo-see-aspnetrazor1740-for-additional-details) for Razor available:

One possible workaround (apart from disabling precompilation entirely) is to remove the reference in your csproj:
```xml
 <Target Name="RemovePrecompilationReference" AfterTargets="_AddDesktopReferences">
    <ItemGroup>
      <Reference Remove="$(_MvcViewCompilationBinaryPath)" />
    </ItemGroup>
  </Target>
```

**Comment by javiercn** [comment]
@pranavkm Where do you drop that snippet, the application project csproj or the test project csproj

**Comment by pranavkm** [comment]
The application project.

**Comment by mkArtakMSFT** [comment]
Referencing the long-term fix https://github.com/aspnet/Razor/issues/1740

**Comment by mkArtakMSFT** [comment]
@bdovaz, di the workaround suggested above by @pranavkm solved the issue?

**Comment by mkArtakMSFT** [comment]
@pranavkm, should we keep this open? Looks like the View compilation during build will fix it (according to your earlier comment).

**Comment by mkArtakMSFT** [comment]
@bdovaz, please let us know if the workaround didn't resolve your issue.
