### ISSUE TITLE
Precompilation fails when more than one _ViewImports has the same `@namespace` directive

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Razor#1811]
_From @pranavkm on July 18, 2017 18:13_

Consider,

```
/Views
    /_ViewImports.cshtml (`@namespace WebApp`)
    /_ViewStart.cshtml
/Pages
    /_ViewImports.cshtml (`@namespace WebApp`)
    /_ViewStart.cshtml
```

Both `_ViewStarts` would be generated with the same fully qualified type name. This works at runtime because the two types are in distinct assemblies but fails for precompilation because we compile them in to one assembly.

_Copied from original issue: aspnet/MvcPrecompilation#174_

**Comment by mkArtakMSFT** [comment]
_From @pranavkm on August 23, 2017 21:12_

@rynowak do you recall why we chose not to mangle the type name when we added the `@namespace` feature? Is mangling the type name a possible solution here? The alternative to this would be to mirror what we do at runtime and produce an assembly per view, but that doesn't seem like a very good solution.

**Comment by mkArtakMSFT** [comment]
_From @rynowak on August 23, 2017 23:23_

Mangling the names would be a good solution, at least for viewstarts.

**Comment by mkArtakMSFT** [comment]
_From @ctolkien on August 29, 2017 13:8_

Just hit this with a MVC `Area` with it's own `_ViewImports`.

**Comment by mkArtakMSFT** [comment]
_From @pranavkm on August 29, 2017 16:3_

@ctolkien until we fix this, picking a different namespace is the way to go.

**Comment by pranavkm** [comment]
I don't think mangling just _ViewStarts.cshtml would help here. Consider this, now that we have areas support:

```
/Areas/MyArea/Pages/_ViewImports.cshtml @namespace MyApp
/Areas/MyArea/Pages/Index.cshtml @page

/Pages/_ViewImports.cshtml @namespace MyApp
/Pages/Index.cshtml @page
```

The fix isn't obvious (change one of the namespaces) and introduces friction between runtime and build-time compilation. Not using prettified names seems like the correct fix here.

**Comment by rynowak** [comment]
You might be right, we might have to mangle/generate names across the board.
