### ISSUE TITLE
Consume new C# completion APIs to avoid loading Razor binaries in non-Razor scenarios

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1813]

**Comment by NTaylorMullen** [comment]
Adding blocked label until the APIs are available.

**Comment by NTaylorMullen** [comment]
https://github.com/dotnet/roslyn/issues/18650 is the issue this is blocked on FYI @mkArtakMSFT

**Comment by NTaylorMullen** [comment]
Double marked this issue for cost because it's still a slight unknown

**Comment by mkArtakMSFT** [comment]
Let's go with most optimistic cost, rather than adding two, as that will mess up my calculations

**Comment by NTaylorMullen** [comment]
aec88e3eba339f91f75a4d1aa68ff7736aee34ee
