### ISSUE TITLE
Razor Pages project using Visual Basic (VB)

### ISSUE THREAD

**Issue by tb-mtg** [aspnet/Razor#1817]
Are there any plans to support Razor Pages projects using Visual Basic?

**Comment by mkArtakMSFT** [comment]
Hey @DamianEdwards, what are your thoughts regarding this?

**Comment by DamianEdwards** [comment]
We have no plans to support VB in Razor itself (i.e. VBHTML). However you should be able to create a multi-project application that has Razor Page CSHTML files in one project (along with the `Program.cs`) and the Page Models in VB files in a class library referenced from the first.

**Comment by DamianEdwards** [comment]
There's an example of a Razor Pages app with Page Models in VB at https://github.com/DamianEdwards/AspNetCoreVbHybrid
