### ISSUE TITLE
Add [NotBound] property to indicate that a property should not come from HTML

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#182]
Right now all public get; set; properties on a `TagHelper` are automatically bound to HTML with no way to opt-out. Adding a `[NotBound]` attribute (or another attribute name) would enable users to opt-out of `TagHelper` binding.

Example:
```C#
class DivTagHelper : TagHelper
{
    [NotBound]
    public string MyValue { get; set; } // Is not auto-filled and is not expected to be represented in HTML.
}
```

**Comment by dougbu** [comment]
de95f67
aspnet/Mvc@c162209
