### ISSUE TITLE
ProjectManagerSnapshot infrastructure doesn't work at runtime in VS for Mac

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1824]
This is because the IDE doesn't update the Roslyn representations of the world; it just forwards all calls to creation of documents, projects etc. to their own structures and don't bidirectionally show that data. Aka, Roslyn's Workspace will show 0 projects but the Ide's workspace (not Roslyn based) will show all the active projects.

Creating this issue for tracking purposes.

**Comment by rynowak** [comment]
Discussion is happening with Xamarin folks on this issue

**Comment by NTaylorMullen** [comment]
Had a little more back-and-forth on this issue and the root cause of this looks to be that the VS for mac system re-creates the Workspace when moving between solutions (or re-opening). This is troublesome because we only ever attach to a single workspace and monitor events from that.

**Comment by NTaylorMullen** [comment]
Tracking issue over on MonoDevelop: https://github.com/mono/monodevelop/issues/3517

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/issues/1973
