### ISSUE TITLE
Get rid of LegacyRazorDiagnostic

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1827]
This is coming up again now that I'm dealing with `RazorDiagnostic` in the build-time-Razor work, and it also deserves to just be fixed.

We should port all of our usage of old Razor errors to the new `RazorDiagnostic` class and get rid of the legacy stuff. 

Checklist:

Razor.Language:
- [x] DefaultDirectiveSyntaxTreePass
- [x] CSharpTokenizer
- [x] CSharpCodeParser
- [x] HtmlMarkupParser
- [x] TokenizerBackedParser
- [x] TagHelperParseTreeRewriter
- [x] TagHelperBlockRewriter - Taylor
- [x] DefaultTagHelperTargetExtension - Taylor

**Comment by rynowak** [comment]
Note that this is on the path for the build-time-Razor work. If it's feasible to get rid of this without too much pain we should do it now.

**Comment by ajaybhargavb** [comment]
6bbd063e263ac2bf79fcfa1240cceffeb0c4ca71
