### ISSUE TITLE
Razor MSBuild needs to handle linked files properly

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1829]
Creating an item to track this because we don't do this correctly today for precompilation. 

This is fundamentally a problem because precompilation looks at files on disk, rather than where a file is linked into the project. 

Links 'just work' when you use runtime compilation, we need to make sure this works well at build-time and in VS.

**Comment by pranavkm** [comment]
Add to this cshtml files that are carried as content inside NuGet packages.
