### ISSUE TITLE
Attribute Parser Error

### ISSUE THREAD

**Issue by MohammadYounes** [aspnet/Razor#183]
I'm developing an Angular app and using Razor as my view engine, I had a case where I needed to use `ng-pattern` attribute. 

Example:
```html
<input type="text" ng-pattern="/^[a-z0-9!#$%&'*+\/=?^_`{|}~.-]+@@[a-z0-9]([a-z0-9-]*[a-z0-9])?\.([a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i" />
``` 
Although I'm escaping `@`, the above gives the following error:

```bash
Parser Error Message: "[" is not valid at the start of a code block.  Only identifiers, keywords, comments, "(" and "{" are valid.
```

I was able to work around this using `data-ng-pattern`, but shouldn't this be allowed by Razor ?

**Comment by yishaigalatzer** [comment]
You can escape this way

```html
    <input type="text" ng-pattern="/^[a-z0-9!#$%&'*+\/=?^_`{|}~.-]+@("@")[a-z0-9]([a-z0-9-]*[a-z0-9])?\.([a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i" />
```

But yes we are going to try and fix it.

**Comment by Eilon** [comment]
@ajaybhargavb good luck :smile: Please chat with @NTaylorMullen for context.
