### ISSUE TITLE
Make Razor.Design work well with MvcPrecompilation installed

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1844]
Discussed with @Eilon and @DamianEdwards 

The main concern here is that both `Razor.Design` and `MvcPrecompilation` will be part of the metapackage, so we need to ensure that both of these packages can coexist.

The desire that that `Razor.Design` would become the new default experience for *Razor-on-Publish*, but that we can fall back to `MvcPrecompilation` if the developer has done anything explicit to customize it.

-----

Some notes about what we need to address:
- [x] How do we no-op when a user wants to use MvcPrecompilation
- [x] Exclude view files from publishing 
- [x] Exclude ref assemblies from publishing
- [x] `Razor.Design` should compile on publish by default

This looks like the main delta between the two systems.

**Comment by mkArtakMSFT** [comment]
Both Razor-dezign and pre-compilation are going to still exist in the metapackage (Universe).
Razor design will need to supersede the preCompilation tool in 2.1, unless the project has some specific configuration for pre-compilation.

**Comment by rynowak** [comment]
@mkArtakMSFT leaving this in preview1 for now. The remaining work is to get a new build of the SDK and verify the end to end without any workarounds. We're still waiting.

**Comment by DamianEdwards** [comment]
Any update on this?

**Comment by rynowak** [comment]
> The remaining work is to get a new build of the SDK and verify the end to end without any workarounds. We're still waiting.

> We're still waiting.

> We're still waiting.

We're still waiting.

**Comment by rynowak** [comment]
The workarounds have been removed from preview1 branches. Yay!
