### ISSUE TITLE
Move to new RazorCSharpCore content type.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1852]
There's a new RazorCSharpCore content type that inherits from the RazorCSharp content type. We should move all of our content type based logic/code to use it.

**Comment by NTaylorMullen** [comment]
So the way I'd like to complete this issue is by changing the [RazorLanguage.ContentType](https://github.com/aspnet/Razor/blob/06c2cf31d48b59b8ab85328d088c0206a8026f87/src/Microsoft.CodeAnalysis.Razor/RazorLanguage.cs#L10) value to `"RazorCoreCSharp"`; however, that's a breaking change since `RazorLanguage.ContentType` is a `public const string` 😢.

@mkArtakMSFT & @rynowak how do you feel about making this breaking change? I can't imagine great use-cases for why others would use the `RazorLanguage.ContentType` anyways.

If we choose not to do the breaking change (just have a non-public representation of the content type) then that property will be semi-invalid for the next foundational tooling release until we release a runtime version of Razor that we feel comfortable breaking.

**Comment by rynowak** [comment]
We should add a new 'core' content type and use that IMO

**Comment by NTaylorMullen** [comment]
8d6b86c76a17067b8fce656cfbab03750b779b15
