### ISSUE TITLE
[Question] Using Microsoft.AspNetCore.Razor as a standalone library

### ISSUE THREAD

**Issue by conniey** [aspnet/Razor#1855]
Hi,

I am trying to migrate [RazorEngine](https://github.com/antaris/RazorEngine) to .NET Core. However, when we restore the Microsoft.AspNetCore.Razor package and use it in an F# script as part of a build process, it fails with TypeLoadException since many of the types are removed from version 1.1.2 and 2.0.0 of the package.  Is there a package with the implementation that we should be referencing?

Difference between version 1.1.2 and 2.0.0 of Microsoft.AspNetCore.Razor
![image](https://user-images.githubusercontent.com/10136526/34169822-88d47832-e49d-11e7-8bf8-58442c60be08.png)

The original issue is: https://github.com/Antaris/RazorEngine/issues/486

**Comment by NTaylorMullen** [comment]
We've moved a ton of that code and made the `Microsoft.AspNetCore.Razor` and `Microsoft.AspNetCore.Razor.Runtime` assemblies runtime focused.

The default Razor code generation process is encompassed in 3 assemblies now:
- `Microsoft.AspNetCore.Razor.Language` - Core Razor pieces not dependent on Roslyn
- `Microsoft.CodeAnalysis.Razor` - Razor pieces that depend on Roslyn
- `Microsoft.AspNetCore.Mvc.Razor.Extensions` - Mvc extension of the core Razor pieces (adds pieces like `@model`, `@page` etc.)

Hope this helps!
