### ISSUE TITLE
Use razor syntax in viewdata before viewmodel

### ISSUE THREAD

**Issue by peirens-bart** [aspnet/Razor#1859]
Hi

is it possibel to render a view twice, adding razor syntax first an then add the actual viewmodel
I have an Asp.net core app where I do:

```
public ViewRenderService(IRazorViewEngine razorViewEngine,
            ITempDataProvider tempDataProvider,
            IServiceProvider serviceProvider)
        {
            _razorViewEngine = razorViewEngine ?? throw new ArgumentNullException("RazorViewEngin");
            _tempDataProvider = tempDataProvider ?? throw new ArgumentNullException("TempDataProvider");
            _serviceProvider = serviceProvider ?? throw new ArgumentNullException("ServiceProvider");
        }

public async Task<string> RenderToStringAsync(string viewName, object model)
        {
            var httpContext = new DefaultHttpContext { RequestServices = _serviceProvider };
            var actionContext = new ActionContext(httpContext, new RouteData(), new ActionDescriptor());

            using (var sw = new StringWriter())
            {
                var viewResult = _razorViewEngine.GetView("~/", viewName, false);

                if (viewResult.View == null)
                {
                    throw new ArgumentNullException($"{viewName} does not match any available view");
                }

                var viewDictionary = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary())
                {
                    Model = model
                };

                var viewContext = new ViewContext(
                    actionContext,
                    viewResult.View,
                    viewDictionary,
                    new TempDataDictionary(actionContext.HttpContext, _tempDataProvider),
                    sw,
                    new HtmlHelperOptions()
                );

                await viewResult.View.RenderAsync(viewContext);
                return sw.ToString();
            }
        }
```

This is used to render emails in de backend, now the users want to use there own templates.
my view can be 
`<html><body>@model.Header</body></html>`
and a template model like 
`template{Header= "<h1>@model.Title</h1>"}`
 this is stored in the database
the the actual viewmodel is having the Title property.

no wthe question is can I call viewResult.View.RenderAsync twice, I tried this by creating a second viewcontext reusing the stringwriter with position set to 0, but I'm keep ending up with.
`<html><body><h1>@model.Title</h1></body></html>`
 and the second render is never done.

Or, and I know this question is asked many times can I create ViewEngineResult from string,
like 
`var viewResult = _razorViewEngine.CreateView("<html><body><h1>@model.Title</h1></body></html>");`

**Comment by mkArtakMSFT** [comment]
@peirens-bart, please use StackOverflow for these types of questions. You can use "asp.net-core-mvc" tag to highlight the relevance.
