### ISSUE TITLE
Support relative paths for errors/diagnostics

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1868]
For readability of our errors we should support relative paths when possible (over absolute paths). This is consistent with what CSC and other tools do.

This means we should flow relative path information through the system, and prefer it when it shows up for display. This doesn't mean that we can't use absolute paths when required.

**Compare:**
```
Views\Home\Index.cshtml(1,2): Error RZ1006: The code block is missing a closing "}" char
acter.  Make sure you have a matching "}" character for all the "{" characters within this b
lock, and that none of the "}" characters are being interpreted as markup. [C:\Users\ryno
wak\AppData\Local\Temp\5lwxg1hw.cjk\SimpleMvc.csproj] 
```

```
C: \Users\rynowak\AppData\Local\Temp\5lwxg1hw.cjk\Views\Home\Index.cshtml(1,2): Er
ror RZ1006: The code block is missing a closing "}" character.  Make sure you have a mat
ching "}" character for all the "{" characters within this block, and that none of the "}" cha
racters are being interpreted as markup. [C:\Users\rynowak\AppData\Local\Temp\5lwxg1
hw.cjk\SimpleMvc.csproj]
```

**Comment by rynowak** [comment]
@ajaybhargavb can you figure out what will be needed to support this?

**Comment by rynowak** [comment]
For instance the problem here seems to be that we always normalize paths when creating the source document. For display, we probably want the relative path. There are still some cases where we want the full path.

**Comment by rynowak** [comment]
We now flow the relative paths into the compiler as of d602f9d770cf186f14446305bf596d04d32f08dd

We still have some additional work in the compiler to actually consume this information. We need to do a search on `RazorSourceDocument.FilePath` and audit where we're using it.

**Comment by ajaybhargavb** [comment]
After some investigation, it looks like we need to do more work where these errors are consumed to support relative paths (Diagnostics etc). Closing this is currently out of our scope.
