### ISSUE TITLE
HtmlConventions -  optional or customizable

### ISSUE THREAD

**Issue by davidhunt135** [aspnet/Razor#1871]
I am currently trying to setup angular 5 with Razor and Asp.Net Core and have some issues with directives not working due to casing of the rendered html. Newer version of angular have updated directives from kebab case to camel case, i.e ng-if is now ngIf and it appears that all html is transformed to lower case by Razor. (I believe its done by HtmlConventions.ToHtmlCase).

Would it be possible to have some way of disabling or customizing html conventions?

**Comment by NTaylorMullen** [comment]
@davidhunt135 are you referring to how TagHelpes render HTML?

**Comment by davidhunt135** [comment]
@NTaylorMullen No, I tried creating a custom TagHelper which created a camel case attribute on the tag, this was also rendered in lower case. All uppercase html in the cshtml files are rendered in the browser as lower case. whether being defined as part of the HtmlAttributes on an html helper or just basic markup.

**Comment by NTaylorMullen** [comment]
@davidhunt135 if you want to override the conventions for a TagHelper you can use the `[HtmlTargetElement("ATagNameExactly")]` on the TagHelper class for element names and the `[HtmlAttributeName("AnAttributeExactly")]` on the TagHelper property for attribute names.

We don't do any work to change attributes added to `output.Attributes`

**Comment by davidhunt135** [comment]
@NTaylorMullen 

I have tried that and no success. When I have an attribute with name "ngModel" in `output.Attributes` it is rendered in html as "ngmodel". From looking at the Razor source I believe this is being done by `HtmlConventions.ToHtmlCase`

**Comment by NTaylorMullen** [comment]
@davidhunt135 How are you adding your `ngModel` attribute to `output.Attributes`?

**Comment by davidhunt135** [comment]
I have tried have an html tag like this `<input [(ngModel)] ... >` which renders in lower case then in the tag helper I also tried adding a new attribute to `output.Attirbutes` via the Add function. i.e `output.Attributes.Add(new TagHelperAttribute("[(ngModel)]", "model"));`

**Comment by NTaylorMullen** [comment]
@davidhunt135 my hunch is that JavaScript is interacting with your output and lowercasing your attributes. If you'd like to provide a repro i can take a closer look.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
