### ISSUE TITLE
Razor needs to had hashes of input files to compiled runtime code

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1875]
We need the hashes of source file inputs so we can decide whether or not to recompile at runtime.

**Comment by NTaylorMullen** [comment]
Is the checksum not enough?

**Comment by rynowak** [comment]
The checksum goes into a comment, we need something visible at runtime (attribute).

**Comment by rynowak** [comment]
186e573

**Comment by rynowak** [comment]
One more piece is needed to add the identifier in MvcTemplateEngine/RazorProject

**Comment by rynowak** [comment]
16324c3126f36ef0537830cd73d2f6411962f610
