### ISSUE TITLE
razor pages view component issue

### ISSUE THREAD

**Issue by azizkazdal** [aspnet/Razor#1883]
hi,
when I try to import view component in asp.net core 2 razor pages like below
```
@{
        await Component.InvokeAsync("DeleteModal", new { name = "Default", item = Model.ViewModel.DeleteModalViewModel });
   }
```
this does not work.  I have to use one line code as below
`@await Component.InvokeAsync("DeleteModal", new { name = "Default", item = Model.ViewModel.DeleteModalViewModel })`

**Comment by pranavkm** [comment]
`Component.InvokeAsync` returns an `IHtmlContent`: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/IViewComponentHelper.cs#L26. The returned value needs to be written to the output, like the second instance, for the view component's content to appear in the output.

**Comment by azizkazdal** [comment]
```
<div>
    **@await Component.InvokeAsync("PriorityList", new { maxPriority = 4, isDone = true })**

    @{
        var ViewModel = new TestViewModel();
        ViewModel.Title = "selam title";
        _@await Component.InvokeAsync("Test", new { item = ViewModel });_
    }

</div>
```

these two Component.Invoke methods works fine in classic Core MVC example
https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/views/view-components/sample/ViewCompFinal . But not working in Razor Pages.

**Comment by pranavkm** [comment]
Does adding the `@` in front of `await` make a difference in your Razor Pages sample?

**Comment by mkArtakMSFT** [comment]
@azizkazdal, will you be able to share the "DeleteModal" view?

**Comment by azizkazdal** [comment]
my test code git url https://github.com/azizkazdal/aspnetcorerazorpages

**Comment by azizkazdal** [comment]
@pranavkm it worked when I added @ in front of await.

**Comment by mkArtakMSFT** [comment]
Thanks @azizkazdal. Can you also share a sample targeting classic AspNet MVC, which would repro the issue?

**Comment by pranavkm** [comment]
@mkArtakMSFT I don't think there's an issue here. The `@` is required to render contents - which is what @azizkazdal was doing in the controller sample.
