### ISSUE TITLE
Simplify RazorDiagnostic deserialization

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#1886]
From https://github.com/aspnet/Razor/pull/1885#discussion_r158877067

Now that `LegacyRazorDiagnostic` is gone, we don't need to look at the type name when deserializing RazorDiagnostic. We can just directly deserialize to `DefaultRazorDiagnostic`.

Additionally, we need to do some profiling on this. This is a hot spot for Razor at build time

Here's a basic plan:
- [x] Use the `dotnet new mvc` template, add the serializers to project, and dump the set of taghelpers as JSON.
- [x] Add a new perf microbenchmark that serializes/deserializes this data
- [x] ~Do some profiling and make improvements to the serialization code~ (Not doing this because serialization doesn't seem to be high impact on perf as shown by the benchmark test)

**Comment by rynowak** [comment]
@ajaybhargavb added some details, thanks!

**Comment by ajaybhargavb** [comment]
98e74b9a69b7b277fc9a78c068de967185104d69

**Comment by ajaybhargavb** [comment]
> This is a hot spot for Razor at build time

After looking at the [benchmark test](https://github.com/aspnet/Razor/pull/1904#issue-286087035), it looks like this is not the case.

**Comment by rynowak** [comment]
@ajaybhargavb - done?

**Comment by ajaybhargavb** [comment]
b68d9cf01fcc2ab39bedfb1d167e455de3f2efa9
