### ISSUE TITLE
Reenable NPV verification for Microsoft.AspNetCore.Razor.Design

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1887]
I added a suppression for all NPV rules for `Microsoft.AspNetCore.Razor.Design` because this package contains assemblies we don't own right now. 

We need to have a conversation about how to ship this tool, and then take the appropriate action and re-renable these rules.

**Comment by rynowak** [comment]
See https://github.com/aspnet/Razor/pull/1879#issuecomment-353690503

**Comment by natemcmaster** [comment]
:eyes:

**Comment by rynowak** [comment]
> We need to have a conversation about how to ship this tool,

They key part of that is this part, I don't think we'll ship it as-is.

**Comment by rynowak** [comment]
Also see https://github.com/aspnet/Universe/pull/730 - we'll need to get this package back to 'ship' so we can use it in MVC

**Comment by rynowak** [comment]
This is done.
