### ISSUE TITLE
Ensure copying settings work for Razor.Design

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#1896]
* `CopyBuildOutputToOutputDirectory` = false should skip copying precompiled binary to ouput directory
* `CopyBuildOutputToPublishDirectory` = false should skip copying precompiled binary to publish directory
* `CopyOutputSymbolsToOutputDirectory` = false or `SkipCopyingSymbolsToOutputDirectory` = true should skip copying pdbs to output directory
* `CopyOutputSymbolsToPublishDirectory` = false should skip copying pdbs to publish directory

**Comment by rynowak** [comment]
bf52e0d
