### ISSUE TITLE
RazorGenerate and RazorCompile can't be invoked directly with multi-targeting

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1912]
You can't call these targets at the command line using `dotnet msbuild /t:RazorGenerate` if the project does multi-targeting

**Comment by rynowak** [comment]
Add `/p:TargetFramework=....` to workaround.

**Comment by pranavkm** [comment]
Do we want to consider taking this for preview1? For the release, this involves removing https://github.com/aspnet/Razor/blob/release/2.1/src/Microsoft.AspNetCore.Razor.Design/buildMultiTargeting/Microsoft.AspNetCore.Razor.Design.targets.

**Comment by rynowak** [comment]
It doesn't hurt to ask. Send mail to PMs and eng leads.

**Comment by pranavkm** [comment]
Preview1 - addressed in https://github.com/aspnet/Razor/commit/766862390b52db5fd4e6e8e502cf2949e7d74eb6
Preview2 - addressed in https://github.com/aspnet/Razor/commit/42c3102cd46413b4caeb711fc904f50920fd8861
