### ISSUE TITLE
Flaky test: WorkspaceChanged_ProjectRemovedEvent_RemovesProject 

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#1913]
I saw this fail on appveyor, and it looks like virtually none of our code is on the stack. 

https://ci.appveyor.com/project/aspnetci/razor/build/1.0.3753

**Comment by mkArtakMSFT** [comment]
@rynowak, any suggestion who should look into this?

**Comment by rynowak** [comment]
@NTaylorMullen can probably start.  We should first do some googling and see if anyone else has hit something like this.

**Comment by NTaylorMullen** [comment]
This is due to Roslyn's dependency on MEF. Looks like MEF has an issue when solutions/workspaces are created in parallel (we do this when creating/using adhoc workspaces). I'll build a helper method that locks around the creation of workspaces so we don't run into issues.

**Comment by NTaylorMullen** [comment]
f025a27f042e13d0a753d559f2f2e9cec8ae0a1c
