### ISSUE TITLE
Using a generic list in tag helpers

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#1923]
_From @muqeet-khan on February 9, 2016 6:55_

Is there a way to:

```
    public class ScCollectionContainsTagHelper : TagHelper
    {
        public List<T> Source { get; set; }
        public T item { get; set; }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
...
        }
    }
```

As of now, I am able to get away with: 

```
    public class ScCollectionContainsTagHelper : TagHelper
    {
        public List<object> Source { get; set; }
        public object item { get; set; }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
...
        }
    }
```

I would like to take a generic list as source and run a contains method on it to append HTML content for true.

_Copied from original issue: aspnet/Home#1291_

**Comment by Eilon** [comment]
_From @dougbu on February 9, 2016 15:15_

Tag helpers are actually designed to avoid requiring generics. MVC's  [`ModelExplorer`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ModelExplorer.cs) fills a similar purpose, exposing the model or a model expression to tag helpers. [`RazorPage<T>`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorPageOfT.cs) does the heavy lifting, with some help from the Razor code gen extensions in MVC. Have a look at how any of the `asp-for` attributes in most of the [MVC tag helpers](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers) are used.

If `ModelExplorer` doesn't provide everything you need, please describe more about your scenario.

**Comment by Eilon** [comment]
_From @FilipZamec on December 14, 2017 15:20_

Sorry to open up an old question, but what about this:
```csharp
@(Html.Kendo().Grid<Kendo.Mvc.Examples.Models.CustomerViewModel>()
        .Name("grid")
        .Columns(columns =>
        {
            columns.Bound(c => c.ContactName)
            .ClientTemplate(
                @"<div class='customer-photo' 
                    style='background-image: url(" + @Url.Content("~/content/web/Customers/#:data.CustomerID#.jpg") + ");'></div><div class='customer-name'>#: ContactName #</div>")
              .Width(240);
            columns.Bound(c => c.ContactTitle);
            columns.Bound(c => c.CompanyName);
            columns.Bound(c => c.Country).Width(150);
        })
        ....
)
```
(taken from Telerik controls: https://demos.telerik.com/aspnet-mvc/grid)

It's easy to implement columns in HtmlHelper (because it's generic), but how can we do it in TagHelper?

Thanks

**Comment by NTaylorMullen** [comment]
@FilipZamec Sadly we don't currently have the capability to have a strongly typed TagHelper representation of what you're trying to do. I'd suggest following https://github.com/aspnet/Razor/issues/788 for improves to TagHelpers templating abilities.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue.   We'll consider your feedback as part of an existing issue we're tracking [here](https://github.com/aspnet/Razor/issues/788).
