### ISSUE TITLE
Block.Length is expensive at design time.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1927]
Lots of perf issues regarding `Block.get_Length` in VS.

Opening MSN.cshtml in VS:
![image](https://user-images.githubusercontent.com/2008729/34846494-366be9da-f6cd-11e7-937a-93e403ea3b42.png)

**Comment by rynowak** [comment]
What's the priority of this? Should we be looking at fixing this for 15.6?

**Comment by NTaylorMullen** [comment]
> What's the priority of this? Should we be looking at fixing this for 15.6?

Figuring that out now in another email thread.

**Comment by NTaylorMullen** [comment]
92111ea515504d80fedadeb23aeb748b6a946ca5
