### ISSUE TITLE
Move over to ZipArchive instead of relying on PowerShell to zip MPacks

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1937]

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, when do you need this to happen?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen, when do you need this to happen?

Can be whenever It's technical debt.

**Comment by rynowak** [comment]
It would be good to do soon while it's paged in.

**Comment by NTaylorMullen** [comment]
49a3b6bcae7b39b04655a2f8657cd15178c7afe0
