### ISSUE TITLE
Use unique names for commonly used parameters

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#1948]
I tried building a project referencing Microsoft.AspNetCore.All + Razor.Design, and got this error:

```
\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.0-preview1-28042\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.targets(127,5): error MSB4062: The "Microsoft.AspNetCore.Razor.Tasks.RazorGenerate" task could not be loaded from the assembly C:\Users\Pranav\.nuget\packages\microsoft.extensions.fileproviders.embedded\2.1.0-preview1-28042\build\netstandard2.0\..\..\tasks\netstandard1.5\Microsoft.Extensions.FileProviders.Embedded.Manifest.Task.dll
```

This is because the two packages share the same property names - https://github.com/aspnet/FileSystem/blob/dev/src/FS.Embedded/build/netstandard2.0/Microsoft.Extensions.FileProviders.Embedded.targets#L4. We need to scan the targets and ensure we're using unique names.

**Comment by rynowak** [comment]
It looks like someone failed to understand @natemcmaster 's awesome blog post on this topic. http://www.natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/
```
<!-- build/GreetingTasks.props -->
<Project TreatAsLocalProperty="TaskFolder;TaskAssembly">

  <PropertyGroup>
    <TaskFolder Condition=" '$(MSBuildRuntimeType)' == 'Core' ">netstandard1.6</TaskFolder>
    <TaskFolder Condition=" '$(MSBuildRuntimeType)' != 'Core' ">net46</TaskFolder>
    <TaskAssembly>$(MSBuildThisFileDirectory)..\tasks\$(TaskFolder)\GreetingTasks.dll</TaskAssembly>
  </PropertyGroup>

  <UsingTask TaskName="MSBuildTasks.SayHello" AssemblyFile="$(TaskAssembly)" />
</Project>
```

It wouldn't hurt to be more defensive, but the fileprovider targets should be using `TreatAsLocalProperty`

**Comment by pranavkm** [comment]
Ahh, didn't realize that was a thing That said, `TreatAsLocalProperty` requires all imported target files to co-operate which might be asking for much?

**Comment by rynowak** [comment]
Yeah I agree on both counts. It's still a good idea to use `TreatAsLocalProperty` and it's also a good idea to choose less-common names.

**Comment by rynowak** [comment]
Actually looking deeper at the docs, it's not clear that `TreatAsLocalProperty` creates a scope for the property. The only thing it claims to do is to prevent it from being set at the command line.
