### ISSUE TITLE
Razor view becomes stuck randomly

### ISSUE THREAD

**Issue by ShadowDancer** [aspnet/Razor#1955]
Sometimes a view in my asp.net core 1.4 app breaks with this message inside razor compilation code:
`Unexpected error writing debug information -- 'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll'`

Such a view is dead, and I need to manually restart application to make it work again. Other views are rendered correctly, but that one is stuck. It occurs randomly (when the view is recompiled?). Fix was to include Microsoft.DiaSymReader.Native nuget package.

I am using self-contained deployment (I have <RuntimeIdentifier>win7-x64</RuntimeIdentifier> in my .csproj), and assembly (DiaSymReader) is not generated to output (unless added by nuget).
I can find assembly in %programfiles%/dotnet directory.

**Comment by mkArtakMSFT** [comment]
@rynowak, any thoughts here?

**Comment by rynowak** [comment]
No idea off the cuff. It seems like the symbol reader should be included in a publish.  


> my asp.net core 1.4 app breaks
@ShadowDancer  - asp.net core is not a release version I'm familiar with. Could you share your project file and `dotnet --info` output?

**Comment by ShadowDancer** [comment]
@rynowak 
dotnetinfo:
https://github.com/ShadowDancer/MissingDiaSymReaderRepro/blob/master/dotnetInfo.txt
Sorry about typo, I thought about 1.1.4. This bug haunted me in 1.1.4, but since then I have upgraded and it didn't help.

CsProj:
https://github.com/ShadowDancer/MissingDiaSymReaderRepro/blob/master/MissingDiaSymReaderRepro/MissingDiaSymReaderRepro.csproj

**Comment by pranavkm** [comment]
Let me investigate this further. Thanks for the sample app @ShadowDancer

**Comment by pranavkm** [comment]
@ShadowDancer does it fail intermittently i.e. after you compile the view several times? I tried your app both on my regular desktop with VS and on a machine without, and I was able to navigate to your pages without issues.

**Comment by pranavkm** [comment]
Summarizing this for @jaredpar : Mvc on desktop compiles views at runtime and emits it with `full` pdbs [if the SymWriter component is installed](https://github.com/aspnet/Mvc/blob/release/1.1/src/Microsoft.AspNetCore.Mvc.Razor/Internal/SymbolsUtility.cs#L15). @ShadowDancer's app fails to compile views with the error `'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll'` and this is remedied by referencing `Microsoft.DiaSymReader.Native`. I couldn't reproduce this error on my machine.

a) Is it necessary to reference this package if we intend on emitting assemblies with full pdbs? 
b) What would get someone to the state that results in the error 'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll'

**Comment by ShadowDancer** [comment]
@pranavkm In the repro I just wanted to point out, that assembly is not emitted to output. My theory is that after IIS periodic app pool restart view cache is gone and then compilation fails.
Also I have machines that are not affected by this, however I am unable to figure out what is different between them.

This problem is around since RC2:
https://forums.asp.net/t/2105966.aspx?Dead+View+with+CompilationFailedException

**Comment by jaredpar** [comment]
CC @tmat, @angocke

> Is it necessary to reference this package if we intend on emitting assemblies with full pdbs?

An end consumer shouldn't need to install this in order to get PDB support. This should be handled at the CLI level. I checked and our NuSpec isn't mentioning this DLL. @tmat is this something the CLI is supposed to embed for us?

**Comment by pranavkm** [comment]
The runtime (`Microsoft.NETCore.App`) carries this binary so presumably that takes care of it in CoreCLR. But the issue @ShadowDancer's running in to is in application targeting desktop framework.

**Comment by pranavkm** [comment]
Bump @tmat \ @agocke

**Comment by tmat** [comment]
@pranavkm Why not use Portable PDBs? That would avoid this extra dependency on DiaSymReader.Native.

**Comment by pranavkm** [comment]
@tmat we addressed this in our more recent releases to use the pdb format that the project's compiling with. The primary reason for using full pdbs was to get line mappings and consequently better error pages when targeting .NET Framework < 4.7.1.

**Comment by tmat** [comment]
I see.

**Comment by tmat** [comment]
The error `Windows PDB writer is not available ...` comes from the compiler. `Microsoft.DiaSymReader.Native.amd64.dll` needs to be next to `Microsoft.CodeAnalysis.dll`.

**Comment by pranavkm** [comment]
This is the bit I'm confused about. I created an application targeting `net461` and published it. The output directory contains Microsoft.CodeAnalysis.dll, but no signs of `Microsoft.DiaSymReader.Native.amd64.dll`. Yet, views compile just fine. What is it that causes it to work on my machine, but fail on others?

**Comment by tmat** [comment]
I do not know how the Roslyn compiler is invoked in ASP.NET for the view compilation.

**Comment by pranavkm** [comment]
We invoke Roslyn's APIs as part of the app. Relevant types

* https://github.com/aspnet/Mvc/blob/release/1.1/src/Microsoft.AspNetCore.Mvc.Razor/Internal/CSharpCompiler.cs
* https://github.com/aspnet/Mvc/blob/release/1.1/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DefaultRoslynCompilationService.cs#L59-L108

Essentially boils down to newing up a `CSharpCompilation` instance for generated code and emitting it. On desktop, the type of pdb is determined by the presence of the SymWriter component - https://github.com/aspnet/Mvc/blob/release/1.1/src/Microsoft.AspNetCore.Mvc.Razor/Internal/SymbolsUtility.cs#L15. If we do not find it, we default to generating portable pdbs.

**Comment by pranavkm** [comment]
Bump @tmat

**Comment by pranavkm** [comment]
Spoke to @tmat offline and I have a slightly better understanding of this. There is a diasymreader component that is installed by the .NET Framework that compilation uses by default. We weren't entirely sure why it's missing in your specific scenario resulting in the exception you see. That said, the correct \ recommended solution, that you discovered on your own, is to reference the `Microsoft.DiaSymReader.Native` package in your project. 

Unfortunately, adding a new package reference to shipped packages when a workaround exists, is unlikely to make it as a patch candidate. We'll address this in 2.1.0 by adding a package reference to Razor: https://github.com/aspnet/Mvc/issues/7478
