### ISSUE TITLE
Generate MPacks when building on non-windows.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1966]
We used to disable MPack generation on non-windows systems because we would use powershell to zip mpacks. Now that the `ZipArchive` task is fixed we should go back to building MPacks on non-windows.

**Comment by NTaylorMullen** [comment]
5c6ff4366f8f0b9e414bd9632fd50ed438f44ebb

**Comment by NTaylorMullen** [comment]
@ToddGrun @KirillOsenkov you guys can now build MPacks on non-windows systems.

**Comment by KirillOsenkov** [comment]
:+1: cc @davidkarlas

**Comment by rynowak** [comment]
We still need to solve portable PDBs it sounds like, but this is a start

**Comment by KirillOsenkov** [comment]
Filed https://github.com/aspnet/Razor/issues/1968 to track this.

**Comment by rynowak** [comment]
Thanks!
