### ISSUE TITLE
Generate portable .pds for the .mpack

### ISSUE THREAD

**Issue by KirillOsenkov** [aspnet/Razor#1968]
Ideally if we can we should just add the portable .pdbs for all .dlls directly into the .mpack.

**Comment by NTaylorMullen** [comment]
> Ideally if we can we should just add the portable .pdbs for all .dlls directly into the .mpack.

Is adding the pdbs to the mpack the expected way to ship PDBs for addins?

**Comment by KirillOsenkov** [comment]
I guess it's the most comfortable one for the debugging experience - debugging will just work and you won't have to worry about adding any additional symbol servers or any other actions. 

@mhutch

**Comment by mhutch** [comment]
Yes, that's currently the only way to get symbolicated stack traces for a deployed extension

**Comment by rynowak** [comment]
That sounds fine to me if you're all happy with it 😆.

**Comment by NTaylorMullen** [comment]
@mhutch @KirillOsenkov is there anything we need to update/add in the manifest/addininfo to account for PDBs or will their presence in the mpack be sufficient?

**Comment by KirillOsenkov** [comment]
Yeah as long as they're next to their corresponding .dll that should be enough. Thanks!

**Comment by NTaylorMullen** [comment]
83c31f611f12e375ebea419d264bc094af6ce832
