### ISSUE TITLE
Change Razor tooling to work with multiple Workspaces

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1973]
Today Razor is bound to the idea of a primary workspace which has pieces added and removed from it. Today, this is how VS windows operates but in VS mac that's not the case. 

After talking with the Roslyn folks they mentioned that they built workspaces with the idea that each host will define the workspaces longevity; therefore, we need to do the work to make our Razor tooling implementations more host-agnostic when it comes to how they interact with workspaces.

**Comment by NTaylorMullen** [comment]
@ToddGrun @KirillOsenkov all changes required to move away from primary workspace have been checked in. I ran bits locally on MonoDevelop and verified the following scenarios:

- Re-open solution.
- Close Solution
- Change ViewImports
- Changing Razor files.
- Razor errors in C#
- Project changes

I'll keep you updated once we have a signed build available with the new mpack.

**Comment by NTaylorMullen** [comment]
Oh and tested having multiple solutions open simultaneously 😉

**Comment by KirillOsenkov** [comment]
:+1:
