### ISSUE TITLE
[Razor SDK]: Fit and polish - Determine what the right way is to indicate an error when Razor.Design is missing

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#1974]
Based on https://github.com/aspnet/Razor/pull/1964/files#r163731196

The Razor.SDK requires CodeGeneration targets to be present to work. Need to ask around with folks more familiar with writing SDKs what is the quintessential MSBuild approach for this is.

**Comment by pranavkm** [comment]
The WebSdk doesn't have anything equivalent to what we're doing here. Unless you feel super strongly about this, I'm going to use this work item to fix up the error message.

**Comment by rynowak** [comment]
ok

**Comment by pranavkm** [comment]
Placeholder link to use in our error message - https://go.microsoft.com/fwlink/?linkid=868374. Thanks @mkArtakMSFT
