### ISSUE TITLE
Prevent razor pages from being included on the nuget package

### ISSUE THREAD

**Issue by javiercn** [aspnet/Razor#1980]
When creating a class library with precompiled views, those views are marked as content. We should prevent that content from being included in the nuget package.

**Comment by mkArtakMSFT** [comment]
@pranavkm. I believe you have a PR out for this.

**Comment by javiercn** [comment]
This bug is to handle it on the SDK. Pranav did the PR on Identity to fix this.

**Comment by pranavkm** [comment]
Yeah, we would fix this in the SDK for preview2. For preview1, we'll document the workaround
