### ISSUE TITLE
Multiple attributes same name (case insensitive) should bind the first, render the rest

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#199]
Right now if there's a tag helper with: `<form action="something" ActIon="else">` last attribute always wins.  After talks with @DamianEdwards we should create a parse level error IF the attribute is bound by the `TagHelper`, otherwise since HTML5 attributes are case insensitive: last attribute wins.

**Comment by yishaigalatzer** [comment]
Please verify and close

**Comment by NTaylorMullen** [comment]
Updated title since this bug was ultimately about two issues (one of which is resolved). First issue was insensitive attribute names causes the parsing system to throw, this was fixed a while back. Second issue was we should create a parse level error if there's a duplicate TagHelper bound attribute, right now last wins.

**Comment by NTaylorMullen** [comment]
Decided to wait for user feedback on this, moving to backlog milestone for now.

**Comment by yishaigalatzer** [comment]
This is not ok to move to backlog, it will be a braking change at that point. We should either fix or wont fix. If we want to delay we can do it for RTM. Lets decide on Monday.

**Comment by NTaylorMullen** [comment]
This is the issue we decided to not do/wait for user feedback on in our meeting (I just never moved it).

**Comment by yishaigalatzer** [comment]
Sure, so we have two options in my mind. We either throw right (or before RTM) now at runtime, or we call it supported.

**Comment by NTaylorMullen** [comment]
Right now this issue has to wait for user feedback so if we are to take that approach we should probably call it supported until users feel differently :smile:

**Comment by yishaigalatzer** [comment]
Lets talk in person. This just doesn't work

**Comment by dougbu** [comment]
Reopening per discussions with @NTaylorMullen and @Eilon. In general Razor should not simply ignore anything in the Razor source. An error in the `<element asp-hello="goodbye" asp-hello="dude" />` case is the Right Thing:tm:.

W.r.t. the above discussion, note browsers do _not_ implement "last one wins". Razor currently uses the actual "first attribute wins" semantic when determining values for attributes duplicated in an element.

Separately Razor now handles the `<input type="a" type="b" />` case when either no tag helper targets the `<input/>` element or `type` is not bound. Both attribute settings are passed through for the browser to interpret.

**Comment by dougbu** [comment]
Also cleared the "Won't fix" label.

**Comment by dougbu** [comment]
Slightly good news: Noticed the editor in VS shows duplicate attributes as incorrect. Nothing fails at runtime but at least there's a visual indication. Message on hover and in Error List (as long as file is open) is `Attribute 'int-prefix-value1' already exists.`
![capture](https://cloud.githubusercontent.com/assets/6431421/7719378/57477596-fe75-11e4-8f43-184a388ebd4f.png)

**Comment by Eilon** [comment]
That indication is presumably an HTML warning and not a Razor warning, so it's not really what we're looking for.

**Comment by dougbu** [comment]
Right. That's why I said "slightly" :smiley_cat:

**Comment by NTaylorMullen** [comment]
Duplicate of: https://github.com/aspnet/Razor/issues/418
