### ISSUE TITLE
Update VS15.7 default Razor to be 2.1

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#1993]

**Comment by rynowak** [comment]
I think we should think carefully about this. This probably requires some signoff from @DamianEdwards

**Comment by NTaylorMullen** [comment]
Talked with @DamianEdwards and we should be falling forward. In vs15.7 case, default to 2.1

**Comment by rynowak** [comment]
Load balancing this

**Comment by NTaylorMullen** [comment]
done?

**Comment by rynowak** [comment]
d1bf120c5482eb3e983ef50ecdcbe2520a772d47
