### ISSUE TITLE
Improve the running time of Design.Tests

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2003]
The Design.Tests project takes a little longer to run than we'd like, approximately 2m-2.5m on a developer machine. This will likely grow to around 5m when we add the rest of the features and tests

Some ideas for improvement:
- [x] Change the TFM - right now this project is not run in parallel with our other test projects
- [ ] Restore the 'testapp' projects once - right now the test project in use is restored for each build
- [ ] Use a directory inside the repro as a 'scratch' directory - right now the tests use temp, which revs up MS Defender. Most developers exclude their build/src directories from antivirus

**Comment by rynowak** [comment]
@mkArtakMSFT - this is a great MQ work item. @NTaylorMullen loves to complain about this.

**Comment by pranavkm** [comment]
> @NTaylorMullen NTaylorMullen removed this from Ready in Razor 2.2.0 a minute ago
> @NTaylorMullen NTaylorMullen removed this from the 2.2.0-preview3 milestone a minute ago
> @NTaylorMullen closed this a minute ago

😭
