### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.Razor.Language Version=2.0.0.0'

### ISSUE THREAD

**Issue by B-Esmaili** [aspnet/Razor#2013]
suddenly  when i attempt to open razor views in visual studio i get following error :

`could not load file or assembly 'Microsoft.AspNetCore.Razor.Language Version=2.0.0.0'`. how to resolve this issue?

**Comment by NTaylorMullen** [comment]
@B-Esmaili what version of VS are you using?

**Comment by B-Esmaili** [comment]
I am using VS 2017.

**Comment by NTaylorMullen** [comment]
If you do `Help => About Microsoft Visual Studio` what does the "Version" label say?

**Comment by B-Esmaili** [comment]
It is  15.3.4 .

**Comment by NTaylorMullen** [comment]
@B-Esmaili if you go into your installed extensions could you search for Razor Language Service and provide the version of that?

**Comment by B-Esmaili** [comment]
The version is 0.3.

**Comment by NTaylorMullen** [comment]
@B-Esmaili Ahhhh, so sadly there's only 1 way to fix the issue you're seeing. You'll need to repair your VS installation 😢

**Comment by B-Esmaili** [comment]
OK thanks for sticking to problem.i'll do accordingly.
