### ISSUE TITLE
Flaky test: Dispatcher_ProcessSimultaneousConnections_HitsKeepAliveTimeout

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2018]
I set `Dispatcher_ProcessSimultaneousConnections_HitsKeepAliveTimeout` to ignore for now because it [fails](http://aspnetci/viewLog.html?buildId=399383&tab=buildResultsDiv&buildTypeId=Lite_MvcTest#testNameId-5931557005942489049) sometimes. It should be investigated and re-enabled once fixed.

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please investigate this?

**Comment by rynowak** [comment]
Just so there's no confusion, this is the Razor build server

**Comment by mkArtakMSFT** [comment]
Thanks @rynowak. Reassigning to @ajaybhargavb.

**Comment by ajaybhargavb** [comment]
0f1bc0e0bde2a16951ef1687a38e2379d823f385
