### ISSUE TITLE
Anchor target attribute causes warning with tag helper

### ISSUE THREAD

**Issue by vaindil** [aspnet/Razor#2034]
Not sure if this is a VS thing or should be opened here, sorry if it should be over there!

I'm on the latest version of everything, so VS 15.5.6, ASP.NET Core 2.0, .NET Core SDK 2.1.4. When I use the anchor tag helper with the `target` attribute, VS puts a warning on the attribute saying `Attribute is allowed only when 'href' is present.`. The `href` attribute is being generated, however, so this warning shouldn't be there. Example code and a screenshot are below.

```html
<a asp-action="MyAction"
   asp-controller="MyController"
   target="_blank">Some text here</a>
```

![image](https://user-images.githubusercontent.com/771134/35974433-10e5360e-0ca7-11e8-897d-2f21ae70b0ca.png)

**Comment by mkArtakMSFT** [comment]
Thank you for reporting the issue. @NTaylorMullen, any thoughts?

**Comment by NTaylorMullen** [comment]
Totally agree this is an issue. We have another issue tracking the fix for this 😄 https://github.com/aspnet/Razor/issues/1428

**Comment by vaindil** [comment]
Ugh, I searched but didn't find that one. Sorry, thank you!
