### ISSUE TITLE
Using dynamic model is causing error.

### ISSUE THREAD

**Issue by juniorgasparotto** [aspnet/Razor#2040]
Hello,

I'm trying to create a dynamic object and pass a template to a view, but I'm having an error that I can not understand why. Does not Razor support dynamic variables with more than level?

**Controller:**

```
public IActionResult Test()
{
      ViewBag.Obj = new { Name = "test" };
      return View();
}
```

**Razor "Index.cshtml":**

```
<html>
<body>
    <p>@ViewBag.Obj.Name</p>
</body>
</html>
```

**Error:** 

> RuntimeBinderException: 'object' does not contain a definition for 'Name'

**Comment by rynowak** [comment]
Hi, @juniorgasparotto - this is not really an issue with Razor exactly, as well you could easily encounter the same problem with any .NET code.

`dynamic` and anonymously-typed objects aren't really related features, even though they seem like they should work well together. Anonymously-typed objects always give their properties a visibility of `internal`. `dynamic` - when applied to an object that doesn't implement `IDynamicMetaObjectProvider` - in other words a *normal* .NET object - will only consider visible properties. Razor code that's compiled at runtime is in another assembly from your app's compiled code and so it doesn't have visibility into anything internal.

You can see where this is going.

-----

You could see a similar problem by doing something like the following:
```
// In A.dll
public class A
{
    internal string Foo { get; set; }
}

// In B.dll
public static void DoDynamicStuff(dynamic obj)
{
    Console.WriteLine(obj.Foo);
}
```

This would fail in the same way.

---

You can use `ExpandoObject` in place of your anonymously-typed object if you something that will work the way you described.

**Comment by juniorgasparotto** [comment]
Thank you very much, I understand the problem and I'm closing the issue.
