### ISSUE TITLE
DocumentWriter.Create should be static

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2041]
See: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/CodeGeneration/DocumentWriter.cs#L11

This method was supposed to be static so that callers could create a writer and use it. Unfortunately we missed this 😢. The workaround is to do some [pretty awful stuff](https://github.com/aspnet/Blazor/blob/dev/src/Microsoft.AspNetCore.Blazor.Build/Core/RazorCompilation/Engine/BlazorLoweringPhase.cs#L39)

Suggestion:
- Make a new method to avoid confusion `CreateWriter(...)` and make it static
- `[Obsolete]` and `EditorBrowsableNever` the old one

Yeah, this is bad enough that **I** even think that it calls for EdtitorBrowsableNever

/cc @pranavkm for EditorBrowsableNever

**Comment by pranavkm** [comment]
> /cc @pranavkm for EditorBrowsableNever

🥇
