### ISSUE TITLE
MethodDeclarationIntermediateNode needs to support parameters

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2043]
`MethodDeclarationIntermediateNode` needs to have support for parameters

The main idea of Razor's code-generation extensibility is that as long as your structure can be represented by a class with methods, that our IR is general enough to be useful, and you can turn it into code however you want.

This breaks down when one of the main pieces like the `MethodDeclarationIntermediateNode` doesn't support parameters, and makes the experience fall apart.

**Comment by mkArtakMSFT** [comment]
@rynowak, is this critical to be part of 2.1?

**Comment by rynowak** [comment]
This was fixed as part of 59a1cf929379a93912401201eea84915d7edee62
