### ISSUE TITLE
Support solution explorer nesting in Razor SDK

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2047]
The solution explorer nesting of files in Razor Pages scenarios isn't showing up without the web sdk. We need to figure out what we need to add for this.

**Expected**
```
  +Pages/Index.cshtml
        Pages/Index.cshtml.cs
```

**Actual**
```
  Pages/Index.cshtml
  Pages/Index.cshtml.cs
```

**Comment by rynowak** [comment]
To do this work we need to add the following to our design time .props when the Web SDK isn't in use.

https://github.com/aspnet/websdk/blob/master/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.targets#L46

**Comment by pranavkm** [comment]
I moved the capabilities over, but it does not have any effect in itself. It works correctly if I change the class library to target Web.Sdk. Maybe we're missing an additional setting here. I'll follow up with @BillHiebert

**Comment by pranavkm** [comment]
Blocked on some VS binaries to become available. Need to work with tooling folks to get this unblocked.

**Comment by pranavkm** [comment]
We'll rely on WTE to provide the IDE tooling to light up the nesting in 15.7 Preview 2. The only change we need to do in the RazorSdk is specify project capabilities.

**Comment by pranavkm** [comment]
Verified that this work with `2018-03-05_b4836`
