### ISSUE TITLE
Update PipeOptions once https://github.com/dotnet/corefx/issues/25427 is fixed

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2056]
We will need to rely on the new setting introduced by https://github.com/dotnet/corefx/issues/25427 to provide a secure experience with the build server.

It's likely we'll need to use the constant value of this new enum to pass the correct value.

**Comment by rynowak** [comment]
This should be unblocked now

**Comment by ajaybhargavb** [comment]
Just checked and we have picked up a build of corefx that contains this fix. I'll work on this now.

**Comment by ajaybhargavb** [comment]
This is now blocked on https://github.com/dotnet/corefx/issues/28371.

**Comment by Eilon** [comment]
Is this still going to happen for Preview2? Is this a must-have for Preview2?

**Comment by ajaybhargavb** [comment]
Yes. This is a must-have for preview2. I am constantly checking for a new release/2.1 corefx build with the fix.

**Comment by Eilon** [comment]
Got it, thanks!

**Comment by natemcmaster** [comment]
We have a prodcon build now. Microsoft.NETCore.App 2.1.0-preview2-26403-06.

See https://github.com/dotnet/versions/blob/master/build-info/dotnet/product/cli/release/2.1/build.xml

**Comment by ajaybhargavb** [comment]
b1007744b00ce094af080602ee26d3887a786d56
