### ISSUE TITLE
Support TagName lookups for @addtaghelper and @removetaghelper

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#206]
Right now `TagHelper`s can only be resolved via an assembly name or both an assembly and type name. We should add the ability to add/remove `TagHelper`s based on `TagName`.

Ex:

```
@addtaghelper "<p>, FooAssembly" @* Adds TagHelpers that target the 'p' tag within the FooAssembly assembly *@
@removetaghelper "<p>, FooAssembly" @* Removes TagHelpers that target the 'p' tag within the FooAssembly assembly *@
```

One somewhat unique case that no-ops for `@addtaghelper` is: `@removetaghelper "<p>"` which removes all p tags on the current page.

**Comment by Eilon** [comment]
Doesn't sound like this is important, so closing.

cc @DamianEdwards @rynowak FYI.
