### ISSUE TITLE
Razor Pages Reference Directories

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Razor#2063]
Reference Directories would allow Razor Pages living in other directories to be included in the Pages structure.

Razor Pages builds routing from the folder structure of the Pages (or other specified) directory. It would be nice to be able to create a folder in the directory that points to another location - a virtual directory. This would allow reusing pages, and composing Razor Page sites from sets of reusable pages.

For example -
Currently, I have a set of pages for an "approval" process.
```
Pages
   Requests
       Approvals
           Review.cshtml
           Approve.cshtml
```
`http://Requests/Approvals/Review`

I want to be able to reuse those pages to approve other things, and keep my route logically clean. AFIK, I would need to duplicate those pages
```
Pages
   Requests
       Approvals
           Review.cshtml
           Approve.cshtml
   Results
       Approvals
           Review.cshtml
           Approve.cshtml
```
`http://Results/Approvals/Review`

Reference Directories would let me move this common set of pages into another director, and reference it from the pages directory.
```
ReusePages
       Approvals
           Review.cshtml
           Approve.cshtml
Pages
    Requests
       Approve[ReusePages/Approvals]
    Results
        Approve[ReusePages/Approvals]
``` 
```
http://Requests/Approve/Review
http://Results/Approve/Review
```

**Comment by pranavkm** [comment]
> Reference Directories would let me move this common set of pages into another director, and reference it from the pages directory.

* What would a reference look like? Is it a directive in the page? 
* There's quite a few Razor semantics that involve the location of the file e.g. things like `_ViewImports` \ `_ViewStart`, ;ookup for partials, layouts etc that are relative to the current page's location. What would these look like with this feature i.e. are these lookups relative to the original path or the mapped path?
* Couldn't you do this with a partial today? Have each Razor page has a single line that invokes the partial? Avoids the need for a new feature.

**Comment by mkArtakMSFT** [comment]
@rynowak , do you have any additional feedback regarding the ask here?

**Comment by RandyBuchholz** [comment]
@pranavkm The implementation would likely live in the space between solution explorer and the routing engine. There should be no changes or impact to the pages themselves - pages aren't aware they are reuse targets, and "calling" pages don't need to be aware of a next step in a workflow.

I can see it working something like this-
I have a Razor Page, say something simple like a "Thank You" page - `ThankYou.cshtml`. It just says, "Thank You". It lives in a folder in `Pages\Workflow1`. At the end of a workflow, I say "Thank You", by using this route `Workflow1/ThankYou`. 
I want to be able to reuse this page at the end of many workflows - to add this to my routes in different places.
```
http"//Workflow1/ThankYou
http://Workflow2/ThankYou
```
The "calling" pages have no need to know about it. It is not part of them, or related to them, so things like partials add an unnecessary dependency.
I create a folder in Solution Explorer called `ReusePages`. To keep the example simple, I add a folder called `ThankYou`, move the page there and rename it `index.cshtml` (so it is picked up by default).

Next, I use the new feature. In the `Workflow1` folder, I create a new `ReferenceFolder`. I can see creating a folder, right-clicking, and selecting `ConvertToReference`. It asks me for the folder name, or lets me click on a folder in Solution Explorer. I select `ReusePages\ThankYou`.
In Solution Explorer, the folder could change color, and the name would change to `ThankYou [ReusePages\ThankYou]` Conceptually, this creates alias for the routing engine to use. I now still have a route available called ` http://Workflow1/ThankYou`, but the routing engine will translate that to the application path `/ReusePages/ThankYou/`. (And pick up `index.cshtml`)  Approaches can allow selecting the `_layout` from either place.

So this feature has nothing to do with the pages themselves (but possibly the layout they use), only routing.

A more common use would be for sets of pages, not individual pages. In this case, you wouldn't rename the page to `index.cshtml`. Say I have a set of "Payment Pages" to process a payment. Together, these represent a "Payment Module". I could create `Pages/Payments/[page]`, and redirect there from multiple pages with links, but again I may be creating an artificial dependency. The page I'm coming from shouldn't really need to know the next step. I may want to determine the step dynamically. I use the same approach and create `ReusePages/Payments/GetCard.cshtml`. From the page `Shopping/Books/Cart` I can go to `Shopping/Books/Payment/GetCard`.

Not only does this give me a way to reuse pages and page groups, it keeps cross-page dependencies minimized. Also, I (and the user) get informative and contextual URL's. When I reach `Payments`, the original URL tells me that they were shopping for books.

This even improves maintenance. It's a form of DI (sort of :)). I can replace my entire payment system by simply changing where the reference folder points. My "Interface" consists of the folder path and file names. As long as two sets match, the URL's don't change. To need to touch the pages.

**Comment by mkArtakMSFT** [comment]
Hi @RandyBuchholz. Thank you for your suggestion. We've decided not to take this feature in as that is not a direction we want to take the framework in.
