### ISSUE TITLE
Separate VS/DesignTime properties from general SDK properties

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2069]
We want to make changes to support a design where the SDK always includes **some** things from the current version of visual studio. This helps us have a consistent VS experience when the SDK is old and VS is new.

Example here: https://github.com/aspnet/websdk/blob/master/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.targets#L36

The kinds of settings that should go in there are things like our capabilities and property xaml rules.

**Comment by pranavkm** [comment]
Attempting to work with @joeloff if there's a way for us to deliver the DesignTime target file in the Razor VSIX. This impacts where the file gets put, so affects this work.
