### ISSUE TITLE
Razor Pages & Partial View Loading with Ajax

### ISSUE THREAD

**Issue by fulviocanducci** [aspnet/Razor#2073]
How to load Partial View with Ajax in Razor Pages?

**Comment by mkArtakMSFT** [comment]
Hi @fulviocanducci. Partial Views are aimed to create modular and reusable view sections to be rendered as part of the main view. While it's not intended to be used for the scenario you're describing, it is technically possible to expose an API on server side, which will return a `PartialViewResult` and then merge that result with the DOM from your JavaScript code.

**Comment by fulviocanducci** [comment]
Good afternoon, I've read this documentation and really does not say anything about calling code snippets rendered with Ajax calls, for example:

```
namespace TesteAjaxPartialViews.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public PartialViewResult DefinicaoArquitetura()
        {
            return PartialView();
        }
    }
}
```
---

```
<script type="text/javascript">

    function atualizarDefinicao() {
        $.ajax(
        {
            type: 'GET',
            url: '/Home/DefinicaoArquitetura',
            dataType: 'html',
            cache: false,
            async: true,
            success: function (data) {
                $('#definicaoArquitetura').html(data);
            }
        });
    }

    $(document).ready(function () {
        setInterval(atualizarDefinicao, 30000);
    });

</script>
```

Source: https://www.devmedia.com.br/asp-net-mvc-e-ajax-atualizando-o-conteudo-de-partial-views-via-jquery/26232


This was done in MVC would you like to know if you have how to do this with Razor Pages?
