### ISSUE TITLE
Razor build tasks should validate Configuration

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2079]
The tag helper task needs some parameter validation https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Tasks/RazorTagHelper.cs

And the generate task needs to validate configuration  https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Tasks/RazorGenerate.cs#L39

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb , can you please look into this? Thanks!

**Comment by ajaybhargavb** [comment]
d8e363d99c07d3afc5991dadb67a3352bb19c106
