### ISSUE TITLE
RazorProjectEngineBuilder.AddDefaultImports should take a source document or a string

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2080]
We merged this from our tests into the product, but it accepts params of `RazorProjectItem` which isn't a very useful type for extenders. This should be cleaned up to take strings or source documents.

**Comment by NTaylorMullen** [comment]
How would this work with our `IImportProjectFeature` (returns project items) and the various APIs that consume those imports?

If we were to go this route I would suggest enforcing a null file path on the default import source documents.

**Comment by rynowak** [comment]
The infrastructure would create the project item for you. It's a pain to have to stub out this class just so you can add some usings 😆

**Comment by NTaylorMullen** [comment]
c5e83c61f89037647c13169983a42d9d342ea850
