### ISSUE TITLE
Obsolete all the IRazorEngineBuilder APIs.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2082]
Now that we've moved to RazorProjectEngineBuilder we should actually obsolete all of the IRazorEngineBuilder APIs

**Comment by Eilon** [comment]
Please refer to breaking change *guidelines* here: https://github.com/aspnet/Home/wiki/Engineering-guidelines#breaking-changes

**Comment by NTaylorMullen** [comment]
@SteveSandersonMS I was going to complete this but I see that you're using the RazorEngine pieces in Blazor. We've replaced `RazorEngine` with `RazorProjectEngine`. It's our primary entry point into parsing Razor now. I'll get out a PR for this issue but i'll hold off on merging until I hear from you that you guys have moved over.

**Comment by rynowak** [comment]
Blazor is currently building against 2.0 so this won't impact them. If/when we start building against 2.1 we will do the needful as part of that upgrade. So I don't think you need to block on this 😆

**Comment by Eilon** [comment]
@NTaylorMullen / @rynowak - were any of these public APIs before? I'm just wondering if this is really a `task` or a bug-hancement? (In other words, is it user-observable, or strictly 100% internal cleanup.)

**Comment by NTaylorMullen** [comment]
user-observable

**Comment by rynowak** [comment]
There are public APIs

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, I'm assigning this to you, as @NTaylorMullen  is going to be out. Please sync up with him regarding what left to be done here.

**Comment by ajaybhargavb** [comment]
f8dc5c470234a490d92eda60e1edcdbe29f1b613
