### ISSUE TITLE
Can't use Razor templates with the text tag.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2100]
Example:

```
@{
    SomeMethodThatTakesTemplate(@<text>...<text>);
}
```

This is an extreme edge case but ideally we should be switching into non-text tag special case mode the second we're in an expression.

As far as priority goes this has been there the lifetime of templates + text tag in Razor.

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, what do you think about this?

**Comment by DamianEdwards** [comment]
Not important

**Comment by mkArtakMSFT** [comment]
Closing this per @DamianEdwards's response.
