### ISSUE TITLE
VS Crashes if it cannot read _ViewImports from disk.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2106]

**Comment by rynowak** [comment]
Note that we made some changes to how we read files in general from Razor in 15.7+. That said, it seems fine for us to do some try/catching around viewimports specifically. 

We already ignore a viewimports that isn't present, so it seems fine for us to ignore one we can't read.

**Comment by NTaylorMullen** [comment]
ca8077737b47fbc3114ddfaaf9ce1a8981b7449c
