### ISSUE TITLE
Handle unreadable project items at design time.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2109]
This issue is inspired from [this](https://github.com/aspnet/Razor/issues/2106). The only difference being for us to not take a tactical fix approach for handling unreadable project items at design time.

To expand, we work around a lot of bad cases in our `DefaultProjectItem.Read` VS15.7+; however, in the case that we we're trying to read a file we don't have access to or an underlying OS file operation occurs as we're trying to read (not 100% sure this is possible, but better to be protective) we may get exceptions that can crash VS. We should handle these cases better.

**Comment by ajaybhargavb** [comment]
79e744f691ac21cb007cb47c3b8786b9fef08d4b
