### ISSUE TITLE
Pack should pack pdb (if present) in a symbol nupkg

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2116]
We do some work to ensure the compiled Razor assembly is added to a package. We're missing the equivalent feature to include the pdb in the symbol nupkg.

**Comment by pranavkm** [comment]
This affects symbol publishing for the Identity UI package, a reason to try and address this in preview2.

cc @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, another one for you to handle:) Thanks!

**Comment by pranavkm** [comment]
There's a couple related issues with our path generation for nupkgs. I might take a stab at this later today

**Comment by pranavkm** [comment]
I got this one
