### ISSUE TITLE
[Fit and Polish]: Remove Verifying assembly message printed as part of build with minimal output

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2117]
Building with RazorCompileOnBuild=true produces a "Verifying..." message anytime Razor views are generated \ compiled:

```
1>------ Build started: Project: MvcSandbox, Configuration: Debug Any CPU ------
1>Verifying assembly at .nuget\packages\microsoft.aspnetcore.mvc.razor.extensions\2.1.0-preview2-30190\lib\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
1>MvcSandbox -> \Mvc\samples\MvcSandbox\bin\Debug\netcoreapp2.1\MvcSandbox.dll
1>MvcSandbox -> \Mvc\samples\MvcSandbox\bin\Debug\netcoreapp2.1\MvcSandbox.Views.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Need to tweak the verbosity of whatever's producing the message

**Comment by rynowak** [comment]
Ah, yeah I think that's coming from the CLI

**Comment by ajaybhargavb** [comment]
It's coming from the `ExtensionDependencyChecker` https://github.com/aspnet/Razor/blob/56ead8118a9a5c72816a594652b0c3c8023d216b/src/Microsoft.AspNetCore.Razor.Tools/DefaultExtensionDependencyChecker.cs#L63

**Comment by ajaybhargavb** [comment]
27e6c699e521fefd3eca523405c5efc586d53050
