### ISSUE TITLE
Asp.net Core

### ISSUE THREAD

**Issue by TheTrigger** [aspnet/Razor#2130]
I started a new project to try asp.net core 2.0 following [this microsoft guide](https://docs.microsoft.com/it-it/aspnet/core/).
The fact is **Microsoft.AspNet.Razor** package does not have the correct target framework

![image](https://user-images.githubusercontent.com/6072718/36936053-25bbc384-1f00-11e8-821e-4a02f01fde15.png)

**Comment by pranavkm** [comment]
`Microsoft.AspNetCore.Razor` is the package you need. That said, could you point me to where in the guide it recommends referencing this package? For .NET Core 2.0.0 applications, we recommend referencing the `Microsoft.AspNetCore.All` metapackage - it avoids having to discover and reference individual packages.

**Comment by TheTrigger** [comment]
My bad sorry, you are right, thanks so much
