### ISSUE TITLE
TagHelperDescriptor serializer doesn't roundtrip 'Kind'

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2139]
The 'Kind' property doesn't get roundtripped. Which means that view component tag helpers and blazor components might not work when using the CLI toolset.

I think the problem is here: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.VisualStudio.LanguageServices.Razor/TagHelperDescriptorJsonConverter.cs#L86 - since Kind is read  only I don't think it is serialized by the default serializer.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please look into this? Thanks!

**Comment by ajaybhargavb** [comment]
@mkArtakMSFT @kichalla, I'm taking this issue because this is needed to fix https://github.com/aspnet/Razor/issues/2150.

**Comment by ajaybhargavb** [comment]
fcd4484542733d9666aa981ba8709bb22ce3de4c
