### ISSUE TITLE
Tilde doesn't resolve path in tag helper attributes

### ISSUE THREAD

**Issue by fschmied** [aspnet/Razor#2145]
When I have a custom tag helper, how can I make Razor expand the tilde character within one of its attributes?

Example: Consider the following view, where `MyAnchorTagHelper` is a tag helper:
```
<a href="~/test">Test 1</a>
<my-anchor href="~/test">Test 1</my-anchor>
```

In this view, Razor will expand the "\~" character within the \<a> tag, but not within the \<my-anchor> tag. Is this expected? Can the tag helper be changed to get automatic expansion of "\~"?

(This question is similar to #1554, but the answer in that issue applies only to  `data-*` attributes.)

Tried with both ASP.NET Core MVC 2.0.1 and 1.1.0.

**Comment by rynowak** [comment]
Here's an example: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L147

This is a feature of a tag helper implemented in MVC, it's automatically applied, but you can do the same thing.

**Comment by fschmied** [comment]
@rynowak Thanks for clearing this up - so the `UrlResolutionTagHelper` contains a taxative list of elements and attributes it resolved, which explains why it doesn't apply for my custom tag. I'll reuse it for my custom tag helper situation.
