### ISSUE TITLE
PreserveCompilationContext in old style csproj

### ISSUE THREAD

**Issue by CurlyFire** [aspnet/Razor#2146]
I'm trying to copy the refs folder of my webapplication into the output folder of my test project.  The webapplication is netcore20 and my test project is an old school csproj targeting full 4.7 (has to be for specflow to work). 

I was able to make it work with a newstyle csproj targeting net47 with this instruction in the csproj.  The refs folder was copied into my output folder.
```
  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
```

However, in the old style csproj, the refs folder is not copied and I'm left with precompilation errors when I run my tests.  Can I get some guidance ?  I think PreserveCompilationContext is from dotnet core.. Maybe there's an equivalent in 4.7 ?

I replicated the two scenarios in this repo:
https://github.com/CurlyFire/InProcKestrel

Thank you very much!

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, can you please look into this? Thanks!

**Comment by rynowak** [comment]
PreserveCompilationContext is part of the .NET SDK. If you project is an old style csproj then there's no way to do this.

**Comment by mkArtakMSFT** [comment]
Thanks @rynowak!

**Comment by CurlyFire** [comment]
Thanks @rynowak
