### ISSUE TITLE
Tag helper design question

### ISSUE THREAD

**Issue by drauch** [aspnet/Razor#2158]
We're not sure how tag helpers are intented to be used for our scenario, we'd be glad if you could provide us with some guideline :-)

Scenario: we want a submit-button tag helper:

    <submit-button fx-style="primary"/>
    // converted by our tag helper to the following HTML:
    <button type="submit" class="submit-button-primary" [...morestuffhere...] />

However, this design has the shortcoming that any other tag helper that registers for all `button` tag helpers is not run because they haven't registered for the `submit-button` tag.

Is it now:

a) better to set a very low order on the submit-button tag helper so that the tag is already of type `button` when other tag helpers are run

or 

b) don't use "own-tag-name"-tag-helpers and instead register our tag helper for `button` as well and fall back to the following (not-so-great) Razor HTML:

    <button fx-type="submit" fx-style="primary"/>

What's your take on this?

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen how should @drauch proceed, any suggestions?

**Comment by NTaylorMullen** [comment]
@drauch I might be misunderstanding but dont a & b require you to not bind to `own-tag-name`? If so, in your case I'd recommend you setting the appropriate order (you may want to run after or before other TagHelpers depending on your scenario) and then bind to specific attributes on the button tag so you're only run if your attributes exist. i.e.:

```C#
// Binds to button tags if they have attribute fx-type or fx-style.

[HtmlTargetElement("button", Attributes="fx-type")]
[HtmlTargetElement("button", Attributes="fx-style")]
```

**Comment by drauch** [comment]
@NTaylorMullen : I don't see how I could make a to work with the default button tag instead of our own tag name?

So you say, use the lowest order to convert our "own tag" into the default tag, then order in the ASP.NET defaults like UrlResolutionTagHelper so that their code is executed, and afterwards run any remaining tag helpers on our side that build upon that?

**Comment by NTaylorMullen** [comment]
@drauch ooooh are you just trying to get `~/` resolution on your own TagHelper?

**Comment by drauch** [comment]
Yes, that was the original problem, which made me think and pushed me to ask this "deeper" question.

**Comment by NTaylorMullen** [comment]
Ah, if you want that support you can make your own TagHelper inherit from `UrlResolutionTagHelper` and then call into [ProcessUrlAttribute](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L147)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
