### ISSUE TITLE
Using Microsoft.NET.Sdk.Web on a class library prevents the app to start

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Razor#2161]
Developing a modular application using Orchard Core Framework, I wanted to use the Web sdk for one of the modules containing controllers and razor pages. Can't start the host app anymore. Using Microsoft.NET.Sdk back fixes the issue.

![image](https://user-images.githubusercontent.com/1165805/37422741-2885caac-2779-11e8-880f-f1317234b3b1.png)

**Comment by sebastienros** [comment]
The host application has a `Main`, it's complaining that the class library doesn't have one.

**Comment by pranavkm** [comment]
> Using Microsoft.NET.Sdk.Web on a class library

Microsoft.NET.Sdk.Web is intended for executables - it explicitly sets the `OutputType` to exe. See https://github.com/aspnet/websdk/blob/master/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L20. The suggestion would be

a) To use Microsoft.NET.Sdk.Razor. This should give you the right Sdk behavior and tooling
b) If you're targeting the `preview1` Sdk (or lower), explicitly set `<OutputType>Library</OutputType>` in your class library.
