### ISSUE TITLE
Functional Testing with Razor UI Class Libraries causes 404 Not Found

### ISSUE THREAD

**Issue by Vittitow** [aspnet/Razor#2162]
I'm using aspnetcore 2.1.0-preview which enables the use of Razor UI in separate class libraries. To perform functional testing I'm using the Microsoft.AspNetCore.Mvc.Testing 2.1.0-preview1-final package.

At runtime I'm able to hit the pages in my class libraries however, when using TestServer I get a 404 Not Found response for them. Using TestServer I'm able to hit the pages that are a part of my main project just not the ones in the class libraries.

My main project has references to the Razor UI class libraries via NuGet.

`    public class PositionsPageTests : IClassFixture<WebApplicationTestFixture<Startup>>
    {
        private readonly HttpClient _client;

        public PositionsPageTests(WebApplicationTestFixture<Startup> fixture)
        {
            _client = fixture.Client;
            _client.BaseAddress = new Uri("https://localhost/");
        }

        [Fact]
        public async Task GetAsync_Returns_SuccessStatusCode()
        {
            var response = await _client.GetAsync("/Positions");

            response.EnsureSuccessStatusCode();
        }
    }`

**Comment by javiercn** [comment]
Can you provide the csproj of your class library?

**Comment by Vittitow** [comment]
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <ResolvedRazorCompileToolset>RazorSdk</ResolvedRazorCompileToolset>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <IncludeContentInPack>false</IncludeContentInPack>
    <Company></Company>
    <Authors></Authors>
    <Description>Positions Razor UI for Asset.Positioning</Description>
    <Version>1.0.0-beta</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Pages\**\*.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Pages\Positions.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0-preview1-final" />
  </ItemGroup>

  <ItemGroup>
    <ProjectCapability Include="DynamicDependentFile" />
    <ProjectCapability Include="DynamicFileNesting" />
  </ItemGroup>

</Project>`

**Comment by javiercn** [comment]
Is there a .Views or .PrecompiledViews assembly being produced/copied to your output folder?
Another thing is. Have you disabled shadow copying in your tests?
xunit.runner.json
```json
{
  "shadowCopy": false
}
```

Or better yet. Can you provide us a small repro project?

**Comment by Vittitow** [comment]
The .precompiledviews assembly is being produced and copied to output and I'm using shadowCopy false as well.

Sorry for the delay, he is a repro project.

[https://github.com/Vittitow/TestingMvc](url)

**Comment by javiercn** [comment]
Are you by any chance using `dotnet xunit` to run your tests? 

I can't see anything wrong with your project, I can repro the issue, but at the same time this area has gone a significant overhaul in the past couple of weeks and I have tests for UI in class libraries, so I don't think it reproduces anymore.

I'll include this as part of our plans for verification.

**Comment by Vittitow** [comment]
I'm using Test Explorer in VS2017 Preview to execute the unit tests.

**Comment by yufeih** [comment]
@Vittitow any reason why this is closed, it still repros in 2.1.2

**Comment by yufeih** [comment]
The root cause is Mvc failed to find the DependencyContext for webapp assembly, copy the `webapp.deps.json` to xunit test output will workaround the problem.
