### ISSUE TITLE
IntelliSense is lost on empty line immediately following directives

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2173]
Issue:
```
@page
|
```
don't type the pipe but try and invoke intelliSense at the pipe.

You'd expect for HTML IntelliSense but in actuality you don't get IntelliSense. This seems to be due to our `SpanKind.None` addition; basically we mark the end of `@page` as `SpanKind.None` (expected) but that has an adverse effect of turning off IntelliSense on the line following it (if there's no content). We should be adding a marker symbol after our `SpanKind.None` to indicate to the editor that we expect HTML at that location.

This was originally reported in TFS: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/584082

Putting this in the VS15.7 milestone to correspond with either preview3 or 4.

**Comment by ajaybhargavb** [comment]
9dc7c65205ef1e0a85c39c0fb067acbdcd1bf0b4
