### ISSUE TITLE
Generate AssemblyDescriptionAttribute by default in RazorSdk

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2177]
Microsoft.NET.Sdk generates an `AssemblyDescriptionAttribute` using the `Description` property. We should do the same in the Razor.Sdk with an option to override the value similar to AssemblyTitleAttribute.

**Comment by mkArtakMSFT** [comment]
Closing this now. We have seen no customer ask for this. If there will be customer involvement here, we may reconsider.

**Comment by pranavkm** [comment]
This was fixed as part of https://github.com/aspnet/Razor/commit/8631f287d9b021e0d3cf73336e4b9889ff27fdb0. Marking it as fixed.
