### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by snielsson** [aspnet/Razor#2181]
Cloned and ran build.cmd but got:

C:\Projects\5_Misc\Razor>build.cmd
Downloading KoreBuild 2.1.0-preview2-15728
Using KoreBuild 2.1.0-preview2-15728
C:\Projects\5_Misc\Razor\run.ps1 : A parameter cannot be found that matches parameter name 'CI'.
At line:1 char:126
+ ... ulture = '';& 'C:\Projects\5_Misc\Razor\run.ps1' default-build ; exit ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [run.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,run.ps1

**Comment by rynowak** [comment]
@natemcmaster @pranavkm @ryanbrandenburg is something wacky going down?

@snielsson - thanks for letting us know about this. You can use the `release/2.1` branch, which I know is working and is also current.

**Comment by mkArtakMSFT** [comment]
@natemcmaster, is this fixed already or does @pranavkm need to do something?

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Razor/commit/531f59acc5413874adfc1f0ced3ecc7625c7a262
