### ISSUE TITLE
Add a way to flow Razor editor parsing errors to the IDE

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2193]
Follow up to https://github.com/aspnet/Razor/pull/2192#discussion_r175602613

This is useful for cases like when we want to report an error if we can't read a view import.

**Comment by NTaylorMullen** [comment]
You'll see this error at build time now because of precompilation.

**Comment by mkArtakMSFT** [comment]
We're closing this as the compilation will be failed anyway.
