### ISSUE TITLE
Razor completion for <text> tags

### ISSUE THREAD

**Issue by vank-ms** [aspnet/Razor#2200]
I understand Razor gets opportunities to include C# completion items (like `@page`, `@inject`) and HTML items, which it currently does not participate in.  It would be nice if Razor contributed the <text> tag to HTML completion when appropriate.

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us, @vank-ms.
To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

/cc @DamianEdwards, @danroth27, @rynowak

**Comment by NTaylorMullen** [comment]
> To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

He's just looking to get the Razor `<text>` tag to be included in IntelliSense in the valid contexts (inside of `@{...}`).

**Comment by vank-ms** [comment]
Taylor Mullen asked me to open this issue after a discussion of Razor IntelliSense interaction.
He mentioned that Razor is asked to contribute IntelliSense items twice; once for C# and once for HTML, but it did nothing for HTML.
I asked if Razor could offer the <text> tag when asked for HTML items.
Taylor said ‘good idea’ and asked me to open an issue.  He sent me a link to the location used.

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetCore#5848
