### ISSUE TITLE
Razor extension does not report the right version number in Help->About

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2205]
![image](https://user-images.githubusercontent.com/1430011/37742327-6aadcb06-2d22-11e8-8d81-b4b482476aba.png)

We will likely need to do something like : https://github.com/dotnet/roslyn/blob/14aed138a01c448143b9acf0fe77a662e3dfe2f4/src/VisualStudio/Core/Def/Utilities/ProvideRoslynVersionRegistration.cs

The code that VS gives you out of the box only provides you the ability to pass a hardcoded version, and so that's what we've always done.

**Comment by mkArtakMSFT** [comment]
@rynowak, is this value part of the installer? Who should handle this? Thanks!

**Comment by rynowak** [comment]
We need to figure out some MSBuild junk.... I'm working on the Blazor version of this right now so I'm probably the one to handle it.

**Comment by rynowak** [comment]
This is done. Merged **everywhere**
