### ISSUE TITLE
Re-enable desktop msbuild tests once we have a compatible dotnet-ci

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2208]
VS \ MSBuild on the dotnet-ci Windows agents is an older version and we're currently waiting for an upgrade. In the meanwhile, we'll disable tests that run on desktop to unblock ourselves

**Comment by pranavkm** [comment]
Commit to undo: https://github.com/aspnet/Razor/commit/ac3065a9e16af31b0711d47287cda8d430b5e569

**Comment by mkArtakMSFT** [comment]
@pranavkm, please assign cost to this. Thanks!

**Comment by pranavkm** [comment]
This can be pushed to 2.2.0. We don't have confirmation of images as yet.

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm
