### ISSUE TITLE
Missing pdb inside Microsoft.AspNetCore.Razor.Design.symbols.nupkg

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2215]
For some reason, the symbols nupkg we create for this assembly doesn't contain any pdb files.

cc @pranavkm

**Comment by pranavkm** [comment]
@mkArtakMSFT we'll need this for `preview2` since that's a prodcon shipping requirement.

**Comment by pranavkm** [comment]
Moving this to rc. See https://github.com/aspnet/Razor/pull/2221#issuecomment-376585225

**Comment by ajaybhargavb** [comment]
dc997821ccd7b74c658b845aabff9a6e40a3bcd5
