### ISSUE TITLE
BuildIncremental_SimpleMvc_PersistsTargetInputFile fails on Unix

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2219]
On mine & @ajaybhargavb's Macs this looks to fail consistently.

```Failed   BuildIncremental_SimpleMvc_PersistsTargetInputFile
Error Message:
 Assert.Equal() Failure
Expected: FileThumbPrint { Hash = "2jmj7l5rSw0yVb/vlWAYkK/YBwk=", LastWriteTimeUtc = 2018-03-26T17:22:11.0000000Z }
Actual:   FileThumbPrint { Hash = "2jmj7l5rSw0yVb/vlWAYkK/YBwk=", LastWriteTimeUtc = 2018-03-26T17:22:23.0000000Z }
Stack Trace:
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.BuildIncrementalismTest.<BuildIncremental_SimpleMvc_PersistsTargetInputFile>d__1.MoveNext() in /Users/ntaylormullen/Documents/GitHub/Razor/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/BuildIncrementalismTest.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ajaybhargavb** [comment]
Looks like `SimpleMvc.TagHelpers.Input.cache` is the culprit. It is somehow touched when it shouldn't have been. This only happens locally on High Sierra. I suspect this could be related to https://github.com/aspnet/Razor/issues/2075. Any idea @pranavkm?

**Comment by ajaybhargavb** [comment]
Did some investigation with the help of @pranavkm. Looks like MsBuild is running `ResolveTagHelperRazorGenerateInputs` because it's input (SimpleMvc.dll) changed. We are not sure what caused that. @pranavkm and I agree we should conditionally skip checking this file in tests and leave this issue open for further investigation as this is not critical and appears to be an OS specific quirkiness with MsBuild.

**Comment by ajaybhargavb** [comment]
Need to revert https://github.com/aspnet/Razor/commit/d1215d8fa15d2fa0327b4ef31a8f50301c0d6b2f after fixing this.

**Comment by mkArtakMSFT** [comment]
Hey @ajaybhargavb, I'm putting this in `preview2`. Please cost it. If, however, it turns out to be bigger than 'S', let's talk. We may end up moving to `rc1`.

**Comment by mkArtakMSFT** [comment]
Moving to `rc1` as there is no enough time for this.

**Comment by pranavkm** [comment]
One more failure, this time on Ubuntu:

```
Failed   BuildIncremental_SimpleMvc_PersistsTargetInputFile
10:51:45 RUNDOTNET : error Message:  [/home/dotnet-bot/.dotnet/buildtools/korebuild/2.2.0-preview1-17034/KoreBuild.proj]
10:51:45    Assert.Equal() Failure
10:51:45   Expected: FileThumbPrint { Hash = "2jmj7l5rSw0yVb/vlWAYkK/YBwk=", LastWriteTimeUtc = 2018-04-17T17:51:29.0000000Z }
10:51:45   Actual:   FileThumbPrint { Hash = "2jmj7l5rSw0yVb/vlWAYkK/YBwk=", LastWriteTimeUtc = 2018-04-17T17:51:40.0000000Z }
10:51:45   Stack Trace:
10:51:45      at Microsoft.AspNetCore.Razor.Design.IntegrationTests.BuildIncrementalismTest.<BuildIncremental_SimpleMvc_PersistsTargetInputFile>d__1.MoveNext() in 
```

**Comment by ajaybhargavb** [comment]
Fixing this temporarily 3adb7c966135e9dfb89b941ff8c0daeadee4b324.

**Comment by natemcmaster** [comment]
More test failures:

http://aspnetci/viewLog.html?buildId=468548&tab=buildResultsDiv&buildTypeId=Releases_21Public_OsxUniverse
http://aspnetci/viewLog.html?buildId=468135&tab=buildResultsDiv&buildTypeId=Releases_21Public_OsxUniverse

**Comment by natemcmaster** [comment]
More test failures:

http://aspnetci/viewLog.html?buildId=469664&tab=buildResultsDiv&buildTypeId=Releases_21Public_OsxUniverse

This is persisent on macOS. Can we fix this in the 2.1 branch after RTM?

**Comment by ajaybhargavb** [comment]
@pranavkm and I investigated this and made sure this is not breaking incrementalism. Basically the file's timestamp is changed between builds even without Razor SDK being involved. We've decided to fix the test and move on.

**Comment by ajaybhargavb** [comment]
78f698db96183cd95c041ccca4a1eae85420bd76
