### ISSUE TITLE
Add end-to-end @removetaghelper "type, assemblyName" test

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#222]
Right now we only test `@removetaghelper "assemblyName"` in our end-to-end scenarios. We should add an end-to-end scenario for the specific type (we just unit test it as of now).

**Comment by dougbu** [comment]
Triage: MVC functional tests include both `@removeTagHelper "*, Assembly"` and `@removeTagHelper "TagHelperClass, Assembly"` now.  suggest we do not need additional e2e testing of these cases in the Razor repo.

**Comment by dougbu** [comment]
note: kind-of external and kind-of won't fix but I'm not assigning either label.  covered in MVC repo.
