### ISSUE TITLE
IViewLocalizer and string concatenation

### ISSUE THREAD

**Issue by tverboon** [aspnet/Razor#2225]
I was trying to concatenate localized strings, but it was a little harder than I expected.

Below is the minimum Razor code to reproduce my difficulties, which could perfectly be part of my short comings 😃 

```csharp
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Some"] + " " + Localizer["Value"];
}
```

I was expecting my page title to be `Some Value`, but instead got `Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString`

The following code without concatenation produces `Some` as the expected page title:
```csharp
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Some"];
}
```

After some trial and error, I decide to check the LocalizedHtmlString and used the Value property like this:

```csharp
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Some"].Value + " " + Localizer["Value"].Value;
}
```

And this got me the expected result. Maybe this is by design, but couldn't find a hint in the docs and to me it isn't very intuitive, because without string concatenation it is working as expected.

**Comment by mkArtakMSFT** [comment]
Hi @tverboon. The behavior you're observing is by-design. Adding @ryanbrandenburg for suggestion regarding how this should be handled.
You may need to use [HtmlContentBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.html.htmlcontentbuilder?view=aspnetcore-2.0) to concatenate those  pieces together. @ryanbrandenburg to confirm.

**Comment by ryanbrandenburg** [comment]
Yeah, I think @mkArtakMSFT is correct here, `LocalizedHtmlString` is a more complex type that would benefit from using HtmlContentBuilder.

**Comment by tverboon** [comment]
Hi @mkArtakMSFT, Thanks for your response. I actually do not need `LocalizedHtmlString`, because I just translate a string, as is recommended by the documentation. The `LocalizedHtmlString this[string key]` in ViewLocalizer is not what I need, so now I use:

```csharp
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer.GetString("Some") + " " + Localizer.GetString("Value");
}
```

Is this the recommended way to do this?

**Comment by ryanbrandenburg** [comment]
The way you've done it is fine if you don't have to worry about Html escaping or anything more complex that HtmlContentBuilder would do for you.

Closing this one out. If you have more questions or something is unclear let us know.
