### ISSUE TITLE
Handle Mutex creation failures gracefully

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2226]
This issue https://github.com/dotnet/roslyn/issues/24124 causes the Mutex constructor to throw on Linux causing the Roslyn build server to fail without falling back to the slow process. We need to account for that in Razor build server as well.

**Comment by ajaybhargavb** [comment]
@mkArtakMSFT, it'd be good to handle this in preview2. I'm assigning this to myself.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, you're missing the cost on this one.

**Comment by ajaybhargavb** [comment]
03938dfd956eef8630b5a5a076ebf27ba12a69ff
