### ISSUE TITLE
Clicking a line-mapped error in VS doesn't open a razor file

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2233]
After fixing https://github.com/aspnet/Blazor/issues/453

I noticed that clicking on an error in the error list doesn't open the file in VS, it just does nothing.

The output window works correctly for this. 

--- 

It's also possible that this might be an artifact of the name-mangling that Blazor does in the editor to prevent conflicts between design-time code and the editor.

We should try this out on vanilla 2.1 Razor and see if this problem is limited to Blazor, I recall this working correctly for MVC in VS before.

It's important in this case that the error must come from the build, not from the editor.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
Verified all works in d15.7stg (15.7.0-preview4, 27530.3001)

**Comment by anirugu** [comment]
I should search first before post it here. When I will see preview 4, I see only preview 2 is out.
