### ISSUE TITLE
For missing C# reference, it's going to a compiled code instead of original place

### ISSUE THREAD

**Issue by anirugu** [aspnet/Razor#2236]
I was working in Blazor and when C# code have some error. Clicking on error windows's error doesn't take focus to correct file. It's going to compiled one instead of C# file which have issue.

I have posted this earlier to Blazor. Please check https://github.com/aspnet/Blazor/issues/453

**Comment by NTaylorMullen** [comment]
This ended up not being an issue for Razor. Duplicate of: https://github.com/aspnet/Razor/issues/2233
