### ISSUE TITLE
Upgrade Microsoft.AspNetCore.Razor.Design.Test to target netcoreapp2.1

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2237]
Right now it targets netcoreapp2.0 because [reasons](https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNetCore.Razor.Design.Test/Microsoft.AspNetCore.Razor.Design.Test.csproj#L7). At this point, I'm not sure if we can work around the above reasons.
cc @pranavkm who has more context.

**Comment by ajaybhargavb** [comment]
Assigning to @pranavkm since he already has a PR https://github.com/aspnet/Razor/pull/2293 out for this.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Razor/commit/1e2a1405e57bb4dee487e63f54ede61ac2b27d5e
