### ISSUE TITLE
Diagnostics in DirectiveIntermediateNode are lost

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2238]
The diagnostics that get added to the directive nodes are all lost because we remove all the directives as part of an optimization [pass](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/DirectiveRemovalOptimizationPass.cs#L9). We should lift those errors up before we delete those nodes so they are not lost.

**Comment by mkArtakMSFT** [comment]
Thanks @ajaybhargavb. How big of a work is this? can we try to fit this in `rc`?

**Comment by ajaybhargavb** [comment]
Shouldn't be too big. Costing this as S.

**Comment by ajaybhargavb** [comment]
5504374125290d419d000293b66a98a329d31bb6
