### ISSUE TITLE
Occasional exceptions when disposing the Razor view engine

### ISSUE THREAD

**Issue by drauch** [aspnet/Razor#2241]
We're running a standalone Razor view engine for e-mail templating. Sometimes, when disposing the corresponding service container, we run into ArgumentNullExceptions/IndexOutOfRangeExceptions inside ASP.NET Core within the `System.Buffers.DefaultArrayPool` class. From the outside it looks like `MemoryPoolViewBufferScope` is somehow used in a non-thread-safe manner during disposal, but we're far away from being sure.

Maybe we're doing something wrong when registering the components at the service collection:

    services.AddSingleton(_hostingEnvironment);
    services.AddLogging();
    services.AddSingleton<DiagnosticSource>(new DiagnosticListener("RazorHtmlRenderer"));
    services.AddSingleton<ObjectPoolProvider, DefaultObjectPoolProvider>();

    var mvcCoreBuilder = services.AddMvcCore();

    var fileProvider = new PhysicalFileProvider(_templatesDirectory);
    services.AddSingleton(fileProvider);

    mvcCoreBuilder.AddRazorViewEngine(o => o.FileProviders.Add(fileProvider));
    
    return services.BuildServiceProvider();

Are we registering something as singleton which should not be a singleton? The problem occurs in one out of 10 to 20 disposals. We checked that our Dispose is not called multiple times, so the problem resides somewhere during the Razor view engine disposal...

...any ideas on what we might doing wrong?

Best regards,
D.R.

PS: Typical stack trace we encounter:

    TearDown : System.ArgumentNullException : Value cannot be null.
    Parameter name: array
       at System.Buffers.DefaultArrayPool`1.Return(T[] array, Boolean clearArray)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope.Dispose()
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
       [...]

PPS: We're using version 1.1.x of ASP.NET Core! Also we're running on .NET 4.7.x full framework.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue, @drauch. In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?

**Comment by mkArtakMSFT** [comment]
Thanks @drauch. Glad that things worked out for you. We're going to close this issue. Feel free to open a new one specific for the documentation in the `aspnet/docs` repo.
