### ISSUE TITLE
Razor SDK switch issues

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2243]
<EnableDefaultContentItems>false</EnableDefaultContentItems> doesn't seem to work on netcoreapp projects.

1. Clone ryanbrandenburg/RazorPageLibrary
2. Add `<EnableDefaultContentItems>false</EnableDefaultContentItems>` to App.csproj's propertyGroup
3. Build and run the app in VS and find that it still found the views.

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@pranavkm, moving onto your plate as this seems to be something related to Razor SDK.

**Comment by pranavkm** [comment]
That's not what the switch does - `EnableDefaultContentItems` adds files as content items in the project. This drives the computation of files used in build time compilation and publishing. Mvc at runtime uses files on disk, so this setting would not affect this behavior.
