### ISSUE TITLE
extra space when using condition in Razor.

### ISSUE THREAD

**Issue by anirugu** [aspnet/Razor#2245]
I have this code in my layout file
```
 @if (condition1)
    {
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    }
    else
    {
        <style>
           // my extra css
        </style>
    }
```
This thing render with a extra indent. The indent is used for Visual studio format. So in case I have 17 line. Line inside this condition rendered with a extra indent. Is this could be fixed.

Thanks

**Comment by ajaybhargavb** [comment]
@anirugu thanks for reporting this. This issue has already been reported and is being tracked [here](https://github.com/aspnet/Razor/issues/1076).
