### ISSUE TITLE
View Compilation build error in VS15.7 due to missing references

### ISSUE THREAD

**Issue by ocdi** [aspnet/Razor#2247]
I have a solution with a large number of projects that I am porting to MvcCore. In this solution I have a number of class libraries that contains views. I was using RazorGenerator.MsBuild in the MVC5 days and some view engine hackery to get the main web project to do what you are enabling in 2.1.

I've been trying out the view precompilation using the 2.1.0-preview1, and I'm using VS 15.7 preview 2.

I got the code to the point where it compiles. From the command line invoking dotnet build and dotnet run I haven't had any issues, it is working well.

The issue I am having is building within Visual Studio I am getting build failures on incremental builds due to missing project references being added to the csc command line. This may not strictly be a View Compilation bug, but I am not sure what else to check.

I've installed the Project System extension and looked at the build log. It appears that the ResolveProjectReferences isn't being called to populate these dll's and then has the build failure.

This only seems to be affecting projects containing views where I have enabled the RazorSdk and and RazorCompileOnBuild=true settings. The csc command does appear to be including PackageReferences.

Strangely according to the Build Logging it is when building the main project that has references to the class libraries, that it is failing.

I've managed to reproduce this in a clean class library project. What I did was create a new project on the 2.0 templates, upgraded to 2.1 and created a class library for the views. I've created a common class library and moved the Web models to the Common library. Then I've moved the Account views into the View library. This is referenced from the web project. It seemed to work OK for a single project, however when duplicating the class library I get the same build error in my full solution.

Sometimes it is a bit hard to trigger the bug. The build output looks like this
```
Error occurred while restoring NuGet packages: Object reference not set to an instance of an object.
1>------ Build started: Project: ViewClass, Configuration: Debug Any CPU ------
1>ViewClass -> C:\dev\BugReport\ViewClass\bin\Debug\netstandard2.0\ViewClass.dll
1>ViewClass -> C:\dev\BugReport\ViewClass\bin\Debug\netstandard2.0\ViewClass.PrecompiledViews.dll
2>------ Build started: Project: BugReport, Configuration: Debug Any CPU ------
2>Class1.cs(1,7,1,17): error CS0246: The type or namespace name 'CommonCode' could not be found (are you missing a using directive or an assembly reference?)
2>Class1.cs(12,30,12,39): error CS0246: The type or namespace name 'SomeClass' could not be found (are you missing a using directive or an assembly reference?)
2>Class1.cs(14,30,14,34): error CS0115: 'SomeOther.Test()': no suitable method found to override
2>Done building project "ViewClassSecond.csproj" -- FAILED.
2>Class1.cs(1,7,1,17): error CS0246: The type or namespace name 'CommonCode' could not be found (are you missing a using directive or an assembly reference?)
2>Class1.cs(12,30,12,39): error CS0246: The type or namespace name 'SomeClass' could not be found (are you missing a using directive or an assembly reference?)
2>Class1.cs(14,30,14,34): error CS0115: 'SomeOther.Test()': no suitable method found to override
2>Done building project "ViewClassThird.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========
```
I've attached the binlog and this is the screenshot. It appears that the project is pulling in the dependency, trying to build the class libraries and this is the scenario it is failing.

![image](https://user-images.githubusercontent.com/2775804/38476352-a39f899a-3bf0-11e8-91d0-ae16331504d4.png)

[BugReport_Debug_AnyCPU_Build_2018-04-09T12_20_01.9597168+10_00.binlog.zip](https://github.com/aspnet/Razor/files/1888268/BugReport_Debug_AnyCPU_Build_2018-04-09T12_20_01.9597168.10_00.binlog.zip)

I'll upload the solution that I managed to reproduce to a new git repo.

**Comment by ocdi** [comment]
I've created a repo here: https://github.com/ocdi/BugReport

Note the bug is more reliably triggered when you F5 to run, and when perhaps tweaking the code in one of the class libraries. This isn't the only scenario but there is definitely an issue. Hopefully you can reproduce and/or the binlog is enough to work out where the problem lies.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this?

**Comment by ocdi** [comment]
@pranavkm I just updated to the preview2 bits on my solution, including removing those temporary properties and changing the SDK to `<Project Sdk="Microsoft.NET.Sdk.Razor">` I was about to close this issue but I just had it occur in my main solution again. I will port my BugReport solution to the new SDK bits. I suspect the underlying issue is still there.

**Comment by pranavkm** [comment]
I'll have a look at this today.

**Comment by pranavkm** [comment]
Yup, looks like a bug with the way Razor Sdk wires up to targets and VS does incremental compilation. We should fix this in rc1.

**Comment by pranavkm** [comment]
Also thanks @ocdi for the detailed issue report! The GitHub repo + the binary logs were super convenient to work with.

**Comment by ocdi** [comment]
@pranavkm your welcome 👍 I'm glad you were able to reproduce on your end :-)
