### ISSUE TITLE
Translate helpers to local functions to capture locals

### ISSUE THREAD

**Issue by alrz** [aspnet/Razor#2252]
Currently this is not valid because `@helper` creates a method,
```cs
@{
  var local = false;
}

@helper Helper() {
   if (local) { // ERROR
   }
}
```
With local functions, local `local` will be in scope in the helper body.

**Comment by mkArtakMSFT** [comment]
Hi @alrz.
The use of the `@helper` directive is deprecated in the recent releases.
What are you trying to do? You can change the `Helper()` to a local function yourself and you should have access to the `local` variable.

**Comment by alrz** [comment]
>The use of the @helper directive is deprecated in the recent releases.


Any rationale on that? what is the alternatives? afaik `@helper` was to make reusable html snippets?

> You can change the Helper() to a local function yourself and you should have access to the local variable.

So I assume you mean something like this
```cs
@{
  string Helper() { .. }
}
```
It works for me. But I don't know how this exactly compares to `@helper` helpers.

**Comment by mkArtakMSFT** [comment]
Yes, the snippet you've provided is exactly what I referred to.
RazorViews and local functions cover the functionality you'd get from `@helper`.
I don't remember all the aspects of the `@helper`, so I'd suggest to post a question regarding differences to [StackOverflow](https://stackoverflow.com).
