### ISSUE TITLE
Is there a reason to generate code with Tuple.Create instead of the classes required by WriteAttribute()?

### ISSUE THREAD

**Issue by JendaPerl** [aspnet/Razor#2255]
Is there a reason the code generated from cshtml contains

`WriteAttribute("class", Tuple.Create(" class=\'", 743), Tuple.Create("\'", 812)
, Tuple.Create(Tuple.Create("", 751), Tuple.Create("ft-filter__whisper", 751), true)
, Tuple.Create(Tuple.Create(" ", 769), Tuple.Create<System.Object, System.Int32>(Model.Filters.IsEmpty() ? "" : "active", 770), false)
);`
instead of
`WriteAttribute("class", new System.Web.WebPages.Instrumentation.PositionTagged<string>(" class=\'", 743), new System.Web.WebPages.Instrumentation.PositionTagged<string>("\'", 812)
, new AttributeValue( new System.Web.WebPages.Instrumentation.PositionTagged<string>("", 751),  new System.Web.WebPages.Instrumentation.PositionTagged<object>("ft-filter__whisper", 751), true)
, new AttributeValue( new System.Web.WebPages.Instrumentation.PositionTagged<string>(" ", 769), new System.Web.WebPages.Instrumentation.PositionTagged<object>(Model.Filters.IsEmpty() ? "" : "active", 770), false)
);`

doubling the number of instances created in runtime? The Tuples get converted to the specific classes using implicit conversion operators so why not save CPU cycles and skip the Tuples altogether?

The long strings of WriteLiteral() calls with short string literals do not look particularly efficient either.

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetWebStack#151
