### ISSUE TITLE
Razor Build tasks fail when using different version of assemblies

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2256]
We see errors like the following in the Razor build server when upgrading packages
```
Extension assembly 'Microsoft.AspNetCore.Blazor.Razor.Extensions' at 'C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor.build\0.2.0-preview1-10195\tools\Microsoft.AspNetCore.Blazor.Razor.Extensions.dll' has a different ModuleVersionId than loaded assembly 'Microsoft.AspNetCore.Blazor.Razor.Extensions, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null'
  Extensions could not be loaded. See output for details.
C:\Users\username\.nuget\packages\microsoft.aspnetcore.blazor.build\0.2.0-preview1-10195\targets\RazorCompilation.targets(179,5): error : rzc generate exited with code 1 
```

There are a few issues with this.

It would firstly be great to know which other assembly is loaded and where it was loaded from - my guess is that this happened when updating the packages used by our templates, or by mixing our templates with a repo-local build.

Secondly, I think this is just a bug. The assembly loading logic we use for Razor is supposed to be based on paths for 'top level' extensions, meaning that we should be able to load two copies of `Microsoft.AspNetCore.Blazor.Razor.Extensions`. We should investigate this and see if it's possible.

Lastly, this **must not** fail the build. We expect users to mix and match dependencies and this is intended to 'just work'.

**Comment by ajaybhargavb** [comment]
I'll investigate. @mkArtakMSFT, I'm self-assigning this.

**Comment by ajaybhargavb** [comment]
@mkArtakMSFT, I merged https://github.com/aspnet/Razor/pull/2277 which should fix what we wanted to fix for RC. We should leave this issue open though to address the underlying issue in a later release.

**Comment by mkArtakMSFT** [comment]
Thanks @ajaybhargavb! Moving!

**Comment by ajaybhargavb** [comment]
> Lastly, this must not fail the build. We expect users to mix and match dependencies and this is intended to 'just work'.

This has been addressed in https://github.com/aspnet/Razor/issues/2278. I'll change the title to reflect the work remaining.
