### ISSUE TITLE
Precompiled Views Not Found

### ISSUE THREAD

**Issue by los93sol** [aspnet/Razor#2262]
I'm doing something that I know is unsupported and attempting to host an ASP.NET Core MVC site within a UWP app.  I have Kestrel working, Routing is working and requests hit my controller, but I'm stuck when it comes to Razor.  I have to use views precompiled at build time to do this and I have the *.Views.dll assembly being generated, but I'm getting the following exception when it tries to find the view...

System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
/Pages/Shared/Index.cshtml

**Comment by los93sol** [comment]
Repo so you can see what I'm talking about is here: https://github.com/los93sol/UwpAspNetCore

**Comment by Eilon** [comment]
This is using 2.1.0-preview2 so I think this is maybe the known issue with app parts. @pranavkm / @mkArtakMSFT / @javiercn - does this look the same?

**Comment by los93sol** [comment]
Any updates or additional information on this one?

**Comment by pranavkm** [comment]
@los93sol sorry, I haven't gotten to it as yet. We're in the middle of wrapping up some of our 2.1.0-rc work and I was planning on getting to it later this week this once I was done with that.

**Comment by los93sol** [comment]
No worries, I am just glad it’s on your radar.  If there’s anything I can do in the meantime that would be helpful to sort this out just lmk

**Comment by los93sol** [comment]
@pranavkm Any ideas how I may be able to get around this issue?  I'm not terribly familiar with MVC's internals, but if you can point me in the right general direction of some documentation or the general flow of how views are located/loaded I should be able to figure it out from there.

**Comment by pranavkm** [comment]
@los93sol I tried spending some timing trying to get the app to build \ deploy but I was stuck at the part where I needed to deploy (it looked like I had to set up a client OS with the fall update). Anyway, looking at the code, I think the issue might be that you're adding parts for the main assembly, but not the view's assembly. This *might* work

```C#
var uwpLib = Assembly.Load("UwpAspNetLib");
var partFactory = ApplicationPartFactory.GetApplicationPartFactory(assembly);
foreach (var part in partFactory.GetApplicationParts(assembly))
{
    manager.ApplicationParts.Add(part);
}

var relatedAssemblies = RelatedAssemblyAttribute.GetRelatedAssemblies(uwpLib, throwOnError: true);
var relatedParts = relatedAssemblies.SelectMany(ApplicationPartFactory.GetApplicationPartFactory);
foreach (var part in relatedParts)
{
    partManager.ApplicationParts.Add(part);
}
```

**Comment by los93sol** [comment]
@pranavkm Thanks, I will give that a try.  Since it's built using the background task UWP template I think it has to be deployed to a machine that supports headless operation, in my case that is a Pi 3 running iot core.

**Comment by los93sol** [comment]
@pranavkm Just tried your suggestion, but the issue there is that GetRelatedAssemblies throws an exception because internally it is calling Assembly.LoadFile and that throws because it is not supported in appx.  I am able to manually load the UwpAspNetLib.Views dll but the Views are not found when doing it that way.  I'm guessing there is some logic that is explicitly checking for assemblies loaded as related assemblies or something?  I would expect to be able to plug up some attributes manually to make this happen, I just don't know where to look in the code to see which assemblies are being searched.

**Comment by los93sol** [comment]
I think I see the issue, it looks like the Microsoft.AspNetCore.Mvc.Razor.Compilation.ViewsFeatureProvider is looking for a suffix of .PrecompiledViews instead of the new default .Views

**Comment by pranavkm** [comment]
Does your views dll have an `ProvideApplicationPartFactoryAttribute` pointing to `CompiledRazorAssemblyApplicationPartFactory`?

**Comment by los93sol** [comment]
I'm not sure how to check for that, but after setting <RazorTargetName>UwpAspNetLib.PrecompiledViews</RazorTargetName> it appears to be finding the view now but still blows up because internally that feature is calling Assembly.LoadFile which throws because it is not supported in appX.  I think it should be using the IRazorCompiledItemProvider feature instead?

**Comment by pranavkm** [comment]
Yup. You could use a disassembler (ILDasm \ ILSpy) to look at the assembly metadata. My guess it it's there. Alternatively, just call `CompiledRazorAssemblyApplicationPartFactory.GetDefaultApplicationParts` on the views dll and add those as application parts.

**Comment by los93sol** [comment]
Awesome!  It works!  I need to go through this more and clean things up, but what I did to hack through it was to implement a custom ViewsFeatureProvider that loads the assembly a little differently and my UWP app is now serving pages up using MVC!  Thank you for your help getting that last bit sorted!

**Comment by pranavkm** [comment]
Great! Feel free to start a new issue if you run in to anything interesting.
