### ISSUE TITLE
Improve testing strategy for the Razor Parser

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2263]
Our strategy for testing the Razor parser leaves much to be desired. Writing new tests is very expensive, and understanding deltas when tests fail is tedious and error prone.

We should adopt a strategy similar to what we use for our integration tests. More details here: https://github.com/aspnet/Razor/issues/2211

The first step would be to define a framework for these tests (using serialization/baselines), and then pivot our existing tests in a series of steps to use baselines rather than in-code verification. Once this is done we can introduce more invariants in the tests and have confidence that these invariants are maintained across all of our parser tests.

Checklist:
- [x] CSharpVerbatimBlockTest (Ajay)
- [x] CSharpAutoCompleteTest (Ajay)
- [x] CSharpBlockTest (Ajay)
- [x] CSharpDirectivesTest (Ajay)
- [x] CSharpErrorTest (Ajay)
- [x] CSharpExplicitExpressionTest (Ajay)
- [x] CSharpImplicitExpressionTest (Ajay)
- [x] CSharpNestedStatementsTest (Ajay)
- [x] CSharpRazorCommentsTest (Ryan)
- [x] CSharpReservedWordsTest (Ryan)
- [x] CSharpSectionTest (Ryan)
- [x] CSharpSpecialBlockTest (Taylor)
- [x] CSharpStatementTest (Taylor)
- [x] CSharpTemplateTest (Taylor)
- [x] CSharpToMarkupSwitchTest (Ryan)
- [x] CSharpWhitespaceHandlingTest (Taylor)
- [x] HtmlAttributeTest (Ajay)
- [x] HtmlBlockTest (Ajay)
- [x] HtmlDocumentTest (Ajay)
- [x] HtmlErrorTest (Taylor)
- [x] HtmlTagsTest (Taylor)
- [x] HtmlToCodeSwitchTest (Ryan)
- [x] TagHelperBlockRewriterTest (Ajay)
- [x] TagHelperParseTreeRewriterTest (Ajay)
- [x] WhiteSpaceRewriterTest (Ryan)

**Comment by rynowak** [comment]
@mkArtakMSFT - here's another great MQ item

**Comment by ajaybhargavb** [comment]
b821ce8b8ef1d38d9e3a86af3910b31b1485ae34

**Comment by ajaybhargavb** [comment]
21f2edce16187a04e8e6bef156cf563b52c78bf4
