### ISSUE TITLE
Consider porting improvements from Blazor integration tests

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2265]
I did a few things differently when writing integration tests in Blazor The most notable is that I put all of the test setup (`.cshtml` source code) in the test files themselves. The other nice thing is that I made it easy to add a tag helper from source code embedded in the test.

 It would be worth comparing these two approaches and seeing if there's anything we want to take back to the Razor integration tests.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, can you please work with @rynowak to see what's pending here to be handled? Thanks!

**Comment by NTaylorMullen** [comment]
Pinging to get more detail from @rynowak / @ajaybhargavb to get a more distinct list of what to do here.
