### ISSUE TITLE
.Net Core 2.0 mvc.razor.viewcompilation.rsp build exception MSB3073 exited with code -2147450751

### ISSUE THREAD

**Issue by karelz** [aspnet/Razor#2280]
_From @DenisKot on April 15, 2018 17:46_

Build solution fails with strange error:

> Error	MSB3073	The command ""dotnet" exec --runtimeconfig "F:\TrackTubeNew\Src\TreckTube\bin\Debug\netcoreapp2.0\TreckTube.Web.runtimeconfig.json" --depsfile "F:\TrackTubeNew\Src\TreckTube\bin\Debug\netcoreapp2.0\TreckTube.Web.deps.json" "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Debug\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code -2147450751.	TreckTube.Web	C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets	60	

If double click on error VS opens up file:

> C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets

At line:
`<Exec Command="$(ExecArgs)" WorkingDirectory="$(MSBuildProjectDirectory)" />`

To fix it I've tried to update .net core libraries from version 2.0.0. to 2.0.6, have been update visual studio 2017 to 17.6.6, even revret my changes but nothing is helping.

How to fix it?

_Copied from original issue: dotnet/corefx#29125_

**Comment by karelz** [comment]
_From @DenisKot on April 15, 2018 17:58_

If to set in .csproj 
`<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>`
it builds. But I'm not publishing I'm just debugging.
But it means that it will not compile if I will publish :(

**Comment by karelz** [comment]
_From @kasper3 on April 16, 2018 10:19_

This issue belongs to https://github.com/aspnet/Razor

**Comment by mkArtakMSFT** [comment]
Hi @DenisKot.
Can you please share some details about what you're trying to do  and a sample repro project please, if possible.

**Comment by pranavkm** [comment]
@DenisKot, could you include more of the text from the build output window? It's likely that the app is targeting a version of Microsoft.NETCore.App without having the corresponding version of the shared runtime installed.

**Comment by DenisKot** [comment]
@pranavkm
There is no file in this path bin\Debug\netcoreapp2.0\TreckTube.Web.deps.json
Clean, rebuild and delete bin and obj folder not helping. :(
Output:

> 7>------ Rebuild All started: Project: TreckTube.Web, Configuration: Debug Any CPU ------
7>The specified deps.json [F:\TrackTubeNew\Src\TreckTube\bin\Debug\netcoreapp2.0\TreckTube.Web.deps.json] does not exist
7>
7>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(60,5): error MSB3073: The command ""dotnet" exec --runtimeconfig "F:\TrackTubeNew\Src\TreckTube\bin\Debug\netcoreapp2.0\TreckTube.Web.runtimeconfig.json" --depsfile "F:\TrackTubeNew\Src\TreckTube\bin\Debug\netcoreapp2.0\TreckTube.Web.deps.json" "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Debug\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code -2147450751.
7>Done building project "TreckTube.Web.csproj" -- FAILED.
========== Rebuild All: 6 succeeded, 1 failed, 0 skipped ==========

**Comment by pranavkm** [comment]
Could you change the

**Comment by DenisKot** [comment]
@pranavkm smaller sample archive :) [https://drive.google.com/file/d/1yN03M5Ws1jU5YFGA8vG_fJCIhVCuxJhq/view?usp=sharing](url)

**Comment by pranavkm** [comment]
`<Target Name="AddGeneratedContentItems" BeforeTargets="AssignTargetPaths" DependsOnTargets="PrepareForPublish">` explains the issue. `AssignTargetPaths` is meant to run before and `PrepareForPulish` usually runs after. I'd wager removing `DependsOnTargets="PrepareForPublish"` should work, but I'm not sure why it's being called so invoked so early in the pipeline. If the order of these target invocations cannot be changed, I'd suggest setting `MvcRazorCompileOnPublish=false` and invoking the `MvcRazorCompile` target (https://github.com/aspnet/MvcPrecompilation#enabling-view-compilation) at a later point in your publish pipeline.

**Comment by DenisKot** [comment]
Yep removing DependsOnTargets="PrepareForPublish" helped
Thakns :)
