### ISSUE TITLE
Update Razor runtime package references to Microsoft.CodeAnalysis and Microsoft.CodeAnalysis.CSharp

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2282]
Right now we're referencing 2.6.1, which means that runtime compilation won't work at all with C# 7.2 or 7.3 unless the user takes steps to get newer packages.

**Comment by ajaybhargavb** [comment]
@mkArtakMSFT as discussed offline, marking this ass shiproom approved.
