### ISSUE TITLE
Inherited razor pages model causes null reference exception when base layout is rendered

### ISSUE THREAD

**Issue by mqudsi** [aspnet/Razor#2283]
_(Tested under .NET Core 2.1 `2.1.300-preview1-008174` with `AspNetCore.All` version `2.1.0-preview1-final`)_

Explicitly specifying the layout for a razor page "A" to point to another model-backed razor page "B" where `A : B : PageModel` results in a null reference exception when rendering the cshtml for razor page "B".

To illustrate with an example, given two razor pages `A.cshtml/A.cshtml.cs` and `B.cshtml/B.cshtml.cs` with the following contents:

A.cshtml:
```cshtml
@page
@model Foo.Pages.AModel
@{
    Layout = "B"
}
```

A.cshtml.cs:
```csharp
namespace Foo.Pages
{
    public class AModel : BModel
    {
    }
}
```

B.cshtml:
```cshtml
@page
@model Foo.Pages.BModel

@Model.Bar
```

B.cshtml.cs:
```csharp
using System;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Foo.Pages
{
    public class BModel : PageModel
    {
        public string Bar { get; set; } = "Baz";
    }
}
```

When accessing `/A`, a `NullReferenceException` is thrown as `Model` is undefined. However, the constructor for `BModel` _has_ been invoked, followed by the constructor for `AModel`.

Additionally, the model _is_ passed in correctly as removing the inheritance from `AModel` causes a runtime exception to the effect of "expecting model of class BModel, found model of class AModel."

(This is obviously a highly contrived and stripped down example)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please investigate this? Thanks!

**Comment by kichalla** [comment]
Closing this issue as we haven't received any updates. Feel free to re-open it with additional information.
