### ISSUE TITLE
Render TagHelper to String

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Razor#2288]
It could be useful to be to get the rendered html from a TagHelper, optionally passing a ViewContext. Maybe an extension method.

```
HtmlString str = MyTagHelperClass.ToHtml();
HtmlString str = MyTagHelperClass.ToHtml(attributes); 
HtmlString str = MyTagHelperClass.ToHtml(attributes, viewContext);
``` 
Similar to Rendering views into strings #2274.

**Comment by mkArtakMSFT** [comment]
Hi @RandyBuchholz.
Is there an actual scenario where this would be used?

**Comment by DamianEdwards** [comment]
It's interesting but I don't think it aligns with the areas we plan to focus on in an upcoming release. It overlaps with other ideas we have around Razor templating and even concepts currently being tested out in Blazor so I don't think we'd do a one-off here that would make sense in the longer term.

**Comment by RandyBuchholz** [comment]
I'm really impressed with how Blazor is coming along and the design decisions. Great job!

It would be nice to see WebSockets (with RPC) as a foundational part of Blazor. The ability to JIT Blazor Components would be awesome. So would be the ability to instantiate classes residing on the server in client code, and/or call methods on server-side objects from the client. SPA's are nice, but three-tiered applications with C#-Browser clients would be even better (IMHO). Just as WebAssembly is changing the use of JavaScript, I think WebSockets is changing the use of HTTP. With C# in the Browser and C# on the server, WebAPI can be replaced with WebSocketsAPI, that exposes raw methods on classes, and returns C# objects, even in a binary form - skipping the whole Json encode/decode.

**Comment by mkArtakMSFT** [comment]
Closing per @DamianEdwards's response.
