### ISSUE TITLE
Error - Referencing C# in Script Class Body

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Razor#2289]
In a `<script>` block in a RazorPage, using `@` errors when inside a `class` body. It works fine inside the `constructor` .  

I'm templating some script in my pages using C# and `@`. In most places, using `@xxx` will render text. It errors in VS when used inside the body of a JavaScript Class.

```
// Somewhere
ViewContext.ViewData.Add("Foo", "Bar")

// Works
<script>
    @ViewContext.ViewData["Foo"]
    class TestClass {  }
</script>

// Works
<script>
    class TestClass {
         constructor() {
             @ViewContext.ViewData["Foo"]
         }
    }
</script>

// Error - Unexpected Token
<script>
    class TestClass {
        @ViewContext.ViewData["Foo"]
    }
</script>
```

![image](https://user-images.githubusercontent.com/13967891/38938131-768f1726-42ea-11e8-8a96-f74fac7e0443.png)

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue, @RandyBuchholz.
@NTaylorMullen, can you please look into this?

**Comment by RandyBuchholz** [comment]
@mkArtakMSFT NP. Quick aside. 
I wanted to ping an item related( to `@`)
In Page
```
@{ var green = "green"; }
<style>
   .colorizer{ background-color: @green; }
</style>
```
This used to kill Intellisense and formatting. A release or two ago (I think) Intellisense started prompting the var. But the whole `style` block is still all white (or black) text, and formatting (ctrl-K-D) doesn't work on the block. Curious if you had any status on this. I didn't want to open a new issues as I think there a couple already.

Thanks --RB

**Comment by mkArtakMSFT** [comment]
@RandyBuchholz, there have been several styling /coloring related issues, which the folks owning it are on top of. I have no info regarding the one specific you're referring to.

**Comment by NTaylorMullen** [comment]
Hey @RandyBuchholz could you share more of the View? I'm not seeing your error (also worked without the `@{}`):

![image](https://user-images.githubusercontent.com/2008729/39146507-cfa489c2-46eb-11e8-8dfb-c568374850ae.png)

**Comment by RandyBuchholz** [comment]
@NTaylorMullen, 
I'm on 2.1.300-preview2-008533 and have ReSharper.
VisualStudio.15.Preview/15.7.0-pre.4.0+27617.1 Installed Version: Community
Microsoft .NET Framework Version 4.7.03056

Created a new Web Application w/https, no authentication. Replaced Index content only.
![image](https://user-images.githubusercontent.com/13967891/39154434-bb51b24c-4713-11e8-99c2-953f41b4e624.png)

**Comment by NTaylorMullen** [comment]
@RandyBuchholz I think you must have some other extension installed that's doing that to your document. Following the same repro as you did I get:

![image](https://user-images.githubusercontent.com/2008729/39155570-685cbdfe-4707-11e8-9854-c44134e395df.png)

**Comment by RandyBuchholz** [comment]
Cool, thanks for checking it out.
