### ISSUE TITLE
Publishing a project with UI class library publishes cshtml files from class library

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2295]
The issue crops up regardless of `CopyRazorGenerateFilesToPublishDirectory`  setting. When publishing, Razor SDK removes cshtml files from the current project from being published, but it does not prevent views from referenced UI class libraries from being published. 

Relevant code: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L504-L510

**Comment by pranavkm** [comment]
cc @rynowak \ @DamianEdwards, is this something we want to consider for 2.1.0-rtm?

**Comment by DamianEdwards** [comment]
Yes, should be considered

**Comment by pranavkm** [comment]
Fixed in a94323499bd0bdb048495035b4bab349ed816123
