### ISSUE TITLE
Publishing an app that references a Razor class library does not publish the class library views dll

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2296]
Found this on @jbagga's VM when debugging a publish to Azure scenario. The scenario was Main App references Razor Pages Class Library. When publishing to a folder from VS, the views dll did not get copied over to the publish directory. Publishing from the command line worked fine.

**Comment by los93sol** [comment]
Possibly related, I'm experiencing the same thing https://github.com/los93sol/UwpAspNetCore
To work around the issue I implemented a post build event to copy the Vews dll to my AppX folder.  I also have my wwwroot in my class library and had to add a post build event to handle that as well.

**Comment by pranavkm** [comment]
@kichalla have you seen this in your testing? I've been able to verify this works pretty consistently. 

@los93sol perhaps you're running in to https://github.com/aspnet/Razor/issues/2301 \ #2300?

**Comment by kichalla** [comment]
> @kichalla have you seen this in your testing? I've been able to verify this works pretty consistently.

No, I haven't seen this in my testing.
