### ISSUE TITLE
Completing C# inside single line @{} doesn't complete

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2299]
When doing: `@{th}` and completing `this` the `is` is never inserted.

https://i.imgur.com/QrgltyC.gifv

![image](https://i.imgur.com/QrgltyC.gif)

This seems to be because we don't generate C# place holders in the middle of a single line `@{}`

VSTS Issue: https://devdiv.visualstudio.com/DevDiv/Project%20Cascade/_workitems/edit/602933 

/cc @ToddGrun

**Comment by NTaylorMullen** [comment]
dc76027a7affd0a9fa4bac8bbaf07ed1effdf687

**Comment by KirillOsenkov** [comment]
Confirmed this is indeed fixed in latest VSMac. Thanks!
