### ISSUE TITLE
Razor compiler error doesn't say where the error is for a lone "@"

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#23]
NOTE: This might not be Razor; it could be WebFX, or maybe Katana.

I'm using WebFX and in my Razor view I had an errant `@` laying around (e.g. on a line by itself). I got a compiler error, which is good, but with the Katana default error page it doesn't say _where_ the error was. The error text I got is shown below. What's even worse, if I disable Katana's error page (i.e. don't call `app.UseErrorPage(ErrorPageOptions.ShowAll);`) then the response appears to be aborted and I get nothing at all - just a blank browser window.

```
A first chance exception of type 'Microsoft.AspNet.Mvc.Razor.CompilationFailedException' occurred in Microsoft.AspNet.Mvc.Razor.dll

Additional information: A space or line break was encountered after the "@" character.  Only valid identifiers, keywords, comments, "(" and "{" are valid at the start of a code block and they must occur immediately following "@" with no space in between.
```

**Comment by philmagr** [comment]
Can this be re-opened? 872 doesn't seem to exist, and the problem is still present.

**Comment by Eilon** [comment]
@philmagr I'm guessing it's referring to https://github.com/aspnet/Mvc/issues/872. Can you log a new issue with info about what you're seeing?
