### ISSUE TITLE
Tag Helpers: Investigate Assembly.Load vs. IAssemblyLoader.Load in DTH / Runtime

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#230]
Right now we're utilizing `Assembly.Load` for the `TagHelperDescriptorResolver` which may or may not cause issues in the DTH. We should attempt to use `Assembly.Load` to see consequences when using it in both design time (in DTH) and runtime.

This issue was spawned from the following conversation with @davidfowl  and @pranavkm: https://github.com/aspnet/Razor/pull/226#discussion_r20661671

**Comment by yishaigalatzer** [comment]
We don't think there is anything left to do here. We can revisit if the need arises again.
