### ISSUE TITLE
IRazorViewEngine can find unsupported pathing formats but then fail to support file change notifications.

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Razor#2305]
_From @KhalilMohammad on April 23, 2018 13:28_

I am converting cshtml to pdf.
I am using IRazorViewEngine.
IRazorViewEngine is picking old view.
Dotnet watch does not work for this scenario.
Is there any work around, I have multiple cshtml to work on

_Copied from original issue: aspnet/RazorTooling#121_

**Comment by mkArtakMSFT** [comment]
_From @KhalilMohammad on April 23, 2018 14:5_

I am using [RazorViewToStringRenderer](https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @KhalilMohammad.
@NTaylorMullen , can you please look into this one? Thanks!

**Comment by mkArtakMSFT** [comment]
_From @NTaylorMullen on April 23, 2018 17:21_

@KhalilMohammad how are you using RazorViewToStringRenderer? Aka, are you lifting that method directly into your site? That samples normal usage scenario is run once and then it goes away (an exe) so i'll need more context 😄

**Comment by mkArtakMSFT** [comment]
_From @KhalilMohammad on April 23, 2018 19:26_

I use this generate pdf from html.
In production ,It will be run once.
In development, I need to change html to get perfect alignment.

**Comment by mkArtakMSFT** [comment]
@KhalilMohammad, can you please provide a repro project to simplify the investigation?

**Comment by KhalilMohammad** [comment]
I will provide repo in 2 days

**Comment by KhalilMohammad** [comment]
[Link to example project](https://github.com/KhalilMohammad/RazorHtmlToPdfDemo)

**Comment by NTaylorMullen** [comment]
Hey @KhalilMohammad so quick reason as to why things aren't working entirely is the syntax you're using to find the view isn't supported: `Home/Pricing`. If you move your view into the `Shared` folder and then pass in `"Pricing"` things will work as expected; you can also update your code to pass `"/Views/Home/Pricing.cshtml"` which will also work.

That being said there's still a minor issue here on our end about not validating the paths when our view engine is used outside the context of an action. Basically, we're finding the view you're requesting based off what you provided us `"Home/Pricing"` but the path isn't fully supported so we fail to wire up our cache expiration tokens correctly.

Thanks for the report and the repo!

**Comment by KhalilMohammad** [comment]
@NTaylorMullen that worked like a charm

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
