### ISSUE TITLE
Broken tests: Build_RazorOutputPath_SetToNonDefault et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2311]
These tests [fail](http://aspnetci/viewLog.html?buildId=456588&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally on OSX-Universe

```
No stacktrace available
```

This is likely a dupe of #2309 but we should figure out why we don't get any output when it happens on OSX.

**Comment by ajaybhargavb** [comment]
This was fixed by 813e50087cc64fb8ff1b06868f51836ef1110d31.
