### ISSUE TITLE
Flaky test: WritePidFile_WorksAsExpected

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2320]
This test [fails](http://aspnetci/viewLog.html?buildId=458610&buildTypeId=Releases_21Public_HighSierraOsxUniverse) occasionally with the following error:
```
Assert.Equal() Failure
Expected: String[] ["86330", "rzc", "/Users/aspnetci/Documents/buildAgent/work/33bdfc1c"..., "3db88ac6-de92-4889-b937-0a4f414b3564"]
Actual:   String[] [""]
   at Microsoft.AspNetCore.Razor.Tools.ServerCommandTest.WritePidFile_WorksAsExpected() in /_/test/Microsoft.AspNetCore.Razor.Tools.Test/ServerCommandTest.cs:line 20
```

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb , can you please handle this? Thanks!

**Comment by ajaybhargavb** [comment]
This was fixed in dev. https://github.com/aspnet/Razor/pull/2319. I'm going to just skip this test in 2.1 because the fix involved refactoring product code.

**Comment by ajaybhargavb** [comment]
b2c59700d5a03eb43ba1b145ee7d3b55893e621e
