### ISSUE TITLE
Razor Build Server is not used by VS

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2325]
The check [here](https://github.com/aspnet/Razor/blob/60b6ec047df29e8345bf2625c6f567e7622d0f88/src/Microsoft.AspNetCore.Razor.Tasks/DotnetToolTask.cs#L127) will always fail when we're running on desktop MSBuild - ie in Visual Studio. We're running on .NET Framework and so this API is not defined. 

This means that since we added the necessary security we haven't been able to use build server at all in Visual Studio.

The fix for this is to add ifdefs and add the ACL/elevation checks on .NET Framework. We already cross-compile this assembly.

**Comment by ajaybhargavb** [comment]
41c0a69c5bce704130f3db6db4fa26df77ff3cb6
