### ISSUE TITLE
How to use @lock(from ASP.NET CORE MVC,Razor)?

### ISSUE THREAD

**Issue by Liauner** [aspnet/Razor#2337]
I can't find out about @lock in Google or Asp.net core. (Sorry,my English is not well)

**Comment by mkArtakMSFT** [comment]
Hi @Liauner. You can find some info about it at https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1#section
There's nothing special about it, hence no special topic for it. Hope this helps.

**Comment by Liauner** [comment]
Thank you, I just asked the question because I didn't understand the example, but I tried it last night and found that it is actually the lock syntax in C#. (I'm sorry again that my English is not good enough, so I just used machine translation to express what I mean).@mkArtakMSFT
