### ISSUE TITLE
Name space Auto Complete is not working after @using 

### ISSUE THREAD

**Issue by sohaibahsan007** [aspnet/Razor#2343]
I'm facing this issue in when I want to declare a namespace on a razor page.
![asp razor issue](https://user-images.githubusercontent.com/19934571/39815740-77de93f8-53b2-11e8-8fa2-356d56811e12.gif)

**Comment by mkArtakMSFT** [comment]
Hi @sohaibahsan007. To help us out with investigation, please provide a repro project (ideally as a GitHub repo).

**Comment by sohaibahsan007** [comment]
you can find this by adding a new razor v3 page to your project and can check

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@sohaibahsan007 thanks for the report! We have another issue [here](https://github.com/aspnet/Razor/issues/1460) tracking the fix. Closing this as a duplicate for now.
