### ISSUE TITLE
way to pass access_token to typescript file retrieved using razor syntax

### ISSUE THREAD

**Issue by hnviradiya** [aspnet/Razor#2347]
What is the way to pass **await Context.GetTokenAsync("access_token")** to typescript file.

As storing this to hidden and then use it in typescript file does not seem right to me.

Is there any other way?

I want to set it to default header of axios which is in typescript file. But I am only able to access this value using Razor in cshtml.

**Comment by mkArtakMSFT** [comment]
Hi @hnviradiya.  It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, do we have any guidance for these situations?

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT I don't think we do have any specific guidance that's been through any kind of security review. My first guess would be simply emitting the string into the HTML in some way that the TypeScript code can pick up (e.g., write it out as `<script>window.myValue='some string';</script>` then access `window.myValue` in the TypeScript code). From a security perspective, this is more or less equivalent to any other way of getting a string to the client, in that the value can be accessed by any code that's running on the client but isn't readable to JS code on external origins except if you also have a XSS bug. Maybe @blowdart has views on the preferred approaches to it.

**Comment by blowdart** [comment]
Honestly I'd keep it server side, and marshal all requests through the backend. If the front end isn't asking for the token it's not meant for the front end IMO.

**Comment by mkArtakMSFT** [comment]
@hnviradiya, can you please provide more details about what are you trying to achieve? Describe your scenario so we can better assist you.

**Comment by hnviradiya** [comment]
@mkArtakMSFT I had asked the same question on stackoverflow which is still unaswered. U can refer for more details.

https://stackoverflow.com/questions/50313489/set-access-token-in-httpheader-in-axios-using-typescript-and-webpack

**Comment by hnviradiya** [comment]
Hey guys. Never mind. I have followed following link. So I will Re-Authenticate using typescript.

https://github.com/aspnet/JavaScriptServices/issues/1645
