### ISSUE TITLE
DocumentClassifier should assign a class name when filepath is null

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2353]
https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/MvcViewDocumentClassifierPass.cs#L28

In the above line, when the file path is null, we set the generated class name to null. This makes the CodeWriter throw an exception when generating the code. I think we should fix this as not all Razor documents have file path, for example, default imports.

@NTaylorMullen @rynowak thoughts?

**Comment by ajaybhargavb** [comment]
Just to be clear, this isn't specific to imports. The other scenario this would break is the following. I create a `RazorSourceDocument` out of a string and I pass it in to `Engine.Process`, I want the generated code for that. Right now that would throw an ArgNull.

**Comment by rynowak** [comment]
Sounds like something we should fix 👍

**Comment by ajaybhargavb** [comment]
ad07036020b5df8bd9173dc0ac0096912f0d7553
