### ISSUE TITLE
Copy-pasting an item in an RCL project adds junk to the project file

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2378]
1. Create a new RCL project in VS (2.1 RTM)
2. Copy the `Page1.cshtml` file in solution explorer
3. Paste

You get this.

```
  <ItemGroup>
    <Content Update="Areas\MyFeature\Pages\Page1 - Copy.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>
```

**Comment by pranavkm** [comment]
@mkArtakMSFT could we consider this for 2.1.1? The fix is fairly trivial, but it makes a big difference in terms of user experience.

**Comment by NTaylorMullen** [comment]
620105cc5e180feb4287dbc792a7704110a10982
