### ISSUE TITLE
Add TagHelperContext.Items bag to enable passing values between related tag helpers

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#238]
Add a new property `public IDictionary<string, object> Items { get; }` to the `TagHelperContext` class to facilitate the passing of arbitrary items between Tag Helpers running on the same element.

e.g.
``` C# 
[HtmlElementName("my-tag")]
public class MyTagHelper : TagHelper {
    public override void Process(TagHelperContext context, TagHelperOutput output) {
        context.Items["message"] = "This came from the MyTagHelper class!";
    }
}

[HtmlElementName("my-tag")]
public class MyOtherTagHelper : TagHelper {
    public override void Process(TagHelperContext context, TagHelperOutput output) {
        var message = context.Items["message"];
    }
}
```

**Comment by NTaylorMullen** [comment]
I don't feel like a single bag to communicate between multiple `TagHelper`s on the same elment has a whole lot of value and doesn't help solve the major problem of communicating between child => parent and vice versa.

Ultimately it will be less common for `TagHelper` authors to write multiple `TagHelper`s that communicate among each other on the same element which is why this item should probably be re-thought to provide greater value.

**Comment by dougbu** [comment]
in an offline discussion, thought we ended with agreement some of the existing property bags (`FormContext.FormData`, `ViewContext.ViewData`, likely a few others) had reasonable semantics but not quite the correct scope. this led us to a proposed design where `public IDictionary<string, object> Items { get; }` is backed by a `CopyOnWriteDictionary` and each `TagHelperContext` would initialize that dictionary to its parent's dictionary.
this design provides
- communication of arbitrary information between tag helpers targeting the same element (no harm though likely not a primary scenario, agreed)
- communication of arbitrary information between tag helpers and any tag helper nested within
- worry-free cleanup of per-helper content -- parent and sibling scopes never see a tag helper's changes to its `Items` content
- communication of arbitrary information from nested tag helpers back to their parent; all that's required is the parent creating its (well-known) `Items` entry before executing its childen

**Comment by NTaylorMullen** [comment]
The way this item is worded leads me to believe the `Items` bag is only accessible to `TagHelpers` running on the same element. If that Items bag is communicated down scope-wise via `CopyOnWriteDictionary` then I'm 100% on board.

**Comment by DamianEdwards** [comment]
:+1:

-----Original Message-----

**Comment by NTaylorMullen** [comment]
b95e73e2b05b528f6f029e1bd93d037d16f47130
677df32160dab9754d6ef6155932dd54f3170fe9
