### ISSUE TITLE
Disable creation of new *.Views.dll?

### ISSUE THREAD

**Issue by Tadimsky** [aspnet/Razor#2380]
I'm upgrading to .NET Core 2.1 and ran into an issue during compilation because of an FxCop violation (https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1016-mark-assemblies-with-assemblyversionattribute).
It turned out that the `*.Views.dll` was not compiled with a DLL version. I'm using [GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning) to do versioning of my application DLLs but that seems to not pick up the new `*.Views.dll` output and so it ends up without a version stamp.

Is there some way to disable the generation of this DLL (and keep it part of my ASP.Net Core application)?

**Comment by pranavkm** [comment]
You might be able to get the Views dll to have the version generated by GitVersioniong by adding something along these lines to your project file:

```xml
<Target Name="AddVersionFile" BeforeTargets="PrepareForRazorCompile">
  <ItemGroup>
    <RazorCompile Include="$(VersionSourceFile)" />
 </ItemGroup>
</Target>
```

Alternatively, there are options in the Sdk to disable view generation entirely: https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/sdk?view=aspnetcore-2.1#properties. Note that build time compiled views are meant to improve startup perf and provide build time diagnostics for views rather than compilation failures at runtime.

**Comment by Tadimsky** [comment]
@pranavkm that worked perfectly! Great idea, thank you so much!

Yeah, I definitely wanted to keep it turned on if possible, but this was the last issue in migrating to 2.1 so was looking for a quick way around it. But this is even better :).

Do you think this is something that `GitVersioning` should be able to handle? Or should Razor compilation handle the version file by default if there is one?

**Comment by pranavkm** [comment]
> Do you think this is something that GitVersioning should be able to handle? Or should Razor compilation handle the version file by default if there is one?

We typically generate an AssemblyInfo but rely on the the primary project's properties such as `GenerateAssemblyVersionAttribute` to determine if we should generate it. The GitVersioning targets disable these (https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/Nerdbank.GitVersioning.NuGet/build/Nerdbank.GitVersioning.targets#L42). The thought was that if you did not want the metadata in your primary assembly (or relied on non-default like in your case), the Razor Sdk shouldn't generate any in the Views dll. 

Not entirely sure why GitVersioning doesn't change the default calculated values and let the Sdk generate the assembly info, that would certainly be a nicer solution to the issue. However, adding the file to the `RazorCompile` itemgroup should be just as viable a fix.

**Comment by AArnott** [comment]
NB.GV can certainly incorporate the `<RazorCompile Include="version file" />` workaround.

> Not entirely sure why GitVersioning doesn't change the default calculated values and let the Sdk generate the assembly info, that would certainly be a nicer solution to the issue. 

There was a reason, I don't remember what it was. And that reason existed during the .NET SDK prereleases so it may not even be current. It might simply be that those attribute-generating targets don't always exist (NB.GV exists for a broader set of projects than those that can generate version attributes automatically). 
I'll evaluate both solutions and get something going so NB.GV "just works" for this.

**Comment by pranavkm** [comment]
Great. I guess https://github.com/AArnott/Nerdbank.GitVersioning/issues/186 is tracking further work and I'm subscribed to it in case you need any guidance. Closing this since we don't have to do anything specific with the Sdk here.
