### ISSUE TITLE
Cannot run dotnet build with .NET core 2.1

### ISSUE THREAD

**Issue by inputfalken** [aspnet/Razor#2382]
#### The steps i do in powershell core to create the error. 

*  `mkdir aspnetcore21`
*  `dotnet new razor`
*  `dotnet build`

#### I get the following error after the build step.

```
C:\Users\user\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error : The project C:\Users\user\source\repos\aspnetcore21 must provide a value for Configuration. [C:\Users\user\source\repos\aspnetcore21\aspnetcore21.csproj]
```

**Comment by inputfalken** [comment]
#### Sdks and runtimes that i have.

```
C:\Users\user\source\repos\aspnetcore21> dotnet --list-sdks
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.100 [C:\Program Files\dotnet\sdk]
2.1.101 [C:\Program Files\dotnet\sdk]
2.1.103 [C:\Program Files\dotnet\sdk]
2.1.104 [C:\Program Files\dotnet\sdk]
2.1.105 [C:\Program Files\dotnet\sdk]
2.1.200 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.300 [C:\Program Files\dotnet\sdk]
C:\Users\user\source\repos\aspnetcore21> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
C:\Users\user\source\repos\aspnetcore21>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @inputfalken.
@NTaylorMullen, can you please look into this?

**Comment by NTaylorMullen** [comment]
@inputfalken i'm not seeing this with the latest relesed 2.1.3 bits. Did you happen to install pre-released versions of dotnet (your sdk list has an odd vesrioning for 2.1.4)? Could you try your same repro with dotnet's downloaded from [here](https://www.microsoft.com/net/download/windows) after uninstalling your 2.1.4 pieces.

For instance my setup using released bits (note the versioning of the 2.1.300):
![image](https://user-images.githubusercontent.com/2008729/40993975-d0ae92dc-68af-11e8-8f74-ac55d7309a65.png)

**Comment by inputfalken** [comment]
@NTaylorMullen 

My installation journey  has been to installing `dotnet core sdk` & `dotnet core` with `chocolatey` using the following packages:

* https://chocolatey.org/packages/dotnetcore-sdk
* https://chocolatey.org/packages/dotnetcore

With this setup it worked fine with `.NET core 2.0` but once I upgraded (using`choco update`) to `.NET core 2.1` this problem started.

I have since uninstalled them (using `choco uninstall`) and then installed `.NET core sdk` from the website you linked, but the build problem still remains. 😟

**Comment by pranavkm** [comment]
@inputfalken could you run `dotnet build /bl` and `dotnet msbuild /t:Build /pp:preprocessed.txt` and share the two files?

**Comment by inputfalken** [comment]
* `dotnet build /bl`
    * [msbuild-binlog.txt](https://github.com/aspnet/Razor/files/2073700/msbuild-binlog.txt) (had to change the extension to upload it here)

* `dotnet msbuild /t:Build /pp:preprocessed.txt`
    * [preprocessed.txt](https://github.com/aspnet/Razor/files/2073697/preprocessed.txt)

**Comment by pranavkm** [comment]
This is odd - the preprocessed.txt suggests that you are missing a reference to one of the packages, `microsoft.aspnetcore.mvc.razor.extensions`, that's referenced by `Microsoft.AspNetCore.App`. Could you try clearing your caches and try restoring again:

1) Get a nuget.exe from https://www.nuget.org/downloads
2) Run `nuget.exe locals -clear all`

**Comment by inputfalken** [comment]
I have deleted the `.nuget` directory multiple times. but i will give `nuget.exe locals -clear all` a try as well.

**Comment by inputfalken** [comment]
I still get the same error 😢

**Comment by pranavkm** [comment]
Could you include the `project.assets.json` from your `obj` directory? Maybe it'll has some clues as to why you're missing the reference.

**Comment by inputfalken** [comment]
[project.assets.json](https://github.com/aspnet/Razor/files/2073774/project.assets.txt)

**Comment by inputfalken** [comment]
What i have noticed is that i keep getting this package when doing nuget restore.
`C:\Users\user\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.0\build\netstandard2.0`

**Comment by pranavkm** [comment]
I wonder if your NuGet fallback folder is messed up. From my local build, here's the entry I have in my project.assets.json:

```json
"Microsoft.AspNetCore.Mvc.Razor.Extensions/2.1.0": {
  "sha512": "6V6nLmn/XJdbWGOCg6pb0/LkDDljWFwi4mnLGTKItSMuxZfh+usTkUc8MiVpLf0M0BKBkkTysEQNiwa0C7F7Vg==",
  "type": "package",
  "path": "microsoft.aspnetcore.mvc.razor.extensions/2.1.0",
  "files": [
    ".signature.p7s",
    "build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.Extensions.props",
    "build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.Extensions.targets",
    "lib/net46/Microsoft.AspNetCore.Mvc.Razor.Extensions.dll",
    "lib/net46/Microsoft.AspNetCore.Mvc.Razor.Extensions.xml",
    "lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.Extensions.dll",
    "lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.Extensions.xml",
    "microsoft.aspnetcore.mvc.razor.extensions.2.1.0.nupkg.sha512",
    "microsoft.aspnetcore.mvc.razor.extensions.nuspec"
  ]
},
```

compared to the one from yours:
```json
"Microsoft.AspNetCore.Mvc.Razor.Extensions/2.1.0": {
  "sha512": "6V6nLmn/XJdbWGOCg6pb0/LkDDljWFwi4mnLGTKItSMuxZfh+usTkUc8MiVpLf0M0BKBkkTysEQNiwa0C7F7Vg==",
  "type": "package",
  "path": "microsoft.aspnetcore.mvc.razor.extensions/2.1.0",
  "files": [
    ".signature.p7s",
    "microsoft.aspnetcore.mvc.razor.extensions.2.1.0.nupkg.sha512",
    "microsoft.aspnetcore.mvc.razor.extensions.nuspec"
  ]
},
```

The hashes are identical, which suggests it's the right nupkg file, but maybe something went wrong in the package extraction \ setup. I'd try reinstalling the 2.1.0 Sdk.

**Comment by inputfalken** [comment]
The problem still remains after reinstalling the sdk 😢

**Comment by inputfalken** [comment]
Yes i ran `choco install dotnetcore-sdk --force-dependencies --force - y` (after i uninstalled dotnet sdk from www.dot.net)

Which will reinstall dotnetcore-sdk and all of its dependencies.

then `nuget.exe locals -clear all` followed by `dotnet build`.

**Comment by pranavkm** [comment]
I'm not super sure what I'd suggest to fix this - my guess is `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.extensions\2.1.0` in your machine is likely missing `build` and `lib` directories and consequently you're seeing the error. Installing [the sdk](https://download.microsoft.com/download/8/8/5/88544F33-836A-49A5-8B67-451C24709A8F/dotnet-sdk-2.1.300-win-x64.exe) on a clean machine installs things correctly and the project builds fine. Perhaps https://github.com/dotnet/core-setup/issues might be able to help you with setup \ installation issues.

**Comment by pranavkm** [comment]
Here's what my directory looks like:

```
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.extensions\2.1.0> tree /F
C:.
│   .signature.p7s
│   microsoft.aspnetcore.mvc.razor.extensions.2.1.0.nupkg
│   microsoft.aspnetcore.mvc.razor.extensions.2.1.0.nupkg.sha512
│   microsoft.aspnetcore.mvc.razor.extensions.nuspec
│
├───build
│   └───netstandard2.0
│           Microsoft.AspNetCore.Mvc.Razor.Extensions.props
│           Microsoft.AspNetCore.Mvc.Razor.Extensions.targets
│
└───lib
    ├───net46
    │       Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
    │       Microsoft.AspNetCore.Mvc.Razor.Extensions.xml
    │
    └───netstandard2.0
            Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
            Microsoft.AspNetCore.Mvc.Razor.Extensions.xml
```

**Comment by inputfalken** [comment]
Ah ok, thanks for your help.

I will try my luck in https://github.com/dotnet/core-setup/issues.

**Comment by pranavkm** [comment]
Could you confirm that the directory looks different? Just to be sure I'm not sending you on a wild 🦆 chase

**Comment by inputfalken** [comment]
```
Folder PATH listing for volume Windows
Volume serial number is 507D-3A73
C:.
│   .signature.p7s
│   microsoft.aspnetcore.mvc.razor.extensions.2.1.0.nupkg
│   microsoft.aspnetcore.mvc.razor.extensions.2.1.0.nupkg.sha512
│   microsoft.aspnetcore.mvc.razor.extensions.nuspec
│   
├───build
│   └───netstandard2.0
│           Microsoft.AspNetCore.Mvc.Razor.Extensions.props
│           Microsoft.AspNetCore.Mvc.Razor.Extensions.targets
│           
└───lib
    ├───net46
    │       Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
    │       Microsoft.AspNetCore.Mvc.Razor.Extensions.xml
    │       
    └───netstandard2.0
            Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
            Microsoft.AspNetCore.Mvc.Razor.Extensions.xml
```

**Comment by pranavkm** [comment]
Oh well, so it doesn't look like a setup issue, that directory looks fine.

**Comment by inputfalken** [comment]
Hopefully, I won't need to reinstall windows in order for this to work 😱

**Comment by inputfalken** [comment]
@pranavkm 

I managed to get it to work 😃

What i did was to uninstall `dotnet sdk,` then delete the `C:\Program Files\dotnet` directory and once i installed `dotnet sdk`, i could build again. 🛠

**Comment by pranavkm** [comment]
Great! Not entirely sure how you got into the situation. In case you see this again, you could poke the core-setup team and provide setup logs.

**Comment by thienly** [comment]
I got the same issue after installing latest .net core sdk. With cli, the project can be built successfully but it can't with latest visual studio

**Comment by tidyui** [comment]
I'm having the same issue after trying to updated the libraries of PiranhaCMS (https://github.com/PiranhaCMS/piranha.core) to bump versions to after the DoS vulnerability. After some research (going through all of my `project.asset.json` files) I can see that projects referencing **individual packages of AspNetCore** gets references to `Microsoft.AspNetCore.Razor.Design 2.1.1` referenced, while the example project referencing `Microsoft.AspNetCore.App 2.1.5` gets a reference to `Microsoft.AspNetCore.Razor.Design 2.1.2`.

As the example project builds **last**, the error occurs when it tries loading version `2.1.2` when the previous projects have loaded `2.1.1` in their build process.

An example:

#### Microsoft.AspNetCore.Mvc 2.1.3 

    "dependencies": {
        "Microsoft.AspNetCore.Mvc.ApiExplorer": "2.1.3",
        "Microsoft.AspNetCore.Mvc.Cors": "2.1.3",
        "Microsoft.AspNetCore.Mvc.DataAnnotations": "2.1.3",
        "Microsoft.AspNetCore.Mvc.Formatters.Json": "2.1.3",
        "Microsoft.AspNetCore.Mvc.Localization": "2.1.3",
        "Microsoft.AspNetCore.Mvc.Razor.Extensions": "2.1.1",
        "Microsoft.AspNetCore.Mvc.RazorPages": "2.1.3",
        "Microsoft.AspNetCore.Mvc.TagHelpers": "2.1.3",
        "Microsoft.AspNetCore.Mvc.ViewFeatures": "2.1.3",
        "Microsoft.AspNetCore.Razor.Design": "2.1.1",
        "Microsoft.Extensions.Caching.Memory": "2.1.1",
        "Microsoft.Extensions.DependencyInjection": "2.1.1"
    }

#### Microsoft.AspNetCore.App 2.1.5

    "dependencies": {
        ...

        "Microsoft.AspNetCore.Mvc": "[2.1.3, 2.2.0)",

        ...

        "Microsoft.AspNetCore.Razor.Design": "[2.1.2, 2.2.0)",

        ...
    }

What is the best approach to side-step this problem? Should I add an explicit reference to `Microsoft.AspNetCore.Razor.Design 2.1.2` in all projects getting an implicit reference?

**Comment by olivergrimes** [comment]
Something similar is driving me mad!  
Latest .Net Core SDK (2.1.5) freshly installed.
Latest VS2017 (15.8.7) freshly installed 
When I create a new .Net Core 2.1 ASP.NET application -> All I get is:

![image](https://user-images.githubusercontent.com/10304062/47171701-520fdf00-d301-11e8-9fc9-2afa1a06e081.png)

This probably isn't the right place however after reading this thread it sounded very similar.  Looks like I'm going to have to wipe my computer....

**Comment by tidyui** [comment]
My problem magically disappeared by itself after a while without me doing anything. It’s almost like the old stuff was floating around in memory somewhere and when it finally got garbage collected everything started working. The whole experience was extremely wierd

**Comment by pranavkm** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
