### ISSUE TITLE
[Patch] Copy-pasting an item in an RCL project adds junk to the project file

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2384]
Issue tracking possibly porting this fix for 2.1.x.

**Comment by muratg** [comment]
Approved for 2.1.3.

**Comment by NTaylorMullen** [comment]
> Approved for 2.1.3.

Am I good to merge the corresponding PR?

**Comment by muratg** [comment]
Yes.

**Comment by pranavkm** [comment]
Waiting on @ryanbrandenburg \ @natemcmaster to confirm when the branches are ready for 2.1.3 patch stuff.

**Comment by natemcmaster** [comment]
We are not yet ready for 2.1.3 last I heard. I'll send mail to the team when release/2.1 branches are open for 2.1.3 work.

**Comment by NTaylorMullen** [comment]
80483f08df1212b42a1b3bd45c407e75a5f15a5b
d25a2687e8fe183491b9ae99f9a62dee349af532
