### ISSUE TITLE
[Bug] Razor SDK project publishing fails when contains external assembly references.

### ISSUE THREAD

**Issue by streepteaze** [aspnet/Razor#2390]
Hi!

After updating to AspNetCore 2.1 I experiencing the problem with publishing my MVC project:

### Sample project structure:
![image](https://user-images.githubusercontent.com/772082/41069360-375a2612-69f6-11e8-8f86-cf98cbe6c6cc.png)

1. Sample class library.
2. Razor class library with a project reference to sample class library and using it's class from inside the view.
3. Mvc project contains reference to Razor class library.

Project is building and running as expected in Visual Studio, however I'm getting an error when try to publish it:

` Areas\MyFeature\Pages\Page1.cshtml(5,24): Error CS0234: The type or namespace name 'ClassLib' does not exist in the namespace 'Sample' (are you missing an assembly reference?)`

Here is repo with sample project: https://github.com/streepteaze/razorbug

**Comment by pranavkm** [comment]
@streepteaze this is a dup of https://github.com/aspnet/Razor/issues/2363. We're addressing this in our upcoming 2.1.1 patch release. There's a couple of workarounds listed here - https://github.com/aspnet/Razor/issues/2363#issuecomment-391535844. 

We also have preview builds of the 2.1.1 Sdk with the fix available here: https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1.

**Comment by streepteaze** [comment]
@pranavkm many thanks for pointing out a solution. It works now!
