### ISSUE TITLE
Vue-like directives

### ISSUE THREAD

**Issue by andoband** [aspnet/Razor#2397]
I've grown to enjoy Vue's `v-if`, `v-show`, and `v-for` directives.  Maybe it's because I've gotten used to Vue, but it feels cleaner than the `@if` and `@foreach` blocks used by Razor and Blazor.  Specifically, it's easier for me to visualize the document structure when the code expressions are inlined with the elements versus external to them.  I also like how well it jells with declarative and reactive client-side development.

Could Razor/Blazor add a similar syntax?

I realize this is a personal preference and that there are folks that dislike this declarative style, so I'm not asking to replace the current syntax but rather to add to it in a Blazor-compatible way.

For example:

**Razor/Blazor** (today)
```html
@if (bar != null)
{
    <ul>
        @foreach (var foo in bar) 
        {
            <li>@foo.Name</li>
        }
    </ul>
}
```

**Vue-like** (suggested, or something similar)
```html
<ul @if="bar != null">
    <li @foreach="var foo in bar">@foo.Name</li>
</ul>
```

**Comment by pauldotknopf** [comment]
This isn't solving a problem. It will just confuse any developer/maintainer opening your code for the first time.

**Comment by myty** [comment]
Would this be a good fit for tag helpers? https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-2.1

**Comment by mkArtakMSFT** [comment]
@rynowak, @SteveSandersonMS thoughts regarding Blazor support for this?

**Comment by rynowak** [comment]
Only that this is not a decision we'd make lightly. This changes the core design principles of the language.

**Comment by andoband** [comment]
Totally understand it's not a simple decision.  But it feels like we're almost there conceptually with [tag-helpers allowing us to create a _condition_ tag helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-2.1#condition-tag-helper) (albeit server-side) and [the discussion of item templates for Blazor](https://github.com/aspnet/Blazor/issues/404) which would _almost_ enable a `foreach` directive.

**Comment by mkArtakMSFT** [comment]
We have no plans to handle this work in the near future, as it doesn't align with our current priorities. Closing this for now. May the priorities change and we'd like to consider this for the future, we may reopen it then.
