### ISSUE TITLE
ASP.NET Core 2.1 gives error CS2017: Cannot specify /main if building a module or library

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2398]
Original issue: https://github.com/aspnet/websdk/issues/350

Steps to reproduce:

- Install .NET Core SDK 2.1
- Create a new project with dotnet new "asp.net core web app"
- The project compiles OK
- Add element `<StartupObject>foo.Program</StartupObject>` to the csproj

Build fails with:

1>CSC : error CS2017: Cannot specify /main if building a module or library

This error did not occur with 2.0. Also a plain .NET core console app initialized with dotnet new "console application" does not have this problem.

**Comment by pranavkm** [comment]
cc @richard-browne @vijayrkn 

Likely an issue here: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets#L136

` MainEntryPoint` shouldn't apply to the Razor assembly since `TargetType` is set to https://github.com/aspnet/Razor/blob/dev/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets#L159.

**Comment by JohnGalt1717** [comment]
So how do you fix it?

**Comment by pranavkm** [comment]
Removing the startup object would be the easiest workaround. Alternatively, you could try resetting the property right before Razor compilation occurs:

```xml
<Target Name="FixStartupObjectIssue" BeforeTargets="RazorCoreCompile">
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
</Target>
```

Yet another option would be to edit the actual Sdk target to not pass the property in Razor's call to the Csc task.  I wouldn't recommend this fix though, since it's tied to your machine.

**Comment by mkArtakMSFT** [comment]
@pranavkm, do you have a PR ready for this?

**Comment by pranavkm** [comment]
Not as yet.
