### ISSUE TITLE
Tag Helpers: Map PascalCase type & property names to HTML element & attribute dashed equivalents

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#240]
By default (convention), Tag Helper type and property names should map to their HTML element attribute equivalents such that pascal-cased names are converted to dashed-names automatically. This can of course be overridden with the `HtmlElementName` and `HtmlAttributeName` attributes.

e.g.
```
"public class MyTagHelper : TagHelper" maps to "<my-tag-helper>"
"public string MyProperty { get; set; }" maps to "my-property='blah'"
```

**Comment by NTaylorMullen** [comment]
2ad828f5bc4b04dcc76403d0c969a70713b31be5
8c47f6a67ecd3da91635c251770a6b872ee33f0b
