### ISSUE TITLE
How to use localization in Razor Class Library

### ISSUE THREAD

**Issue by Jenan** [aspnet/Razor#2404]
I have tried to create the Razor Class Library with Asp.Net Core in following project structure:

![alt text](https://user-images.githubusercontent.com/1324242/41396821-a231ab30-6fa1-11e8-992d-dacad64edbd6.png "Logo Title Text 1")

I have used in my web application these settings for localization in `Startup` class:

```cs
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                    .AddViewLocalization(
                        LanguageViewLocationExpanderFormat.Suffix,
                        opts => { opts.ResourcesPath = "Resources"; })
                    .AddDataAnnotationsLocalization();

                services.Configure<RequestLocalizationOptions>(
                    opts =>
                    {
                        var supportedCultures = new[]
                        {
                            new CultureInfo("en-US"),
                            new CultureInfo("en")
                        };

                        opts.DefaultRequestCulture = new RequestCulture("en");
                        opts.SupportedCultures = supportedCultures;
                        opts.SupportedUICultures = supportedCultures;
                    });

....

var options = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
            app.UseRequestLocalization(options.Value);
```
In` Index.cshtml`:
```
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


<h1>@Localizer["Title"]</h1>
```
Unfortunately, the result is only string "Title". I can't load these resx files from Razor Class Library.

How can I use the localization in Razor Class Library like above?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Jenan.
@ryanbrandenburg, @pranavkm any thoughts?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, @pranavkm any suggestions?

**Comment by ryanbrandenburg** [comment]
@Jenan I believe this is essentially a copy of aspnet/Localization#328, which as far as I know still stands. Basically it boils down to not being able to make guarantees about packages/projects that we import using the same systems and conventions that your main app does. There are some suggestions on that bug about what to do in this situation, so please check them out.

I'm closing this out. If you believe that the above issue does not cover your situation please re-open with a description of the differences and a reproduction app so we have a better idea of exactly what you're running into.
