### ISSUE TITLE
Port fix to https://github.com/aspnet/Razor/issues/2398 to 2.1.x

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2407]
Issue: https://github.com/aspnet/Razor/issues/2398

**Comment by pranavkm** [comment]
Commit to cherry-pick https://github.com/aspnet/Razor/commit/9677553a33638721a306961d4d7f21834754d3ce

**Comment by muratg** [comment]
Approved for 2.1.3.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Razor/commit/74667eda9c5a1826b2876a718e6de22832ef6550
