### ISSUE TITLE
Question: How would I intercept the completed render at compile time

### ISSUE THREAD

**Issue by Seabizkit** [aspnet/Razor#2413]
Hi 

I would like to know if it is possible to get the completed page render at compile time. (not chunks)
https://github.com/aspnet/Razor/issues/444
As i get the impression that all compile type minifications **happen in chunks of sorts.**

I would just like to run some regex on the finial entire render, is this possible?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen thoughts?

**Comment by NTaylorMullen** [comment]
@Seabizkit could you explain your scenario more specifically? Here's some questions that would help me:

- What framework are you using? MVC?
- What version of Razor?
- Could you elaborate more on "happens in chunks of sorts?"

**Comment by Seabizkit** [comment]
Hi
I have worked with Ms MVC for more 4 years, building my own sites.
In that time I have researched many methods of doing minifications of the html page. 

One which seems to work very well was an costume attribute which which intercepted the on-action result, it would then run through some regex. Problem with this approach is that it would be how the result is streamed to the client i.e. in chunks, where as i would like the entire page string to run against.

Similarly razor base page overrides, seem to process segments in bits and pieces.

MVC 5 latest
Razor version latest for above.

i would imagine, that there would be a way to intercept the final result as a hole which razor would out put for a given page, but in all the examples i have seen, like the link i included in the original question, i never see the approach of modifying after final parse of the razor engine.

I hope that makes sense. I have research and tired different solutions. but what would make sense to me is if there was a way to get the final razor engine result and then modify that as a whole.

Like for example i know there are ways that you can render partial views to a string and then result the html to the view, as this point you would have all the html as a string and could parse it through some regex, now i would like something similar but for normal pages not partial views, which means i would need to hook into the razor view engine... but examples i have seen do not process it as a whole page but rather segments/chucks/render nodes/blocks

**Comment by pranavkm** [comment]
Perhaps something like this - http://meleze.github.io/Meleze.Web?

**Comment by Seabizkit** [comment]
@pranavkm Meleze i believe hooks through mvc base page and does what it does on **segments**. I'm looking for away of getting the final html render/parse from razor. the entire page, not segments. Reason i asked on here is i would think that the devs behind it would have the best answer. PS i dont think it matter to much interns of Core MVC vs MVC as their will be similar constructs, i believe its more of a case that the razor engine with either does not have a option to be able to hook on the finial render/parse, which is what I'm asking for confirmation. if not could it be proposed as an enhancement/feature.

**Comment by pranavkm** [comment]
Perhaps something like this - https://arranmaclean.wordpress.com/2010/08/10/minify-html-with-net-mvc-actionfilter? 

> i believe its more of a case that the razor engine with either does not have a option to be able to hook on the finial render/parse

That's correct. For MVC Core, the hope is that we'd have a solution once https://github.com/aspnet/Razor/issues/444 is addressed. It's pretty unlikely we'd add features to MVC 5 though at this point.

**Comment by Seabizkit** [comment]
@pranavkm like i said this **receives the html in chunks.**   **if it didn't** this would be perfect. This is too late in the pipe line... as this to close to IIS which is why its chunked. I'm look for a solution like this but without receiving in segments. Is what you are addressing for Core, give you this option? surely its a override which would mean its available regardless of tech.

**Comment by Seabizkit** [comment]
Create a method in Razor which happens at the end of its normal process. make this public and overwrite-able. then anyone can simply hook on to it? maybe what im am saying is to simplistic as i dont know the technical challenges.

**Comment by mkArtakMSFT** [comment]
Hi @Seabizkit. It seems what you're asking for is not supported. And we have no plans to introduce an interception point where you'd get the full html return string.

**Comment by Seabizkit** [comment]
@mkArtakMSFT why not,  seems to make a load of sense to me as it would be available and not that far to make available.
