### ISSUE TITLE
Investigate C# 7.3 & 8.0 impact

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2419]
Need to verify that there are no new language features that require changes in Razor.

**Comment by rynowak** [comment]
note that we also don't have things like `unchecked { }`. I think it's pretty safe to assume we don't need it if we've gone this long without some asking.

Giving infinite time, I'd want us to 100% compatible with C#'s feature set, but I wouldn't prioritize this over like anything else.
