### ISSUE TITLE
Add version file to prevent VS insertion merge conflicts.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2423]
Need to figure out how to get the following into the vsmanproj:

```XML
<PropertyGroup>
    <ManifestBuildVersion>$(ManifestBuildVersion)</ManifestBuildVersion>
</PropertyGroup>
```

**Comment by rynowak** [comment]
I need to figure out what a vsmanproj is

**Comment by NTaylorMullen** [comment]
> I need to figure out what a vsmanproj is

ditto, why i costed this small instead of xs 😄

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen is this related to some VS release? Or just should this be just 2.2.0-preview1?

Related to a VS release but is optional.

**Comment by NTaylorMullen** [comment]
I'm great, already did this.
