### ISSUE TITLE
Respect indentation of layout when using @RenderBody

### ISSUE THREAD

**Issue by reck13ss** [aspnet/Razor#2427]
The problem is described here: https://stackoverflow.com/questions/42759139/add-indent-to-renderbody

It would be nice if indentation before calling `@RenderBody` was respected.

**_layout.cshtml:**
```
<html>
   <body>
      <div>
         @RenderBody()
      </div>
    </body>
</html>
```

**index.cshtml**
```
@{
     Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<h2>Index</h2>
```
**Result:**
```
<html>
    <body>
       <div>
<h2>Index</h2> <!-- problem here -->
       </div>
    </body>
</html>
```

I think the same goes for rendering partials. Is there any workaround? Possibly with some override.

**Comment by NTaylorMullen** [comment]
This isn't supported out of the box. 

To make something like this work you'd have to do a decent amount of hacks to flow indentation to the underlying body and then change how it renders to understand which pieces of content contain newlines and pre-indentation rendering. Basically, it'd be super costly in regards to performance and would require a lot of changes/API replacements in MVC to make it work

**Comment by lecoque** [comment]
I see. I use razor for code generation other than HTML(something like scaffolding project) and it's pretty problematic because I can't use partials and layouts.
