### ISSUE TITLE
Is it possible to disable form model binding in a Razor PageModel method?

### ISSUE THREAD

**Issue by kirk-quinbar** [aspnet/Razor#2436]
I am working on doing streaming of files during an upload in a core razor page site. There is a great walkthrough that microsoft created that shows how to do streaming in Core, but the code only applies to an MVC controller based page, not a Razor page with PageModel base class. The key class i wanted to try to get working in a PageModel is shown below. In the MVC world this is important in order to get the MultipartReader to read the stream. Unfortunately the IResourceFilter does not apply for the PageModel class, only Controller class. 

Is there a similar concept in the Razor PageModel where i can disable the form value model binding?
I did consider just calling an MVC controller from my Razor page for the actual file upload part, but thought I'd try to keep all the code together for a page if i could.

**Example for MVC controller:**
```

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
public class DisableFormValueModelBindingAttribute : Attribute, IResourceFilter
{
    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        var factories = context.ValueProviderFactories;
        factories.RemoveType<FormValueProviderFactory>();
        factories.RemoveType<JQueryFormValueProviderFactory>();
    }

    public void OnResourceExecuted(ResourceExecutedContext context)
    {
    }
}    

```
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1

**Comment by pranavkm** [comment]
You can apply the attribute to the PageModel instance. https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.1#implement-a-filter-attribute has some samples showing auth and result filters being applied to the model

**Comment by kirk-quinbar** [comment]
I tried to add the following filter to my razor page code, but when i get to the reader.ReadNextSectionAsync call, it errors out with this:

_IOException: Unexpected end of Stream, the content may have already been read by another component._

I tried putting that factory removal code in the OnPageHandlerSelected method too but neither one seems to work the same as my other attribute for mvc. I changed my razor page to point to an api controller for the form post and applied my original attribute and that got past the reader.ReadNextSectionAsync line so my backup would be to use an api controller to save the uploadedfile, but I was hoping to be able to just keep all my code together in the razor page. 
Any other thoughts?

```
 public class DisableFormValueModelRazorBindingAttribute : Attribute, IPageFilter
    {
        public void OnPageHandlerSelected(PageHandlerSelectedContext context)
        {
        }

        public void OnPageHandlerExecuting(PageHandlerExecutingContext context)
        {
            if (context.HandlerInstance is IndexModel handler)
            {
                if (context.HandlerMethod.HttpMethod == "Post" && context.HandlerMethod.Name == "Reply")
                {
                    var factories = handler.PageContext.ValueProviderFactories;
                    factories.RemoveType<FormValueProviderFactory>();
                    factories.RemoveType<JQueryFormValueProviderFactory>();
                }
            }
           // throw new NotImplementedException();
        }

        public void OnPageHandlerExecuted(PageHandlerExecutedContext context)
        {
           // throw new NotImplementedException();
        }
    }
```

**Comment by pranavkm** [comment]
I haven't tried this out, but I suspect the antiforgery filter is reading the request body before you can get to it. Could you try adding a `IgnoreAntiforgeryTokenAttribute` to the model like so:

```
C#
[IgnoreAntiforgeryTokenAttribute(Order = 1001)]
DisableFormValueModelRazorBindingAttribute]
public class MyPageModel : PageModel { ... }
```

Note that the `Order` property is relevant for the `IgnoreAntiforgeryTokenAttribute` attribute (See https://github.com/aspnet/Mvc/issues/5863). Also you should leave `DisableFormValueModelRazorBindingAttribute` as a resource filter. You want to read your file streams before model binding occurs.

**Comment by kirk-quinbar** [comment]
In my testing i think i proved out your theory on the antiforgery check. I can see that core (v2.0.5 btw) and/or Razor is automatically adding the AutoValidateAntiforgeryTokenAuthorizationFilter to the context.Filters property. I am not a fan of making the page less secure (using IgnoreAntiforgeryToken) in order to get this to work. It kinda seems there are just enough differences in how razor pages function vs mvc controllers that might prevent me from keeping my upload code in the razor page class?

Can you think of any way to get upload streaming to work in a razor page class without giving up security?

I'm going to double check, but i think i did get all this to work fine by calling an api controller from my razor page for the upload post, so unless you can come up with a razor version of upload streaming, then i might just go that route.

Here are my test results with each attribute (code above) in a razor page class..
**DisableFormValueModelBindingAttribute (resourcefilter)**
- applied to method: attribute is ignored and does not run at all.
- applied to class: attribute runs, model binding stops, but i get the end of stream at ReadNextSectionAsync line
- applied to class with IgnoreAntiforgeryToken: attribute runs, model binding stops and i can get past ReadNextSectionAsync like (expected behavior)

**DisableFormValueModelRazorBindingAttribute (pagefilter)**
- applied to method: attribute is ignored and does not run at all.
- applied to class: attribute runs, model binding stops, but i get the end of stream at ReadNextSectionAsync line
- applied to class with IgnoreAntiforgeryToken: attribute runs, model binding stops and i can get past ReadNextSectionAsync like (expected behavior)

**Comment by pranavkm** [comment]
You're right - I shouldn't have suggested disabling antiforgery here. Looking at the docs \ samples, the recommendation for large streaming is to pair with a client library that sends the antiforgery token in the request header. See https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1#uploading-large-files-with-streaming. Does that make sense?

**Comment by kirk-quinbar** [comment]
well that example is based on a site that uses angular. I am not using any spa code at all in my site. just razor pages and some knockout code for binding certain portions of the page. in their example, angular sends the antiforgery token as a header so you need to let asp.net know that since its default is to pull it from a form field. According to what ive been reading, when a razor page is pointed back to its codebehind and using an htmlhelper attribute such as asp-page-handler on the form, it will automatically add an antiforgerty token as a form field that just gets passed back and then it adds the AutoValidateAntiforgeryTokenAuthorizationFilter to the handler. i didnt tell it to do any of that in my startup.cs. it just does it by default. If i change the form in my cshtml to use the action attribute instead, then it can call an api controller and doesnt seem to have any issue with the antiforgery stuff interfering. im not positive why it works (maybe its not even doing that check), but i can get all the sample code to work as far as pulling form fields and files from the ReadNextSectionAsync stuff.

So I think because i am not using angular, the code that was suggested would not work as is in just a basic razor page. it will work in a controller which means razor pages are doing a lot more for me than just hiding routing choices, etc.

**Comment by pranavkm** [comment]
> it will work in a controller which means razor pages are doing a lot more for me than just hiding routing choices, etc.

All it's doing is turning on antiforgery by default. For the controller case, the guidance is to include the `ValidateAntiforgeryToken` on the action which gives you identical behavior. Using Antiforgery with a streaming file upload requires using sending the XSRF token via a header. (cc @rynowak \ @kichalla to confirm this). The only way to do this is using a JS library. The sample uses Angular, but you could vanilla JS (https://stackoverflow.com/questions/36067767/how-do-i-upload-a-file-with-the-js-fetch-api) to post the file with the XSRF header.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
