### ISSUE TITLE
Use Razor pages under Microsoft.NET.Sdk

### ISSUE THREAD

**Issue by Johanneshn** [aspnet/Razor#2462]
I've been trying to implement razor pages in a console application, that's running under `Project Sdk="Microsoft.NET.Sdk"`. 

The controllers work fine, but the Views are never found:
`System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
   /Views/Home/Index.cshtml
   /Views/Shared/Index.cshtml
   /Pages/Shared/Index.cshtml`

Switching to `<Project Sdk="Microsoft.NET.Sdk.Web">` and everything works. 
Is it possible to use Razor pages under `Project Sdk="Microsoft.NET.Sdk"`?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Johanneshn.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
You'll need to use `Microsoft.NET.Sdk.Razor` to use this in console \ class library application. See https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1. Feel free to reopen if you have further questions.
