### ISSUE TITLE
Razor views seem to always pre-compile (even in build) in ASP.NET Core v2.1

### ISSUE THREAD

**Issue by salzersoftware** [aspnet/Razor#2466]
During development, I'd like my Razor views to not be precompiled, so that I can quickly make changes and see them, without having to rebuild. (i.e. have the .cshtml views available).

I've been able to reproduce this behavior, where compilation of Razor views happens by default, on simple File->New projects using the ASP.NET Core template, where the csproj file looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

I [reached out to David Fowler via Twitter](https://twitter.com/matt_salzer/status/1015336522172780544) with some additional information and screenshots on the issue.

I also tried playing around with the `MvcRazorCompileOnPublish` as talked about [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.1).

Scanning [several articles,](https://scottsauber.com/2017/03/10/pre-compiling-razor-views-in-asp-net-core-with-csprojs/) it makes seem like this precompilation of views shouldn't be happening when building (especially in debug mode), so I'm not sure what I'm missing.

**Comment by pranavkm** [comment]
The 2.1 Sdk compiles views at build time by default, but 2.1 MVC also supports updating compiled views if the file changes. We did have some issues with runtime framework roll forward with the 2.1.1 runtime installed - https://github.com/aspnet/Mvc/issues/7969, but it doesn't look like that's the error you're seeing here. Any chance you could share a minimal repro app that we could look at?

In the meanwhile, you could turn off build time compilation by changing `RazorCompileOnBuild` in your project. See https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1#properties for more details.

**Comment by salzersoftware** [comment]
Thank you @pranavkm, this pointed me in the right direction.

Taking the advice from those links, I did the following:

Downloaded and installed the latest SDK + Runtime (2.1.301 and 2.1.1).

I then switched my web's csproj file from `<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />` to `<PackageReference Include="Microsoft.AspNetCore.App" />`

And also updated any referenced nuget packages in my project to 2.1.1, through the nuget package manager UI:

```
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="2.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
```

I can now update views and see my changes.

**Comment by tidyui** [comment]
Hi there, I'm experiencing the same issue with `Razor Pages`. As soon as I modify a `.cshtml` file during run and update the web browser I get a `404` from the server. I am running:

    .NET Core SDK (reflecting any global.json):
     Version:   2.1.302
     Commit:    9048955601

    Runtime Environment:
     OS Name:     Mac OS X
     OS Version:  10.13
     OS Platform: Darwin
     RID:         osx.10.13-x64
     Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

    Host (useful for support):
      Version: 2.1.2
      Commit:  811c3ce6c0

Best regards

**Comment by pranavkm** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
