### ISSUE TITLE
Razor SDK - View.dll file not generated if "Microsoft.AspNetCore.Mvc" reference within dependent project

### ISSUE THREAD

**Issue by nfplee** [aspnet/Razor#2469]
If a project (e.g. MyLibrary) using the "Microsoft.NET.Sdk.Razor" SDK has a package reference to "Microsoft.AspNetCore.Mvc" then it will generate the MyLibrary.Views.dll on build.

However if the MyLibrary project doesn't reference "Microsoft.AspNetCore.Mvc" directly but instead has a reference to another project which itself has a package reference to "Microsoft.AspNetCore.Mvc" then it doesn't generate the MyLibrary.Views.dll on build.

I was wondering if this is a potential bug or is there a solution?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nfplee.
@pranavkm, can you please have a look?

**Comment by pranavkm** [comment]
The Razor Sdk requires build assets exported (transitively) by the `Microsoft.AspNetCore.Mvc` package reference. By default, NuGet does not flow `build` assets between P2P dependencies. You'll need to configure the package reference in the library project to allow exporting it (e.g. using `PrivateAssets="None"`). See https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets for more details on how this setting works.
