### ISSUE TITLE
Auto Attribute removal in TagHelpers

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Razor#247]
Attributes that in normal razor code gets automatically removed gets special treatment with TagHelpers.

1. Only attributes that are not bound to tag helper properties will keep the existing razor behavior.
1. These attributes will generate the "naive" string and populate the TagHelperContext.AllAttributes
1. Expression Values that are result in false, null or string.Empty are stripped from TagHelperOutput.Attributes.
  1. Example input: <input class="@false" />
     1. TagHelperContext.AllAttributes will include [class, "false"]
     1. TagHelperOutput.Attributes will not include class.
  1. For other examples follow unit tests for WriteAttribute.

**Comment by dougbu** [comment]
think we tested these scenarios and found `attribute="@string.Empty"` resulted in `attribute=""` with a regular (non-tag helper) attribute.  only `attribute="@null"` and `attribute="@false"` lead to no generation for the attribute.  tag helper attributes should do the same thing.

FYI, see special-cases at:
- https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs#L336 (for `null`)
- https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs#L358 (for `false`)

**Comment by NTaylorMullen** [comment]
4604c807c49daa560b92868503922bb89096a40d
https://github.com/aspnet/Mvc/commit/a0da6ec19f17dd0579ab0424044778608e483997
