### ISSUE TITLE
Refactoring/Renaming Inside Razor Views

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#2476]
_From @stap123 on July 13, 2018 9:9_

Is there a way to to have refactoring (specifically renaming things) work inside razor view files within VS2017? I thought I'd heard Damien mention that it was possible in a community stand up video a while ago but can't work out how to do it.

If it's not possible is it planned at all?

_Copied from original issue: aspnet/Home#3326_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @stap123.
@ajaybhargavb, can you please refernece the issue where we track the refactoring work?

**Comment by ajaybhargavb** [comment]
https://github.com/aspnet/Razor/issues/2271
