### ISSUE TITLE
Automatic view compilation isn't happening in asp.net core 2.1.2

### ISSUE THREAD

**Issue by shoe788** [aspnet/Razor#2478]
When I upgraded my project to asp.net core 2.1.2 and the ViewCompilation package to 2.1.1 the automatic view compilation doesn't appear to be working when I publish

To test I created two new projects from the asp.net core templates targeting .net framework 4.6.2. In one of them I upgrade it to asp.net core 2.1.2 and the other is default asp.net core 2.0.4 with ViewCompilation 2.0.4.

The resulting output is below

ViewCompilation 2.0.4

![ViewCompilation 2.0.4](https://i.imgur.com/1p8PYnc.png)

ViewCompilation 2.1.1

![ViewCompilation 2.1.1](https://i.imgur.com/GaV7uKs.png)

csProj for 2.0.4
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.0.4" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
  </ItemGroup>
</Project>
```

csProj for 2.1.2

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.1.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.1.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
  </ItemGroup>
</Project>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @shoe788.
@pranavkm, can you please look into this? Thanks!

**Comment by shoe788** [comment]
I am on Visual Studio 15.7.5

**Comment by shoe788** [comment]
Here are the build logs.

[vslog_1.txt](https://github.com/aspnet/Razor/files/2194321/vslog_1.txt)
[vslog_2.txt](https://github.com/aspnet/Razor/files/2194322/vslog_2.txt)
[vslog_3.txt](https://github.com/aspnet/Razor/files/2194323/vslog_3.txt)
[vslog_4.txt](https://github.com/aspnet/Razor/files/2194324/vslog_4.txt)

**Comment by pranavkm** [comment]
It looks like your app's using the 2.0 SDK (the SDK versioned 2.1.2x is for the 2.0 runtime \ release). It's strange that VS did not install the 2.1.3.x SDK that shipped with the 2.1 runtime. You may download the Sdk from here - https://www.microsoft.com/net/download/dotnet-core/2.1 if you don't already have it installed. If you do have it installed, perhaps you have a global.json that's pinning the sdk?

**Comment by shoe788** [comment]
Yep, the VS update didn't install the sdk. Thank you very much!

You said that the ViewCompilation package is deprecated so does it work to uninstall that package and just have Microsoft.AspnetCore.Mvc?

**Comment by pranavkm** [comment]
> You said that the ViewCompilation package is deprecated so does it work to uninstall that package and just have Microsoft.AspnetCore.Mvc?

Yup. Removing that package reference would be the way to go.

**Comment by sergei66666** [comment]
I had the same problem. Thanks you!
