### ISSUE TITLE
Razor SDK view doesn't honour _ViewImports file provider

### ISSUE THREAD

**Issue by nfplee** [aspnet/Razor#2481]
My application has the following file provider defined:

```
public class ViewImportsFileProvider : IFileProvider {
    public IDirectoryContents GetDirectoryContents(string subpath) {
        return null;
    }

    public IFileInfo GetFileInfo(string subpath) {
        if (subpath == "/_ViewImports" + RazorViewEngine.ViewExtension)
            return new ContentFileInfo("_ViewImports" + RazorViewEngine.ViewExtension, 
                "@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers");

        return null;
    }

    public IChangeToken Watch(string filter) {
        return null;
    }
}

public class ContentFileInfo : IFileInfo {
    private readonly byte[] _content;

    public ContentFileInfo(string name, string content) {
        Name = name;
        _content = Encoding.UTF8.GetBytes(content);
    }

    public bool Exists => true;

    public long Length => _content.Length;

    public string PhysicalPath => null;

    public string Name { get; }

    public DateTimeOffset LastModified => DateTimeOffset.MinValue;

    public bool IsDirectory => false;

    public Stream CreateReadStream() {
        return new MemoryStream(_content);
    }
}
```

Now say I have a view with the following content:

```
<a asp-action="Contact">Contact</a>
```

The tag helper works fine if the view is within my application but doesn't if it is within a class library (using the Razor SDK).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nfplee.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Build time compilation does not load \ run your app's code. Files need to be present on disk for them to be affect Razor code generation and compilation.

**Comment by nfplee** [comment]
This technique works fine if the views are within the web application. It even works when the application is published and the views are pre-compiled.

**Comment by pranavkm** [comment]
Right - `_ViewImports.cshtml` affects code generation of other Razor files - `_ViewStart.cshtml` is simply executed. In all other cases you listed, runtime compilation is performed so things work as expected.

**Comment by nfplee** [comment]
Oh right thanks, for now I've added a file on disk but this does mean that I have multiple ones across each of my libraries/modules which isn't idea.

**Comment by pranavkm** [comment]
This might be an option depending on how your libraries are set up, but you could try using linked files:

```xml
<ItemGroup>
   <RazorGenerate Include="..\SomeCommonDir\_ViewImports.cshtml" Link="_ViewImports.cshtml" />
</ItemGroup>
```

**Comment by nfplee** [comment]
Thanks, I have a sample project in an issue you have helped me on before:

https://github.com/aspnet/Razor/issues/2425

After your suggestion, the MyLibrary project now has the following target defined:

```
<Target Name="UpdateTargetPath" BeforeTargets="AssignRazorGenerateTargetPaths">
  <ItemGroup>
    <RazorGenerate Include="@(RazorGenerate)" Link="$(TargetName)\%(RazorGenerate.RelativeDir)%(RazorGenerate.FileName)%(RazorGenerate.Extension)" />
  </ItemGroup>
</Target>
```

This saved me from having my views within an Areas directory within my library. Say I placed the _ViewImports within a MyCommonLibrary project then what would I need to add the MyLibrary project file?

Here is the file structure in case it helps:

Application
├── Program.cs
└── Startup.cs
MyLibrary
├── Controllers
│   └── HomeController.cs
└── Views
    └── Home
        └── Index.cshtml
MyCommonLibrary
└── Views
    └── _ViewImports.cshtml

Sorry to ask, but I only know the basics of MsBuild and have never really used linked files before. Also my attempts so far have been in vain.

**Comment by pranavkm** [comment]
I guess you could do something along the lines of:

```xml
<Target Name="UpdateTargetPath" BeforeTargets="AssignRazorGenerateTargetPaths">
  <ItemGroup>
    <RazorGenerate Include="@(RazorGenerate)" Link="$(TargetName)\%(RazorGenerate.RelativeDir)%(RazorGenerate.FileName)%(RazorGenerate.Extension)" />
  </ItemGroup>

   <ItemGroup>
    <RazorGenerate Include="..\MyCommonLibrary\Views\_ViewImports.cshtml" Link="_ViewImports.cshtml" />
  </ItemGroup>
</Target>
```

basically update the "area" paths to start with followed by dropping a "_ViewImports.cshtml" at the root of the application.

**Comment by nfplee** [comment]
Thanks that worked perfectly.

**Comment by nfplee** [comment]
After digging into this a little further I found if I add the following to my project which has a package reference to MyCommonLibrary:

```
<Target Name="UpdateTargetPath" BeforeTargets="AssignRazorGenerateTargetPaths">
  <ItemGroup>
    <RazorGenerate Include="@(RazorGenerate)" Link="$(TargetName)\%(RazorGenerate.RelativeDir)%(RazorGenerate.FileName)%(RazorGenerate.Extension)" />
  </ItemGroup>

   <ItemGroup>
    <RazorGenerate Include="$(NuGetPackageRoot)\MyCommonLibrary\1.0.0\contentFiles\any\$(TargetFramework)\_ViewImports.cshtml" Link="_ViewImports.cshtml" />
  </ItemGroup>
</Target>
```

Then it works fine. I hope this helps someone else.
