### ISSUE TITLE
IsValidCompilation breaks Blazor

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2482]
The check here: https://github.com/aspnet/Razor/blob/master/src/Microsoft.CodeAnalysis.Razor/CompilationTagHelperFeature.cs#L41

Is looking for `ITagHelper` to be defined, but Blazor doesn't use `ITagHelper`. As a workaround we are defining this type as internal inside the Blazor runtime.

We should look for a way to generalize this type, or move this check upstream into the `ITagHelper` based tag helper provider.

**Comment by pranavkm** [comment]
@rynowak what's the suggested fix here?

**Comment by rynowak** [comment]
We should be checking for `string` inside `CompilationTagHelperFeature` and checking for `ITagHelper` in the place that it's used (`DefaultTagHelperDescriptorProvider`)

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Razor/commit/7144add4adb0e18ac897268173556abd187c84ad
