### ISSUE TITLE
GetDesiredIndentation can null ref if it's asked for indentation at a gap.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2489]
We have gaps in our syntax tree and our `GetDesiredIndentation` null refs in the case that it asks for owners at a gap. Thankfully we don't end up crashing VS but it does destroy indentation.

Backing VS issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/594848

**Comment by rynowak** [comment]
Is the plan really to fix this for 15.8 - lets make sure we're on top of this due to timing.

**Comment by NTaylorMullen** [comment]
cb557cf77173414c39e8fd4524ab38c0d5799725
