### ISSUE TITLE
Server-side comments inside tags

### ISSUE THREAD

**Issue by lonix1** [aspnet/Razor#2491]
I looked for an existing issue about this but didn't find one. My `dotnet --version` is `2.1.302`, which is the latest I think.

These are not rendered:

````html
@* foo *@
<div>@* foo *@</div>
````
But these are:

````html
<div @* foo *@></div>
<div class="one two @* foo *@ three"></div>
````

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lonix1.
This is indeed a bug.

**Comment by Eilon** [comment]
Is this a bug or is this by design?

**Comment by Eilon** [comment]
I could imagine maybe this should not get rendered:

```html
<div @* foo *@></div>
```

But this I could see as being by design.

```html
<div class="one two @* foo *@ three"></div>
```

Just like in C# you can't put a comment inside a string: `Console.WriteLine("Hello /* ignore */ world!");`

**Comment by mkArtakMSFT** [comment]
My concern is the first case
```<div @* foo *@></div>```

And I agree with this
> Just like in C# you can't put a comment inside a string: Console.WriteLine("Hello /* ignore */ world!");

**Comment by lonix1** [comment]
I guess you guys are gonna handle this the way you see fit. I'm looking forward to a fix for the first case, so thanks for that.

But for the second case - my 2c is that this isn't like mangling a string in code. This is markup. I often during the design stage comment or uncomment stuff to see how it works. More often than not you comment DOM classes to turn on/of behavior. If this can't be done then the markup ends up being a mess. Try working on, or maintaining, some razor file that was written by someone else for example, without being able to rely on this. It'll be a total mess.
