### ISSUE TITLE
Escaping Razor syntax with '@:' while preserving white-space

### ISSUE THREAD

**Issue by Worble** [aspnet/Razor#2495]
Hi there, I've been bashing my head against this problem for a while now and I can't seem to get through it.
I'm trying to iterate through a series of words and display them preserving whitespace. If certain words match a criteria, I need to display them differently, so I try to put them in a span tag with a certain class. 

Some example code:
```
@{ var words = "the quick brown fox jumps over the lazy dog"; }
<p style="white-space:pre;">
    @foreach (var word in words.Split(' '))
    {
        @if (word == "fox")
        {
            @:<span class="fox-word"> 
        }
        @(word + " ")
        @if (word == "fox")
        {
            @:</span>
        }
    }
</p>
```

The main issue with this is that the `@:` preserves the newline at the end of the `span` definition and closing tag, so it displays like this:
```
the quick brown              
fox             
jumps over the lazy dog 
```
instead of simply
```
the quick brown fox jumps over the lazy dog
```
I've tried using the `<text>` tag, however that errors out on trying to do `<text></span></text>` stating that
```
The "text" element was not closed. All elements must be either self-closing or have a matching end tag.

                <text></span></text>

Encountered end tag "text" with no matching start tag. Are your start/end tags properly balanced?

                <text></span></text>
```

My only other option would be to use `Html.Raw()`, however I am using the experimental framework Blazor, which doesn't support the Html helpers yet, and while I don't see any way a user could potentially inject a script, I wouldn't like running the risk.

Is it possible to achieve what I want here?

(Also as an aside, the contributing guide currently returns a 404 (https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md))

**Comment by NTaylorMullen** [comment]
@Worble the only way to accomplish what you're looking for is to save the text `</span>` into a variable and then spit that out via an `@myClosingSpan`.

**Comment by Worble** [comment]
Hi @NTaylorMullen, took me a little to understand what you meant, but after fiddling around with it I found out I was able to do this:
```
@{ var closingTag = "/span"; }
<text><closingTag></text>
```
And this would close the tag and render it properly without any errors, although razor does complain about the intial start tag not having an end one. Thanks a lot!

**Comment by NTaylorMullen** [comment]
No prob 😉
