### ISSUE TITLE
Can't build VSIX locally with VS 15.8 or later installed

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#2499]
Tried changing `korebuild.json` to extend the VS version range (`"versionRange": "[15.0.26730.03, 15.9)"`) but that leads to numerous restoration failures when building `tooling\Microsoft.VisualStudio.RazorExtension\Microsoft.VisualStudio.RazorExtension.csproj` with `msbuild.exe`.

Current workaround is to build with `/p:BuildVsix=false` and the above VS version range extension. (Tests fail whether building the VSIX or not when `msbuild.exe` isn't found.) Not sure how to clean up restore errors seen in VS&hellip;

Suspect I'm missing something that must change when extending the VS version range. Either that or the latest build tools (`msbuild.exe` et cetera) have a bug affecting restore operations.

**Comment by dougbu** [comment]
Not sure it's related. But, what's with the following build output (right near the end of a successful build)?
```
WARNING: Unnecessary exclusion in Microsoft.AspNetCore.Razor.Design
Issue: NEUTRAL_RESOURCES_LANGUAGE
Instance: tools/Newtonsoft.Json.dll

WARNING: Unnecessary exclusion in Microsoft.AspNetCore.Razor.Design
Issue: VERSION_INFORMATIONALVERSION
Instance: tools/Newtonsoft.Json.dll
```

**Comment by dougbu** [comment]
/cc @rynowak @NTaylorMullen 

Note 59baad17da (a `git merge` into `master`) _reduced_ the VS version range to exclude all 15.8 versions. Odd since 63af9221dc set the upper limit at 15.9. Is there a known problem in the 15.8 range?

**Comment by rynowak** [comment]
I know there *was* a problem at some point. VS/unittesting/msbuild frequently break on prerelease builds. No idea about the current status.

**Comment by dougbu** [comment]
I opened this issue for two reasons
1. Builds fail on my machine because I only have VS 15.8 installed. The root cause may be an inability to find `msbuild` unless 15.7 or lower is available.
  - Would be great if discovering `msbuild` were independent of the VSIX support checks.
 - Error is
  ```
  .dotnet\buildtools\korebuild\2.2.0-preview1-17102\modules\vstest\module.targets(108,5): error : Test group UnitTests/netcoreapp2.2 failed with exit code '1'. [.dotnet\buildtools\korebuild\2.2.0-preview1-17102\KoreBuild.proj]
  ```
2. Changing `korebuild.json` to include VS 15.8 in the supported versions (i.e. `"versionRange": "[15.0.26730.03, 15.9)"`) cleans up the test failure above. But, `restore` fails with 41 errors, starting with
  ```
  tooling\Microsoft.VisualStudio.RazorExtension\Microsoft.VisualStudio.RazorExtension.csproj : error NU1100: Unable to resolve 'Microsoft.VSSDK.BuildTools (>= 15.7.109)' for '.NETFramework,Version=v4.6'. [dotnet\buildtools\korebuild\2.2.0-preview1-17102\KoreBuild.proj]
  tooling\Microsoft.VisualStudio.RazorExtension\Microsoft.VisualStudio.RazorExtension.csproj : error NU1100: Unable to resolve 'System.Composition (>= 1.0.31)' for '.NETFramework,Version=v4.6'. [.dotnet\buildtools\korebuild\2.2.0-preview1-17102\KoreBuild.proj]
  tooling\Microsoft.VisualStudio.RazorExtension\Microsoft.VisualStudio.RazorExtension.csproj : error NU1100: Unable to resolve 'System.Text.Encoding.CodePages (>= 4.3.0)' for '.NETFramework,Version=v4.6'. [C:\Users\dougbu\.dotnet\buildtools\korebuild\2.2.0-preview1-17102\KoreBuild.proj]
  tooling\Microsoft.VisualStudio.RazorExtension\Microsoft.VisualStudio.RazorExtension.csproj : error NU1100: Unable to resolve 'System.ValueTuple (>= 4.3.0)' for '.NETFramework,Version=v4.6'. [.dotnet\buildtools\korebuild\2.2.0-preview1-17102\KoreBuild.proj]
   ```

**Comment by mkArtakMSFT** [comment]
Closing this as done!
