### ISSUE TITLE
rzc.dll - Do a better job handling AggregateExceptions

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2519]
Instead of looking at the first [`InnerException`](https://github.com/aspnet/Razor/blob/master/src/Microsoft.AspNetCore.Razor.Tools/Application.cs#L58-L63), this should call `Flatten` and print all available inner exceptions. This should handle both nested AggregateExceptions as well as multiple thrown exceptions. Vitally important for good stack traces since code generation occurs inside of a `Parallel.For`.

**Comment by ajaybhargavb** [comment]
a4b91d6dce18c0f3fb7a76b7e092f1886bfcdad8
