### ISSUE TITLE
Test failure: BuildIncremental_SimpleMvc_PersistsTargetInputFile

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2527]
This test [fails](http://aspnetci/viewLog.html?buildId=525796&buildTypeId=Releases_21Public_OsxUniverse) occasionally with the following error:
```
Assert.Equal() Failure
Expected: FileThumbPrint { Hash = "2IHpM77CVXJiLyOQKZyWNaRVLJw=", LastWriteTimeUtc = 2018-08-08T10:20:36.0000000Z }
Actual:   FileThumbPrint { Hash = "2IHpM77CVXJiLyOQKZyWNaRVLJw=", LastWriteTimeUtc = 2018-08-08T10:20:44.0000000Z }
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.BuildIncrementalismTest.<BuildIncremental_SimpleMvc_PersistsTargetInputFile>d__1.MoveNext() in /_/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/BuildIncrementalismTest.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by pranavkm** [comment]
Looks like the failure is in 2.1.x. In 2.2 and later, we skipped the test on xplat (See https://github.com/aspnet/Razor/issues/2219 for details). Are we fine porting the skip in to 2.1.x?

**Comment by ryanbrandenburg** [comment]
BuildIncremental_SimpleMvc_PersistsTargetInputFile [failed with about the same error](http://aspnetci/viewLog.html?buildId=526750&buildTypeId=Releases_21Public_OsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
BuildIncremental_SimpleMvc_PersistsTargetInputFile [failed with about the same error](http://aspnetci/viewLog.html?buildId=529799&buildTypeId=Releases_21Public_OsxUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
BuildIncremental_SimpleMvc_PersistsTargetInputFile [failed with about the same error](http://aspnetci/viewLog.html?buildId=530686&buildTypeId=Releases_21Public_OsxUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
BuildIncremental_SimpleMvc_PersistsTargetInputFile [failed with about the same error](http://aspnetci/viewLog.html?buildId=533376&buildTypeId=Releases_21Public_OsxUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ajaybhargavb** [comment]
d0c7d81336c3c5f2914241bbaa8ac764028fc72c
