### ISSUE TITLE
razor pages [BindProperty] for Ilist<T>

### ISSUE THREAD

**Issue by FIVIL** [aspnet/Razor#2533]
Hi, im trying to use `[BindProperty]` annotation in asp.net core razor pages in order to Bind an `Ilist<T>` collection of one of my model classes so i can edit some of them at once, but it doesnt work at all, every time in OnPostAsync function the collection is empty, and neither  the changes that i made on data nor its default values wont post back to the server.
is there any way for doing so??

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @FIVIL.
We will need more details about your scenario to be able to assist you. A repro project would be great.

**Comment by mkArtakMSFT** [comment]
FYI: We also had an issue related to model binding of top-level collections, which may be is what you're facing here: https://github.com/aspnet/Mvc/issues/7712

**Comment by FIVIL** [comment]
@mkArtakMSFT 
the problem is that i have sth like a blog and users are posting some comments about blog posts, but these comments in order to be shown publicly need to be verified, which is a simple bool prop, i can do this verification by editing this bool property one by one which means that i have to open edit page for each post and check a check box and then hit the submit button which is a time consuming, so i wants to have an lets say  IList<PostComment> so i can see all the comments at once and verify some of them at once, but every time in OnPostAsync function the IList<PostComment> is empty but i did used [BindProperty] and every thing,
in order to make this clear i provided [this ](https://github.com/FIVIL/CollectionBindingTest)repo which contains a razor page named index.cshtml/indexed.cshtml.cs and in that page i tested two scenarios of updating, one like this
`  [BindProperty]
        public IList<TestModel> TestModels { get; set; }`
which is dont work and one like
`  [BindProperty]
        public TestModel TestModel { get; set; }`
which works fine as expected

Tnx for your investigation.

**Comment by dougbu** [comment]
@FIVIL thank-you for the repro project; looking&hellip;

**Comment by dougbu** [comment]
This is a naming issue. The `EditorFor` method and the tag helpers aren't given enough information to correctly name the fields it generates.

Best choice is to switch to a `for` and pass all of the expressions:
``` c#
@for (var i = 0; i < Model.TestModels.Count; i++)
{
      var item = Model.TestModels[i];
      <tr>
          <td>
              <input type="hidden" asp-for="@Model.TestModels[i].ID" />
              <input type="text" asp-for="@Model.TestModels[i].Test1" />
          </td>
          <td>
              @Html.EditorFor(m => Model.TestModels[i].Test2)
          </td>
      </tr>
}
```

**Comment by FIVIL** [comment]
@dougbu Tnx, it worked
