### ISSUE TITLE
`@model` C# expressions confuse Razor fairly thoroughly

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#2539]
I haven't checked whether confusion with other Razor directives (that should be legal only at the start of the file) cause similar problems.

### Repro steps
1. Start with ASP.NET Core 2.1 project template for Razor Pages
2. Update `.csproj` to stable versions (I used `2.1.2`)
3. Remove `Microsoft.VisualStudio.Web.CodeGeneration.Tools` dependency
4. Add following to `IndexModel`
  ``` c#
  public IList<TestModel> TestModels { get; } = new List<TestModel>
  {
      new TestModel { Name = "Fred" },
      new TestModel { Name = "Barney" },
  };

  public class TestModel
  {
      public string Name { get; set; }
  }
  ```
5. Add following to end of `IndexModel.cshtml`:
  ``` html
  <div class="row">
    <form method="post">
        @{
            var index = 0;
            var fieldPrefix = ViewData.TemplateInfo.HtmlFieldPrefix;
        }
        @foreach (var model in Model.TestModels)
        {
            @* Update HtmlFieldPrefix so generated id and name attribute values are correct. *@
            ViewData.TemplateInfo.HtmlFieldPrefix = $"{(string.IsNullOrEmpty(fieldPrefix) ? string.Empty : fieldPrefix + ".")}TestModels[{index++}]";
            <div>
                <input asp-for="@model.Name" />
            </div>
        }
        @{ ViewData.TemplateInfo.HtmlFieldPrefix = fieldPrefix; }
        <input type="submit" />
    </form>
  </div>
  ```
  (The above is one way to generate correct names for fields.)

### Expected
Project should build and run without issue

### Actual
Unexpected errors with no clear cause:
![image](https://user-images.githubusercontent.com/6431421/44133269-cfdf5dbe-a013-11e8-9c98-1eb5c306aaec.png)

In addition, the C# expression is not coloured correctly. It appears as if `@model` makes Razor believe this is the `@model` directive.
![image](https://user-images.githubusercontent.com/6431421/44133230-91ff4ad6-a013-11e8-88f3-c1a12e8240aa.png)

### Workaround
After narrowing the problem down or guessing the improper colouring indicates the problem area, users can work around the issue using parentheses. (Parentheses should not be necessary in this situation and aren't required with other variable names.)
``` c#
<input asp-for="@(model.Name)" />
```
(Don't hit #2065 in this case.)

### Notes
- Same problem occurs in MVC views.
- Variables named `model` are fine in many other contexts. The issue here is the need to "escape" out of naming properties on the current `Model` in the `asp-for` attribute.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, this one is all yours.

**Comment by ajaybhargavb** [comment]
I spent some time investigating this. Here are my findings. 
Consider the following example,
```html
<input asp-for="@foo.Name" />
```
Here, `foo.Name` is categorized as an expression by our parser and our intermediate tree.

Where as,
```html
<input asp-for="@model.Name" />
```
Here, `@model` is categorized as a **malformed directive** and `Name` is just a CSharp token.
This is the reason our `ModelExpressionPass` ignores the above expression and generates nothing causing a compilation error. Other directives e.g. `<input asp-for="@page.Name" />` will also cause the same error.

Supporting this correctly is not trivial as it involves the parsing and the IR layer.

Here are a few approaches we can take,
- Accept this as By Design and do nothing. Directives are special in Razor anyway. The workaround (surround with parenthesis) isn't awful.
- Add a diagnostic message when this happens suggesting the workaround
- Hack the `ModelExpressionPass` to understand more than what it should and act accordingly

@NTaylorMullen @mkArtakMSFT thoughts?

**Comment by NTaylorMullen** [comment]
Good finds @ajaybhargavb. My suggestion is to ensure that we have an appropriate error that shows up at design time and runtime indicating that the `directive XYZ is not valid in the current context for the following reasons....`

**Comment by NTaylorMullen** [comment]
Oh and I wouldn't mark this as required. It's fine if we complete this for 3.0

**Comment by dougbu** [comment]
After repairing VS (it was working fine) and experimenting more, I found this issue touches on two separate behaviours:
1. We have reasonable design-time errors for Razor directive use in invalid locations. But, those errors are not visible at runtime and the runtime errors are not helpful.
2. In a `ModelExpression` context, the near-useless runtime error is all that's shown at design-time.

We should see reasonable error messages about the three misuses of the `@model` directive with the following text in PagesHome.cshtml of the MVC sandbox:
``` c#
@page
@model TestModel
@{
    ViewData["Title"] = "Hello from pages";
    var model = Model;
}

<div class="row">
    <div class="col-md-3">
        <h2>RazorPages says Hello @model.Name!</h2>
    </div>

    <form method="post">
        <label>Say hello to <input type="text" asp-for="@model.Name" /></label>
        <label>And again <input type="text" name="@model.Name" /></label>
    </form>          
</div>
```

Instead, using `@model.Name` in an `asp-for` attribute causes only the runtime error message.
![image](https://user-images.githubusercontent.com/6431421/44732404-0deb2580-aa9a-11e8-818a-c798eafbb5cb.png)
![image](https://user-images.githubusercontent.com/6431421/44732471-34a95c00-aa9a-11e8-8f17-ece1178f2124.png)

**Comment by NTaylorMullen** [comment]
> Suggest fixing at least the design-time error message in a ModelExpression / asp-for context should happen before 3.0.

That would require a VS release. In my opinion not worth all the work to get out a VS release to fix an error message that's been there since 1.0.

**Comment by dougbu** [comment]
> That would require a VS release.

Ah. Hoped the problem was in one of the assemblies we pick up from the project, not one that's always loaded from the VS installation.

**Comment by ajaybhargavb** [comment]
Discussed with @mkArtakMSFT. The plan is to have the error about `@model` directive show up at runtime as well. I filed https://github.com/aspnet/Razor/issues/2558 for this. Closing this one.
