### ISSUE TITLE
Update the Razor template to use latest Bootstrap 4.1.3

### ISSUE THREAD

**Issue by josejmoran** [aspnet/Razor#2544]
It will be great if we can have the template make use of the latest Bootstrap 4.1.3.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @josejmoran.
This is what we've already completed as part of https://github.com/aspnet/Templating/pull/595/files#diff-17c118ca0a5be6ae962a56eaad41f6bcR13
