### ISSUE TITLE
Allow Tag Helpers to restrict child elements

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#255]
It can be desirable to design a number of Tag Helpers that work in conjunction with each other, e.g. aspnet/MVC#1688. To better enable this and provide a more guided IntelliSense experience, Tag Helpers should be able to declare that they expect only certain types of elements (usually other Tag Helpers) as their children, by way of  the `RestrictChildrenAttribute`.

The parser should throw an exception if it encounters children of an element with a Tag Helper attached where those children don't match those specified by the Tag Helper. This would show up as an error in Visual Studio with suitably located squiggly.

### Declaration
``` C#
[System.AttributeUsage(AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
public class RestrictChildrenAttribute : Attribute {
    public RestrictChildrenAttribute(params string[] tagNames) {
        ChildTagNames = tagNames;
    }

    public string[] ChildTagNames { get; private set; }
}
```

### Usage
``` C#
[RestrictChildren("source")]
public class TraceTagHelper : TagHelper {
    ...
}

public class SourceTagHelper : TagHelper {
    ...
}
```
``` HTML
<trace output="TraceOutput.Console">
    <source name="Microsoft.AspNet.Mvc.TagHelpers" level="LogLevel.Warning" />
</trace>
```

**Comment by NTaylorMullen** [comment]
Been thinking this issue through a bit and came up with two semi-edge cases:

---
**Issue:** Multiple `TagHelper`s targeting same element with different `RestrictedChildren`.  
**Solution**: Concatenate all `TagHelper`s restricted children. This also makes https://github.com/aspnet/Razor/issues/474 possible through the use of multiple `TagHelper`s. Still might be worth adding the feature however.

---
**Issue:** Non tag related content inside of `TagHelper`. Aka:
```HTML
<trace output="TraceOutput.Console">
    Hello World
    @if(...)
    {
        <source name="Microsoft.AspNet.Mvc.TagHelpers" level="LogLevel.Warning" />
    }
    else
    {
        <super-source name="SomethingElse" level="LogLevel.Error" />
    }
</trace>
```  
**Solution**: Allow non tag related content. Possibly create another issue to add a property to `RestrictChildrenAttribute` to disallow it.

**Comment by DamianEdwards** [comment]
The first is fine. I think for the second we should just simplify for now to strictly allow only what was specified. We can always open up ability to allow non-element content later based on usage and feedback.

**Comment by NTaylorMullen** [comment]
@DamianEdwards alright sounds good.

**Comment by NTaylorMullen** [comment]
One change: v1 will only allow `TagHelper`s targeting the given tag names as children.

**Comment by NTaylorMullen** [comment]
465ff9713df193beb9ef707022943a5a144953e7
https://github.com/aspnet/RazorTooling/commit/49f49d90e446b6aa2221bbef0ed32df2678964cc
