### ISSUE TITLE
POST Model to Controller from HTML form, then pass to ViewComponent Invoke: in View, HtmlHelper outputs value properly, but TagHelper does not.

### ISSUE THREAD

**Issue by JDGHHou** [aspnet/Razor#2556]
1) In my MVC/Razor project, I have an html form:
```
    <form>
           <span>
                <label asp-for="CustomerNumber" class="lm_title"></label>
                <input asp-for="CustomerNumber" id="params_customernumber" />
            </span>
            <span>
                <label asp-for="SalesOrderNumber" class="lm_title"></label>
                <input asp-for="SalesOrderNumber" id="params_salesordernumber" />
                @Html.TextBox("mytext", Model.SalesOrderNumber)
            </span>
    </form>
```
2) In the onChange event of that form, I call a javascript function that converts my form to JSON:
```
    {"CustomerNumber" : "2", "SalesOrderNumber": ""}
```
3) I pass that JSON string to my Controller action. The Controller properly maps the JSON string to my model. Inside that Controller action, I update the SalesOrderNumber on the model, then return the ViewComponent....
```
        [HttpPost()]
        public IActionResult updateParams(Parameters paramModel)
        { 
            paramModel.SalesOrderNumber = "8675309";
            return ViewComponent("ParametersTab", paramModel);
        }
```
4) Which then calls the ViewComponent Invoke code below. When I set breakpoints, I can see that model.SalesOrderNumber = "8765309" right before it returns the View.
```
        public IViewComponentResult Invoke (Parameters pModel)
        {
            MyProject.Models.Parameters model = (pModel is null)?new Parameters():pModel;
            return View(model);
        }
```
5) So then, WHY, in my View 
     ...does this HtmlHelper output the value properly....
```
     @Html.TextBox("mytext", Model.SalesOrderNumber)
``` 

     ... But this TagHelper does not ....

```
     <input asp-for="SalesOrderNumber" id="params_salesordernumber" />
```      
I will add that the other TagHelper that outputs the CustomerNumber works just fine:
```
    <input asp-for="CustomerNumber" id="params_customernumber" />
```
6) If I set the value directly in the Invoke function, instead of passing the model to the Invoke function, it works... so can someone please tell me why setting the value on the model in the Controller, then returning the ViewComponent seemingly passes the value all the way through, but can't output it with an input TagHelper?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JDGHHou.
In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
