### ISSUE TITLE
Assert hit rewriting tag helpers (in VS)

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2566]
https://github.com/aspnet/Razor/blob/master/src/Microsoft.AspNetCore.Razor.Language/Legacy/TagHelperParseTreeRewriter.cs#L141

It's possible to trigger this assert with some valid code:
```
<TemplatedTable Items="@Items">
    <Header><th>Col1</th><th>Col2</th><th>Col3</th></Header>
    <Footer>
        @if (ShowFooter)
        { }
        <tr><td>The</td><td></td><td>End</td></tr>
    </Footer>
</TemplatedTable>
```

In this case `TemplatedTable` and `Footer` are both tag helpers created from a Blazor component. Putting the cursor at the end of `@if (ShowFooter)` and typing `{` (let vs complete the matching `}`. Deleting the `}` again will rethrow the assert.

It looks like what's happening is that the change triggers a full reparse, which changes the context of `</Footer>` which makes the tag helper invalid. 

This seems like a less than great way for us to do error recovery on an unclosed code-block. It would be better to terminate the code block once we see an unpaired closing tag.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Placing this in preview3 for now. If the cost is bigger than `S` let's talk.

**Comment by NTaylorMullen** [comment]
I'll quick fix this as an XS by removing the debug.assert (this was an unknown situation which from my investigation should be safe to remove the assert). To avoid mucking with the SyntaxTree while we're performing surgery on it I filed a follow up [issue ](https://github.com/aspnet/Razor/issues/2568) to address @rynowak's suggestion:


> It would be better to terminate the code block once we see an unpaired closing tag.


For now the side effect of not mucking with the SyntaxTree today will manifest as an extra error talking about the end tag being in an invalid location:
![image](https://user-images.githubusercontent.com/2008729/45059104-b4fa2f00-b04f-11e8-8817-c19437e5ad42.png)

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/commit/3a281b8f58665be676ddb8ed551547140470cc4d
