### ISSUE TITLE
Duplicate attribute on new mvc or Razor Pages application

### ISSUE THREAD

**Issue by cmooring** [aspnet/Razor#2567]
Hi,

I submitted [a comment on this issue](https://github.com/dotnet/cli/issues/4710#issuecomment-395801559) a while back on the dotnet issues board. This occurs when simply creating a new mvc or razor project, letting vscode add the tasks and launch.json files and then performing a build. 

I'm not sure if this is Razor specific, but I think if there is an easy way to get this addressed for new users, it would be really good. I did manage to stop the build errors from occurring by simply adding the following suggestion shown by [this comment](https://github.com/dotnet/cli/issues/4710#issuecomment-404974482) further down the same issue. 

`<PropertyGroup>
  <EnableDefaultRazorTargetAssemblyInfoAttributes>false</EnableDefaultRazorTargetAssemblyInfoAttributes>
</PropertyGroup>`

Thanks,
Chris

**Comment by mkArtakMSFT** [comment]
@pranavkm, @NTaylorMullen what are your thoughts here?

**Comment by pranavkm** [comment]
@cmooring what build of vscode \ dotnet are you using? I could not reproduce the issue when I tried the steps you listed here - https://github.com/dotnet/cli/issues/4710#issuecomment-395801559 - and it built fine without having to edit the project file. The generated file that code complained about is meant to be for the .Views.dll - I wonder if for some reason Omnisharp decides to include it when compiling the main dll. 

Another thing you could try out to narrow the source would be to run `dotnet build` on the project directory. If it builds fine, it's more likely that it's an issue with Omnisharp \ VSCode's C# extension.

**Comment by cmooring** [comment]
`dotnet build` works just fine. Also, funnily enough, I can't seem to reproduce it at work today either. I originally found this issue on my work machine and it has dotnet core version 2.1.300 and vs code version 1.23.1

I did reproduce it at home yesterday, and had only just updated vscode yesterday too. I'll try again tonight and see if I can come up with any further information. You may well be correct about it being an issue with Omnisharp though too. That was also suggested in the initial thread I referred to. 

If I find any additional information, then I'll post it here as well.

**Comment by cmooring** [comment]
I've just tried to reproduce this at home after restarting my laptop, and I can't get it to occur again now. This is slightly frustrating as it has happened to me multiple times over the past 6 months or so. At any rate, I don't think it is worthwhile anyone else spending time on it. If I happen to run across it again, I'll do my best to investigate further and try and establish the cause of the issue before opening an issue again.

Thanks,
Chris
