### ISSUE TITLE
Using vstool (vsmac commandline tool) breaks when razor addin is installed

### ISSUE THREAD

**Issue by Therzok** [aspnet/Razor#2574]
See https://devdiv.visualstudio.com/DevDiv/_queries/edit/621189

Excerpt stacktrace: https://gist.github.com/GouriKumari/085633916efa0de5110e6cd7b3927252

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Therzok.
@NTaylorMullen, can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@KirillOsenkov why in the vstool scenario is MonoDevelop.Core.Runtime.MainTaskScheduler `null`? The foreground thread is typically used for UI but given that it is a public API a user is able to also depend on it for other reasons. In our case we do all project level operations on the foreground thread (even though there's no corresponding UI). 

In my opinion this looks like an issue in VS4Mac not us. It's public API and isn't documented to be null in any scenario. Isn't adding a fake scheduler in the vstool scenario better? That way no other extension runs into this undocumented issue.

**Comment by NTaylorMullen** [comment]
Awesome! If you need, here's a fake scheduler I wrote a little while back that you guys could use:

```C#
public class ForegroundTaskScheduler : TaskScheduler
{
	public static ForegroundTaskScheduler Instance = new ForegroundTaskScheduler();

	private readonly Thread _thread;
	private readonly BlockingCollection<Task> _tasks = new BlockingCollection<Task>();

	private ForegroundTaskScheduler()
	{
		_thread = new Thread(ThreadStart)
		{
			IsBackground = true,
		};

		_thread.Start();
	}

	public int ForegroundThreadId => _thread.ManagedThreadId;

	public override int MaximumConcurrencyLevel => 1;

	protected override void QueueTask(Task task) => _tasks.Add(task);

	protected override bool TryExecuteTaskInline(Task task, bool taskWasPreviouslyQueued) => TryExecuteTask(task);

	protected override IEnumerable<Task> GetScheduledTasks() => _tasks.ToArray();

	private void ThreadStart()
	{
		while (true)
		{
			var task = _tasks.Take();
			TryExecuteTask(task);
		}
	}
}
```

**Comment by KirillOsenkov** [comment]
Turns out this is all we had to do:
https://github.com/mono/monodevelop/pull/5907

:)

**Comment by NTaylorMullen** [comment]
lmao, awesome 👍
