### ISSUE TITLE
Tag Helper code generation produces unused variables

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#260]
Code generation for Tag helpers produces ValueBuffer fields that might not be used.
E.g.

> The field 'ASPV_Views_Account_ConfirmEmail_cshtml.__tagHelperStringValueBuffer' is assigned but its value is never used

 If the application has WarningAsErrors on if you have precompilation enabled, these warnings prevent the application from launching. Once https://github.com/aspnet/Mvc/pull/1677 goes in, this would cause runtime view compilation failures (since the flag gets passed along).

**Comment by NTaylorMullen** [comment]
2d2c2cdf0fb448ad8e44affe56d2156b10be0f79
