### ISSUE TITLE
msbuild error: Microsoft.AspNetCore.Razor.Design.CodeGeneratio n.targets(69,5):

### ISSUE THREAD

**Issue by bkskomal** [aspnet/Razor#2607]
Getting below given error when building using msbuild command line:

ResolveTagHelperRazorGenerateInputs target) ->
  C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.de
sign\2.1.1\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneratio
n.targets(69,5): error : The project xyz must provide a value for Configuration. [xyzcs.proj]

Project is building successfully when building from visual studio 2017.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bkskomal.
What is the command you run to build?
@ajaybhargavb, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Could you share the project file too?

**Comment by bkskomal** [comment]
I am using below given command to build project
MSBuild project.sln /t:rebuild /p:Configuration=Release

I am trying to build the solution file and this solution file contains many projects.

**Comment by pranavkm** [comment]
@bkskomal could you share the build logs from doing the build? Run `MSBuild project.sln /t:rebuild /p:Configuration=Release /bl` and share the generated msbuild.binlog file

**Comment by pranavkm** [comment]
Ping @bkskomal

**Comment by pranavkm** [comment]
@bkskomal please reopen the issue once you've had the chance to include the build log.
