### ISSUE TITLE
Razor Class Library, error NU1201: Project ... is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project ... supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)

### ISSUE THREAD

**Issue by luboid** [aspnet/Razor#2611]
Hi
I have problem with compiling **Razor Class Library** which depend on lib **Class Library 2.1**, Visual Studio don't allow change framework from netstandard2.0 to netstandard2.1 for Razor Class Library

```cmd
F:\b3next\B3Next.Clients>dotnet build
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for F:\b3next\B3Next.Clients\B3Next.Clients.Web.csproj...
  Restore completed in 62,68 ms for F:\b3next\B3Next.Clients.Interfaces\B3Next.Clients.Interfaces.csproj.
F:\b3next\B3Next.Clients\B3Next.Clients.Web.csproj : error NU1201: Project B3Next.Clients.Interfaces is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project B3Next.Clients.Interfaces supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
  Generating MSBuild file F:\b3next\B3Next.Clients\obj\B3Next.Clients.Web.csproj.nuget.g.props.
  Restore failed in 1,06 sec for F:\b3next\B3Next.Clients\B3Next.Clients.Web.csproj.

Build FAILED.

F:\b3next\B3Next.Clients\B3Next.Clients.Web.csproj : error NU1201: Project B3Next.Clients.Interfaces is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project B3Next.Clients.Interfaces supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.67

F:\b3next\B3Next.Clients>dotnet --version
2.1.402
```

![image](https://user-images.githubusercontent.com/383517/46068873-d8158b80-c182-11e8-9519-a518a3a1ffe3.png)

**Comment by pranavkm** [comment]
What's the target framework that `B3Next.Clients.Web` targets? My guess is that it's targeting `netstandard2.0` while the project you're referencing (`B3Next.Clients.Interfaces`) is `netcoreapp2.1`. You could change the Web project's target framework to `netcoreapp2.1` too if that's the issue.

**Comment by luboid** [comment]
Hi,
Visual Studio don't allow me to set 2.1 version

Project:**B3Next.Clients.Web**
![image](https://user-images.githubusercontent.com/383517/46126080-862d3e00-c234-11e8-8200-5e516da7809c.png)

here is test repo:
https://github.com/luboid/test-razor-class-library.git

**Comment by mkArtakMSFT** [comment]
@luboid, the way you got it working by manually changing the `TargetFramework` in the `csproj` file is fine. Alternatively, there is a different type of class library project, which would target .Net Standard, and that's what you could create from the beginning.
