### ISSUE TITLE
Razor 3.0 Versioning

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#2612]
There are a few things we need to do to 'turn the crank' to bootstrap the 3.0 version of Razor. A list of things I can think of right now:

- [ ] Create a `Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X` tooling shim. This needs to go into the VSIX and get loaded at tool time for 2.X projects
- [ ] Do the same as the above but for the 2_X tests. We want to make sure we can make changes to the 3.0 codebase while keeping old behaviour the same. 
- [ ] Update `Microsoft.AspNetCore.Mvc.Razor.Extensions` to the 3.0 language version and branding in MSBuild-related properties
- [ ] Define a 3.0 Razor language version value in `Razor.Language`
- [ ] Unit tests for project system, ProjectEngineFactory

**Comment by pranavkm** [comment]
Self-assigning. I'm going to need some of this for the component work
