### ISSUE TITLE
Is it possibile to implement Razor intellisense / syntax highlighting out of Visual Studio?

### ISSUE THREAD

**Issue by wakuflair** [aspnet/Razor#2615]
I want to create a tool which can edit Razor page (cshtml).
For now I use [AvalonEdit](https://github.com/icsharpcode/AvalonEdit) for basic editing.
It will be more useful to add Razor intellisense and syntax highlighting features in my tool.

So can Razor Language Service help me  and is it possibile to it out of Visual Studio?
I need some guide for this, thanks.

**Comment by SIkebe** [comment]
This might help you.
https://github.com/OmniSharp/omnisharp-vscode/pull/2554

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
