### ISSUE TITLE
Add option to disable encoding

### ISSUE THREAD

**Issue by dehghani-mehdi** [aspnet/Razor#2632]
Hello,

Seems like Razor encode string by default, it's good for English, but not for Non-English content. it can be fixed using `@Html.Raw`, but it's not great option I think.

So would you add an option to disable encoding?

Thanks.

**Comment by blowdart** [comment]
No we will not. It would introduce a huge security vulnerability when we've made explicit promises that everything will be encoded.

**Comment by dehghani-mehdi** [comment]
It can be optional (to disable encoding) not default behavior.
Thanks for the link.

**Comment by blowdart** [comment]
We will not introduce such an option due to the security concerns. Your only option is to adjust what is encoded, or use Html.Raw

**Comment by dehghani-mehdi** [comment]
I'm using Razor outside of MVC (using [RazorViewToStringRenderer.cs](https://github.com/scottsauber/RazorHtmlEmails/blob/master/src/RazorHtmlEmails.RazorClassLib/Services/RazorViewToStringRenderer.cs)) and your mentioned link doesn't work for me, would you help me how I can use that solution in this case?

**Comment by blowdart** [comment]
As that's not an MVC package that question would best be asked for that package author.

**Comment by dehghani-mehdi** [comment]
Thanks for the help here.

By using that, I mean just copy/paste that code and some edit. there is no nuget or package. there is also an answer on [SO](https://stackoverflow.com/a/47756437/3367974) that is the same as my prev mentioned link.
