### ISSUE TITLE
Razor changes the attribute's value to the attribute's name if the value was true.

### ISSUE THREAD

**Issue by HamidTheGeek** [aspnet/Razor#2635]
#### Is this a Bug or Feature request?: 
I am not sure that whether is it a bug or meant to be like that.

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
You just need to add the following tag to any view file and check the result.
``` html
<input type="hidden" value="@true" />
<input type="text" value="@true" />
```

#### Description of the problem:
If you pass the `true` as the value of a value attribute in input tag, it generates `value="value"`. So if you have this tags in a form tag and try to bind them the boolean property value would be considered as false and the string would be change to value instead of true.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @HamidTheGeek.
@NTaylorMullen, can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
Hi @HamidTheGeek this is by design and is something we call "conditional attributes". It enables scenarios such as `<input type="checkbox" checked="@checked" .. />`

If you'd like to work around the conditional attributes feature you can do the following:
```C#
@{
    var attr = "value=" + true;
}

<input type="text" @attr />
```
