### ISSUE TITLE
Re-enable ManualServerShutdown_NoPipeName_ShutsDownServer with different pipe name choosing mechanism

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2636]
When updating Roslyn to 2.9.0 I ran into an issue with this test where the test would try to launch a non-published variant of rzc resulting in mismatched dependencies at runtime (explosions).

We need to change the test to use a published version of rzc and use a specific pipe name instead of relying on location.

**Comment by ajaybhargavb** [comment]
8e62dbcae97a0da303ee50bbeff44323515e33e9
