### ISSUE TITLE
Test failure: GetCopyToOutputDirectoryItems_WhenNoFileIsPresent_ReturnsEmptySequence

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Razor#2645]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=576328&buildTypeId=Releases_21Public_HighSierraOsxUniverse) with the following error:

```
System.TimeoutException : command '$dotnet msbuild /restore /p:_RazorBuildServerPipeName="dafb7556-fc3c-4533-8e3a-243c708d43b7" /p:_RazorSuppressCurrentUserOnlyPipeOptions=true /p:Configuration=Release ' timed out after 00:01:00.
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass0_0.<RunProcessAsync>b__0(Task t) in /_/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/MSBuildProcessManager.cs:line 79
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.BuildIntrospectionTest.<GetCopyToOutputDirectoryItems_WhenNoFileIsPresent_ReturnsEmptySequence>d__4.MoveNext() in /_/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/BuildIntrospectionTest.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.1.

CC @mkArtakMSFT

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 9 failures [with about the same error](http://aspnetci/viewLog.html?buildId=576328&buildTypeId=Releases_21Public_HighSierraOsxUniverse) on 2.1 at 1:36:28 AM:
- DesignTimeBuild_DoesNotRunRazorTargets
- Pack_WithIncludeSymbols_IncludesRazorPdb
- Build_WithMvc_AddsConfigurationMetadata
- IncrementalBuild_WithP2P_WorksWhenBuildProjectReferencesIsDisabled
- Publish_NoopsWith_RazorCompileOnPublishFalse
- ManualServerShutdown_NoPipeName_ShutsDownServer
- RazorCompile_Success_CompilesAssembly
- RazorGenerate_Rebuilds_IfOutputFilesAreMissing
- Build_SimpleMvc_NoopsWithRazorCompileOnBuild_False

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, can you please look into this? Thanks!

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 6 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588426&buildTypeId=Releases_21Public_OsxUniverse) on 2.1 at 4:34:49 PM:
- RazorCompile_Success_CompilesAssembly
- IncrementalBuild_WithP2P_WorksWhenBuildProjectReferencesIsDisabled
- RazorGenerate_Rebuilds_IfOutputFilesAreMissing
- ManualServerShutdown_NoPipeName_ShutsDownServer
- Build_WithMvc_AddsConfigurationMetadata
- Pack_WithIncludeSymbols_IncludesRazorPdb

**Comment by ajaybhargavb** [comment]
https://github.com/aspnet/Razor/pull/2710
