### ISSUE TITLE
Feature Request: F# Razor "fshtml" support

### ISSUE THREAD

**Issue by hez2010** [aspnet/Razor#2660]
Can you add support for F# HTML rendering with ".fshtml"?

Although currently dotnet core supports F# web apps, the html rendering still is "cshtml" but not "fshtml".

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hez2010.
@Eilon, @danroth27 can you please ping the F# team folks so they can comment here? Thanks!
