### ISSUE TITLE
Cannot find reference assembly 'Microsoft.Win32.Primitives.dll' after set RazorCompileOnBuild=false

### ISSUE THREAD

**Issue by sergei66666** [aspnet/Razor#2663]
At first we used .net Core 1.1.2 with `<TargetFramework>net461</TargetFramework>`.
Now we migrated to .net Core 2.1.5 with `<TargetFramework>net472</TargetFramework>`.

We have two developer machines (machine A and machine B), both with VS 2017 15.8.7 and installed net472, with the same **dotnet --info** output:
```
 Version:   2.1.403
 Commit:    04e15494b6

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510
```

We have problem with views precompilation (I think).

**First case. Use this settings**
```xml
<RazorCompileOnPublish>true</RazorCompileOnPublish>
<RazorCompileOnBuild>true</RazorCompileOnBuild>
```
All works correctly while debug on both machines (IIS local). If we made any changes to *.cshtml during debug - all works fine on machine A (views recompiled), but on B we get exception:

> InvalidOperationException: Cannot find reference assembly 'Microsoft.Win32.Primitives.dll' file for package Microsoft.Win32.Primitives.Reference
> Microsoft.Extensions.DependencyModel.Resolution.ReferenceAssemblyPathResolver.TryResolveAssemblyPaths(CompilationLibrary library, List<string> assemblies)

**Second case**
```xml
<RazorCompileOnPublish>true</RazorCompileOnPublish>
<RazorCompileOnBuild>false</RazorCompileOnBuild>
```
At machine A all works, on B we get the same exception, but at the startup.

We try:
1) Different combinations of:
```xml
<PreserveCompilationContext>true</PreserveCompilationContext>
<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
```
2) Clear nuget cache and restore packages.

Also we try to get exception on machine A but without results - all works fine.

Please, help us find diference between machine A and B, what can be cause of this behavior?

[full stack here.txt](https://github.com/aspnet/Razor/files/2501948/stack.txt)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@sergei66666, just a generic advice: try to either repair VS installation on the B machine or just reinstall the 2.1.5 SDK on that machine. It may be your setup somehow got messed up.

**Comment by mkArtakMSFT** [comment]
@pranavkm, do you have any suggestions regarding the razor compilation aspects here? Thanks!

**Comment by pranavkm** [comment]
Setting `<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>` should be the only one that should matter here assuming you are publishing your app.

**Comment by sergei66666** [comment]
@pranavkm We did not check what happen on publish, but during debug this flag did not work (no `refs` folder).

So, for now we went back to net461 and all works fine. We get `refs` folder during debug and no problems.

**Comment by pranavkm** [comment]
The `refs` directory is used for runtime compilation for a published application. The intent is that the server the application is deployed to would not have the packages dir or reference assemblies required for view compilation. Debugging generally should not require the `refs` folder (although there are are a couple of known cases where the folder gets published).

Regardless, this looks like a dup of https://github.com/dotnet/sdk/issues/1738. The fix was made in the SDK v2.1.4 or newer. Could you verify both the machines have the right Sdk installed?

**Comment by sergei66666** [comment]
Both have `Version:   2.1.403`

**Comment by pranavkm** [comment]
@sergei66666 was the issue resolved for you?

**Comment by sergei66666** [comment]
@pranavkm Yes, after rolling back to net461.
