### ISSUE TITLE
Duplicate RazorDiagnostic IDs for two different errors

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2669]
https://github.com/aspnet/Razor/blob/master/src/Microsoft.AspNetCore.Razor.Language/RazorDiagnosticFactory.cs#L235 and https://github.com/aspnet/Razor/blob/master/src/Microsoft.AspNetCore.Razor.Language/RazorDiagnosticFactory.cs#L245 both have the same diagnostic id `RZ1020`. We need to fix it.

@rynowak is this a breaking change?

**Comment by rynowak** [comment]
I think we're free to change this.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, all yours!

**Comment by ajaybhargavb** [comment]
8674dd923636ea5667b3c4b3554b41ee4e442ec1
