### ISSUE TITLE
Converting Razor Pages to Controller+View pair

### ISSUE THREAD

**Issue by M-Zuber** [aspnet/Razor#2684]
Hope I have the terminology correct.

I am looking for tooling that will enable me to "Eject" a razor page into the underlying components.

My current use case is when I am using the default scaffolded Identity, I can't auto-redirect to the users profile page from within my Home controller.

**Comment by danroth27** [comment]
We don't have any plans to convert Razor Pages to MVC controllers/views, but we should still be able to help you out with your scenario.

> I can't auto-redirect to the users profile page from within my Home controller.

You should be able to redirect to any page in the Identity area, like this:

```csharp
return RedirectToPage("/Account/Manage/Index", new { area = "Identity" });
```

Let me know if that works for you!

**Comment by M-Zuber** [comment]
Thank you!

That does work.

As for the eject tool, maybe I'll try putting something together
