### ISSUE TITLE
VS build fails when using microsoft.aspnetcore.razor.design package

### ISSUE THREAD

**Issue by IgorKravcov** [aspnet/Razor#2685]
Hi all,

We seem to experience an issue when trying to build the project in VS. We get:

_Assembly location for Razor SDK Tasks was not specified. The most likely cause is an older incompatible version of Microsoft.NET.Sdk.Razor, or Microsoft.NET.Sdk.Web used by this project. Please target a newer version of the .NET Core SDK._

We are using VS 2017, latest patch - 15.8.8 and microsoft.aspnetcore.razor.design is 2.2.0-preview3-35497.

Tried this on vanilla .Net Core 2.1 web app and got the same issue. The only two versions of SDKs installed are 2.1.202 and 2.1.403

Just wondering if anyone else had this issue or know why this might be happening.

[msbuild.zip](https://github.com/aspnet/Razor/files/2529601/msbuild.zip)

**Comment by pranavkm** [comment]
@IgorKravcov you will need the 2.2 preview3 SDK (or newer) to reference the preview3 Razor.Design package. The SDK is available for download from here - https://www.microsoft.com/net/download/dotnet-core/2.2

**Comment by IgorKravcov** [comment]
thanks @pranavkm the issue is now resolved.
