### ISSUE TITLE
Build error: IntegrationTestBase.cs(130,8): Target frameworks need to be updated

### ISSUE THREAD

**Issue by KirillOsenkov** [aspnet/Razor#2728]
1. `git clone https://github.com/aspnet/razor`
2. `nuget restore`
3. `msbuild /bl`

**Expected:**
builds fine

**Actual:**
```
Errors
    Language\IntegrationTests\IntegrationTestBase.cs(130,8): error CS1029: #error: 'Target frameworks need to be updated            ' [C:\razor\test\Microsoft.AspNetCore.Razor.Test.Common\Microsoft.AspNetCore.Razor.Test.Common.csproj]
    Language\Legacy\ParserTestBase.cs(74,8): error CS1029: #error: 'Target frameworks need to be updated.' [C:\razor\test\Microsoft.AspNetCore.Razor.Test.Common\Microsoft.AspNetCore.Razor.Test.Common.csproj]
```

This is because neither `NETFRAMEWORK` nor `NETCOREAPP` define is defined. 

I realize the instructions say to use build.cmd (which will eventually call run.ps1 which will use KoreBuild), however it feels like it's very close to be able to build just by using nuget restore + msbuild.

I'm filing this bug in hope that there's an easy default somewhere that will allow this repo to build by just calling `msbuild /r`. This is an ideal that repos in our ecosystem should strive towards, because custom tooling such as build.cmd or KoreBuild is not standard and so creates barriers that are probably avoidable.

**Comment by pranavkm** [comment]
@KirillOsenkov support for `NETFRAMEWORK` \ `NETCOREAPP` constants was added as part of the 2.1.3 SDK. If you don't have it installing, running `.\build /t:Restore` should install it for you. You can run `dotnet build` once it's in your PATH

**Comment by KirillOsenkov** [comment]
Thanks! Shouldn't it default to NETFRAMEWORK in that case? Or is having an SDK a prerequisite?

**Comment by mkArtakMSFT** [comment]
Thanks @KirillOsenkov and @pranavkm!
Closing this as this repo will eventually move to AspNetCore where build will be slightly different, while the rules may still be applicable.
