### ISSUE TITLE
Broken Microsoft.AspNet.Razor.Runtime 4.0.0-beta2 aspnet50 assembly on Mono

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Razor#275]
Some time today, the aspnet50 DLL of the Razor Runtime started to be broken. Clearing the restore-cache and downloading it again does not help.

```
Restoring packages for [...]/project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Razor.Runtime'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Razor.Runtime'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.CodeAnalysis.CSharp'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.CodeAnalysis.CSharp'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Razor.Runtime' 1122ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.CodeAnalysis.CSharp' 1211ms
  OK https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.CodeAnalysis.CSharp' 3859ms
  OK https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Razor.Runtime' 4063ms
  GET https://www.nuget.org/api/v2/package/Microsoft.AspNet.Razor.Runtime/4.0.0-beta2.
  OK https://www.nuget.org/api/v2/package/Microsoft.AspNet.Razor.Runtime/4.0.0-beta2 464ms
Resolving complete, 4799ms elapsed
```

The actual error is not very helpful:
```
System.IO.FileNotFoundException: Could not load file or assembly '[My TagHelpers Assembly.dll]' or one of its dependencies. The system cannot find the file specified.
File name: '[My TagHelpers Assembly.dll]'
  at...
```
So here as a monodis output.
```
$ monodis ~/.kpm/packages/Microsoft.AspNet.Razor.Runtime/4.0.0-beta2/lib/aspnet50/Microsoft.AspNet.Razor.Runtime.dll
[...]
.namespace Microsoft.AspNet.Razor.Runtime.TagHelpers
{
  .class public auto ansi sealed beforefieldinit ContentBehaviorAttribute
        extends [mscorlib]System.Attribute
  {
    .custom instance void class [mscorlib]System.AttributeUsageAttribute::'.ctor'(valuetype [mscorlib]System.AttributeTargets) =  (
                01 00 04 00 00 00 02 00 54 02 0D 41 6C 6C 6F 77   // ........T..Allow
                4D 75 6C 74 69 70 6C 65 00 54 02 09 49 6E 68 65   // Multiple.T..Inhe
                72 69 74 65 64 00                               ) // rited.

    .field  private  <BROKEN CLASS token_ 100000e> '<ContentBehavior>k__BackingField'
* Assertion at class.c:5607, condition `!mono_loader_get_last_error ()' not met

Aborted (core dumped)
```

**Comment by NTaylorMullen** [comment]
@Tragetaschen it sounds like you're having mismatched assmemblies. Did you try clearing both your `%userprofile%/.kpm/packages` and `%localappdata%/kpm/cache`?

**Comment by Tragetaschen** [comment]
Yes, that was my first thought, too. But the behavior `restore`d entirely. I also checked which versions there are in my packages folder and they are all, which is what my project.json's expect anyways.

**Comment by NTaylorMullen** [comment]
@davidfowl or @pranavkm Does this happen for either of you? I would give it a shot but I don't have a working mono machine setup on my end :cry:

**Comment by Tragetaschen** [comment]
What I've done throughout the day was:
- Keep the .kpm and the cache directory as well as the beta2 installation untouched
- Develop new code in my git repository (on Windows)
- Push the changes onto my build machine
- In my Yocto build environment, I 
 - Entirely whipe any previous build bits
 - Copy my sources into the build environment
 - Run `kpm restore` and `kpm pack --no-source -o ...`
 - Copy the contents of the pack folder onto another, embedded computer and run `sh kestrel` there (again with beta2)

This morning, those steps created a working environment, now in the evening they don't.

I'm trying to reproduce this on a second Linux computer, but so far I'm unable to and everything works like this morning.

**Comment by NTaylorMullen** [comment]
@Tragetaschen Try validating that your package sources are properly setup. There is a bug that we occassionally run into where the default nuget feed gets disabled and then results in a failure to build the rest of the project. So steps I'd do is:

1. Delete `%userprofile%/.kpm/packages`
1. Delete  `%localappdata%/kpm/cache`
1. Ensure proper nuget feeds are enabled.
1. kpm restore.
1. compile/build/whatever your normal final step is.

**Comment by Tragetaschen** [comment]
Do you mean [Home#255](https://github.com/aspnet/Home/issues/255)? I have checked that beta2 was downloaded from nuget.org (see `kpm restore` log above)

**Comment by Tragetaschen** [comment]
Ok, I have narrowed it down to a single commit of mine that activates some TCP server code by listening on IPv4 and IPv6 simultaneously. It has nothing to do with any of the ASP.NET 5 stuff, though. On my second computer (x86_64, not the embedded ARM), I now get a really scary mono runtime abort, and this is something that I guess can easily kill the runtime an ARM in strange ways.

```
libgcc_s.so.1 must be installed for pthread_cancel to work

Native stacktrace:


Debug info from gdb:

warning: File "/usr/bin/mono-sgen-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /usr/bin/mono-sgen-gdb.py
line to your configuration file "/home/kai/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/kai/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Could not load shared library symbols for 9 libraries, e.g. linux-vdso.so.1.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
0x00007f8961d7514c in ?? ()
  Id   Target Id         Frame 
* 1    process 21422     0x00007f8961d7514c in ?? ()

Thread 1 (process 21422):
#0  0x00007f8961d7514c in ?? ()
#1  0x0000000000000000 in ?? ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

/home/kai/.kre/packages/KRE-Mono.1.0.0-beta2/bin/klr: line 15: 21422 Aborted                 mono $MONO_OPTIONS "$DIR/klr.mono.managed.dll" "$@"
```

**Comment by Tragetaschen** [comment]
And for the interested, here is the final analysis:

My code was trying to open two TcpListeners on the same port. One for IPv4-any and one for IPv6-any. This works on Windows, but fails on Mono. Due to the way my code was structured, this resulted in a tight loop creating and not releasing TcpListeners.

This loop quickly consumed all available file handles and other parts of the program could not do simple tasks like loading a DLL.

The scary runtime abort is Mono trying to cancel the Task-Thread where the tight loop is spinning. Obviously something isn't working as expected there as well.

**Comment by NTaylorMullen** [comment]
Glad you figured it out! :smile:
