### ISSUE TITLE
TagHelperOutput doesn't allow multiple non-bound TagHelper attributes with identical names.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#279]
This item adds the infrastructure needed to complete https://github.com/aspnet/Razor/issues/220 and https://github.com/aspnet/Razor/issues/96.

Ultimately we should be able to have tags such as:
`<input class="btn" class="btn-success" />` which generate the correct output. Today this type of tag which happens to be a `TagHelper` would generate:
`<input class="btn-success" />` because last attribute in wins with no way for the `TagHelper` author to chose the other value.

To properly complete this item we need to create an attribute abstraction that has many types, one of which is a one key => many values (in addition to the default 1=>1 mapping). Other types that could be added in the future are key only, C# etc.

**Comment by NTaylorMullen** [comment]
Assigned this to RC due to #220 and #96 being assigned to the milestone (this is a pre-requisite).

**Comment by dougbu** [comment]
@NTaylorMullen, could you clarify why this issue is a prerequisite to #220 (single attributes w/ no value e.g. `checked`) or #96 (single C# attributes e.g. `@checked`)?

**Comment by NTaylorMullen** [comment]
The correct way to fix #96/#220 is to enable different types of attribute values in the `TagHelperOutput`. Any other fix would be more or less a hack/half-fix. By having a single attribute abstraction that can handle 1->many, no value, 1->1, C# attributes users then only have a single abstraction they need to work with without risk of ambiguity between things like:

`<input checked="" />` and `<input checked />`

**Comment by NTaylorMullen** [comment]
7c604d2b1141f8dc3dc78e14aaacb8f489c3d1e6
dcee0d2ff718dace8087f07f15fa24c9db579131
https://github.com/aspnet/Mvc/commit/f152ea700419b8244677e10adf02aec2a9dc7f9e
