### ISSUE TITLE
Remove the @helper directive from Razor

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#281]
At this point, the design for the `@helper` directive seems incomplete vis-a-vis 
1. support for async code 
2. support for Helper files that could be placed under App_Code

Based on design discussion for https://github.com/aspnet/Mvc/issues/1130, the current thought is to remove the `@helper` feature until we come up with a better design for these questions.

**Comment by ajaybhargavb** [comment]
b3c60976a448182c3bfc96a1a71d8b6eb71a3289

**Comment by alexaku** [comment]
@helper is a simple construction that intended for frequent use in place. @helper is not intended for an async code embedding or a detached code use. It is useful when we need to define tiny portion of the parameterized html-code inside the View-file and reuse it inside the same View-file. The most meaningful thing is direct access to Model from @helper. In other words, helper is a simple context-related part that completely depended on a concrete View-file. Delete of this functionality is a hooliganism.

**Comment by ateregulov** [comment]
Implementation of the ViewComponents turned out horrible.

**Comment by alexaku** [comment]
@pranavkm, @ajaybhargavb, @yishaigalatzer 
You have provided us with TagHelpers that are going to be added to ASP.NET MVC 6 (RTM), basically to replace @helpers. Each tag helper is a new separate file (class). Furthermore, each of these separate file can't contain an HTML markup (Razor). There are only C# or VB code. If you remember ViewComponents, there will be appear even two files. How can I reuse some portion of the simple HTML code in my View without adding a bunch of extra files? If you retain the @functions in the Razor despite deletion of the @helper, than you must add HTML markup feature in their bodies. See below two @functions that could perform the same code.

`@functions {`

`	public HtmlString GetTableHeader1(String className)`
`	{`
`		HtmlString result = <text>`
`			<tr class="@className">`
`				<td title="abc">one</td>`
`				<td title="xyz">two</td>`
`			</tr>`
`		</text>;`
`		return result;`
`	}`

`	public HtmlString GetTableHeader2(String className)`
`	{`
`		HtmlString result = new HtmlString(@"`
`			<tr class=""" + Html.Encode(className) + @""">`
`				<td title=""abc"">one</td>`
`				<td title=""xyz"">two</td>`
`			</tr>`
`		");`
`		return result;`
`	}`

`}`
