### ISSUE TITLE
Razor allows 0 whitespace between HTML attributes.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#287]
Right now if you were to type: `<input type="text"value="something" />` Razor would understand it. This seems beneficial from a top-level view but is actually against the HTML5 spec. The most notable way this gets surfaced is through `TagHelper`s attributes.

We should not allow zero whitespace between HTML attributes.

**Comment by Eilon** [comment]
Can this be done easily in Razor Evolution? If not, I'm inclined to close this bug. The workaround is simple: don't write invalid HTML 😄

**Comment by NTaylorMullen** [comment]
Close 😄
