### ISSUE TITLE
Enable directive completions in the editor.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#291]
We should enable the ability to provide completions on directives within the editor.

**Comment by yishaigalatzer** [comment]
@DamianEdwards this is an awesome idea, but I'd like to chat about the priority.

**Comment by Eilon** [comment]
@NTaylorMullen @rynowak does Razor Evolution make this a reality?

**Comment by NTaylorMullen** [comment]
Hmm, forgot about this issue. Today there's not enough data in our evolution abstractions to make this a reality. Ultimately it'd be a dual effort in tooling and Razor to make this a reality.

**Comment by DamianEdwards** [comment]
Apparently the editor APIs exist to make this possible now.

**Comment by Eilon** [comment]
Can we get an idea of what it would take to make this a reality? This is definitely a common annoyance while editing Razor 😄

**Comment by NTaylorMullen** [comment]
> Can we get an idea of what it would take to make this a reality? This is definitely a common annoyance while editing Razor 😄

Would need to add a description API (`public string Description { get; set; }`) to our directive descriptors and would need to have the Razor editor understand that.

**Comment by rynowak** [comment]
We should make sure we can provide all the information that the editor needs for 2.0.0.

This is definitely lower in our priority list than getting the editor onto the new codebase and pages support (come at me bro).

**Comment by rynowak** [comment]
This is not going to happen for 15.3 preview 1 because the dates have become more aggressive.

**Comment by NTaylorMullen** [comment]
61260ddf1cca8ae56797632a3ea80217ca08c3fe
