### ISSUE TITLE
Add helper method to suppress outer TagHelper tag.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#293]
Right now we have a helper method on the `TagHelperOutput` object named `SuppressOutput` to remove all aspects of output of the currently executing `TagHelper`. We should also add an extra helper method named something to the extent of `SupressOuterTag` which is a glorified way of setting `TagHelperOutput.TagName = null`. This is typically a hidden functionality of the `TagHelperOutput` object and we should add a method to make it more user friendly.

**Comment by dougbu** [comment]
@NTaylorMullen I suspect the only difference between calling this new method and the existing `SuppressOutput()` is required ordering i.e. authors must set `[Pre|Post]?Content` after calling `SuppressOutput()`. am I missing something?
separately I'm wary of providing a second, "glorified" way of doing something tag helper authors can already do.  is the `TagName` property insufficiently documented?

**Comment by NTaylorMullen** [comment]
@DamianEdwards, @yishaigalatzer and I were talking today and felt that the functionality of setting `TagName` to `null` is very hard to discover and not a great API to have hidden. Exposing the functionality as a method (much like `SuppressOutput`) would help users. 

We could also consider reverting the `TagName = null` behavior and provide an alternative property to indicate if the outer tag will render.

**Comment by danroth27** [comment]
We've decided to stick with the property behavior.
