### ISSUE TITLE
Provide a mechanism for handling large content in TagHelper

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Razor#295]
In TagHelperOutput the mechanism to communicate the content is through a string. If the tag helper ever renders over 80K of data, it is going to end up in LOH, causing multi-second pauses. Further more, strings are constantly being generated by a `StringBuilder`  and through testing we did with MVC5 we realized that a large portion of the runtime (could be in the 20% range) is spent in garbage collection (see http://blogs.msdn.com/b/webdev/archive/2014/07/28/announcing-the-beta-release-of-web-pages-3-2-1.aspx)

**Comment by NTaylorMullen** [comment]
Closing this since we've designed a replacement: https://github.com/aspnet/Razor/issues/296
