### ISSUE TITLE
Change TagHelperOutput Content, PreContent and PostContent to all be TextWriters to avoid large string allocations.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#296]
This issue is the more concrete version of https://github.com/aspnet/Razor/issues/295.

What should be done to `TagHelperOutput`:  

1. Change `TagHelperOutput.PreContent` to be `TagHelperOutput.PreContentWriter`.
1. Change `TagHelperOutput.Content` to be `TagHelperOutput.ContentWriter`.
1. Change `TagHelperOutput.PostContent` to be `TagHelperOutput.PostContentWriter`.  

All new property names here should be of type https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Rendering/StringCollectionTextWriter.cs but exposed as `ITextWriter`. This means that type will need to be transitioned into the `Microsoft.AspNet.Razor.Runtime` repo.

Extra additions to make this change more consumable:  

1. `ITextWriter` should have an extension method to write on `ITextWriter` into another `ITextWriter`.
1. `TagHelperContext`'s `GetChildContentAsync` should have an override to provide your own `ITextWriter` to write to.

The impact of this change will end up affecting all existing `TagHelper`'s and will greatly affect how `TagHelper`s used (NOTE: Lots of impact in MVC to make this plausible).

**Comment by NTaylorMullen** [comment]
@sornaks: @yishaigalatzer, @DamianEdwards, @dougbu, and I felt like this is a pretty large feature that should make it in sooner rather than later (since it has huge impact). We can sit down together tomorrow or when you're ready to pair program the beginning parts of this to give you enough context on what needs to be done (lotssss of pieces to this :smile:).

**Comment by dougbu** [comment]
> All new property names here should be of type https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Rendering/StringCollectionTextWriter.cs.

Do you mean "of type `ITextWriter` which we (in MVC) back using `StringCollectionTextWriter`"?  If yes, `StringCollectionTextWriter` might not need to move.

**Comment by NTaylorMullen** [comment]
Yes, muchas gracias :smile:

**Comment by sornaks** [comment]
Checked in. https://github.com/aspnet/Mvc/commit/284eb9ac6a4f69f80f2c767a6d35f40dbd091131, https://github.com/aspnet/Razor/commit/bd9d57d33ef9e3021a5c7760f7a0a7bed5701a1d
