### ISSUE TITLE
Razor does not respect html comments inside a razor block

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Razor#301]
See original comment - https://aspnetwebstack.codeplex.com/workitem/2233

Does not work
```
@{
    <!-- Hello, I'm a comment that will break razor --->
}
```

Works
```
    <!-- Hello, I'm a comment that will break razor --->
```

If you have more than 2 dashes at the end of the comment - Razor shows compilation error. Only 2 dashes are accepted. However, if this comment is outside a codeblock, it works fine.

**Comment by danroth27** [comment]
Dup of #302
