### ISSUE TITLE
Prefer the new encoders over the old WebUtility APIs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/Razor#304]
There are still some call sites in the Razor code base that invoke WebUtility.HtmlEncode.  These call sites should instead use IHtmlEncoder.HtmlEncoder.

**Comment by danroth27** [comment]
See aspnet/mvc#2012.

**Comment by GrabYourPitchforks** [comment]
The types `IHtmlEncoder`, `IJavaScriptStringEncoder`, and `IUrlEncoder` are in the Microsoft.AspNet.WebUtilities package. To register them from within your own AddServices method, reference the Microsoft.AspNet.Http.Extensions package and call `AddEncoders`.

**Comment by ajaybhargavb** [comment]
7ecce1b66618bcbaca8227df652f8d53a7b8b294
