### ISSUE TITLE
Support a directive to set a prefix that opts elements into Tag Helper processing (parse time)

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#309]
We should support a new directive that allows the app to set a prefix that is used to opt elements into Tag Helper processing at parse time. It should default to nothing (no prefix). This is the functional opposite of the `!` prefix for opting elements out of Tag Helper processing.

The directive should be hierarchical so that it can be set globally (in _GlobalImport.cshtml) or at any folder level.

It can be set to any string literal that the razor parser considers valid as part of an HTML element name.

.e.g. in _GlobalImport.cshtml
``` HTML
@tagHelperPrefix "th:"
```
in Views/Home/Index.cshtml
``` HTML
<input class="not-processed-for-tag-helpers" />
<th:input class="processed-for-tag-helpers" />
<cache>Not processed for tag helpers</cache>
<th:cache>Processed for tag helpers</th:cache>
```

**Comment by NTaylorMullen** [comment]
@DamianEdwards what do you think should happen in the case that a user has two of these on a single page? Error right?

**Comment by DamianEdwards** [comment]
@NTaylorMullen yep, error.

**Comment by NTaylorMullen** [comment]
4d97a544f13a9bb1cf6d21a1c622a50af22add91
4bd02badda18e7097dbc38bcd67b48b7965f022f
