### ISSUE TITLE
TagHelperExecutionContext must be smart about new TagHelper Content allocations.

### ISSUE THREAD

**Issue by sornaks** [aspnet/Razor#317]
Quoting Taylor's comment:

You'll have to add a bit more to make the copying work as expected/performantly. The generated code that calls into this method looks like:
```c#
if (__tagHelperExecutionContext.Output.IsContentModified)
{
    Write(__tagHelperExecutionContext.Output.GenerateContent());
}
else if (__tagHelperExecutionContext.ChildContentRetrieved)
{
    Write(__tagHelperExecutionContext.GetChildContentAsync().Result);
}
else
{
    __tagHelperExecutionContext.ExecuteChildContentAsync().Wait();
}
```
So in the case that the user retrieved the child content: `__tagHelperExecutionContext.ChildContentRetrieved` you will end up copying the result again before writing it (no bueno).

Now it's also important to re-copy each time the `GetChildContentAsync` method is called so multiple TagHelper authors can see the original content (without worrying about someone else modifying it); you have this part covered.

You'll need to add a capability to retrieve the original, uncopied version for the page to use in the `else if (__tagHelperExecutionContext.ChildContentRetrieved)` clause.

**Comment by rynowak** [comment]
The work item here is really to profile our new changes and see what still lights up as a hotspot for allocations and copying. The comments linked here called out a case that we might want to optimize, but the work that we need to do is much broader than what's called out above.

**Comment by Eilon** [comment]
Covered by https://github.com/aspnet/Razor/issues/358.
