### ISSUE TITLE
Consider moving TagHelperOutput.Generate*() functionality to RazorPage.Write in Mvc.

### ISSUE THREAD

**Issue by sornaks** [aspnet/Razor#318]
Quoting @dougbu 's [comment](https://github.com/aspnet/Razor/pull/312#discussion-diff-25563399):

for future consideration (not this PR) but related to the `TagHelperContent / DefaultTagHelperContent` split introduced here: suggest we split `TagHelperOutput` along similar lines and get the `Generate*()` methods and perhaps `ContentSet` out of tag helper authors' faces.

This split could go further and move the `Generate*()` methods completely out of this class (or class hierarchy). if `_isTagNameNullOrWhitespace` were exposed as a property (like `ContentSet`), these methods would not require any private information. could move generation many places but I suggest the `RazorPage.WriteLiteral[To]([TextWriter,] TagHelperExecutionContext)` methods I proposed elsewhere. in any case, this would pull apart the mix of responsibilities `TagHelperOutput` has today.

**Comment by dougbu** [comment]
the general point is to revisit what we expose in `TagHelperContent` and how we use that class in the framework.  this includes looking closely at the [boilerplate code](https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNet.Razor.Test/TestFiles/CodeGenerator/CS/Output/BasicTagHelpers.CustomAttributeCodeGenerator.cs#L39-L54) generated for tag helper scenarios.

another [comment](https://github.com/aspnet/Razor/pull/312#discussion_r25563274) from the same review:
> not necessarily a part of this PR: suggest we create `WriteLiteral(TagHelperExecutionContext)` and `WriteLiteralTo(TextWriter, TagHelperExecutionContext)` overloads in `RazorPage`.  no reason to generate the boilerplate code from `WriteLiteral(__tagHelperExecutionContext.Output.GenerateStartTag());` through this line.  possible to include the `RunAsync()` call in the methods but that doesn't fit well into a "WriteSomething()` method.

**Comment by danroth27** [comment]
@sornaks Please work with @DamianEdwards @NTaylorMullen @dougbu on this.

**Comment by sornaks** [comment]
https://github.com/aspnet/Razor/commit/7daec14e49b96ff7833409c465ec73ce9b151e8b and https://github.com/aspnet/Mvc/commit/c1338a05428baaf1ba31ffd40a3078e5f8d013aa
