### ISSUE TITLE
Move ParserErrorSink, RazorError and SourceLocation to a better namespace

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#320]
These files are used somewhat regularly and are no longer only used during the parsing phase.

Associated convo: https://github.com/aspnet/Razor/pull/316#discussion_r26010720

**Comment by dougbu** [comment]
fixed in
- 3f7c75e
- aspnet/Mvc@cef32d4
- aspnet/RazorTooling@16b4c64
