### ISSUE TITLE
Don't special case '*' retrieval in TagHelperDescriptorProvider

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#324]
Associated convo: https://github.com/aspnet/Razor/pull/316/files#r26606226

**Comment by danroth27** [comment]
@NTaylorMullen The convo is too big. Please paste in the relevant points here. Thanks.

**Comment by dougbu** [comment]
simply about removing code (a few lines) that is never used in any realistic scenario.  exists in case someone uses a low-level internal detail of our tag helper resolution system in a somewhat strange way.  note tag helper authors don't even know `TagHelperDescriptor` exists.

**Comment by NTaylorMullen** [comment]
3ba92523ff90c9d77fc8c1dd5e722927e10e21c1
