### ISSUE TITLE
Consider simplifying syntax for @addTagHelper

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#337]
Had some discussion around this feature while testing it for beta4. Right now we don't provide any intellisense/validation for the format inside an `@addTagHelper` and it would be useful for catching errors. 

Additionally we provide globbing-like support with `*` and `?` - which doesn't seem especially useful. I don't get why we'd want to use a file-like metaphor for code-artifacts that are expected to match a fully-qualified class-name. _This seems like a barrier to providing a better experience here, because we can't map these directives directly to a class/classes - there's more possible ways for it to be wrong._

I suggest we stick to the prior-art in this area - there's a direct parallel between this and python/java `import` which only provide wildcarding for the final token.

**Comment by Anderman** [comment]
I can't think of any usefull with globbing-like support for the `@addtaghelpers`. If the intellisense show me a list with all the taghelpers in the solution then a star at the end should be enough.
