### ISSUE TITLE
Support string interpolation literals for Tag Helper string properties

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#338]
To use C# 6 interpolated string literals with attributes bound to string Tag Helper properties, you currently need to enclose the string literal in a Razor expression block:

``` HTML
<th:sample name="@($"Hello {User.GetUserName()}")"></th:sample>
```

It would be much nicer to just support string interpolation directly on attributes bound to string properties like so:

``` HTML
<th:sample name=$"Hello {User.GetUserName()}"></th:sample>
```

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by NTaylorMullen** [comment]
I don't feel like this is important for beta5, putting it lower on my priority since there's other larger issues.

**Comment by DamianEdwards** [comment]
Agreed

**Comment by Eilon** [comment]
@DamianEdwards @NTaylorMullen moving to backlog. This seems a bit more obscure in terms of usage.

**Comment by rynowak** [comment]
We think this is good enough for now. We'll revisit if there's a killer scenario later
