### ISSUE TITLE
TagHelper attribute targeting doesn't work with an attribute with no value

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#339]
![image](https://cloud.githubusercontent.com/assets/1430011/6878232/9e1bc25e-d497-11e4-9b64-417c2b4e376a.png)

This `TagHelper` won't run unless the attribute has a value. Adding `=""` makes it start working.

```
[TargetElement("p", Attributes = "data-th-order-before")]
    public class OrderBeforeTagHelper : TagHelper
    {
        public override int Order
        {
            get
            {
                return -1;
            }
        }

        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            string style;
            if (output.Attributes.TryGetValue("style", out style))
            {
                return;
            }
            else
            { 
                output.Attributes.Add("style", "font-size: 24px;");
            }
        }
    }
```

**Comment by dougbu** [comment]
probably a dupe of #220

**Comment by danroth27** [comment]
@dougbu @rynowak @NTaylorMullen Looks a bit different than #220. This is just about targeting while #220 is about actually getting the value. We think this is getting addressed as part of @NTaylorMullen's changes.

**Comment by NTaylorMullen** [comment]
Looked into this and this is due to the bound attributes being prefixed with `data-` (was unable to repro it with any other type of bound attribute). Ultimately this issue will be fixed by: https://github.com/aspnet/Razor/issues/342 I recommend closing this item
