### ISSUE TITLE
TagHelper attributes with data- have surprising behavior

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#342]
Consider the following:
```
@{ var pwnt = "Hello, world!"; }
<p data-th-color="color: red; @pwnt">
            This should be red.
</p>


[TargetElement("p", Attributes = "data-th-color")]
    public class ColorTagHelper : TagHelper
    {
        [HtmlAttributeName("data-th-color")]
        public string Color { get; set; }

        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            output.Attributes.Add("style", Color);
        }
    }
```

Inside the taghelper, the value of `Color` is `"Hello, world!"` instead of the expected `"color: red; Hello, world!"`. According to @NTaylorMullen this is because razor has special handling of data-* attributes.

Changing the attribute to something that doesn't begin with data- will give the expected behavior.

**Comment by dougbu** [comment]
whatever the special case is, the **Principal of Least Surprise** says Razor is broken here.  either binding an attribute named `data-*` is an error or it should do the Right Thing:tm: i.e. behave like any other bound attribute.

**Comment by NTaylorMullen** [comment]
Agree.

Curious: @anurse why did we special case `data-` in Razor?

**Comment by anurse** [comment]
We special-cased it for conditional attributes. Conditional attributes are designed to make it easier to write HTML that User Agents can properly interpret. We do this by making `checked="@foo"` render as `checked="checked"` if `foo` is `true`, or removing it entirely if foo is `false` or `null`.

However, `data-` attributes are explicitly called out as being reserved solely for the purpose of the end-application-developer:

> These attributes are not intended for use by software that is not known to the administrators of the site that uses the attributes. For generic extensions that are to be used by multiple independent tools, either this specification should be extended to provide the feature explicitly, or a technology like microdata should be used (with a standardised vocabulary). (http://www.w3.org/html/wg/drafts/html/master/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes)

Thus, they are explicitly not implemented by User Agents and we didn't want conditional attributes getting in the way of existing application code (and turning something like `data-enabled="@foo"` suddenly vanishing when the JavaScript that reads it expects a literal string `false`).

For a similar reason, I think we should take @dougbu 's first suggestion here and disallow binding Tag Helpers to `data-` attributes.

**Comment by NTaylorMullen** [comment]
@DamianEdwards do you feel like we should be able to bind `data-` attributes? Or should it result in an error?

**Comment by NTaylorMullen** [comment]
Note: Decision was to not allow `TagHelper` authors to bind to attributes starting with `data-`. If they try to we will create an error.

**Comment by NTaylorMullen** [comment]
5bcda94b2c7a0179250d73b73ae4b39ce0a0789e

**Comment by NTaylorMullen** [comment]
Looks like this also occurs for unbound `TagHelper` attributes and doesn't end up falling into (shouldn't) the error case which is how we initially addressed this issue.

**Comment by NTaylorMullen** [comment]
b25bf01158f69bce1db4c8e2b244bc8c21403273
