### ISSUE TITLE
Escape shortcut fails when first text character is a `:`

### ISSUE THREAD

**Issue by Buildstarted** [aspnet/Razor#346]
@if(true) {
        @::Something
    }

The above code block produces this error: `"::" is not valid at the start of a code block. Only identifiers, keywords, comments, "(" and "{" are valid.`

The expected output is `:Something`. I can get around this by using `<text>:Something</text>`. My assumption is because `::` is a valid namespace qualifier in c#.

**Comment by tkirill** [comment]
Hi!

I want to try to fix this, hope `up-for-grabs` bug isn't too difficult.  What branch should I choose as starting point?  `master` or `dev`?

**Comment by Eilon** [comment]
@NTaylorMullen move this to the right milestone and close as Done?

**Comment by NTaylorMullen** [comment]
Si :smile:

**Comment by NTaylorMullen** [comment]
a0164b005d9bdd0ee59de3c90c38499fdc8ebd15
