### ISSUE TITLE
Consume docs on TagHelper classes to provide IntelliSense at design time.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#352]
Right now when writing `TagHelper`s users consume them in the editor without any added IntelliSense. If we were to discover docs related to `TagHelper` classes and expose those via `TagHelperDescriptor`s we could provide more information to make tooling easier to use.

I believe we should do this at the Razor level to enable cross-platform scenarios.

**Comment by danroth27** [comment]
Need to understand the tooling impact.

**Comment by NTaylorMullen** [comment]
This wont be done for beta5, this is a larger issue that will most likely be post rtm.

**Comment by NTaylorMullen** [comment]
ccf8433f27f0a3e4d20a8a75beefd6a07f0748a8
9055da1894d2df0aaabe642498a94c5001a01981
02a3ca8abb042102980c85e4dd41835aac562602
920358ab0de25b868e8192e62e9af38839588660
