### ISSUE TITLE
Analyze performance impact of TagHelperContent not being lazy on TagHelperOutput properties.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#358]
The initial implementations of the "new" `TagHelperOutput` data structure (one with buffers instead of strings) was originally lazy with the buffers construction but was then removed due to the added complexity via code review. We should analyze its perf impact to determine if being lazy about construction of `PreElement`, `PreContent`, `Content`, `PostContent` and `PostElement`'s `TagHelperContent` objects is beneficiary.

**Comment by Eilon** [comment]
Please see https://github.com/aspnet/Razor/issues/317 for additional info.

**Comment by Eilon** [comment]
Please have a chat with @rynowak before starting the perf investigation.

**Comment by rynowak** [comment]
> beneficiary

Yes. Let's discuss

**Comment by Eilon** [comment]
Hah!

**Comment by rynowak** [comment]
Let's discuss
![image](https://cloud.githubusercontent.com/assets/1430011/11051973/17d183e4-8709-11e5-9a9b-4f04e239baad.png)

This is definitely worth addressing

**Comment by NTaylorMullen** [comment]
Upon investigating a proper fix for this issue I decided to investigate what it'd take to have `TagHelperOutput` be an `IHtmlContent` (since it's responsible for lazily initializing buffers). After a lot of playing around with the idea and talks with @DamianEdwards it definitely fits. 

This will also involve removing the `WriteTagHelperAsync` method from Mvc.

**Comment by NTaylorMullen** [comment]
bdf869c3d586e1ac4b94882aa91a719058ec9aa3
e8327eeec76afcb4156e95763e580df3693f4d8e
6b43ebc88b4645ab62e0f0f87a687d477f7f7c39
https://github.com/aspnet/Mvc/commit/2dc13b523d9b346fc99f998902f8d69a44222948
