### ISSUE TITLE
Support * wild card in TargetElement Attribute.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#361]
This will enable `TagHelper` authors to target `IEnumerable<KeyValuePair>` attributes (https://github.com/aspnet/Razor/issues/89).

Essentially:

```C#
[TargetElement(Attributes = "q-*")]
public class QueryParamTagHelper : TagHelper { }
```

Use:

```HTML
<!-- A TagHelper because of q-custom -->
<a href="~/home/index" q-custom="AValue">Go to index</a> 
```

**Comment by danroth27** [comment]
@DamianEdwards How important is this? Do we want this for beta5?

**Comment by DamianEdwards** [comment]
Yes, it's needed for the anchor Tag Helper when we finish the work to support binding to dictionary properties.

**Comment by NTaylorMullen** [comment]
0e61b49881f77fb9123792ea12eb6f5e4411078d
