### ISSUE TITLE
Two-way model binding with TagHelpers doesn't seem to be working for <select>

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Razor#363]
Win7
Brackets/Omnisharp
DNX: dnx-coreclr-win-x64.1.0.0-beta5-11572
MVC: 6.0.0-beta5-13567

New to MVC, so I might be to blame for this, but consider this markup for a `<select>`:
```
<th:select asp-for="department" size="3">
   <option>Sales Department</option>
   <option>Billing Department</option>
   <option>Technical Support</option>
</th:select>
```
I have other `<input>` elements on this `<form>` with `asp-for` on them, e.g., 
```
<th:input asp-for="email" type="text" />
```
The model binding for the `<input>` elements works both ways: I can specify in my controller that a value should be:
```
visitor.email = "test@test.com";
```
It goes to the view ... I can change it in the browser ... submit that form and check the value in the controller ... sure enough ... it sets the `visitor.email` value correctly. That two-way binding is working fine.

However, the binding with the `<select>` is only going back to the controller. If I click on an `<option>` in the browser, the `visitor.department` value correctly reflects the chosen `<option>` in the controller on postback, but that value doesn't make its way back client-side after the postback: The element resets itself back to no selected `<option>`. This is also true if I explicitly set the value of `visitor.department` on an `[HttpGet]`:
```
visitor.department = "Billing Department";
```
... and send the model to the view: The `<select>` doesn't get a `selected` attribute on the "Billing Department" `<option>`.

So, am I using `<select>` model binding incorrectly here? ... or is there a model binding bug?

**Comment by dougbu** [comment]
@GuardRex if you have configured your view to use a prefix such as "th:", you must use it for every tag helper.  given both `<select/>` and `<option/>` are associated with tag helpers, `<option>Sales Department</option>` looks incorrect in your description.  that should be `<th:option>Sales Department</th:option>`.  same for the other `<option/>` elements in your .cshtml file.

**Comment by GuardRex** [comment]
Ah! Thank you. I'll try that.
