### ISSUE TITLE
Duplicate HTML attribute names should be invalid

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#364]
Razor intentionally does not support binding a single attribute from the .cshtml file to multiple attributes in a tag helper.  However `TagHelperDescriptorFactory` creates `TagHelperDescriptor`s for such tab helpers and does not report an error to the `ErrorSink`.

e.g. the following tag helper should not be valid since the calculated name of one property matches the provided name of the other.
``` c#
private class DuplicateAttributeNameTagHelper
{
    public string MyNameIsLegion { get; set; }

    [HtmlAttributeName("my-name-is-legion")]
    public string Fred { get; set; }
}
```

**Comment by dougbu** [comment]
also restore test at https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNet.Razor.Runtime.Test/TagHelpers/TagHelperDescriptorFactoryTest.cs#L497

**Comment by danroth27** [comment]
We would only fix this based on customer feedback.
