### ISSUE TITLE
Add timeout values to all regex expressions

### ISSUE THREAD

**Issue by blowdart** [aspnet/Razor#369]
To avoid regex attacks add a time-out value to every regular expression in the code base.

**Comment by NTaylorMullen** [comment]
Is there a recommended way to determine appropriate timeout values?

**Comment by blowdart** [comment]
No, that's left as an exercise for the developer.

**Comment by Eilon** [comment]
See this example for a recommended pattern: https://github.com/aspnet/FileSystem/pull/119/files

**Comment by ajaybhargavb** [comment]
88f4153fd97b8c9f5f74c1455895d113d84d02ab
