### ISSUE TITLE
Did ContentBehavior go away?

### ISSUE THREAD

**Issue by roblom** [aspnet/Razor#373]
Watching this video: http://channel9.msdn.com/Shows/Web+Camps+TV/Create-your-own-Domain-Specific-Language-in-ASPNET-with-TagHelpers
I'm creating the same "EmailTagHelper" but the attribute ContentBehavior is nowhere to be found "ctrl + ." doesn't give any suggestion except generating a class.
What could be missing here? (The project is a "starter"-project.)
Without the attribute it compiles and runs, but without any "magic" happening to my "email"-tag.

I have the VS 14.0.22823.1 and project.json says
"Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta4"

    [ContentBehavior(ContentBehavior.Append)]
    public class EmailTagHelper : TagHelper
    {
        public static string EmailDomain = "mycompany.com";
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            output.TagName = "a";
            output.Content.SetContent(output.Content + "@" + EmailDomain);
            output.Attributes["href"] = "mailto:" + output.Content;
        }
    }

**Comment by NTaylorMullen** [comment]
Ya we removed `ContentBehavior` in beta4, it's been designed away (https://github.com/aspnet/Razor/issues/221). Sorry for the confusion, i've reached out to get the comment updated on the video .

An equivalent `EmailTagHelper` now looks like:

```C#
public class EmailTagHelper : TagHelper
{
    public static string EmailDomain = "mycompany.com";
    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        output.TagName = "a";
        output.PostContent.SetContent(output.Content + "@" + EmailDomain);
        output.Attributes["href"] = "mailto:" + output.Content;
    }
}
```

Note the `Content` => `PostContent` change :smile:

**Comment by roblom** [comment]
Works better now =)
But getting the content seems to be not working. While in debug-mode the output.Content is empty while the markup looks like:
<email>robert</email>
and the output is:
<a href="mailto:@mycompany.com">robert@mycompany.com</a>

Bug?

**Comment by NTaylorMullen** [comment]
@roblom Ahh yes, so we transitioned "receiving" the content into a method call. You can do this as follows:

```C#
// Executes everything inside of your TagHelper and returns the rendered output
var childContent = await context.GetChildContentAsync(); 
```

Aka you can't directly retrieve what's inside of the `TagHelper` via the `.Content` property, you have to choose to invoke it.

**Comment by roblom** [comment]
All good!
