### ISSUE TITLE
Implement VirtualPathProvider

### ISSUE THREAD

**Issue by ericis** [aspnet/Razor#377]
Would this be a ["FileSystem"](https://github.com/aspnet/FileSystem) concern?  I apologize if this is the wrong repository or already under consideration, but I couldn't find it in search.  I found ["IFileProvider.cs"](https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.AspNet.FileProviders.Abstractions/IFileProvider.cs), but couldn't (easily) find the implementation details and how to potentially substitute another provider to serve ".cshtml" files from else-where.  Thoughts?

**Comment by pranavkm** [comment]
https://github.com/aspnet/Mvc would be the right place to discuss details about serving views \ cshtml files. There's a similar work item with some discussion here - https://github.com/aspnet/Mvc/issues/2432#issuecomment-95312850
