### ISSUE TITLE
C# parsing has a too-simple notion of `string`s

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#381]
When in HTML mode, Razor passes `&quot;` through to the output correctly.  However in C# mode, Razor unconditionally ends an attribute value when _any_ matching quote is found.

For example, given a tag helper containing:
``` c#
  public object MyObject { get; set; }
```

Razor source containing one of the following results in parser errors or garbled code generation:
``` html
  <element my-object="some string" />
  <element my-object="\"some string\"" /> @* Not parsed correctly though in C# mode *@
  <element my-object="&quot;some string&quot;" />
```

Current workarounds:
``` html
  <element my-object='"some string"' />
  <element my-object="@("some string")" />
```

My suggestion is to support syntax such as `"@"some string""` in a C# context.  Bonus points if we support doubled quotes (`""`) within "some string".

**Comment by danroth27** [comment]
@DamianEdwards thoughts?

**Comment by DamianEdwards** [comment]
I'm not too fussed. The workarounds seem reasonable right now. Low priority.

**Comment by dougbu** [comment]
@DamianEdwards a bit more background:
- Relates to #89 because the new `<a>` and `<form>` tag helper `RouteValues` dictionary properties are of type `IDictionary<string, object>`.  So `<a route-name="myRoute" />` must change to `<a route-name="@("myRoute")" />` with current workarounds.
- `<a route-name='"myRoute"' />` may work but is not discoverable because the editor auto-fills `route-name=""`
- Relates to #338 because supporting some but not all C# `string` literal formats would just be weird.  I.e. if we support `<a route-name=$"myRoute" />`, why not `<a route-name=@"myRoute" />` or
``` c#
<a route-name=$@"
myRoute" />
```
?

In general the special case for `string` properties leads to some strange inconsistencies.  This bug is one place where `string` properties work more naturally.

However every other tag helper property leads to a "pure" C# interpretation of attribute values.  So if both `a` and `b` are `string` variables, `bound-attribute="@a + @b"` means "concatenation of `a` and `b` values" unless the `BoundAttribute` property happens to be of type `string`. In the `string` special case, it instead means "concatenation of `a` value, `" + "` and `b` value". Further it is not possible to explicitly set a tag helper's `string` property to `null` in the Razor source.

We also generate significantly more-complicated code for `string` property assignments.  That code does _not_ match generation for regular HTML attributes because HTML encoding must be disabled.  And the extra complication leads to increased chance of bugs.

**Comment by NTaylorMullen** [comment]
Curious: Would it be ok if `RouteValues` were `IDictionary<string, string>`?

**Comment by DamianEdwards** [comment]
@NTaylorMullen yeah that's the conclusion we came to as well

**Comment by dougbu** [comment]
Other conclusions of offline conversations:
- Don't remove special case(s) for bound `string` properties.  Just too common a case.
 - Unless we get customer demand for explicitly setting, a `string` property to `null`, assume that's not a case at all.
- @dougbu to file a bug about fact entire attribute value is not C# when a non-`string` (note: *non-*) bound property is used e.g. `<element non-string="@object + value" />`.
- Have strong feelings against introducing `<element bound-object=@"some (verbatim) string" />` due to confusion with other use of `@` in Razor.  #338 (`<element bound-object=$"some {interpolated} string" />`) is an easier fit.
- Low-priority fix for _this_ bug would be to handle backslashes for bound `string` properties (and perhaps regular HTML attributes) e.g. `<input asp-format="\"{0:d}\"" />`.

**Comment by dougbu** [comment]
We have one corner case when route filters are in use if we do not support `object` values in the `RouteValues` dictionary:
``` c#
// In Startup.cs:
routes.MapRoute(
    name: "intDefault",
    template: "{controller=Home}/{action=Index}/intValue",
    defaults: new { id = 3 });
routes.MapRoute(
    name: "stringDefault",
    template: "{controller=Home}/{action=Index}/stringValue",
    defaults: new { id = "3" });
routes.MapRoute(
    name: "default",
    template: "{controller=Home}/{action=Index}/{id?}");

// In Index.cshtml:
<a asp-route-id="3">three</a>

// Resulting link is:
http://localhost:58457/Home/Index/stringValue
```

The generated link would be `http://localhost:58457/Home/Index/intValue` if the `3` were provided to the routing system as an `int`.  This could be a bug in the filtering (@rynowak ??).  Otherwise we're forgoing direct support of this corner case in favour of a usable Razor experience.

**Comment by rynowak** [comment]
@dougbu whatever the MVC5 behavior is is correct WRT filtering and object-equality comparisons.

To me, using strings here is a pit-of-success thing.

**Comment by Eilon** [comment]
Strings are generally recommended, of course, but even with routing it is *not* the case that only strings are used. People define routes with defaults that have values of enum types, ints, etc. and they need to match when generating URLs, so strings are insufficient there. Now, I will concede that these aren't super common, and so if tag helpers use `Dictionary<string, string>` that's fine. I'm merely asserting that it is *incorrect*, but perhaps acceptable.

Of course, none of this takes away from the fact that non-string support is a bit "delicate" right now, and we'll want to revisit all the tag helper bound attribute value behaviors after beta5.

**Comment by danroth27** [comment]
https://github.com/aspnet/Razor/issues/434
