### ISSUE TITLE
Add OutputElementHintAttribute to control inherited TagHelper IntelliSense.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#382]
Right now if you create a `TagHelper` `<foo>` which translates into a `<ul>` you miss out on any `ul` specific HTML IntelliSense when writing `<foo `. It'd be nice to have an attribute that would cause the HTML editor to inherit specified tag IntelliSense. AKA

```C#
[OutputElementHint("ul")]
public class FooTagHelper : TagHelper
{
...
}
```

Which would result in `<foo ` invoking global and `ul` based IntelliSense.

**Comment by DamianEdwards** [comment]
Nice idea, crappy name. I'd go with something like `[OutputElementName("ul")]` or similar. We don't want to include VS-specific names in our APIs. This is really just a "hint" to the IDE in case it cares.

**Comment by NTaylorMullen** [comment]
:smile: :+1:

**Comment by NTaylorMullen** [comment]
@DamianEdwards I'm thinking of adding support for multiple `OutputElementName`s like so:

```C#
[OutputElementName("ul", "div", "p")]
public class FooTagHelper : TagHelper
{
...
}
```

Which would indicate "give me all of the IntelliSense for `ul`, `div`, and `p` tags combined". Thoughts?

**Comment by danroth27** [comment]
@NTaylorMullen Please add a tooling issue to tracking the tooling side of this work.

And the name is OutputElementHintAttribute.

**Comment by NTaylorMullen** [comment]
85be731e2b39ea9a0e2d39cf11775f23c2a2528f
https://github.com/aspnet/Mvc/commit/15cb2ce709e7b118437c9ea39ad66f1ac9c4d5d3
https://github.com/aspnet/RazorTooling/commit/71a5a9f0c4026da3b368f4dbeaf4d210ad509eb8
