### ISSUE TITLE
Incorrect classification (and therefore IntelliSense) for expressions containing transition characters (ex @)

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#387]
When providing values for non-`string` tag helper properties, Razor authors lose IntelliSense and other C# support when the expression contains transitions.  A simple example would be `<element non-string="@object + value" />`.

Using existing MVC tag helpers in a contrived way, the following illustrates the issue.  Note only `@ValidationSummary.All` is highlighted in the second case.  Even the attribute name gets the wrong classification.
![highlighting](https://cloud.githubusercontent.com/assets/6431421/7604287/ecef64b8-f8f4-11e4-9de1-3c7af7a025f8.png)

Problem is likely related to fact not all `Span` components of the more-complex expression get `SpanKind.Code`.  In particular `TagHelperBlockRewriter.CreateMarkupAttribute()` isn't called on every code path through `TagHelperBlockRewriter.TryParseBlock()`.

**Comment by NTaylorMullen** [comment]
039062c5eb1e3c2f6f5320995406a40fb448b250
