### ISSUE TITLE
Motivation Behind GeneratedClassContext?

### ISSUE THREAD

**Issue by daveaglick** [aspnet/Razor#389]
Just curious if anyone could share the motivation behind the `GeneratedClassContext` class and why method and other names are supplied as strings. I'm going to guess that this was done to make the code generator a bit more general so that it could adapt to base classes with different method names. The part I don't get though is that the method signatures are still really specific, which means any class serving as a base for the code generation output still has to follow a very specific contract or it won't compile. Right now libraries that use Razor have to kind of guess at the expected signatures. Given this, I wonder about the utility of allowing alternate names - it just seems to make everything more complicated. Not to mention that the primary user of Razor (MVC) just uses the default names anyway.

It seems to me like a better alternative would be to define an `IRazorResult` or `IRazorCodeGenBase` (the name of the interface isn't important) that contains the exact method and property names and their expected signatures and then have the code generator assume the base class implements this interface and output accordingly. That would provide a much clearer contract for third-party Razor consumers. It would also remove ambiguity as well as the magic strings used to specify method names. The code generator could also then be strongly-typed using generics with a constraint on the interface, or at least take a `Type` instead of specifying the base type by name.

In the cases where the existence (or not) of a method name in `GeneratedClassContext` currently indicates support (or not) of a given feature, additional interfaces could be provided. Then the code generator could just check if the result base class implements those interfaces to see what kind of code it should emit.

Anyway, curious to hear some feedback on this line of thinking - especially if I've missed the boat entirely (which is always possible, if not likely). Thanks.

**Comment by NTaylorMullen** [comment]
`GeneratedClassContext` was there initially to remove runtime dependencies from `Microsoft.AspNet.Razor`. As the Razor parser has evolved the signatures have become quite complex resulting in a significantly difficult time consuming the output of the parser outside of MVC. This is why we created the `Microsoft.AspNet.Razor.Runtime` for newer contracts (like `TagHelper`s).

Now as for providing core/existing base classes/interfaces that users can derive from: We had the same idea. I have a task wayyy on my backlog to move the core pieces of https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs into the `Microsoft.AspNet.Razor.Runtime` project. For the interim I'd recommend pulling bits from `RazorPage.cs` to ease the pain :smile: . If that's too heavy you can look for a lighter/less functional implementation here https://github.com/aspnet/Diagnostics/tree/dev/src/PageGenerator

**Comment by daveaglick** [comment]
Got it, thanks. I know you folks have your heads down getting everything working for the vNext push, but I appreciate that thought has and is being given to non-MVC uses. Projects like RazorEngine, RazorGenerator, Nancy, etc. have shown that there are use cases for Razor outside of the MVC ecosystem. And more broadly, projects like Liquid, Textile, and even Markdown have shown that there is a need for general-purpose templating languages. I suspect that the easier it is to integrate, the more developers will take a look and find uses for Razor in their own systems.

In any case, your suggestion was exactly where I headed - I currently have an empty class full of `NotImplementedExceptions` with a comment at the top: `\\Steal this from RazorPage implementation` :) I'll take a look at `PageGenerator` too - I hadn't noticed that one and it might be more appropriate for my own use.

Thanks again!

**Comment by NTaylorMullen** [comment]
Not a problem, glad I could help. :smile:
