### ISSUE TITLE
Document signature information for methods with names in `GeneratedClassContext` and `GeneratedTagHelperContext`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#406]
We have a large number of `string ...MethodName` properties in `GeneratedClassContext` and `GeneratedTagHelperContext`. Some of these (especially those in `GeneratedClassContext`) have no documentation at all. Most of the rest provide no information on how generated code will call the method.

One example approach, used in the #89 fix (PR #395), is:
``` c#
        /// <remarks>
        /// Method signature should be
        /// <code>
        /// public string FormatInvalidIndexerAssignment(
        ///     string attributeName,       // Name of the HTML attribute associated with the indexer.
        ///     string tagHelperTypeName,   // Full name of the tag helper type.
        ///     string propertyName)        // Dictionary property in the tag helper.
        /// </code>
        /// </remarks>
```

Another approach would be for Razor to expose a few new `public interface`s describing the interesting methods. Unfortunately that would be too restrictive and wouldn't help with the numerous methods that are not invoked as instance methods. (Side note and good news: At least `GeneratedTagHelperContext` makes it clear what `...MethodName`s are instance methods.)

**Comment by danroth27** [comment]
Not high enough priority to spend time on right now.
