### ISSUE TITLE
Non-english characters are encoded

### ISSUE THREAD

**Issue by anfomin** [aspnet/Razor#409]
Every non-english character is encoded. For example:
```razor
@{
	string s = "Добрый день"; // this is Russian text
}
@s
```

The result is something like:
![2015-05-27 9 55 55](https://cloud.githubusercontent.com/assets/1905503/7829109/e6386e18-0456-11e5-8b52-408c3a15dc31.png)

**Comment by dougbu** [comment]
@anfomin are any characters displayed incorrectly in the page? Encoding should be visible only when viewing the HTML source.

**Comment by anfomin** [comment]
@dougbu characters displayed correct, but page size increased significantly :-1: Also MVC 5 rendered unicode symbol correctly in HTML source.

**Comment by dougbu** [comment]
@anfomin one of the benefits of MVC 6 is your ability to change most of the defaults. In this case you prefer a less-strict HTML encoder. To enable that, implement `IHtmlEncoder` and place it in DI using `services.AddInstance<IHtmlEncoder>(new CustomHtmlEncoder())` in your `Startup` class. (`AddInstance` is an example; pick the lifetime appropriate for your replacement service.)

**Comment by anfomin** [comment]
@dougbu I know I can replace with custom `IHtmlEncoder`, this is not a problem. But I thought this is not a feature but a bug because MVC 6 is the only framework that encodes normal Russian symbols (I think problem is not only in Russian language).

**Comment by dougbu** [comment]
FYI @danroth27 moved this to https://github.com/aspnet/HttpAbstractions/issues/315
