### ISSUE TITLE
Error is occurred if there is a link in the render section

### ISSUE THREAD

**Issue by pherbel** [aspnet/Razor#412]
Error is occurred if there is a link in the render section.
I don't know exactly why this error is coming. Maybe it is a bug. Please check it.
I'm running on beta4 version.

Error will be this:
error CS0246: The type or namespace name 'TagHelperContent' could not be found (are you missing a using directive or an assembly reference?)

Sample code:
@{
    ViewBag.Title = "MyPage";
}
@section mysection {

    <a href="http://www.test.com">Test</a>
}

This will work:
@{
    ViewBag.Title = "MyPage";
}
@section mysection {

    @*<a href="http://www.test.com">Test</a>*@
}

**Comment by dougbu** [comment]
This and aspnet/Mvc#2595 are duplicates. Closing aspnet/Mvc#2595 since most if not all of the fix will be in this repo.

**Comment by dougbu** [comment]
Self-assigning since aspnet/Mvc#2595 was in this milestone and assigned to me.

**Comment by dougbu** [comment]
113d80c

**Comment by pherbel** [comment]
Thank you.

**Comment by Azaret** [comment]
Thank you, I'll check this out.
