### ISSUE TITLE
Allow c# 6.0 null propagation in razor

### ISSUE THREAD

**Issue by kidchenko** [aspnet/Razor#416]
**I trying it**
![image](https://cloud.githubusercontent.com/assets/5432753/7941895/bd6c16e0-0930-11e5-9f17-811cf68ea96e.png)

**and get it**
![image](https://cloud.githubusercontent.com/assets/5432753/7941940/fb637b00-0930-11e5-965e-617aad1da284.png)

**Comment by NTaylorMullen** [comment]
Thanks for the report @kidchenko. This was completed via https://github.com/aspnet/Razor/issues/44. You can expect it in the beta5 release.

**Comment by kidchenko** [comment]
ok, sorry, I searched before creating a new :/

**Comment by NTaylorMullen** [comment]
All good, the 44 issue isn't the best since it's a catch-all for some of the C# 6 features. Did a great bug report though :+1:

**Comment by dotnetchris** [comment]
@kidchenko Available in MVC 5.2.3 and Razor 3.2.3 via

> Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform

Possibly available in other versions of MVC and Razor but i have not verified. I use null conditionals in razor almost every day with the latest MVC.
