### ISSUE TITLE
TagHelper removing ~ from HtmlAttribute

### ISSUE THREAD

**Issue by danroth27** [aspnet/Razor#417]
Reported by @grahamehorner as https://github.com/aspnet/Mvc/issues/2631.

When HtmlAttribureString a string starts with '~' this is stripped from the value populated into the TagHelper class property.  eg. "~/folder/file.txt" becomes "/folder/file.txt"

From @NTaylorMullen:

Good find, it even looks like we rely on this behavior a little bit in our own `TagHelper` samples which I believe is wrong.

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by dougbu** [comment]
Doesn't the `~` removal exist for back-compat reasons?  @pranavkm ?

**Comment by NTaylorMullen** [comment]
@dougbu it should only ever remove for `href` attributes, not "any" attribute. Today we're re-building the CodeGenerators on the Razor objects and it looks like we're stripping away the one that understood the `~` so it's no longer rendering.

**Comment by dougbu** [comment]
>  it should only ever remove for `href` attributes

Huh? What about `action` attributes in `<form>` elements, `src` attributes in `<script>` elements, and the various `asp-*` attributes that contain URLs (like `asp-fallback-href`)?

**Comment by NTaylorMullen** [comment]
That's not the behavior of `~` as far as Razor is concerned (Razor only does work to it for `href` attributes), it's an unintended side effect. We should be handling the `~` in those `TagHelper`s ourselves. We can't be stripping the `~` blindly for arbitrary attributes.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by NTaylorMullen** [comment]
Investigated this bit and it looks like it's generating the correct code to resolve Urls. Therefore, what's being seen is the resolution of `~/folder/file.txt` => `/folder/file.txt` by calling the `Href(..)` method.

As @Eilon linked, we should restrict this behavior: https://github.com/aspnet/Razor/issues/427.
