### ISSUE TITLE
Duplicate bound attributes should flow through as unbound attributes.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#418]
If you have a `TagHelper` with duplicate (same name) attributes only the first attribute gets added to `TagHelperContext.AllAttributes`. Ex:

```HTML
<myTagHelper abc="..." ABC="..." />
```

Today the second one `ABC` is ignored completely. Instead it should flow through to the output as if it were unbound.

**Comment by dougbu** [comment]
Same thing happens even when the attribute names have identical case e.g.
``` html
 <myTagHelper name="value1" name="value2" />
```

Only the first name / value pair (containing `"value1"`) will be in `AllAttributes`.

**Comment by NTaylorMullen** [comment]
0bb9457fd97c81c2e1a285dd9825b618f2755272
