### ISSUE TITLE
Unable to set a breakpoint on a tag helper

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#425]
While it is easy to set a breakpoint on an HTML helper, it is not possible to set one on a tag helper. Experience here should be similar -- break on the start tag in the `.cshtml` file.

Bonus points if we do the [`[DebuggerStepThrough]`](https://msdn.microsoft.com/en-us/library/system.diagnostics.debuggerstepthroughattribute%28v=vs.110%29.aspx) thing (or some similar approach) such that stepping in when at the breakpoint would take developer to the `Process()` or `ProcessAsync()` method of the first associated tag helper.

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by Eilon** [comment]
While this sounds nice, there doesn't appear to be demand for this, so closing.
