### ISSUE TITLE
Support bound and minimized boolean (or bool?) TagHelper attributes.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#431]
Today `TagHelper`s do not support bound minimized attributes because typically it doesn't make sense to have a bound attribute that will have 0 value. This isn't the case for `boolean` attributes though; we could special case `boolean` and even `bool?` values to allow situations such as:

``` C#
public class InputTagHelper : TagHelper
{
    public bool Checked { get; set; }

    public bool? Extra { get; set; }

    public override void Process(...)
    {
        // <input checked />                 Checked = true, Extra = null
        // <input checked="1 + 1 == 2" />    Checked = true, Extra = null
        // <input />                         Checked = false, Extra= null
        // <input extra />                   Checked = false, Extra = true
        // <input extra="1 + 3 == 2" />      Checked = false, Extra = false
        // <input extra checked />           Checked = true, Extra = true
    }
}
```

**Comment by NTaylorMullen** [comment]
Updated issue to showcase `bool?`

**Comment by dougbu** [comment]
Note this works today: The `TagHelper` could _not_ bind the bool attribute. Instead check whether it appears in `TagHelperOutput.Attributes`. Check `TagHelperAttribute.Minimized` to differentiate the minimized case from `checked="checked"` (for some reason).

**Comment by dougbu** [comment]
Related to #1589 as well. That probably is _not_ more advanced.

**Comment by ajaybhargavb** [comment]
Assigning this to myself as I am already working on this.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/commit/bd8e9ecc318946e70e33e406a43e31b3ea307d9c
