### ISSUE TITLE
Need to evaluate whether any C# 6 features will require changes to the Razor parser

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#44]
Please don't close this bug until the C#6 features are finalized (which won't be any time soon). We can use this bug to track potential changes we might need to make to Razor. E.g. imagine a new C# 6 feature has some additional `@` signs in it somewhere - we'll likely have to adapt to that.

**Comment by Eilon** [comment]
Also need to support exception filters:

Today with this code:

```c#
try
{
    throw new InvalidOperationException();
}
    catch (Exception e) if (e.Message.Contains("Operation is not valid"))
{
}
```

You get this error
```
CompilationFailedException: Compilation for 'c:\users\mattgal\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\Views\Home\Index.cshtml' failed:
Expected a "{" but found a "if". Block statements must be enclosed in "{" and "}". You cannot use single-statement control-flow statements in CSHTML pages. For example, the following is not allowed:

@if(isLoggedIn)
<p>Hello, @user</p>

Instead, wrap the contents of the block in "{}":

@if(isLoggedIn) {
<p>Hello, @user</p>
} 
```

From TFS bug 1099131.

**Comment by NTaylorMullen** [comment]
I investigated and it looks like the only pieces that aren't working are:

1. Exception Filters
1. Null-Conditional for expressions (works fine in statement blocks)

/cc @DamianEdwards Do you feel strongly one way or the other about exception filters making it?

**Comment by Eilon** [comment]
Just making sure these are tested:

***Using Static Members***
* Tricky because it could change how we parse `@using ...` (or maybe not)
```c#
using static System.Console;
```

***Expression-bodied members***
* Tricky because there's an extra `>` where we might not expect it (or maybe not)
```c#
public double Dist => Sqrt(X * X + Y * Y);  
```

***String interpolation***
* Tricky because all kinds of weird stuff can happen inside a string
```c#
$"{p.Name} is {p.Age} years old."  

var @class = "History";
var happiness = 6;
$"I like taking {@class} class? {(happiness > 5).ToString()}."  
```

**Comment by NTaylorMullen** [comment]
## Status

***Null Propagation***
Breaks by using them in implicit expressions such as `@Foo?.Bar`, `@Foo?()`, `@Foo?[0]`.

***Using Static Members***
Breaks in the scenario @Eilon mentioned: `@using static System.Console`

***String Interpolation***
Breaks in the following scenario.
```
@{
    $"abc{"123\""}.def";
}
```
Note the `\"`, it causes the chaos and results in the `}` being treated as the end of the `@{` block. 

***Exception Filters***
Breaks by using them :trollface: 

## Conclusion

I'm addressing each of these issues (in order mentioned) and associating their fixes with this issue. If needed I can break them into separate issues.

**Comment by dougbu** [comment]
What about the following features within a c# block?
- new dictionary indexer initialization syntax
- `nameof` operator (probably works, just confirming)
- `await` in `catch` and `finally` blocks (probably work and very minor since `try` is unusual in Razor source)

**Comment by NTaylorMullen** [comment]
@dougbu Yup, all of those work :smile:

**Comment by NTaylorMullen** [comment]
Investigated string interpolation and the fix for it is relatively complex. Talked to @DamianEdwards about prioritization and it's not a must-have for beta5. Will file two separate issues for exception filters and string interpolation so I can close this issue out in regards to null conditional operators and static usings once I've completed them.

**Comment by NTaylorMullen** [comment]
58c0a36200727b449996242ec9976f8f9fd1e612
1879ac642754b5f84e6055580e6fc60e13fa2100
