### ISSUE TITLE
Proposal: Razor Markup Minification

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Razor#444]
**Problem:** Razor directives require line feeds in markup that don't allow for simple Gulp HTML minification of views.

**Suggestion:** Add line termination character option (semicolon?) for Razor directives that will allow the Razor parser to work with minified directives.

For HTML minification of Razor views with Gulp, one can setup a folder of debug views (unminified markup) and use a Gulp `watch` to minify the markup files into the `Views` folder with one of the Gulp plugins, such as `gulp-minify-html`; thereafter, the Razor parser can go to work on the minified views. This works as long as no Razor directives are present.

Razor directives must be on separate lines at the top of `.cshtml` views. Of course, Gulp plugins do not take this into account. Gulp will minify any Razor directives along with the rest of the markup (i.e., remove the line feed character from each directive), thus breaking the Razor parser.

There is an ugly workaround: You can use a plugin like `gulp-inject-string` to inject your directives into the tops of the minified markup files after minification ... :-1:

```
var gulp = require('gulp'),
    minifyHTML = require('gulp-minify-html'),
    inject = require('gulp-inject-string');
gulp.task('processContactView', function () {
    gulp.src('Views_debug/Contact/*.cshtml')
        .pipe(minifyHTML({ quotes: true }))
        .pipe(inject.prepend('@model wpuc.Models.Visitor\n@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"\n'))
        .pipe(gulp.dest('Views/Contact'));
});
```

I'd like to propose that an optional line termination character be used with the Razor directives parser. If it were developed as an additional option to the line feed, it would not result in a breaking change. The semicolon is a reasonable choice. Such an upgrade would allow the Razor parser to work with minified Razor directives, thus allow you to use a task runner for HTML minification without issue.

Related Issues:
[Building Razor views in release mode should minify HTML](https://github.com/aspnet/Razor/issues/423)
[gulpfile.js in File-New Project template needs to be improved](https://github.com/aspnet/Home/issues/628)
[Discussion: Directives inside CodeBlocks](https://github.com/aspnet/Razor/issues/61#issuecomment-116785326)
[what about bundling and minification?](https://github.com/aspnet/dnx/issues/238)
[What about bundling and minification?](https://github.com/aspnet/Home/issues/45)
[What about Bundling and Minification](https://github.com/aspnet/Home/issues/134)
[Bundling and Minification workflow](https://github.com/aspnet/Home/issues/156)

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by danroth27** [comment]
This is really just one small piece of the problem. We think to minimize razor files properly you really need to do this by rewriting the code chunk tree. Moving to backlog.

**Comment by GuardRex** [comment]
No worries. I was hoping it would be as simple as this: https://github.com/GuardRex/Razor/commit/e2b24272bb9e9bc3018294cc2f28371c1bed5551 ... but it doesn't surprise me that it's not nearly that simple.

I have a more complete workaround with Gulp in case anyone stumbles over this. There is also `gulp-remove-code` that will strip out specific comments (and markup sections) from markup.

So if we start with something like this as a debug (unminified) view in a `Views_debug/Contact` folder ...
```html
<!--removeIf(razor)-->
@model wpuc.Models.Visitor
@tagHelperPrefix "th:"
<!--endRemoveIf(razor)-->
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Contact";
    ViewBag.Description = "Please feel free to contact us.";
}<div id="wrapper">
    ... unminified markup of the view here ...
</div>
```
... use Gulp like this:
```c#
var gulp = require('gulp'),
    inject = require('gulp-inject-string'),
    minifyHTML = require('gulp-minify-html'),
    removeCode = require('gulp-remove-code');

gulp.task('processContactViews', function () {
    gulp.src('Views_debug/Contact/*.cshtml')
        .pipe(removeCode({ razor: true, commentStart: '<!--', commentEnd: '-->' }))
        .pipe(minifyHTML({ quotes: true }))
        .pipe(inject.prepend('@model wpuc.Models.Visitor\n@tagHelperPrefix "th:"\n'))
        .pipe(gulp.dest('Views/Contact'));
});
```
... and end up with this in a `Views/Contact` folder ...
```html
@model wpuc.Models.Visitor
@tagHelperPrefix "th:"
@{ Layout = "/Views/Shared/_Layout.cshtml"; ViewBag.Title = "Contact"; ViewBag.Description = "Please feel free to contact us."; }<div id="wrapper">... unminified markup of the view here ...</div>
```
Ugly, but it works. Anyone with a better idea, I'm all :ear:'s.

**Comment by dougbu** [comment]
Knowing the in-box HTML and tag helpers generate XHTML for the most part, I'd like to reach a point where it's relatively simple to minify or uglify the generated HTML much later, just before the content is returned to a client. Shouldn't need to clean up the input `.cshtml` files if we get to that point.

**Comment by GuardRex** [comment]
@dougbu May I just add that regarding ...
> just before the content is returned to a client

I like the idea of having to do less work, and I also like the idea of not having to have a `Views_debug` folder and files. I just hope performance doesn't suffer.

Because I'm using Gulp (with a `watch` task) earlier than the Razor parser even sees the markup, I'm enjoying great performance.

What sucks is jumping through hoops because Razor directives can't exist in minified markup. You may decide to feature the framework with some kind of on-the-fly markup minification, but some (perhaps for performance reasons) may still want to pre-Razor-minify markup. We just need the Razor parser to look for a semi-colon **OR** a line feed when it's parsing the directives.

**Comment by GuardRex** [comment]
@DamianEdwards provided a full explanation of @danroth27's comment
> rewriting the code chunk tree

on today's [Community Standup (9/8)](https://youtu.be/tQC7P6n3pqk?t=1700).

**Comment by GuardRex** [comment]
@DamianEdwards @danroth27 @dougbu @NTaylorMullen 

This is hackish ... but without getting too deep into the weeds with the `ChunkVisitor` and just trying to do something simple ...

Add a property to the `ChunkTreeBuilder` to keep track of when you've only seen an open bracket as you process chunks ...
```
public static bool HasOnlySeenOpenBracket;
```
Do something like this with the `MarkupChunkGenerator` ...
```
namespace Microsoft.AspNet.Razor.Chunks.Generators
{
    public class MarkupChunkGenerator : SpanChunkGenerator
    {
        private bool _outsideOfElement;

        public override void GenerateChunk(Span target, ChunkGeneratorContext context)
        {
            if (target.Content.Contains("<") && !target.Content.Contains(">"))
            {
                ChunkTreeBuilder.HasOnlySeenOpenBracket = true;
                _outsideOfElement = false;
            }
            else if ((target.Content.Contains("<") && target.Content.Contains(">")) || target.Content.Contains(">") || !ChunkTreeBuilder.HasOnlySeenOpenBracket)
            {
                _outsideOfElement = true;
                ChunkTreeBuilder.HasOnlySeenOpenBracket = false;
            }
            else
            {
                _outsideOfElement = false;
            }
            string content;
            if (_outsideOfElement)
            {
                content = target.Content.Replace("\r\n", string.Empty).Trim(' ');
            }
            else
            {
                content = target.Content.Replace("\r\n", string.Empty);
            }
            if (!content.Equals(string.Empty))
            {
                context.ChunkTreeBuilder.AddLiteralChunk(content, target);
            }
        }
    }
}
```
... seems to work ok, but I admit that in the short time I hacked this up that I may have missed an edge case (or a few).

This approach seemed like a good way to go about it because the `MarkupChunkGenerator` seems to get a crack at markup content sans any c# code, directives, etc.

Is there a more elegant way to do it? 

If this is an ok approach, then one would just want to add an MVC option to either run this or just run the normal 
```
 context.ChunkTreeBuilder.AddLiteralChunk(target.Content, target);
```
when the option for markup minification is turned off by the developer.

I guess my take home point is that if this really is just this simple, can we please have this before the middle of next year? If I can hack this up in an hour, then I bet you could properly solve it in a production-quality way in the same amount of time.

**Comment by Antaris** [comment]
I did something similar in my FuManchu project, which is a .NET port of Handlebars based on Razor's parser framework. Handlebars supports the notion of collapsing the whitespace around tags, which I handled by marking a Span as collapsible and running the complete document tree through a custom parser visitor to remove the Spans. 

Wonder if something similar to this would be a step in the right direction? 

https://github.com/Antaris/FuManchu/blob/master/src/FuManchu/Parser/WhiteSpaceCollapsingParserVisitor.cs

**Comment by GuardRex** [comment]
@Antaris Yes, which is much more production quality compared to what I did. There is also a `ChunkVisitor`, which might similarly be approached in a more production-quality way. I like what you did.

I just needed something quick and dirty to do the job, and chunk inspection/modification was fast to hack up after @DamianEdwards comments yesterday.

I just hope that this could come off the backlog. I love what's been done with Razor. I just need one more thing: I need professionally-produced markup that loads lightening fast, and that means minified markup.

**Comment by GuardRex** [comment]
@danroth27 @DamianEdwards @pranavkm @NTaylorMullen Markup minification is on the backlog and probably won't get design until sometime next year (if at all). I've replaced `GenerateChunk` in the `MarkupChunkGenerator` with my own version that does what I need; however, it seems that I need to include the entire `Microsoft.AspNet.Razor` codebase in my projects to replace that method. 

`MarkupChunkGenerator` derives from `SpanChunkGenerator`, so it doesn't seem like I can simply override the method I need to replace. If I'm wrong about that, could you give me a tip on what I can do to only override `GenerateChunk` of `MarkupChunkGenerator` in my code to avoid having to keep the entire `Microsoft.AspNet.Razor` around in my projects?

**Comment by NTaylorMullen** [comment]
Instead of replacing the GenerateChunk for `MarkupChunkGenerator` you can replace the visitor that's responsible for rendering it [here](https://github.com/aspnet/Razor/blob/deaf2dc828b549f425a54d484d94afc9f8770635/src/Microsoft.AspNet.Razor/CodeGenerators/CSharpCodeGenerator.cs#L91) (you can start the process of overriding this method by replacing the `IMvcRazorHost`).

You can then override [this](https://github.com/aspnet/Razor/blob/deaf2dc828b549f425a54d484d94afc9f8770635/src/Microsoft.AspNet.Razor/CodeGenerators/Visitors/CSharpCodeVisitor.cs#L119) to change what `LiteralChunk`s do.

**Comment by GuardRex** [comment]
@NTaylorMullen I finally got back to this. As a first step (replacing `IMvcRazorHost`), is it supposed to go something like this ...
```c#
services.AddTransient<IMvcRazorHost, ICustomIMvcRazorHost>();
```
```c#
public class ICustomIMvcRazorHost : IMvcRazorHost
{
    public string DefaultNamespace { get; }

    public string MainClassNamePrefix { get; }

    GeneratorResults IMvcRazorHost.GenerateCode(string rootRelativePath, Stream inputStream)
    {
        var className = MainClassNamePrefix + ParserHelpers.SanitizeClassName(rootRelativePath);
        var host = new RazorEngineHost(new CSharpRazorCodeLanguage());
        //host.NamespaceImports.Add("System");
        //host.NamespaceImports.Add("System.Linq");
        //host.NamespaceImports.Add("System.Collections.Generic");
        //host.NamespaceImports.Add("Microsoft.AspNet.Mvc");
        //host.NamespaceImports.Add("Microsoft.AspNet.Mvc.Rendering");
        host.DefaultBaseClass = typeof(RazorPage).FullName;
        //host.DefaultNamespace = "<my_namespace>";
        var engine = new RazorTemplateEngine(host);
        return engine.GenerateCode(inputStream, className, DefaultNamespace, rootRelativePath);
    }
}
```
The commented lines there don't seem to matter; defaults seem to kick-in. However, this looks like it almost works and produces this ...

![capture](https://cloud.githubusercontent.com/assets/1622880/10628267/f7b7da52-7788-11e5-988b-eb17257d9a1b.PNG)

**Comment by GuardRex** [comment]
With a combination of great development by @Anderman and pathetic-excuse-for-code by your's truly, I have a tide-me-over until the team gets to this on the backlog.

See @Anderman cool `IMvcRazorHost` replacement at: https://github.com/Anderman/RazorMinify
See my hacked minifier adjustment at: https://github.com/Bartmax/HtmlMinifier/issues/1#issuecomment-160333171

**Comment by GuardRex** [comment]
@NTaylorMullen In the recent changes to `IMvcRazorHost`, the chunk visitor changed. @Anderman allowed me to plug in with the `LiteralChunk` visitor.
```
protected override void Visit(LiteralChunk chunk)
{
    chunk.Text = MinifyChunk(chunk.Text);
    ...
}
```
... Which visitor is the corollary in the new world order? I just want to get a shot at `.Text` to do my bit.

**Comment by NTaylorMullen** [comment]
@GuardRex We've transitioned adjaced `LiteralChunk`s to be grouped in a `ParentLiteralChunk`.

**Comment by GuardRex** [comment]
@NTaylorMullen Thanks ... I tap in there.

**Comment by GuardRex** [comment]
@NTaylorMullen @SteveSandersonMS Got it!

```c#
protected override void Visit(ParentLiteralChunk chunk)
{
    if (Context.Host.DesignTimeMode)
    {
        // Skip generating the chunk if we're in design time or if the chunk is empty.
        return;
    }

    var text = chunk.GetText();

    if (Context.Host.EnableInstrumentation)
    {
        var start = chunk.Start.AbsoluteIndex;
        Writer.WriteStartInstrumentationContext(Context, start, text.Length, isLiteral: true);
    }

    if (Context.ExpressionRenderingMode == ExpressionRenderingMode.WriteToOutput)
    {
        RenderPreWriteStart();
    }

    Writer.WriteStringLiteral(MinifyChunk(text));

    if (Context.ExpressionRenderingMode == ExpressionRenderingMode.WriteToOutput)
    {
        Writer.WriteEndMethodInvocation();
    }

    if (Context.Host.EnableInstrumentation)
    {
        Writer.WriteEndInstrumentationContext(Context);
    }
}
```

**Comment by GuardRex** [comment]
Updated (12/8) for RC2. NOT your 100% perfect minfier ... more like the 90% "it works ... sort of" version. https://gist.github.com/GuardRex/d3c08c8c337f646b8b60

**Comment by GuardRex** [comment]
@Anderman [Side Note on getting messages when mentioned in gists: Me neither on getting messages. You replied over there, and I only just saw that when I went there to update the gist. I'm going to file an issue with Github on that.]

Updated (12/9): I added the correct `LiteralChunk` chunk visitor in addition to the `ParentLiteralChunk` visitor above. I also made some mods to the Regex expression. It's working better than ever. Again, not perfect ... but a decent workaround for now. The gist has been updated to reflect the changes.

https://gist.github.com/GuardRex/d3c08c8c337f646b8b60

**Comment by GuardRex** [comment]
@Anderman I filed an issue with them on the gist messaging. I'll let you know what they say.

**Comment by Anderman** [comment]
Ok, maybe I will test your solution today. The Gists is all I need?

**Comment by GuardRex** [comment]
@Anderman Yes ... it's all there. Plug and play. It seems to be working ok as a singleton, but maybe @NTaylorMullen will jump in and correct me if it should be done as a transient replacement.

**Comment by GuardRex** [comment]
@Anderman Oh ... and it still doesn't handle comments. I guess just because I don't have any in my markup files (and maybe a touch of laziness on my part combined with other things I'm working on here). :smile:

**Comment by GuardRex** [comment]
@Anderman Cool ... Here's Github's response ...

> Notifications aren't currently sent out for events that occur within GitHub Gists, but I agree that would be a useful feature. I'll go ahead and add your +1 to our internal feature request list for Gist notifications.

**Comment by Anderman** [comment]
@GuardRex  Cool!

**Comment by GuardRex** [comment]
@Anderman Yeah, it seems strange that they didn't put that into place a long time ago. Oh, well.

I think someone asked Stephen Hawking about why Newton didn't immediately make some additional, straight-forward connections based on his earlier work ... Hawking's response ... "You can't think of everything!" :smile:

**Comment by Antaris** [comment]
@GuardRex Does this consider whitespace significant HTML elements, like `<pre>` and `<textarea>`?

**Comment by GuardRex** [comment]
@Antaris Great question. It will remove the tabs `\t`, the carriage returns `\r`, and linefeeds `\n` ... and of course, that kills `\r\n` newlines ... from text BETWEEN the element tags of your markup ... including `<pre>` and `<textarea>` tags, whether they are open tags, close tags, or void element tags. On the whitespace issue, it will only `.Trim()` the inter-tag sequence of characters, so I only expect it to do something like this ...
```html
<textarea>   My text with\t a tab and \ra carriage     return and a <br> tag return  </textarea>
```
should become
```html
<textarea>My text with a tab and a carriage      return and a <br>tag return</textarea>
```
... well ... that's what I'm hoping for anyway.

Note that the space in front of the `<br>` will occur because I only account the `<b` as "big" and should probably make it look for the full `<b>` when adding a space back. Hey! I never said it was perfect! :smile:

Anyway ... it will only `.Trim()` the text that it saves for minification between the tags. In the example above, I put a bunch of spaces in the middle there, and I don't expect it to kill those. It's setup to sort of help you when you've already knocked out obvious spaces. I.e., I wouldn't personally have had those spaces between "carriage" and "return" in my original markup at the outset, so I didn't bother to engineer this to be smart enough to deal with a case like that. I just wanted the whitespace around the contents next to tags to get dumped ... along with tabs, carriage returns, and line feeds.

There's a **TON** of improvement that could be done with this, but I just wanted something to tide me over. I didn't mean to produce something for production, per se. However, I am using this in production.

The thing about doing this this way is that ... well ... it sucks! The Razor engine is amazing; but to do minification, it's about element context. The Razor engine is breaking the markup into chunks that work well for Razor ... not for minification. The question of whether or not an inline element, like a hyperlink, should have a space outside of it will depend on what's actually outside of it. If it's text, yes, if it's like a `<li>` or something, no.

If what's outside of the element that we need to check is in a *different Razor chunk*, this becomes a problem. I think what would work best is if we could get a crack at the final, finished, done version of the markup out of the Razor engine ... like when it goes into its cache. We could pull the full markup document when Razor is finished, run it with a different logic (not Razor chunks ... some other chunking or scanning logic) and shoot it back in when we're done.

Anywho ... the amazing engineers at Microsoft like @NTaylorMullen and @DamianEdwards will do a real Class A job on it when the time comes. For now, if anyone tries it and has corrections, suggestions ... or death threats ... let me know. Thanks again to @Anderman for his help with the `IMvcRazorHost` replacement. His help on this vastly sped up the "hack" minifier I did! :beers:

**Comment by RehanSaeed** [comment]
I also took a stab at this using a Gulp task. more info here https://github.com/aspnet/Mvc/issues/3409.

**Comment by GuardRex** [comment]
I did, too. One of the things that really hurts that approach is that Razor
directives must be on their own lines. Also, you end up having to keep/have
two sets of views. Ultimately, I hated the approach and dropped it ... but
it was worth a shot.

**Comment by RehanSaeed** [comment]
Yes but think of the potential of having a .min.cshtml file generated by Gulp.

Gulp is the main source of all scripts and styles. So the above method could inject script and style tags into the cshtml at compile time!!! Now, as soon as you add a new package to your Gulp pipeline, it's automagically added to the cshtml.

**Comment by GuardRex** [comment]
It's great that u put this out. I'm a speed nut ... love hi perf apps. I'm
looking forward to trying it out this evening.

**Comment by RehanSaeed** [comment]
I'm still tinkering with the script and style tag injection and I have not included that in the project template yet.

I felt I was going down a rabbit hole and wanted to feel out the community first before I spent weeks perfecting the above approach.

I had a bunch of questions. Is this something that is a good idea? Will it get backing? Is there something better that someone is making?

**Comment by GuardRex** [comment]
There is nothing better for gulp. What I did with gulp wasn't a proper
package ... It was a cobbled together mess. It worked but only barely so.

The thing I did with @Anderman and with help and advice from @NTaylorMullen
is the only thing I'm aware of for getting minification at compile time.
Check my gist if you haven't seen it.

For what u did let me know how to configure if there are any special steps.
I was going to check it out tonight.

**Comment by RehanSaeed** [comment]
@GuardRex Here are some Gulp tasks I'm playing around with. They inject `script` and `link` tags into the cshtml before running the `gulp-minify-cshtml` task and spitting out .min.cshtml files.

The **really** cool thing about this approach is that when you want to add a new script, the bower.json and the sources object (shown below) in gulpfile.js become the **only** files you need to edit. Part of the trouble with the web in my experience is that you have to edit so many files in so many different places to add a single script or style. This decouples that.

```
var sources = {
    // An array containing objects required to build a single CSS file.
    css: [
        {
            // name - The name of the final CSS file to build.
            name: "font-awesome.css",
            cdn: "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css",
            // paths - An array of paths to CSS or SASS files which will be compiled to CSS, concatenated and minified
            // to create a file with the above file name.
            paths: [
                paths.bower + "font-awesome/scss/font-awesome.scss"
            ]
        },
        {
            name: "site.css",
            paths: [
                paths.styles + "site.scss"
            ]
        }
    ],
    // An array containing objects required to build a single JavaScript file.
    js: [
        {
            // name - The name of the final JavaScript file to build.
            name: "bootstrap.js",
            // The link to the file on a CDN.
            cdn: "//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js",
            // paths - A single or array of paths to JavaScript or TypeScript files which will be concatenated and
            // minified to create a file with the above file name.
            paths: [
                // Feel free to remove any parts of Bootstrap you don't use.
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/transition.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/alert.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/button.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/carousel.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/collapse.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/dropdown.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/modal.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/tooltip.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/popover.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/tab.js",
                paths.bower + "bootstrap-sass/assets/javascripts/bootstrap/affix.js"
            ]
        },
        {
            name: "jquery.js",
            cdn: "//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js",
            paths: paths.bower + "jquery/dist/jquery.js"
        },
        {
            name: "jquery-validate.js",
            cdn: "//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js",
            paths: paths.bower + "jquery-validation/dist/jquery.validate.js"
        },
        {
            name: "jquery-validate-unobtrusive.js",
            cdn: "//ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js",
            paths: paths.bower + "jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"
        },
        {
            name: "modernizr.js",
            cdn: "//ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.8.3.js",
            paths: paths.bower + "modernizr/modernizr.js"
        },
        {
            name: "site.js",
            paths: [
                paths.scripts + "fallback/styles.js",
                paths.scripts + "fallback/scripts.js",
                paths.scripts + "site.js"
            ]
        }
    ]
};

paths = {
    views: "Views/",
    cssLink: "~/css/",
    jsScript: "~/js/"
};

/*
 * Deletes all files and folders within the Views directory.
 */
gulp.task("clean-html", function(cb) {
    return rimraf(paths.views + "**/*.min.cshtml", cb);
});

minifyCshtml = require("gulp-minify-cshtml"),

/*
 * Builds the C# HTML files (.cshtml) for the site.
 */
gulp.task("build-html", ["clean-html"], function () {
    return gulp
        .src(paths.views + "**/(!(*.cshtml)|*.min.cshtml)")
        .pipe(replace("@* CSS Placeholder *@", getCssLinks()))
        .pipe(replace("@* Head JavaScript Placeholder *@", getJsScripts("head")))
        .pipe(replace("@* Body JavaScript Placeholder *@", getJsScripts("body")))
        //.pipe(minifyCshtml())
        .dest(paths.views + "**/*.min.cshtml");
});

function getCssLinks() {
    return sources.css.map(function (source) {
        var cssLink;
        if (source.cdn !== undefined) {
            cssLink += "<environment names=\"" + environment.development + "\">";
        }

        cssLink += "<link asp-append-version=\"true\" rel=\"stylesheet\" href=\"" + paths.cssLink + source.name + "\" />";

        if (source.cdn !== undefined) {
            cssLink += "</environment>";
            cssLink += "<environment names=\"" + environment.staging + "," + environment.production + "\">";
            cssLink += "<link asp-append-version=\"true\" rel=\"stylesheet\" href=\"" +source.cdn + "\" />";
            cssLink += "</environment>";
        }

        return cssLink;
    }).join();
}

function getJsScripts(location) {
    return sources.js
        .filter(function (source) {
            return source.location === location;
        })
        .map(function (source) {
            var scripts;
            if (source.cdn !== undefined) {
                scripts += "<environment names=\"" + environment.development + "\">";
            }

            scripts += "<script asp-append-version=\"true\" src=\"" + paths.jsScript + source.name + "\"></script>";

            if (source.cdn !== undefined) {
                scripts += "</environment>";
                scripts += "<environment names=\"" + environment.staging + "," + environment.production + "\">";
                scripts += scripts += "<script asp-append-version=\"true\" src=\"" + source.cdn + "\"></script>";;
                scripts += "</environment>";
            }

            return scripts;
        }).join();
}
```

**Comment by GuardRex** [comment]
@RehanSaeed Interesting ... but this doesn't look Razor-friendly (e.g. it will probably break on Razor directives). It also has the issue of having minified files of the markup and unminified files of the markup in the project (after its run once, anyway). I didn't like that about what I did earlier with gulp before moving to the `IMvcRazorHost` replacement approach.

> Part of the trouble with the web in my experience is that you have to edit so many files in so many different places to add a single script or style

I haven't experienced that. I usually have one to three layout pages (often only one) and one home index page without a layout page (as the primary landing page, I highly optimize to load insanely fast), so I usually only have two places in apps where I usually need to keep track of scripts and stylesheets. Once I setup gulp for bundling and minification, it isn't much of a bother.

It looks like what you're doing here is not using layout pages at all ... I mean injecting the scripts and stylesheets into every view??? If so, no wonder you're been editing so many files.

**Comment by RehanSaeed** [comment]
I should have been more clear, the code above is just stuff that I've been playing with. The above would all be wrapped in another Gulp package which could be used something like this:

```
gulp.task("build-html", ["clean-html"], function () {
    return gulp
        .src(paths.views + "**/(!(*.cshtml)|*.min.cshtml)")
        .pipe(injectLinkTags("@* CSS Placeholder *@"))
        .pipe(injectScriptTags("@* JavaScript Placeholder *@"))
        .pipe(minifyCshtml())
        .dest(paths.views + "**/*.min.cshtml");
});
```

This would inject the following into the .min.cshtml files replacing `@* JavaScript Placeholder *@`:

```
<environment names="Development">
    <script asp-append-version="true" src="~/js/jquery.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</environment>
```

I'm not sure why you say this would break Razor directives. Yes you do have minified files in the project but adding .min.cshtml to your .gitignores would not be difficult, you could use Gulp to move these into a separate folder or with some tooling the files could be nested like .min.css and .min.js files are now. This is not anything different to what we are doing with CSS and JavaScript files already!

I'm not in any way suggesting using this in each view. What I meant was that currently adding a new script is a multi-step complicated process:

1. Add a Bower package.
2. Add the package to your Gulp pipeline to lint, minify and concatenate it.
3. Add the the link to the script to the _Layout.cshtml files with CDN links included.
4. Add a fallback if the CDN goes down. Using the `asp-fallback` tag helper is no good if one of your scripts depends on another e.g. jQuery CDN goes down and Bootstrap.js depends on it (More info [here](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/Source/MVC6/Boilerplate.Web.Mvc6.Sample/Scripts/fallback/scripts.js)).
5. If you are using Content-Security-Policy you need to add the CDN domain the HTTP header too.

As a project template author, I get a **lot** of newbie developers asking me questions. Explaining the five step process above to them is a non-trivial process.

**Comment by GuardRex** [comment]
Update: I've made my mediocre **Minifying MvcRazorHost** available via NuGet. Thanks again to @Anderman for the initial host replacment.

https://www.nuget.org/packages/GuardRex.MinifyingMvcRazorHost/1.0.0

@dougbu @NTaylorMullen Please I hope the :pray: server gods :pray: will get this off of the backlog as soon as feasible.
