### ISSUE TITLE
HashCodeCombiner should not be public

### ISSUE THREAD

**Issue by anurse** [aspnet/Razor#449]
The [HashCodeCombiner](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNet.Razor/Common/HashCodeCombiner.cs) class is a purely internal helper class. If it's shared, it should be shared via source code sharing (using a shared-source package or a reference in the project.json `compile` project).

It's extremely unrelated to the project and collides heavily with other types, causing weird things like this:

![image](https://cloud.githubusercontent.com/assets/7574/8661621/c2564f10-296d-11e5-8770-2dab712160a2.png)

Above I was pressing Ctrl-. to see if the project I was working in had HashCodeCombiner lying around and saw this :).

@NTaylorMullen and I chatted and suggested just making copies of the class with different namespaces. It's not pretty but it works. This isn't a huge deal, but it is weird that Razor would be leaking such an internal infrastructure class to the public.

**Comment by dougbu** [comment]
How is this an issue for our customers? `HashCodeCombiner` is hidden away in the `Microsoft.Internal.Web.Utils` namespace.

**Comment by anurse** [comment]
As I said, it's probably not a big issue. Unfortunately, Ctrl-. and package search means it isn't fully hidden as it can easily appear in those lists. You do have to know what you're looking for (at least partly, in the case of package search) but it still seems like we're "productizing" a hack used to work around compiler issues :)

**Comment by dougbu** [comment]
I'm missing something. Similar things could be said about every `public` class in one of our `.Internal` namespaces. Why is `HashCodeCombiner` different?

**Comment by anurse** [comment]
I'd argue `HashCodeCombiner` is different from other classes in `Internal`. It is not a component that anyone outside the assembly could ever be expected to use, even in the most contrived scenario. Public things in Internal are cases where it's useful for testing for the things to be public or we can't be completely sure there isn't value in closing this away. This class literally just does some math with ints in order to combine multiple hash codes into an aggregate hash code for an object. It should be in a sources package maybe, but it's not something Razor should leak out as a public class. Other projects define this class in this namespace (not 100% sure if there's any in DNX, but I know [MVC <=5 and earlier versions of Razor](https://aspnetwebstack.codeplex.com/SourceControl/latest#src/Common/HashCodeCombiner.cs) did) and mark it internal so the now-public version can cause collisions if anyone who is using this class references Razor, as it will now collide. The class used to be `internal` and was made public to fix issues caused by tag helper tests and `InternalsVisibleTo` (per @NTaylorMullen) and I think it would be better to solve those issues a different way.

If there are other things in `.Internal` that fit this case, I would be concerned. At the very least, this should be moved to a Razor-specific `Internal` namespace instead of the much more general `Microsoft.Internal.Web.Utils` namespace it is in today. Regardless, this isn't worth arguing over if there are concerns about doing it. It was just something that seemed off to me and unlike other things. I leave it entirely in your hands :)

**Comment by Eilon** [comment]
Since you're doing https://github.com/aspnet/Common/pull/30, have fun with this too :smile:

**Comment by anurse** [comment]
Well, this usage would be an exception and probably can't use the Common version. The problem is that two different projects in Razor use it and because of InternalsVisibleTo, there is a collision. Razor may have to have an actual copy of the code.

**Comment by dougbu** [comment]
@anurse `src/Microsoft.AspNet.Razor` is the only `src` project that uses `HashCodeCombiner`. It makes internals visible to both test projects, which also use `HashCodeCombiner`. So it shouldn't matter where the source of the `internal` `HashCodeCombiner` actually is as long as neither `test/...` project has a build-time reference to this new Common project.

**Comment by Eilon** [comment]
We shouldn't have IVT between any two runtime projects. If we do, that is a mistake.

**Comment by dougbu** [comment]
@Eilon we don't in Razor at least. `src/Microsoft.AspNet.Razor` has an IVT for `test/Microsoft.AspNet.Razor.Test` and `test/Microsoft.AspNet.Razor.Runtime.Test`. Put another way, there's only one `HashCodeCombiner` class in Razor, `src/Microsoft.AspNet.Razor/Common/HashCodeCombiner.cs`, and it is not used in the `src/Microsoft.AspNet.Razor.Runtime` project (the only other product project in Razor).

@anurse exactly what is your concern with replacing that source file with the Common project? Making the contained class `internal` should have no impact. Overall, a few `using` updates should be the worst of it.

**Comment by anurse** [comment]
@NTaylorMullen indicated that there was a problem. I might be mistaken in interpreting this :). I'll give it a shot and if it works then great!

**Comment by NTaylorMullen** [comment]
e722f9048140b2c47978746cbb1eef8dc548a9da
