### ISSUE TITLE
Add ability to control TagHelper property binding.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#452]
This would be a post v1 feature that would fit in similar to how action filters fit in MVC. This would add the ability to have a middle-man control how values flow through to a `TagHelper`s properties.

With this feature we could expand this feature to add the ability to auto-resolve app-relative URLs for `TagHelper`s.

/cc @DamianEdwards

**Comment by rynowak** [comment]
No plans to do this without significant feedback
