### ISSUE TITLE
TagHelper in @ Section returns error

### ISSUE THREAD

**Issue by Karadox** [aspnet/Razor#456]
Created a TagHelper for *< reactjs >* within *@ section Scripts*
When run this returns the error: *error CS0246: The type or namespace name 'TagHelperContent' could not be found*

When placed outside the *@ sections Scripts* everything works fine.

**Comment by Eilon** [comment]
See https://github.com/aspnet/Mvc/issues/2857 for another repro.

**Comment by danroth27** [comment]
@NTaylorMullen Please take a look

**Comment by dougbu** [comment]
@Karadox are you using Beta 5 (Razor 4.0.0-beta5)? This sounds like a dupe of #412 and that was fixed in Beta 6.

**Comment by Karadox** [comment]
Thx for the comments, i am indeed using a earlier version: beta4.
Going to update everyting...
