### ISSUE TITLE
OutputElementHint is not recognized at design time.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#457]
When creating `TagHelperDesignTimeDescriptor`s we don't transition from `TypeInfo` => `DeclaringType` correctly resulting in the inability to resolve `OutputElementHint`s in the DTH.

**Comment by dougbu** [comment]
@NTaylorMullen could you provide an example of a scenario that doesn't work as expected?

Separately was this bug triaged before you filed it?

**Comment by NTaylorMullen** [comment]
@dougbu We improperly pass in the `Type` of a `TagHelper` to the `TagHelperDesignTimeDescriptorFactory`. https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNet.Razor.Runtime/TagHelpers/TagHelperDescriptorFactory.cs#L97 should be `.AsType`.

This was triaged in person with @danroth27

**Comment by dougbu** [comment]
I agree that line looks wrong. However what is the visible impact of the bug? Why are the `TagHelperDescriptorFactory` and general design-time tests passing?

**Comment by dougbu** [comment]
... Put another way, bug describes a coding error and not a symptom.

**Comment by NTaylorMullen** [comment]
@dougbu this unblocks tooling. The tests today are hitting the `TagHelperDesignTimeFactory` directly and not going through `TagHelperDescriptorFactory`.

**Comment by dougbu** [comment]
Thanks for the answers and for improving the title :ok_hand:

**Comment by NTaylorMullen** [comment]
3ab6f56284946d9d735f5b67a606e0a4b2ea6373
