### ISSUE TITLE
Different TagHelpers with the same element name, depending on scope

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/Razor#474]
Now we have `context.Items` (#238) and can compose hierarchies of tag helpers like:

    <parent>
        <child attr="value" />
    </parent>

It would be nice to be able to map an element name to different tag helpers, depending on a parent tag:

    <some-widget>
        <datasource attrs="for" some="widget" />
    </some>

    <other-widget>
        <datasource something="different" />
    </other-widget>

Probably possible in the context of #255: restrict by type name, not by element name.

**Comment by dougbu** [comment]
@AlekseyMartynov do you have a scenario in mind that would benefit from this type of extension beyond what's described in #255?

**Comment by NTaylorMullen** [comment]
@AlekseyMartynov @DamianEdwards, @madskristensen and I discussed an extension like this when talking about #255.  It's on our road map. At first I was thinking it'd be done as part of #255 but it honestly should be something separate; lets leave this issue open and use it to complete the feature.

Added feature and ready label, will wait for it to be picked up by triage to be assigned a milestone.

**Comment by AlekseyMartynov** [comment]
@dougbu it's relevant for any tag helper with rich configuration, when you want to use nested tags. Consider:

Case 1 (repeating branded prefix is untidy):

    <brandedTag>
        <brandedConfig ... />
    </brandedTag>

Case 2 (using simple names globally is conflict-prone):
    
    <brandedTag>
        <config ... />
    </brandedTag>

**Comment by AlekseyMartynov** [comment]
@NTaylorMullen sounds good!

**Comment by Eilon** [comment]
We decided to add another property to the `HtmlTargetElement` attribute: `string ParentTag { get; set; }`

This would restrict a child tag to being that tag helper iff its containing parent is a tag helper with the specified tag name.

**Comment by NTaylorMullen** [comment]
Hmmmm, so I'm working on this issue and it got me thinking about the required parent interaction. If we have:

```HTML
<tagHelperA>
  <p>
    <requiresParentA>
    </requiresParentA>
  </p>
</tagHelperA>
```

And `requiresParentA` says it has a required parent of `tagHelperA`. Does the nested `requiresParentA` tag fulfill its required parent aka have the `RequiresParentATagHelper` execute on it? 

I'm thinking as long as there's a parent (no matter how far up) that fulfills the parent tag then the `TagHelper` should apply. Thoughts?

**Comment by Eilon** [comment]
@NTaylorMullen That doesn't sound like it's the feature people want. I would think it has to be immediate parent only.

**Comment by NTaylorMullen** [comment]
@Eilon but isn't the value of restricting your parent to ensure that you have another `TagHelper` to talk to? If you want the restriction to apply to the immediate parent that sounds like more of a use-case for the `[RestrictChildren]` attribute.

**Comment by dougbu** [comment]
@NTaylorMullen I suggest `[RestrictChildren("child")]` on the parent and `[HtmlTargetElement(ParentTag = "parent")] on the child should have matching semantics -- both should control the immediate child or parent.

If we were talking _only_ about communication via `TagHelperContext.Items`, should change `[RestrctChildren(...)]` as well.

**Comment by Eilon** [comment]
Debatable. There is a reasonable scenario where the parent can have arbitrary tag helper children and so it can't restrict the children on its own. E.g. let's say the children must all satisfy a condition, such as "implement IColumnDescriptor" -- there's no way to describe this statically. But each child tag helper will want to restrict itself to appearing only as a child of `<webgrid>`.

**Comment by dougbu** [comment]
@Eilon were you responding to me or @NTaylorMullen?

**Comment by Eilon** [comment]
@dougbu oh you snuck in there! Yes it was to Nicholas. Will edit to clarify.

**Comment by NTaylorMullen** [comment]
@Eilon There's definitely cases where it'd be useful to restrict the immediate parent. I think it's more of a question of what would be more common/applicable (immediate parent vs. any parent).

We should probably discuss in person but I'm thinking restricting things like `<input>`, `<select>` or other similar constructs in a parent like `<form>` (no matter what they're surrounded with like `<p>`) is a more common scenario.

Of course there's always another option to enable `TagHelper` authors to be explicit on if its the immediate or any parent but i'm not convinced that a v1 version of this warrants that capability.

Lets talk tomorrow.

**Comment by IlyaKhD** [comment]
Hi guys! 
I'll also suggest considering the following scenario:

Imagine that we have two TagHelpers: `<aTag>` and `<bTag>`, and both of them have the allowed child tag `<title>`.
 
If this 'Title' is nested within `<aTag>`, it has the only attribute: *color*.
If this 'Title' is nested within `<bTag>`, it has one more attribute: *background-color* as well as *color*.
 
To implement it, I would require two things:
1. I can create two classes both targeting the `<title>` tag.
2. TagHelpers processing the pipeline can distinguish `<title>` nested within `<aTag>` from `<title>` nested within `<bTag>`.
 
At the moment, the first step can be easily done with the help of **TargetElementAttribute** but it is impossible to perform the second one.
 
To achieve this, we require the capability to restrict child (or parent) tags according to class names.
I've already encountered this problem and found this feature extremely useful.

_P.S. Of course, it is possible to use different tags like `<aTagTitle>` and `<bTagTitle>` but it's untidy and can become more complex with nesting growth._

**Comment by dougbu** [comment]
@IlyaKhD would your scenario work correctly with the following?
- `[RestrictChildren("title")]` in the `<aTag>` and `<bTag>` helpers
- `[HtmlTargetElement("title", ParentTag = "aTag")]` in one child tag helper
- `[HtmlTargetElement("title", ParentTag = "bTag")]` in the other child tag helper

**Comment by IlyaKhD** [comment]
@dougbu yes, this will work fine, if it checks for immediate parent/child.

**Comment by AlekseyMartynov** [comment]
If `ParentTag` restriction reacts to any parent (as opposite to immediate parent), then there might be problems with nesting.

For example, consider @IlyaKhD's example additionally with bTag contained within aTag. Innermost title now is both in aTag and bTag.

**Comment by Eilon** [comment]
@AlekseyMartynov yeah I don't think the parent restriction should work on "any parent in the hierarchy" - that's not what the word "parent" means :smile: I think it implies only the immediate parent.

**Comment by IlyaKhD** [comment]
I guess I found one more problem.

I have my  `<title>` that should be nested within my `<aTag>`. 

`<aTag> <title/> </aTag>`

I use the `TargetElementAttribute` to describe these two restrictions:

* `<aTag>` accepts  child tag***s*** named `title` only
* `<title>` accepts parent tag***s*** named `aTag` only

Seems to be ok, right?

But what if my NuGet is used with some 3rd party pack and this pack has also TagHelper targeting `title`? This new `<title>` is supposed to be used independently and has NO restrictions at all.

In this case both TagHelpers from different assemblies targeting `<title>` will be processed and their output will be messed.

It seems that the only way to protect my TagHelpers from such an 'invasion' is to gain an ability to describe child restriction based on TagHelpers Type (or something else making each TagHelper unique).

**Comment by DamianEdwards** [comment]
@IlyaKhD if you're really concerned about that you'd have to make the element names your Tag Helpers target less generic. Tag Helpers aren't like Web Forms or XAML controls whereby they're strongly typed and are registered as a component, etc. They're much more like Angular directives in that you "attach" to HTML elements.

I honestly don't think the scenario above is likely to occur often in reality. We can of course adjust the rules and feature in the future based on what actually eventuates.

**Comment by leus** [comment]
In reality, bootstrap-happy HTML designers will add indiscriminate `<span>` tags everywhere to match their immaculate pixel-perfect designs and that may be a problem if the decision to process a tag helper is based on parent-child relationship only; it seems arbitrary on the surface, design-wise.

**Comment by NTaylorMullen** [comment]
67739ea565fc1b49b051b8796b2a4581f2a80016

**Comment by IlyaKhD** [comment]
@DamianEdwards 

>     I honestly don't think the scenario above is likely to occur often in reality.
>     We can of course adjust the rules and feature in the future based on what 
>     actually eventuates.

We started using `ParentTag` restriction and encountered the following case:

    <webgrid-branded>
      <column>
        <extra-options />
      </column>
    </webgrid-branded>

There is no problem with restricting that `column` is nested within `webgrid-branded`, works fine. But `extra-options` parent could be restricted to too generic tag `column`.

This can become a problem for 3rd party `TagHelper` authors if there are multiple `column` usages for different parents.

**Comment by NTaylorMullen** [comment]
@IlyaKhD Why couldn't you just add the "column" `ParentTag` restriction on `extra-options`?

**Comment by IlyaKhD** [comment]
We could of course, but then `extra-options` would be allowed also in 'alien' `column` tags, not only in `webgrid-branded`'s

**Comment by NTaylorMullen** [comment]
Why is that an issue though? If someone else wants to use your columns and they work then yayy :smile:. 

Keep in mind `TagHelper`s are all about running code on HTML elements, unlike their webform counterparts which were more like invoking a method; therefore, these less strict situations are by-design.

**Comment by IlyaKhD** [comment]
Suppose we have `webgrid-branded` and `scheduler-branded`. Both have `column` but these columns are different, so we restrict one `column` is nested within `webgrid-branded` and the second one - within `scheduler-branded`.

But how do I restrict `extra-options` ? It's parent - `column` - is too generic.

**Comment by IlyaKhD** [comment]
TagHelpers are undoubtedly not WebForms.
But if such an opportunity exists - I mean parent\children restriction - shouldn't it work in all cases?

**Comment by NTaylorMullen** [comment]
You're correct, you cannot make that restriction if you choose to use the same `extra-options` name for both. If you wanted, you could however change the name to indicate what type of grid it's in, or even have the extra-options detect what type of grid it's in.

What you're asking for is essentially something like `AncestorTag` or `AncestorTagHelper` (if you wanted to restrict to only `TagHelper`s). If you'd like you could open up an additional issue for that added flexibility and we can discuss.

**Comment by AlekseyMartynov** [comment]
@IlyaKhD Let's try adding extra runtime checks inside the `Process` method to prevent execution in non-appropriate locations. And if we need more, then we'll open additional feature request.

**Comment by pranavkm** [comment]
I was working on signing off on this feature as part of the beta8 milestone and it took me a while to figure out what was and wasn't changed as part of this work item. tl; dr of this thread: the issue as originally described wasn't completed as is. Instead we expanded `RestrictChildren` and `ParentTag` to now be able to specify any html element.
