### ISSUE TITLE
Setting option tag selected problem

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Razor#478]
<img width="813" alt="qq20150810-1 2x" src="https://cloud.githubusercontent.com/assets/2216750/9157550/f3101a64-3f34-11e5-85f6-0f8a90f13adb.png">

It seems that a tag highlighted by taghelper cannot insert c# in it.

**Comment by Kagamine** [comment]
<img width="1018" alt="qq20150810-2 2x" src="https://cloud.githubusercontent.com/assets/2216750/9157649/c1860928-3f38-11e5-895f-8a5300d859f7.png">

**Comment by NTaylorMullen** [comment]
Correct, `TagHelper`s cannot have C# in their tag area. If you don't want it to function as a `TagHelper` you use the opt-out character `!`:

`<!option @(Context.Request.Query["Status"] == status ? "selected" : "">@status</option>`

A side note: Razor has an auto-attribute removal system which would enable you to accomplish the same thing.

```
@foreach (var status in Enum.GetNames(typeof(ProjectStatus)) {
    <!option selected="@(Context.Request.Query["Status"] == status)">@status</option>
}
```

Essentially what's happening is if Razor sees the boolean `true` as the attribute value it'll replace the `true` with the attribute name `selected` which is equivalent to juts having the minimized `selected` attribute like you had before. If it sees `false` it'll remove the attribute for you entirely.

Once https://github.com/aspnet/Razor/issues/247 is completed you'll be able to have this functionality work with `TagHelper`s.

**Comment by Kagamine** [comment]
Thank you :)

**Comment by Kagamine** [comment]
</!option> not </option>

**Comment by NTaylorMullen** [comment]
Hah, yes! Thanks :smile:
