### ISSUE TITLE
Attributes don't work in Tag Helper if newline precedes first attribute

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Razor#484]
Tag helper:
```csharp
public class HelloTagHelper : TagHelper
{
	public string First { get; set; }
	public string Second { get; set; }

	public override void Process(TagHelperContext context, TagHelperOutput output)
	{
		output.TagName = "span";
		output.SelfClosing = false;
		output.Attributes.Add("data-first", First);
		output.Attributes.Add("data-second", Second);
	}
}
```

cshtml:
```
<hello first="1111" second="2222" />
<hello
	first="1111"
	second="2222"
/>
<hello first="1111"
       second="2222"
/>
```

Result:
```
<span data-first="1111" data-second="2222"></span>
<span data-first="" data-second=""></span>
<span data-first="1111" data-second="2222"></span>
```

The middle `<hello />` tag has a newline before the first attribute, which seems to break it (all attributes come through as empty). The final `<hello />` only has a newline before the second attribute, which seems to work.

Tested on beta 6.

**Comment by dougbu** [comment]
Just did a quick repro with current Beta 7 bits. It looks as if Razor generates nothing at all for the attributes in the newline-before-attributes case. Likely something is causing the attributes to have a null generator or they're lost completely.
