### ISSUE TITLE
Remove unnecessary whitespace that is rendered for non markup content

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#485]
Extra new lines from razor comments has been removed in #428. But we still need to handle unnecessary whitespace in other places.

From @danroth27:
We've decided to be smart about removing whitespace for any non-HTML content that occupies the entire line. So in addition to @RehanSaeed's example https://github.com/aspnet/Razor/issues/428#issue-90321772, the following example:

```html
@{
}
<!DOCTYPE html>
```
Should render just the doctype without any leading whitespace (which would be invalid). Also:

    @foreach (var item in items)
    {
        <li>@item</li>
    }
Should not render a line with four spaces before the list item.

cc' @NTaylorMullen

**Comment by RehanSaeed** [comment]
@ajaybhargavb Please also consider this (https://github.com/aspnet/Razor/issues/423) related suggestion for minifying HTML at compile time.

**Comment by ajaybhargavb** [comment]
e2881b0eca0d219539543128ee5c90aa24ba97f3

**Comment by NickAb** [comment]
In ASP.NET Core project in my .cshtml when I use
```
Some text
@if (Model.BranchesSection.TotalCount == Model.BranchesSection.PreviousIssuedBranchesCount)
                    {
                        <text> same as before</text>
                    }.
```
I get following as a result:
```
Some text same as before .
```

There is a space before full stop symbol. How can I get rid of it? Is my only option to inline it like so:
```
Some text @if (Model.BranchesSection.TotalCount == Model.BranchesSection.PreviousIssuedBranchesCount) { <text> same as before</text> }.
```

**Comment by NTaylorMullen** [comment]
@NickAb I was able to reproduce your issue with:

```
Some text
@if (true)
{
    <text> same as before</text>
}.
```
And even
```
@if (true)
{
    @: same as before
}.
```

Would you mind opening a separate issue with what you have?

Also, as a work around this works (still ugly :cry: ):
```
Some text
@if (true)
{
    <text> same as before</text>}.
```

**Comment by NTaylorMullen** [comment]
Actually, nm @NickAb this issue should be reopened. The browser was being kind rendering a space, the HTML is actually a newline which should have been covered by this issue.

**Comment by ajaybhargavb** [comment]
b520c9c15ef61f6e84c83d4a297449c87f6a74fa
