### ISSUE TITLE
Add copy constructor for IReadonlyTagHelperAttribute => TagHelperAttribute

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#492]
Today in a `TagHelper`s `Process` method you're unable to copy values from `TagHelperContext.AllAttributes` => `TagHelperOutput` effectively. Aka this results in an error:

```C#
public override void Process(TagHelperContext context, TagHelperOutput output)
{
    output.Attributes.Insert(0, context.AllAttributes[0]);
}
```

Because `context.AllAttributes[0]` is an `IReadonlyTagHelperAttribute` and `output.Attributes.Insert` only takes `TagHelperAttribute`s (as expected). To make this work you need to re-create the `TagHelperAttribute` via`

```C#
var existingAttribute = context.AllAttributes[0];
var copiedAttribute = new TagHelperAttribute
{
    Name = existingAttribute.Name,
    Value = existingAttribute.Value,
    Minimized = existingAttribute.Minimized
};
```

It'd be nice to make this slightly easier by providing a semi-copy ctor for `TagHelperAttribute` so  it can take in an `IReadonlyTagHelperAttribute` and construct itself accordingly. Would let us do:

```C#
var existingAttribute = context.AllAttributes[0];
var copiedAttribute = new TagHelperAttribute(existingAttribute);
```

**Comment by dougbu** [comment]
Alternatively, could add an `Insert(int index, [NotNull] IReadOnlyTagHelperAttribute attribute)` or `Insert(int index, [NotNull] string name, object value)` method to `TagHelperAttributeList`. The second is a nice match for the existing `Add([NotNull] string name, object value)` method.

**Comment by NTaylorMullen** [comment]
Going to take the copy ctor approach.

**Comment by NTaylorMullen** [comment]
55760b4fcbb7285aa1b1d8f328378e8e72df6639
