### ISSUE TITLE
Nested Tag Helpers

### ISSUE THREAD

**Issue by vkichline** [aspnet/Razor#496]
Suggestion submitted by email from Prabhakar.Mishra@grapecity.com:

As we know, for a webcontrol, the properties and sub-properties which types are complex can be set by the nested tag in the control tag. Although we can customize the taghelper like this, it is a little complex to implement this. We think it would be great if the taghelper framework could help us to do some work so that  the developer of a TagHelper has to write less code.
For example, we define mydatagrid taghelper. It has two attributes: headerstyle and rowstyle, whose types are same: DataStyle.
Now in order to use it as the following way, we have to define four taghelpers: mydatagrid, datastyle, headerstyle and rowstyle. In fact headerstyle and rowstyle extends from datastyle. They are almost same except the taghelper name. We also need to write some code to build the relationship between mydatagrid and its nested taghelpers.

``` HTML
<mydatagrid id="grid1">
<headerstyle forecolor="red" />
<rowstyle forecolor="blue" />
</mydatagrid>
```

We wish we just have to define two taghelpers: mydatagrid and datastyle. Then we just do some settings in the property “headerstyle” and “rowstyle” of mydatagrid, the taghelper framework can help to process the rest. If it can be done, that would be great.

We see that you plan to add support for restricting which elements can show up under a TagHelper and vice versa. That would be perfect for nested taghelper.

**Comment by dougbu** [comment]
How do you use the four tag helpers today? I'm wondering about a single tag helper instead e.g.
``` c#
[TargetElement("my-data-grid")]
public class DataGridTagHelper : TagHelper
{
    public DataStyle HeaderStyle { get; set; }
    public DataStyle RowStyle { get; set; }

    // ...
}
```
and
``` html
<my-data-grid header-style="new DataStyle(...)" row-style="new DataStyle(...)">
</my-data-grid>
```

**Comment by NTaylorMullen** [comment]
The user wants to be able to specify the values via attribute OR element. Aka `HeaderStyle` would be settable via attribute: `<my-data-grid header-style="..."></my-data-grid>` OR `<my-data-grid><header-style>....</header-style></my-data-grid>``

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by DamianEdwards** [comment]
This is an interesting concept but is getting a little too close to XAML for my liking. Putting on the backlog for further consideration in the future. If anybody wants to take a stab at fleshing out the design a little more that would be welcome.

**Comment by IRooc** [comment]
What about something like a menu?
```HTML
<ul my-menu-helper-root="/" my-menu-helper-type="Namespace.ClassItem">
    <li class="@(item.Active ? "active":null)"><a href="@item.Url">@item.Title</a>
</ul>
```
this will print all ```<li>``` items for the root menu.

You can get the ChildContent in the taghelper with ```await context.GetChildContentAsync() ```
But is there any way to parse the contents as Razor items with a specific model (like ItemType of the asp:Repeater). Is there any way (other than string parsing) to do this with current tag helpers?

**Comment by DamianEdwards** [comment]
Not really, no. Tag Helpers can't generate new members for their content (like `item` above), however they can mutate state that's passed to them. Code generation is something we're looking to add to Tag Helpers in the next major release after RTM.

**Comment by IRooc** [comment]
So only existing partial views not "new" partials based on child content.

Thanks

**Comment by newsash** [comment]
What about tables?
```html
<table for="Items">
    <column for="Type"/>
    <column for="Name"/>
    <column for="Price"/>
    <column>
        <th>Actions</th>
        <td><a asp-action="Remove" asp-route-id-by="Id">Remove</a></td>
    </column>
</table>
```

**Comment by leus** [comment]
I'd love to be able to write tag helpers like the one in @newsash 's post, but I think it's different from what the original request is asking (it looks to me that the original request is just to get parameter values from inner elements instead of attributes.) I like this idea way more.

**Comment by michal-ciechan** [comment]
It would be nice to allow to process HtmlContent with any TagHelpers necessary.

E.g. In inside Process/Async

    public class CustomTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
               // Allow us to force TagHelper processing on content set here 
        }
    }
Allow us to force any `TagHelperContent` to be processed by TagHelpers in one of the following ways:

Add a boolean to `TagHelperContent.SetHtmlContent`

    output.Content.SetHtmlContent(@"<input asp-for=""SomeField"">", processTagHelpers: true);

Provide a method to tell Razor to go and process content with any relevant tag helpers:

    output.Content.ApplyTagHelpers();

Provide a generic method that lets us decide which TagHelper should be processed, potentially adding any additional attributes

    output.Content.ApplyTagHelper<InputTagHelper>(tag =>
    {
        tag.Order = 10;
        // Other Properties 
    });

It would be nice to allow to process HtmlContent with any TagHelpers necessary.

E.g. In inside Process/Async

    public class CustomTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
               // Allow us to force TagHelper processing on content set here 
        }
    }
Allow us to force any `TagHelperContent` to be processed by TagHelpers in one of the following ways:

Add a boolean to `TagHelperContent.SetHtmlContent`

    output.Content.SetHtmlContent(@"<input asp-for=""SomeField"">", processTagHelpers: true);

Provide a method to tell Razor to go and process content with any relevant tag helpers:

    output.Content.ApplyTagHelpers();

Provide a generic method that lets us decide which TagHelper should be processed, optionally adding any additional attributes not set in the content

    output.Content.ApplyTagHelper<InputTagHelper>()
    
    // Or with optional Tag pre-processing before beign applied
    output.Content.ApplyTagHelper<InputTagHelper>(tag =>
    {
        tag.Order = 10;
        // Other Properties 
    });

**Comment by rynowak** [comment]
No plans to do this right now

**Comment by RehanSaeed** [comment]
> No plans to do this right now

Does that mean never? No pressure, I just want to know what step to take next. Should I wait and see if this issue comes back alive or do the hard manual labour in the coal mine and write child tag helpers.

I built TagHelper's for Twitter Cards and Open Graph (Facebook) meta tags by hand using properties of [complex types](https://github.com/aspnet/Mvc/issues/3180). Last week I also released the [Schema.NET](https://rehansaeed.com/structured-data-using-schema-net/) project which is 1000 machine generated strongly typed POCO's for [schema.org](https://schema.org). These can be converted to JSON-LD and used in the <`head>` section for better SEO (See [Google Structured Data](https://developers.google.com/search/docs/guides/intro-structured-data)). I was waiting to see what happens with this issue before deciding how to write tag helpers for them.

This issue would help with all three sets of tag helpers I outlined above.

**Comment by rynowak** [comment]
@RehanSaeed - There are a few of things here, so I'll try to be specific.

It's very unlikely that we would **ever** allow you to 'process' chunks of HTML and and turn them into other tag helpers. This is not something we're investigating, and it would be a significant technical challenge to make this work in way that users would be happy with.

------------

One of the other ideas here is that you could opt-in to getting a DOM for the content inside your tag helper, that would make it easier to parse/rewrite. We're super stoked on this idea, but not actively working on it right now.

This whole theme of, "I want to make a tag helper that does something with its inner content" is something we want to make better, but it will happen a long time from now.

------------

Most of our immediate investments in Razor will be focused on improving our tooling in the short term, we have some catching up to do. We'll be ready to start talking about actual runtime features in maybe 6 months from now, and shipping them in 3.0. That's not a promise of any specific thing getting delivered, that's when we're ready to start prioritizing this work.

Everyone will hopefully get to see a list of our 2.1 planning items *soon* for some definition of soon. Right now we're still going through the 2.0 release process.

**Comment by RehanSaeed** [comment]
Sounds interesting, I'll sit tight and wait for some magic.
