### ISSUE TITLE
Razor code generator produces unnecessary writeliteral with whitespaces 

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#50]
Original Issue on Codeplex: https://aspnetwebstack.codeplex.com/workitem/1548

 Sample code:
```
 <div>@{var a = 1; <text>@a</text>}</div> It translates to: 
```

```C#
 public class Index_cshtml : System.Web.Mvc.WebViewPage { 
 ... 
 public override void Execute() { 
 var a = 1; 
 WriteLiteral(" "); 
 Write(a); 
 WriteLiteral("</div>"); 
 } 
 } 
```
 After code var a = 1; and before code Write(a);, Razor translator generates unnecessary writes of whitespace: WriteLiteral(" ");. 

 And result of this output:
 <div> 1</div> When replace cshtml code by replacing whitespace between ; and @ (this is CODE CONTEXT) by more than one space, for ex., 3 tabs:
```
 <div>@{var a = 1;<text>@a</text>}</div> 
```
It generates: 

```
 var a = 1; 
 WriteLiteral("\t\t\t"); 
 Write(a); 
 WriteLiteral("</div>"); 
```
 So, Razor translator generates unnecessary writes of whitespaces BEFORE @ from CODE CONTEXT.

**Comment by Eilon** [comment]
@ajaybhargavb another interesting Razor bug.
