### ISSUE TITLE
Consider adding non-async GetChildContent methods to TagHelperContext

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#501]
Getting to the child content in `TagHelper.Process` requires the user to deal with  `TagHelperContext.GetChildContentAsync()` and make blocking calls. Would be nicer to be able to do `TagHelperContext.GetChildContent()` instead.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by danroth27** [comment]
No plans to do this.
