### ISSUE TITLE
Tag Helpers not available within script tag

### ISSUE THREAD

**Issue by dgee2** [aspnet/Razor#502]
I'm trying to use a tag helper within a script tag (this is how knockoutjs does its templating) but this seems to be blocked from happening. This is the sort of thing that I'm wanting to do where bool is my own custom tag helper:
```
<script type="text/html" id="checkbox-template">
    <li>
        <bool ko-bind-checked="Checked" ko-bind-value="Value" ko-bind-label="Name" />
    </li>
</script>
```

**Comment by dgee2** [comment]
Just had a further think about this and I have a further question. Are the contents of a tag helper processed before or after the outer tag helper is processed or are they processed at all?

e.g. if I had a tag helper for divs (very hypothetical here) would the form tag helper be processed.
```
<div>
    <form />
</div>
``

**Comment by dougbu** [comment]
At present Razor does almost nothing with the body of a `<script>` tag. That's partially an optimization for the common `type="text/javascript"` case -- a syntax Razor can't parse. Agree it may make sense to handle at least `type="text/html"`. Just likely to be a lot of extra work...

**Comment by dgee2** [comment]
Yes it potentially could make using templates very difficult for us due to the amount that we are proposing to produce with tag helpers. Are there any work arounds at present? Also what would need to be involved to make the contents of custom tag helpers be processed by Razor (and thus any contained tag helpers)?

**Comment by dougbu** [comment]
>  what would need to be involved to make the contents of custom tag helpers be processed by Razor

Are you asking in general or specifically about within `<script>` elements? I ask because tag helpers work pretty much everywhere _but_ within `<script>` elements. (Fixed a few bugs related to templates and some helpers recently. But the basics work in released bits.)

**Comment by dgee2** [comment]
Well the fact that it didn't work in script tags made me wonder if it worked in any at all (but they do). A workaround for the script tag would be useful though.

**Comment by danroth27** [comment]
@DamianEdwards Thoughts on this?

**Comment by Eilon** [comment]
We decided to special case `<script>` tags with `type="text/html"` and process everything inside it as HTML, and thus process tag helpers.

**Comment by dgee2** [comment]
Thankyou. Will this be configurable (either on the fly or via startup)? Given that KO is using script tags in this way, I guess there's probably others as well that may or may not be using the same type.

**Comment by Eilon** [comment]
@dgee2 We're currently planning on just special-casing `text/html` because Razor knows how to parse only HTML. If in the future that is not enough, we can look at making it fancier.

**Comment by NTaylorMullen** [comment]
fb6a08d5de3d11933c7d5884a7d5760646bdd249

**Comment by verysimplenick** [comment]
Workaround:
```cshtml
<script>
// ... some long function here
            @if (true)
            {
                <abtest name="MyAbTesting">
                    <a-option> additionalCode1 </a-option>
                    <b-option> additionalCode2 </b-option>
                </abtest>
             }
</script>
```

**Comment by dougbu** [comment]
**Hi @verysimplenick, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

In particular, #502 was an issue in early 1.0 Beta releases. Are you using the workaround for a `<script>` tag that isn't of `type` "text/html"? If there's an need for your suggestion with "text/html", please open a new issue.
