### ISSUE TITLE
Code formatter does not always love the textarea content

### ISSUE THREAD

**Issue by Casimodo72** [aspnet/Razor#513]
Hi,
when using a non-one-liner textarea and writing its text value directly into the file, then auto-formatting the file (via whatever keys you have assigned) produces different effective HTML.

Scenario:
Before auto-formatting:

```xml
<textarea id="Message"
	name="Message">Senden Sie mir ein Angebot für...</textarea>
```

After code auto-formatting.

```xml
<textarea id="Message"
	name="Message">
Senden Sie mir ein Angebot für...
</textarea>
```

The text comes out as:

![razor-auto-formatting-textarea-breaks-intention](https://cloud.githubusercontent.com/assets/10551738/9801968/f6154cfc-5816-11e5-98af-f3a737fc5712.png)

On ther other hand, if one uses a one-liner textarea, e.g.

```xml 
<textarea id="Message" name="Message">Senden Sie mir ein Angebot für...</textarea>
```

... then everything's ok.

Using VS 2015 vNext, DNX Core 5.0 & co.

Regards,
Kasimier Buchcik

**Comment by Eilon** [comment]
@Casimodo72 thanks for the bug report. This looks to be an issue with VS's formatting - can you log the issue in https://github.com/aspnet/Tooling/issues/ ?

**Comment by Casimodo72** [comment]
@Eilon: done: https://github.com/aspnet/Tooling/issues/177

**Comment by NTaylorMullen** [comment]
Thank you @Casimodo72 ! :smile:
