### ISSUE TITLE
Rename TargetElement to HtmlTargetElement

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#516]
See discussion in https://github.com/aspnet/Mvc/issues/3101.

Please post an announcement when done.

**Comment by NTaylorMullen** [comment]
f71f9fb67995c0d5aa56354fbe11769a5e26497b
https://github.com/aspnet/Mvc/commit/93735a5be67479616d92d07e5d04329ec4d64099
https://github.com/aspnet/RazorTooling/commit/30a8c5bebe6d15800250eec8bbcf90c026ed3ca1
