### ISSUE TITLE
Rename RestrictChildrenAttribute properties/params to be `ChildTag` etc.

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#517]
See https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNet.Razor.Runtime/TagHelpers/RestrictChildrenAttribute.cs

```c#
tagName --> childTag
tagNames --> childTags
ChildTagNames --> ChildTags
```

**Comment by NTaylorMullen** [comment]
4fd866f340ef5c53432717fe4451be25ac2c71b7
