### ISSUE TITLE
Razor intellisense doesnt show up when user overwrites existing method

### ISSUE THREAD

**Issue by anandjp** [aspnet/Razor#52]
Razor intellisesne doesn't show up in below scenario
Scenario#1: going backward with selection and hitting . (dot)
1. User types razor keyword like `@await Html.Password`
2. Then sees error in the error list that this is not async method, realizes mistake
3. Selects text with string Password and . (dot) (backward selection ctrl+shift+back arrow button)
4. Tries to type .(dot) again and now intellisense shows “Parsing document” and after few seconds gets nothing.
 	Workaround: User need to select and type . (dot) again to get correct intellisense.
 
Scenario#2: Slight variation of scenario 1 but in step4 when user sees parsing document, hit ctrl+ J and user will see html tag intellisense

**Comment by yishaigalatzer** [comment]
Duplicating of #81

**Comment by anandjp** [comment]
#81 is exact copy of this bug. Don't know why #81 was even created. 
I am not sure whether I will get notification when #81 is fixed.
