### ISSUE TITLE
ITypeInfo.FullName should return the same value as TypeInfo.FullName

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#523]
Right now we sanitize the FullName to remove assembly name for generic types for e.g.
`typeof(List<string>).FullName` - `System.Collections.Generic.List`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]`

versus
`new RuntimeTypeInfo(typeof(List<string>).GetTypeInfo()).FullName` - `System.Collections.List`1[[System.String]]`

The primary motive for sanitizing these type names was to workaround an issue in precompilation where CoreCLR types are compiled against types in System.Runtime (consequently FullName has `[[System.String, System.Runtime...]]`) but get type forwarded to mscorlib at runtime. 

To resolve this issue, we should declare make `ITypeInfo: IEquatable<ITypeInfo>` which can do the right thing in terms of comparisons rather than relying on comparability of `ITypeInfo.FullName`

**Comment by NTaylorMullen** [comment]
:+1:
