### ISSUE TITLE
Consider changing encoding behavior of TagHelperContent.AppendFormat

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#524]
We made a change recently to make the `Append(string)` method on `TaghelperContent` perform encoding. (`AppendEncoded(string)` is available for pre-encoded text.)

However, now `AppendFormat(...)` is much less useful. The **result** of formatting gets encoded. We probably want something closer to the semantic for formatting in localization - where the format string is considered pre-encoded and the parameters get html-encoded by default.

**Comment by danroth27** [comment]
@DamianEdwards 

Let's remove AppendFormat for now and we can discuss adding an extension method in the future that property HTML encodes just the token values.

**Comment by danroth27** [comment]
https://github.com/aspnet/Razor/issues/526

**Comment by rynowak** [comment]
9a41bafea7c9eef0128443b2b648147e0e8194fc
a602b47e262b1733611018f1d357784dd7e10c5c
