### ISSUE TITLE
Support full lambda expression parameters

### ISSUE THREAD

**Issue by schotime** [aspnet/Razor#53]
It would be great if you could use lambdas in Razor, without just having the one Func<string,string> which takes one parameter item.

Here is an example syntax:

```
@Form.For(..., @=> builder {
        @builder.EditorFor(m => m.Name)
})
```

or

```
@Form.For(..., @=> (builder,i) {
        @builder.EditorFor(m => m[i].Name)
})
```

More info can be found here:
http://hammett.castleproject.org/index.php/2011/07/mr-3-update-castle-blade/

**Comment by schotime** [comment]
Hey guys,
Just wondering where we stand with this?
It seems Tag helpers might have worked but you can't pass variables to the nested context (unless i'm missing something) and view components are just method partials it seems.
Cheers,
Adam

**Comment by yishaigalatzer** [comment]
As you can tell this is in the backlog milestone. That means post RTM.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.

**Comment by schotime** [comment]
Boo.
Seems like razor has just become spark without the power.
