### ISSUE TITLE
Modify parsed attribute names to allow the open angle character.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#538]
This in addition to #137 will almost fully complete the HTML5 spec for supported attribute names as far as commonly used characters go.

This would allow scenarios such as: `<p cl<ass="hello"></p>`.

**Comment by Eilon** [comment]
Doesn't look like Angular or other libraries presently require this, so moving to RC1.

**Comment by rynowak** [comment]
No plans to do this without a strong reason
