### ISSUE TITLE
Review Razor.Runtime tests for reliance on the default HTML encoder

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#539]
There's a bunch of tests here calling `DefaultTagHelperContent.GetContent()` and `DefaultTagHelperContent.ToString()` - these tests rely on the behavior of the default HTML encoder, which we want to avoid.

The other risk is that these tests rely on the default HTML encoder, and mostly use input which is not being encoded by the default HTML encoder, so it's not clear we have good coverage of when encoding should be performed.

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by rynowak** [comment]
Self-assigning, as I was already doing this because reasons

**Comment by Eilon** [comment]
If that floats your boat, go for it!

**Comment by rynowak** [comment]
323befaaf10a4c3bf90f73153065b331a5e8ace0
