### ISSUE TITLE
Update tag name and attribute name parsing to respect HTML5 encoding/control character requirements

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#540]
The HTML5 spec defines that tag names should be treated as [ASCII case insensitive](http://www.w3.org/TR/html5/infrastructure.html#ascii-case-insensitive) were we use `StringComparer.OrdinalIgnoreCase`. It also states that attribute names can't contain control characters.

**Comment by NTaylorMullen** [comment]
This is an issue that's been there forever with Razor parsing but has not been complained about by customers. Most likely due to the fact that these issues are extremely uncommon. Nevertheless, here's an issue to track if we ever want to do this. :smile:

**Comment by Eilon** [comment]
Let's discuss this in RC1, along with some of the other Razor/HTML5 items.

**Comment by rynowak** [comment]
No plans to fix this without a specific complaint
