### ISSUE TITLE
Allow nested razor commenting

### ISSUE THREAD

**Issue by Buildstarted** [aspnet/Razor#551]
When testing changes to a file I find I comment out blocks of code often. However this is a pain when you comment out a block of code that contains a commented out block of code.

    @*<ul>
        <li>Home</li>
        @*<li>Menu Item 1</li>*@
        <li>Menu Item 2</li>
        @*<li>Menu Item 3</li>*@
        <li>Menu Item 4</li>
        @*<li>Menu Item 5</li>*@
    </ul>*@

When commenting out the containing `ul` the entire thing basically breaks and must be commented either haphazardly or all the sub comments must be removed.

I can't think of any reason this should have any affect to allow nesting comments.

![image](https://cloud.githubusercontent.com/assets/743025/10172106/849aabb4-6692-11e5-9697-1d32738b358f.png)

Pasted is an example of the cshtml for the above. It shows how the parser views the file and doesn't accurately comment out what should be commented.

**Comment by Eilon** [comment]
Supporting nested comments is generally a can of worms. Though it might conceivable fix the case you have, it could just as easily break other cases that work today.

Some interesting discussions on this topic are here:
* http://stackoverflow.com/questions/7872981/language-support-for-recursive-comments
* http://programmers.stackexchange.com/questions/116330/why-dont-more-languages-support-recursive-nested-comments

So, while this is certainly an interesting suggestion, the benefits don't seem to outweigh the costs.
