### ISSUE TITLE
Expose `FilePath` on `MappingLocation` to let Razor editor know mapping origination.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#552]
Today the Razor editor has to jump through hoops to determine if a projected [mapping location](https://github.com/aspnet/Razor/blob/0a1edbe3f96bcf3807ba8483d47a6ecc00ee0562/src/Microsoft.AspNet.Razor/CodeGenerators/MappingLocation.cs) originated from the current file or from a `_ViewImports.cshtml`. Due to their roundabout way of determining a mappings original location it can occasionally be wrong. We should expose what file created the mapping location so tooling can respond accordingly.

/cc @pranavkm @ToddGrun

**Comment by Eilon** [comment]
Do we need to have a matching tooling bug to consume this new property?

**Comment by NTaylorMullen** [comment]
@ToddGrun already has one :smile:

**Comment by Eilon** [comment]
Cool.

**Comment by NTaylorMullen** [comment]
be324b220a9d3adb98b7dec2c1eaf5a0924c3a8f
