### ISSUE TITLE
`TreeStructureChanged` marked as `true` when whitespace is added to a page with `TagHelper`s

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#553]
The Razor editor uses the [TreeStructureChanged](https://github.com/aspnet/Razor/blob/0a1edbe3f96bcf3807ba8483d47a6ecc00ee0562/src/Microsoft.AspNet.Razor/DocumentParseCompleteEventArgs.cs#L18) property to determine if a full-parse should occur. Today, if there's a `TagHelper` on a page hitting *Enter* results in its value being set to `true`. This winds up causing unneeded parsing of the document.

**Comment by Eilon** [comment]
So this is a perf issue?

**Comment by NTaylorMullen** [comment]
On the editor side yes. I didn't want to mark it as perf because for Razor it's more of a bug that alleviates the editors perf issue :smile:

**Comment by NTaylorMullen** [comment]
deaf2dc828b549f425a54d484d94afc9f8770635
