### ISSUE TITLE
Editing a tag helper in a view throws exception causing VS to crash

### ISSUE THREAD

**Issue by kichalla** [aspnet/Razor#555]
Example:
After typing in `<a asp-action="` especially if its the **last** tag in the .cshtml file there is an exception being thrown which causes VS to crash.

This was with Canary build.

@NTaylorMullen @ajaybhargavb have already investigated the cause and this issue is to track it

**Comment by NTaylorMullen** [comment]
The tag has to be the last tag in the file correct?

**Comment by kichalla** [comment]
Yup, I mentioned it above :-)

**Comment by NTaylorMullen** [comment]
You said *especially* so wanted to verify that it was a requirement :smile:

**Comment by ajaybhargavb** [comment]
bc103fcaa404c3fabd902259e170f18f2f183738
