### ISSUE TITLE
Make Razor codegen use invariant culture

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#557]
There are places in Razor where we use CultureInfo.CurrentCulture in Razor code generation to format non-user strings. There's no reason to vary generated code based on user culture.

**Comment by dougbu** [comment]
We may have user-visible problems here. In particular, we have a few places where C# generation uses `CurrentCulture` when writing out non-`string` values. Could generate invalid C# if for example an `int` is negative and the user's culture has a number format with a trailing negative symbol. Should make sure large values (greater than `999`), negative values, and so on work end-to-end.

**Comment by Eilon** [comment]
I think it's extremely unlikely that this would ever be a real issue - I doubt Razor code-gens many negative integers or any fractions. Nevertheless, we should fix for the purpose of correctness.

**Comment by dougbu** [comment]
#### FYI
As @Eilon thought, this issue doesn't have any apparent user-visible symptoms. Fix is for correctness.

While investigating I found a few places where we aren't explicit about `StringComparison`s and will fix those as well -- also for correctness.

##### Details
`CurrentCulture` was used when generating C# only for `int`s, specifically `SourceLocation.AbsoluteIndex` and `LineIndex` values (or derived from them). These values are never negative and the default format does not include separator characters. In particular Razor never generates code for `SourceLocation.Undefined`.

**Comment by dougbu** [comment]
fe5e1b8
