### ISSUE TITLE
RestrictChildren does not honor modified `TagName` value

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#560]
```C#
    [RestrictChildren("div")]
    public class MyTagHelper : TagHelper
    {

    }

    public class OtherTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            output.TagName = "div";
        }
    }
```

Results in
```
The <other> tag is not allowed by parent <my> tag helper. Only child tags with name(s) 'div' are allowed.
<my>
    <other></other>
```

The check should instead be performed at runtime (rather than parse time) and the designer should flag these as warnings instead of errors.

**Comment by NTaylorMullen** [comment]
O_o... Whaaaa, This seems like a horribad idea.

**Comment by NTaylorMullen** [comment]
I could see honoring `[OutputElementHint]` however.

**Comment by pranavkm** [comment]
Ahh. We need to update the docs on that attribute to indicate it's a catch all tag helper.

**Comment by danroth27** [comment]
@DamianEdwards We think this behavior is by design.
