### ISSUE TITLE
Consider not requiring quotes around @tagHelperPrefix values

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#561]
The usage for this is `@tagHelperPrefix "th"` where the value cannot have whitespaces. Unless I'm missing something obvious, there isn't a whole lot of use for the extra quotes.

**Comment by NTaylorMullen** [comment]
If we decide to do this, we should do the same for `@addTagHelper` and `@removeTagHelper`

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by Eilon** [comment]
Please post an announcement when done. Also need to consider if any tooling changes are needed (including templates).

**Comment by NTaylorMullen** [comment]
Yup, will need changes across the board to react to this change. Will breakk evvverything :imp:

**Comment by NTaylorMullen** [comment]
013f3a27afc6ecdc58a8c246a67cbc5b2c531ce3
0c953155001e49d92a15dbce3db1a9ea98d0697f
https://github.com/aspnet/Mvc/commit/d564a4a96b891bea1f321824b9ed7c7c77c3cf85
https://github.com/aspnet/Docs/commit/031406a2f1b7c956ef4644beecb7f5346154c61c
https://github.com/aspnet/Templates/commit/94946892c0ae93cd93acfaf1144a57a66bdb20ad

**Comment by dougbu** [comment]
and aspnet/MusicStore@dddc6a2

**Comment by Kagamine** [comment]
I think this should be filed on aspnet/Announcements

**Comment by NTaylorMullen** [comment]
@Kagamine it is :smile: https://github.com/aspnet/Announcements/issues/103
