### ISSUE TITLE
Specifying `RestrictChildren` and empty `HtmlTargetElement` results in an error

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#562]
```
[RestrictChildren("div")]
[HtmlTargetElement]
public class MyTagHelper : TagHelper
{

}
```

```HTML
<p>
    <my>
        <div></div>
    </my>
</p>
```

Expected: This should render MyTagHelper correctly
Actual: `The <my> tag is not allowed by parent <p> tag helper. Only child tags with name(s) 'div' are allowed.`

**Comment by NTaylorMullen** [comment]
By design. By specifying `[HtmlTargetElement]` you're saying that the `TagHelper` applies to every tag.

**Comment by pranavkm** [comment]
We need to update the docs on that attribute to indicate it's a catch all tag helper.

**Comment by danroth27** [comment]
The doc comments for `HtmlTargetElementAttribute` could be improved. The default constructor summary should specify what `*` means - you shouldn't have to read the remarks.

Also, the error message doesn't specify clearly which tag helper is causing the issue. What if you have multiple tag helpers targeting `<p>`?

**Comment by dougbu** [comment]
1c7af0d
