### ISSUE TITLE
Taghelpers do not preserve whitespace around HTML attributes

### ISSUE THREAD

**Issue by kirthik** [aspnet/Razor#563]
```
<div class =          "hey">
```

If I have a taghelper for div tag then my end output for the above razor code would be
`<div class="hey">`

Related to https://github.com/aspnet/Razor/issues/123. Looks like tag helpers are not considering spaces surrounding equals.

**Comment by dougbu** [comment]
@kirthik is there a parsing issue here? Or did you expect the spaces to be preserved in the generated HTML?

Put another way, did anything fail?

**Comment by kirthik** [comment]
I was expecting spaces to be preserved in the generated HTML.

**Comment by Eilon** [comment]
Does Razor attempt to do any preservation of whitespace in a tag? E.g. if I have:

```html
<div
    foo      =                   "bar"
baz    =
      "qux"
>whatever</div>
```

Won't it always render
```html
<div foo="bar" baz="qux">whatever</div>
```
?

**Comment by kirthik** [comment]
Yes razor preserves white space in a tag now. We fixed that issue(https://github.com/aspnet/Razor/issues/123) with this commit https://github.com/aspnet/Razor/commit/08c8f9f7ba6f9b48d93a4c6ea407a698fb94e4d8

**Comment by Eilon** [comment]
I know we now *allow* it, but does it actually ever get preserved in the rendering?

**Comment by kirthik** [comment]
When I inspect html source for the razor code above, I see this
```
<div
     foo           =      "bar"
baz     =
     "qux"
>whatever</div>
```

not `<div foo="bar" baz="qux">whatever</div>`

**Comment by Eilon** [comment]
Well `<div>` probably doesn't have a tag helper on it :smile: 

But same thing for `<a href="">...</a>` I think will show the whitespace is trimmed.

I talked to @dougbu and as far as he knows all whitespace is trimmed when a tag helper is used.

This would ultimately be a feature request that we could consider in a future version.

**Comment by dougbu** [comment]
The feature would be somewhat analogous to preserving how attribute values are quoted in the `.cshtml` file: We'd need to extend `IReadOnlyTagHelperAttribute` and so on to expose information about whitespace before and after the `=` sign. Then `RazorPage` would need to do something with the extra information to generate the attribute appropriately.

Note "preserving how attribute values are quoted in the `.cshtml` file" is a significantly higher-value feature request we aren't even tracking at the moment. At least that one would avoid some special cases in `RazorPage`.

**Comment by rynowak** [comment]
No plans to do this without significant feedback
