### ISSUE TITLE
Can't compile templates on OS X

### ISSUE THREAD

**Issue by michaelrkn** [aspnet/Razor#565]
I've built a very [simple Hello World app](https://github.com/michaelrkn/nancy-hello-world) with Nancy using Razor views. On Windows, when I launch the app with `dnx kestrel` and browse to `localhost:5004`, I see "hello world". On Mac OS X, I see:

```
Error compiling template: views/index.cshtml

Errors:
[CS0006] Line: 0 Column: 0 - Metadata file `/Users/michael/Code/data-0x7fe71aff6c00' could not be found (show)

Details:
hello world

Compilation Source:
// ------------------------------------------------------------------------------
Line 1:	//  <autogenerated>
Line 2:	//      This code was generated by a tool.
Line 3:	//      Mono Runtime Version: 4.0.30319.17020
Line 4:	// 
Line 5:	//      Changes to this file may cause incorrect behavior and will be lost if 
Line 6:	//      the code is regenerated.
Line 7:	//  </autogenerated>
Line 8:	// ------------------------------------------------------------------------------
Line 9:	
Line 10:	namespace RazorOutput {
Line 11:	    using Microsoft.CSharp.RuntimeBinder;
Line 12:	    using System;
Line 13:	    using System.IO;
Line 14:	    
Line 15:	    
Line 16:	    public class RazorView : Nancy.ViewEngines.Razor.NancyRazorViewBase {
Line 17:	        
Line 18:	#line hidden
Line 19:	        
Line 20:	        public RazorView() {
Line 21:	        }
Line 22:	        
Line 23:	        public override void Execute() {
Line 24:	WriteLiteral("hello world\n");
Line 25:	
Line 26:	        }
Line 27:	    }
Line 28:	}
Line 29:	
```

One thing that caught my eye was that the exception references `/Users/michael/Code/data-0x7fe71aff6c00` but I'm running the app from `/Users/michael/nancy-hello-world/`.

I'm using DNX 1.0.0-beta7 and Mono 4.2.0. I've tried this on a couple machines including a clean install of DNVM/DNX. Here's my `project.json`:

```json
{
  "dependencies": {
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNet.Owin": "1.0.0-*",
    "Nancy": "1.3.0",
    "Nancy.ViewEngines.Razor": "1.3.0"
  },
  "commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
  },
  "frameworks": {
    "dnx451": {}
  }
}

```

Let me know if this isn't the right place to open this issue, or if there's any other information I provide to help track it down.

Thanks!

**Comment by pranavkm** [comment]
I performed a cursory scan of `Nancy.ViewEngines.Razor` binaries and it looks relies on Asp.Net 4.6 constructs (such as web.config). Have you checked with NancyFx to see if their code's meant to work on Mono \ AspNet5?

**Comment by michaelrkn** [comment]
Ah, I will check with them. Sorry to open the issue in the wrong place! Thanks for the help.

**Comment by michaelrkn** [comment]
Oh, one thing before I close this out - I am running this on dnx451, not dnxcore50. I *thought* that meant that it should be compatible with Asp.Net 4.6 - is that not right? Sorry for the newb questions - I'm just getting started with C# :)

**Comment by danroth27** [comment]
Targeting dnx451 means you are targeting the full .NET Framework version of DNX. This means you can use most existing .NET Framework libraries in your DNX app. However, running ASP.NET 4.6 components inside of DNX isn't supported - you need to use ASP.NET 5 instead (ex use MVC 6 instead of MVC 5).

**Comment by michaelrkn** [comment]
Thanks @danroth27! One last question if you have a sec - so why does this work on Windows then, but not Mac? Does the Windows distribution of DNX include those ASP.NET 4.6 components?

**Comment by danroth27** [comment]
On Windows you have the option of running DNX and ASP.NET 5 on the full .NET Framework. This allows you to use most of your existing libraries. The closest thing to the full .NET Framework on OS X is Mono, but there are a bunch of incompatibilities in Mono that can cause issues.

**Comment by michaelrkn** [comment]
Thanks a bunch @danroth27!
