### ISSUE TITLE
Alternative for Environment TagHeper domain

### ISSUE THREAD

**Issue by vkichline** [aspnet/Razor#567]
I see this pattern in the Web Application template's _ValidationScriptsPartial.cshtml:

```
<environment names="Development">
       …
</environment>
<environment names="Staging,Production">
       …
</environment>
```

This pattern above seems brittle; if I add a new environment setting, I have a lot of searching and modification to do.

I wish I had something like:

```
<environment names="Development">
       …
</environment>
<environment names="!Development">
       …
</environment>
```

…or:

```
<environment names="Development">
       …
<else>
       …
</environment>
```

**Comment by Eilon** [comment]
The `<else>` thing can't be done because it's not valid syntax.

But something like this can certainly be done:

```html
<environment names="Development">
    <true>
       …
    </true>
    <false>
       …
    </false>
</environment>
```

**Comment by Eilon** [comment]
(Not saying it's worth it or that it's a good idea, but it's implementable.)

**Comment by Eilon** [comment]
Another alternative to consider would be something like:

```html
<environment names="Development">
       …
</environment>
<environment names="Development" behavior="OppositeDay">
       …
</environment>
```

Or at least something like that.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#5671
