### ISSUE TITLE
Provide FormattableString overloads for format methods that special case the format arguments

### ISSUE THREAD

**Issue by Suchiman** [aspnet/Razor#568]
As suggested by https://github.com/aspnet/Razor/issues/566#issuecomment-146580237 i'm suggesting to provide FormattableString overloads for methods which special case the arguments.
With C# 6 you can now safe yourself from writing MethodFormat("...", ...) as sugar for Method(String.Format(...)) since you can just write Method($"...").
But this also works when the arguments are special cased if you demand a "FormattableString" argument.

So in addition to

``` csharp
public TagHelperContent AppendFormat(string format, params object[] args)
{
    HtmlContentBuilderExtensions.AppendFormat(this, null, format, args);
    return this;
}
```

I suggest

``` csharp
public TagHelperContent AppendFormat(FormattableString formatString)
{
    HtmlContentBuilderExtensions.AppendFormat(this, null, formatString.Format, formatString.GetArguments());
    return this;
}
```

Then you can have

``` csharp
string unencodedText = "Hello, World!";
context.AppendFormat($"<blink>{unencodedText}</blink>")
//or even
context.AppendFormat($"<blink>{"Hello, World!"}</blink>")
```

**Comment by rynowak** [comment]
Closing because we think this is low value and would be a breaking change for us to add it as an overload
