### ISSUE TITLE
API namespace cleanup for tag helpers

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#578]
From a meeting with @dougbu @rynowak @DamianEdwards

Move what’s in the `Microsoft.AspNet.Razor.TagHelpers` namespace to something like 
`Microsoft.AspNet.Razor.Compilation.TagHelpers`.

And move what's in the `Microsoft.AspNet.Razor.Runtime.TagHelpers` namespace to `Microsoft.AspNet.Razor.TagHelpers`. An alternative that we considered was to rename it to `Microsoft.AspNet.Html.TagHelpers`, because it's not really Razor-specific, but meh.

**Comment by NTaylorMullen** [comment]
bd2a98e5ecb7afe7ca621b01af68c03e43e29669
b1ad14fd46c50d6613a5d9dc691cefbe21516e0e
https://github.com/aspnet/Mvc/commit/0e254706607e7cccef11dc50d6b69e746c5827c3

**Comment by dougbu** [comment]
aspnet/Mvc@0e25470 leaves references to `Microsoft.AspNet.Razor.Runtime.TagHelpers` in the `LinkTagHelper` and `ScriptTagHelper`. Either unused `using`s were not removed or this issue should be reopened and the dangling type moved to `Microsoft.AspNet.Razor.TagHelpers`.

Who reviewed that commit BTW? I don't remember a PR for it.

**Comment by NTaylorMullen** [comment]
It was a reaction. Shouldn't need a review. As for them having `Runtime.TagHelper`s. That's due to them creating new `DefaultTagHelperContent`'s

**Comment by dougbu** [comment]
If they need to do that, others will as well. `DefaultTagHelperContent` is not in the correct namespace yet.

**Comment by NTaylorMullen** [comment]
Moved `DefaultTagHelperContent` to `Razor.TagHelpers`
