### ISSUE TITLE
Discussion: Breaking changes for tag helper authors in RC1

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#583]
Due to the new `TagHelper` addition of `Init` used to setup your `TagHelperContext` and other related item bag info for executed children to consume we decided that the ability to execute children doesn't entirely make sense on the context object since it has no connection to the actual structure of the element.

The alternative would have been to make `GetChildContentAsync` throw when invoked within the `Init` method (yuck).
## Before

``` C#
public class CustomTagHelper : TagHelper
{
    public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        await context.GetChildContentAsync();
    }
}
```
## After

``` C#
public class CustomTagHelper : TagHelper
{
    public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        await output.GetChildContentAsync();
    }
}
```

**Comment by NeelBhatt** [comment]
```Before``` and ```After``` looks similar. May be i am missing something or need to correct?

**Comment by thoemmi** [comment]
Though I see the rationale behind the change, it seems strange to call **output** for the **input**. :confused:

**Comment by dougbu** [comment]
> seems strange to call **output** for the **input**. :confused:

This delegate returns the _output_ of the child elements. In MVC tag helpers that use this for example, the return value is often not used -- it's just called to ensure children have executed (and output whatever they're going to output).

**Comment by dougbu** [comment]
Broadening the subject to include additional changes. Please use this issue to discuss aspnet/Announcements#89 as well as aspnet/Announcements#90.
