### ISSUE TITLE
Tag helpers and Multiple Select vs Select

### ISSUE THREAD

**Issue by rhires** [aspnet/Razor#586]
I think that the tag helpers should be more explicit when rendering a multi-select or not. Depending on the data-type to figure whether to show multiple lines in a select is a bit non-intuitive, and hard to catch when just reading the unrendered html. I've read through a few examples and the same html/tag helper code renders differently depending on what data type is passed in...I should be able to control whether it's multi select more directly (maybe `asp-items-multi`?) And it makes it more clear that is what is expected.

**Comment by dougbu** [comment]
@rhires if the `<select>` element already has a `multiple` attribute, the tag helper won't change it. That seems sufficiently explicit.

**Comment by rhires** [comment]
hmmm...using [this](http://www.davepaquette.com/archive/2015/05/18/mvc6-select-tag-helper.aspx) as my reference. 

    <select asp-for="CountryCodes" 
        asp-items="ViewBag.Countries">
    </select>

If I change the type of "CountryCodes" from IEnumerable<SelectListItem> in my model to IEnumerable<string> then my rendered html will have a multiple element in it, but I won't be able to tell using the snippet above. I can't just declare how I want it to show in my view, I have to depend on the model to pass in the right type. 

On the other hand, I could be totally reading that wrong. Or I may have said it wrong above.

**Comment by dougbu** [comment]
When does the user writing the `.cshtml` file not know the type of their `asp-for` expression?

In your example `CountryCodes` implies a collection. Therefore perhaps the following would be more explicit.
``` html
<select asp-for="CountryCodes" asp-items="ViewBag.Countries" multiple="multiple">
</select>
```

**Comment by rhires** [comment]
Actually, I think I got focused on the wrong thing. If you want a multiple select, IEnumerable goes on the *asp-for* tag; if you want a (regular?) non multiple select, IEnumerable goes on the *asp-items* tag. Also, for the non multiple select, the `asp-for` from the model should be something that isn't IEnumerable, such as string (as in the example). But that also leads to needing to add an empty property to the model just to avoid having the multiple select, because something has to go on the `asp-for`. Being somewhat new to all of this, I'm sure there's a way to populate the asp-for in the view without having to create a new property just for that...just not sure what it would be. Just use the ViewBag? 

Anyway, thank you for helping me learn this, and think it through. I have it figured out now.

**Comment by dougbu** [comment]
Sorry @rhires your description isn't quite correct. Contained `<option>` elements in the `<select>` element and the `asp-items` value are sources for `<option>` elements in the generated HTML. The first choice is good for static items while the second is required when the items are not known up-front or are a bit more complicated. On the other hand the `asp-for` expression determines which `<option>` element(s) will be selected and the default `id`, `multiple`, and `name` attribute values of the `<select>` element.

**Comment by thecobe** [comment]
Hi all 
i have this problem
My first select is:
 <select id="UserRoleId" class="form-control" asp-for="UserType" asp-items="@Model?.UserType">
and second is:
<select id="salePointsListMaster" class="form-control" asp-for="SalePointMasterCode" asp-items="@Model?.SalePointsListMaster">

The first one render a multiple select while the second one a single value select
I load them in the same manner and i don't want a mutiple select but a simple single select

**First select loading**
List<SelectListItem> selectListItems = new List<SelectListItem>();
 foreach (DB.DAL.UsersRoles usersRoles in listUsersRoles)
            {
                SelectListItem salePoint = new SelectListItem();
                salePoint.Text = usersRoles.Description;
                salePoint.Value = usersRoles.ID.ToString();
                selectListItems.Add(salePoint);
            }
return selectListItems;

**Second select loading**
 List<SelectListItem> selectListItems = new List<SelectListItem>();
foreach (DB.DAL.SalePointsInfo salePointsInfo in salePointsInfoList)
            {
                SelectListItem salePoint = new SelectListItem();
                salePoint.Text = salePointsInfo.Description;
                salePoint.Value = salePointsInfo.Code;
                selectListItems.Add(salePoint);
            }
return selectListItems;

The only difference is the first DAL Object has e value caming from an int field while the second from a varchar field 
What can i do?

**Comment by dougbu** [comment]
@thecobe this is a closed issue and it's just luck that I happened to notice your comment. Please open a new issue describing exactly what you're seeing and how that differs from what you expect.

The information you've provided is a good start but please add the definition of the model type -- we can't see anything about `UserType` or `SalePointMasterCode`. I'm also not sure whether your concern is the number of `<option>` elements in the `<select>` or the presence of a `multiple` attribute.
