### ISSUE TITLE
Discussion: @addTagHelper, @removeTagHelper and @tagHelperPrefix no longer have quotes around value.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#596]
## Old

``` HTML
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@removeTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@tagHelperPrefix "th:"
```
## New

```
@addTagHelper *, Microsoft.AspNet.Mvc.TagHelpers
@removeTagHelper *, Microsoft.AspNet.Mvc.TagHelpers
@tagHelperPrefix th:
```

**Comment by caioproiete** [comment]
It would be useful to know rational for taking the quotes out from a design perspective.

I personally think it feels a little bit odd not having the quotes. Maybe it is because I'm used to defining types and namespaces like that everywhere and always having to use quotes.

**Comment by brockallen** [comment]
@caioproiete 

Do you use quotes around @model in razor? Or @using? It feels more consistent with the way the other directives work. This is my conjecture for the rationale of the change.

**Comment by caioproiete** [comment]
@brockallen: Good point. We don't use quotes on `@model` or `@using`.

I guess what seems odd with the `*, namespace` is the fact that I'm used to this syntax in .svc files when using WCF, or from WebForms, or even when declaring relationships between assemblies via `assembly` directives. The `type, namespace` declaration is always a string as far as I can remember.

**Comment by brockallen** [comment]
Maybe remove the single whitespace after the "," and that will make you feel better? :)

**Comment by caioproiete** [comment]
:) I don't think the whitespace is the big issue... The whole expression using the `*` and `,` (comma) looks like a string to me.

The `@tagHelperPrefix th:` is equally strange as `th:` is clearly a string to my eyes...

Just thinking that using the quotes seemed to make more sense.

**Comment by Tasteful** [comment]
Why should the tag helper prefix include the colon. Can we use other characters as prefix also?

**Comment by dougbu** [comment]
@Tasteful `th:` is an example. `@tagHelperPrefix t` or `@tagHelperPrefix t-t-t-t-` are just as valid.

FYI characters are valid by default. The list of _invalid_ prefix characters include whitespace and `{ '@', '!', '<', '/', '?', '[', '>', ']', '=', '"', '\'', '*' }`.

**Comment by Bartmax** [comment]
Tooling (like colors and intellisense) on VS is broken after moving to RC2. Is there anything I can do to get it back or should I wait for some beta tooling?

**Comment by NTaylorMullen** [comment]
@Bartmax IntelliSense will be broken temporarily due to this change. Reason being VS bits don't yet understand the new directive syntax without quotes.

**Comment by Bartmax** [comment]
thank you @NTaylorMullen I'm tempted to go back to rc1 ;) can't live without full th powers.

**Comment by NTaylorMullen** [comment]
Haha, ya don't blame you. As a temporary work around you can provide the quotes to the `@addTagHelper` at design time then prior to running remove them :persevere:

**Comment by cwe1ss** [comment]
Will there be an update to VS tooling before RC2? Would be great to get IntelliSense sooner in case RC2 will not be released within the next 1-2 months.

**Comment by Eilon** [comment]
@cwe1ss we would definitely like to release something early, but there isn't anything planned at this time.

**Comment by mikes-gh** [comment]
I installed update 2 RC for VS and @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers is still underlined in red.
Also I now have an issue with 
```
The Name (User,Viewbag etc) does not exist in the current context.
```

I deleted and recreated suo and componentcache directory but still no joy.

This is my project.json
```
{
    "commands": {
        "web": "Reports2",
        "ef": "Microsoft.EntityFrameworkCore.Commands"
    },
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "hiqpdf": "9.0.0",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
        "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0-*",
        "Microsoft.AspNetCore.Authentication.Google": "1.0.0-*",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
        "Microsoft.AspNetCore.Hosting": "1.0.0-*",
        "Microsoft.AspNetCore.HttpOverrides": "1.0.0-*",
        "Microsoft.AspNetCore.Identity": "1.0.0-*",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
        "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc.Dnx": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.Commands": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-*",
        "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-*",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-*",
        "Microsoft.Extensions.Logging": "1.0.0-*",
        "Microsoft.Extensions.Logging.Console": "1.0.0-*",
        "Microsoft.Extensions.Logging.Debug": "1.0.0-*",
        "Microsoft.NETCore.Platforms": "1.0.1-*",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-*"
    },
    "tools": {
        "dotnet-razor-tooling": "1.0.0-*"
    },
    "exclude": [
        "wwwroot",
        "node_modules"
    ],
    "frameworks": {
        "dnx451": {
            "dependencies": {
            }
        }
    },
    "publishExclude": [
        "**.user",
        "**.vspscc"
    ],
    "scripts": {
        "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
    },
    "userSecretsId": "aspnet5-Reports2-46c610d6-c595-4b6b-8db1-5b4cf0b84541",
    "version": "1.0.0-*"
}
```

**Comment by mikes-gh** [comment]
Even if I add the quotes back I still get this.

![broken intellisense](https://cloud.githubusercontent.com/assets/16208742/14488164/a320efaa-015e-11e6-8735-93a53916c1e5.png)

Am I missing a using or something.

**Comment by Eilon** [comment]
@NTaylorMullen is this just because the tooling is old at this point?

**Comment by NTaylorMullen** [comment]
Hmm @Eilon I don't believe so because there was a `User` property in RC1 as well.

@mikes-gh Are you using `@inherits` anywhere that would affect that page?
