### ISSUE TITLE
Intellisense suggests child tags and attributes restricted by ParentTag

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/Razor#597]
Consider:

    [RestrictChildren("child")]
    public class Parent1 : TagHelper {
    }

    [RestrictChildren("child")]
    public class Parent2 : TagHelper {
    }

    [HtmlTargetElement("child", ParentTag = "parent1")]
    public class ChildOfParent1 : TagHelper {
        public string Prop1 { get; set; }
    }

    [HtmlTargetElement("child", ParentTag = "parent2")]
    public class ChildOfParent2 : TagHelper {
        public string Prop2 { get; set; }
    }

Visual Studio editor (Tools Beta8) suggests both `child` tags regardless of the parent:

![img](http://i.imgur.com/iLsNBeI.png)

**Comment by dougbu** [comment]
The work to support `ParentTag` has not yet been done. It's tracked at aspnet#273. Believe it's slated for the Tooling RC2 milestone.

**Comment by Eilon** [comment]
Closing as dup of https://github.com/aspnet/Tooling/issues/273.
