### ISSUE TITLE
Set CompilationOptions.StrongNameProvider for Roslyn to compile pages in strong named web apps

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Razor#598]
If you strong name a web app, Razor fails to compile pages:

    An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

    /Views/Home/Index.cshtml

    Error signing output with public key from file 'C:\Users\cesars\Documents\Visual Studio 2015\Projects\RC1StrongNameValidation\src\RC1StrongNameValidation\Key.snk' -- Assembly signing not supported.

Apparently this happens because no strong name provider is being set for Roslyn (see https://github.com/dotnet/roslyn/issues/4953 and https://github.com/aspnet/dnx/blob/1bb5a1d24fcd7d21d2278528c243e2b9f181c43d/src/Microsoft.Dnx.Compilation.CSharp/RoslynCompiler.cs#L205).

**Comment by davidfowl** [comment]
This is not a razor bug. It's an mvc bug and it shouldn't affect razor and needs to be fixed

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/Mvc/issues/3831.
