### ISSUE TITLE
Optimize allocations in TagHelperAttributeList and friends

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#599]
This is a particular hotspot for allocations as these are created and used all over.

![image](https://cloud.githubusercontent.com/assets/1430011/11107265/02bc23b8-8891-11e5-8b5c-0a22971f3837.png)

**Comment by NTaylorMullen** [comment]
This significantly overlaps with https://github.com/aspnet/Razor/issues/605 but is a stepping stone. Going to grab this one and start work.

**Comment by NTaylorMullen** [comment]
31a68a0705b8274e6345705787ea11b6820885b9
