### ISSUE TITLE
Consider pre-allocating TagHelperAttributes

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#600]
Where these are read-only/const/immutable we should try to optimize by putting these into readonly static fields. The attributes and associated collections are a significant enough amount of allocations that we should do something about it.

![image](https://cloud.githubusercontent.com/assets/1430011/11107310/9bc15f88-8891-11e5-8b86-f9f0897ed6ef.png)

**Comment by NTaylorMullen** [comment]
9f675abbcada6f64af954844155eafc6c7b9ede6
