### ISSUE TITLE
Optimize RazorPage.WriteTagHelperToAsync

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#602]
We're not doing deferred writing with TagHelperOutput. Lots of little chatty writes are taking place here and even a `string.Format`!

![image](https://cloud.githubusercontent.com/assets/1430011/11107377/2fa15fa0-8892-11e5-9278-650bb5c400ed.png)

**Comment by rynowak** [comment]
Propose closing this - we did a bunch of work here and the screenshot above isn't relevant anymore.

/cc @Eilon

**Comment by Eilon** [comment]
Ok.
