### ISSUE TITLE
Consider a design when TagHelperAttribute is a struct

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#604]
It may be possible to mitigate some of this with caching, but here's the data as-of now.

![image](https://cloud.githubusercontent.com/assets/1430011/11107457/e4481912-8892-11e5-9067-e48491131751.png)

The HtmlHelpers equivalent to this allocates about 82mb **total**. 2mb of just attributes seems like enough to consider a design change.

**Comment by NTaylorMullen** [comment]
fc99082ea8d97b6b5ffbde3c92a1f03377c9c2fd
b7b3273fa49d31f004a4b739be142db8d068e357
https://github.com/aspnet/Mvc/commit/dca15c0a60ae8282c4b3b5cd4f1ef33e09816834
