### ISSUE TITLE
Do a pass for Linq and boxed enumerators in TagHelpers

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#605]
We should just do a general pass of TagHelpers code for Linq use and boxing foreach'es

![image](https://cloud.githubusercontent.com/assets/1430011/11107507/79d5be08-8893-11e5-87d2-73c15e182588.png)

Some of these are coming from MVC/`HtmlGenerator` as well.

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Mvc#3599
