### ISSUE TITLE
TagHelper GetChildRawContentAsync from parent tag

### ISSUE THREAD

**Issue by evilz** [aspnet/Razor#610]
Hi,

I try to get the raw code inner a parent tag, or avoid childs transformations.

## Use case : create a raw tagHelper

**razor**
```
  <pre><code>
     <raw><my-child-tag>some text</my-child-tag></raw>                                                                       
</code></pre>
```

**tag declaration**
```
[HtmlTargetElement("raw")]
    public class HtmlEncodeTagHelper : TagHelper
    {
        public override int Order
        {
            get { return int.MinValue; }
        }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            // Get Raw child here
            var childContent = context.GetChildRawContentAsync();
            content = HtmlEncoder.Default.HtmlEncode(childContent );
            output.Content.SetContentEncoded(content);
        }
    }
```

What do you think about this ? Is there another way to do that ?

**Comment by NTaylorMullen** [comment]
@evilz is your suggestion that `GetChildRawContentAsync` would return `<my-child-tag>some text</my-child-tag>` and not the evaluated version?

**Comment by dougbu** [comment]
@evilz your approach can double-encode the content. For example users writing `.cshtml` files may stick the `&amp;` or `&quot` wherever they like. And they may need to do that to satisfy the editor. Basically `GetChildRawContentAsync()` cannot return "raw" (unencoded) HTML reliably.

**Comment by evilz** [comment]
True,
And then, I now think, it must be better to disable the "Processing" using some sort of flag in tags.

```
<my-child-tag asp-disable>some text</my-child-tag>
```

@dougbu
Still that  **Raw** or **HtmlEncode** tagHelper can be usefull in some ways.

Some people are using this
```
@Html.Raw(Html.Encode(some_string))
```

**Comment by dougbu** [comment]
> `@Html.Raw(Html.Encode(some_string))`

Why? That's identical to `@some_string` except that, with a number of improvements we've implemented recently, using `@Html.Raw()` and `@Html.Encode()` is less efficient.

**Comment by evilz** [comment]
@dougbu so right ... I'm stupid.

Does it still makes sense to do so for tags? May be it's just overkill and it's just more simple to encode it manualy.

The use case is to create documentation of tagHelper.But I may be going the wrong way.

**Comment by dougbu** [comment]
Simple ways to encode something include assigning it to a variable then using `@variable`. Or just `@("<some>tagged code</some>")`. Either is shorter and should be more efficient than involving `@Html.Encode()`.

**Comment by Eilon** [comment]
I think if you want to show content that looks like HTML when rendered you just need to use good old `&lt;` and `&gt;`. There's nothing special about tag helpers or Razor.
