### ISSUE TITLE
TagHelper Dictionary attributes must always be set via property initializers, even if they're set later.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#620]
Take the following example:

``` C#
public class PersonTagHelper : TagHelper
{
    public Dictionary<string, double> Gpas { get; set; }
}
```

``` HTML
<person gpas="new Dictionary<string, double>()" />
```

This will result in the following being generated:

``` C#
if (PersonTagHelper1.Gpas == null)
{
    throw new InvalidOperationException(FormatInvalidIndexerAssignment("gpas-", "PersonTagHelper1", "Gpas"));
}
PersonTagHelper1.Gpas = new Dictionary<string, double>();
```

We should be smarter at code gen and not create the if statement enforcing the pre-setting of the property for cases when a user provides the entire attribute value.

**Comment by Eilon** [comment]
Discussed with @DamianEdwards , moving to Backlog, we could fix this later if it's still an issue.

**Comment by rynowak** [comment]
Closing unless we get strong feedback
