### ISSUE TITLE
Optimize TagHelperContent for SetContent

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#621]
Much of the time a `TagHelperContent` has its content set by calling `SetContent`. In these usages there will generally just be one item added to the buffer. We can optimize this by eliding the creation of the buffer when `SetContent` is used.

We might want to look for another magic number here besides 1, but it's clear that inlining a single item can be a win.

![image](https://cloud.githubusercontent.com/assets/1430011/11346255/93a404d4-91d0-11e5-8bbf-35a0509606be.png)

**Comment by dougbu** [comment]
There's also a bug in how MVC uses `SetContent()`: Those tag helpers currently _assume_ `Content` is empty but should be clearing what other tag helpers have done.

**Comment by rynowak** [comment]
`SetContent` calls clear

**Comment by dougbu** [comment]
I know but the tag helpers I'm talking about start w/ `Append()` and don't clear implicitly or explicitly.

**Comment by Eilon** [comment]
@dougbu can you log a separate bug for the other issue you're discussing? I'm not sure it's 100% related to this bug, is it?

**Comment by dougbu** [comment]
@Eilon 
> @dougbu can you log a separate bug

Filed aspnet/Mvc#3852.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/pull/728/commits/c400289de5f174accfd7fec3dda7a8c894189726
https://github.com/aspnet/Mvc/pull/4412/commits/ee80f5f84c9ee6b3d4f900e14e574f5b88ecec28
