### ISSUE TITLE
Add ability to provide TagHelper delimited attribute values.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#623]
We currently have several `TagHelper`s that require some sort of delimited attribute value. Such as `<environment names="a, b, c">`, `<a ... vary-by-route="a, b, c">`, etc. This leads to a lot of duplicate code where we do `attributeValue.Split(...).Select(v => v.Trim().Where(v => v.Length > 0)`. Not to mention doing all this results in several allocations that aren't very friendly to perf (especially when we could optimize it at compile time).

**Comment by NTaylorMullen** [comment]
Note: We'd somehow have to limit this capability to only raw strings. Not ones returned via `@value`

**Comment by rynowak** [comment]
Closing, we have no plans to do this.
