### ISSUE TITLE
`@section mySection {` creates an invisible error in the editor.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#625]
Technically an error is logged 1 character past the starting `{` but the editor can't show the red suiqggly since it's passed the EOF.

We should probably investigate other errorswhere +1 is used to ensure we don't surpass the end of the file.

**Comment by Eilon** [comment]
Is this a problem only at the very end of the file?

**Comment by NTaylorMullen** [comment]
Yes

**Comment by Eilon** [comment]
So while you're typing at the end of the file you don't see an error? That doesn't sound super terrible, right?

**Comment by NTaylorMullen** [comment]
You don't see a red squiggly but you do see a (1) pop up in your error dialog. Not horrible, but definitely inconsistent. Also need to consider scenarios where the user legitimately forgot to close out the section and continued writing.

**Comment by Eilon** [comment]
What happens if there's content in the un-closed section?

**Comment by NTaylorMullen** [comment]
Same deal. The error was built assuming the section had content following it.

**Comment by Eilon** [comment]
Likely an easy fix? If so, I'm fine doing it. If not, backlog.

**Comment by NTaylorMullen** [comment]
Yup, easy fix. However, we should probably take a look at all the errors that do similar behavior and fix them aswell.

**Comment by Eilon** [comment]
Make it so.

**Comment by NTaylorMullen** [comment]
392871beb62683bc366a8add4697af657b61a859

/cc @ToddGrun
