### ISSUE TITLE
LocateOwner dives the entire SyntaxTree when partial parsing (while typing)

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#626]
We can be smarter in our `LocateOwner` implementation to determine the potential location of a text change based on the starts of `Block` children

**Comment by NTaylorMullen** [comment]
@ToddGrun talked with @Eilon to do this in RC2 would need to see performance numbers.

**Comment by Eilon** [comment]
@NTaylorMullen can you work with the tooling folks to identify what perf analysis we need to do here?

**Comment by NTaylorMullen** [comment]
Will do

**Comment by Eilon** [comment]
@NTaylorMullen need an update on this because it's been stale. Have we seen perf issues here that we need to investigate for 1.0.0? If not, I'll move this out.

**Comment by NTaylorMullen** [comment]
Move out. It's being worked around in Visual Studio.

**Comment by NTaylorMullen** [comment]
Talked with @ToddGrun offline. Perf issues found with this are many years old. Will have to re-profile.

**Comment by NTaylorMullen** [comment]
After completing #800 `LocateOwner` shows itself to be around 6% of execution for successful partial parses: 
![image](https://cloud.githubusercontent.com/assets/2008729/16696953/29f7f6b4-44fc-11e6-9787-d1590260b041.png)

This was done with the MSN home page.

**Comment by NTaylorMullen** [comment]
@ToddGrun I worked on short circuiting this logic and the best I could do as to avoid the final OwnsChange call on an EditHandler (no perf impact). I know you said you worked around this on your end. Could we sink up to see what you've done?

**Comment by NTaylorMullen** [comment]
Took a shot at minimizing call paths here. Got through it a bit but turned out allocations muddled the perf gains (went from 6% impact to 25% after attempted fix).
