### ISSUE TITLE
TagHelperDesignTimeDescriptorFactory.GetXmlDocumentationFile unused parameter

### ISSUE THREAD

**Issue by IlyaKhD** [aspnet/Razor#629]
The first parameter `assembly` of the static method `TagHelperDesignTimeDescriptorFactory.GetXmlDocumentationFile(Assembly assembly, string assemblyLocation)` is unused.

Relevant to [b1ad14f](https://github.com/aspnet/Razor/blob/b1ad14fd46c50d6613a5d9dc691cefbe21516e0e/src/Microsoft.AspNet.Razor.Runtime/Runtime/TagHelpers/TagHelperDesignTimeDescriptorFactory.cs) which is the latest `TagHelperDesignTimeDescriptorFactory.cs` version at the moment.

**Comment by NTaylorMullen** [comment]
33d32cecd926e3533763e1e2d1444823baa50789
