### ISSUE TITLE
TagHelperDesignTimeDescriptorFactory performance

### ISSUE THREAD

**Issue by IlyaKhD** [aspnet/Razor#630]
Documentation file is read each time a `DocumentationDescriptor` is built (see the `CreateDocumentationDescriptor` method), though while resolving TagHelpers this file could be loaded only once for each assembly.

The process of TagHelpers resolving takes much more time for documented TagHelpers.

Check PerfTest console app in this [branch](https://github.com/IlyaKhD/RazorTooling/tree/khd/resolve-taghelpers.performance).

I've created two fake TagHelper NuGet packs (hosted on MyGet) containing 200 TagHelpers (each has 20 properties). The only difference is that properties in the second pack have summary.
You can run the following commands:

`> dnx resolve-taghelpers`
`> dnx resolve-taghelpers-withsummary`

On my environment it takes 3 sec and 21 sec accordingly.

Caching documentation files decreases execution time from 21 sec to 5sec (check this illustration: https://github.com/IlyaKhD/Razor/commit/db7d1a5b4860fe3e5ef19bc889cd3f37e0f812c0)

This affects greatly Design Time since this code is used in [RazorTooling](https://github.com/aspnet/RazorTooling).
The original thread is here: https://github.com/aspnet/RazorTooling/issues/35

**Comment by NTaylorMullen** [comment]
Talked with @Eilon offline about taking this one for RC2. + @danroth27

**Comment by NTaylorMullen** [comment]
dbe4ce06f2d4dcd3924204ce8bf0673686b5a2a9
