### ISSUE TITLE
Looking for the ChunkTree for the ChunkInheritanceUtility in IMvcRazorHost

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Razor#632]
@NTaylorMullen I moved to `dnx-coreclr-win-x64.1.0.0-rc2-16249` and ...
```
"Microsoft.AspNet.Mvc.Razor": "6.0.0-rc2-16518"
```
... it doesn't like one reference in the @Anderman `IMvcRazorHost` [replacement](https://github.com/Anderman/RazorMinify), apparently removed (or moved) ... I don't see it readily obvious. Were was it moved? ... or was it totally removed?

![capture](https://cloud.githubusercontent.com/assets/1622880/11610254/d75c44c2-9b51-11e5-99c9-305bb7f88e05.PNG)

**Comment by NTaylorMullen** [comment]
Hey @GuardRex it was renamed to `.Root`. See [here](https://github.com/aspnet/Razor/blob/66c9a2184865c57a22cdd05c473d1470c69efe6b/src/Microsoft.AspNet.Razor/Chunks/ChunkTreeBuilder.cs#L24).

**Comment by GuardRex** [comment]
@NTaylorMullen Got it ... `context.ChunkTreeBuilder.Root` ... thanks. cc/ @Anderman

**Comment by NTaylorMullen** [comment]
The `GetInheritedChunkTrees` looks to be defined by the mvc razor host replacement that he wrote. As for your screen shot, the `ChunkTree` property was renamed to `Root` on `ChunkTreeBuilder`. See [here](https://github.com/aspnet/Razor/blob/66c9a2184865c57a22cdd05c473d1470c69efe6b/src/Microsoft.AspNet.Razor/Chunks/ChunkTreeBuilder.cs#L24).

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by GuardRex** [comment]
@NTaylorMullen Side ? if you don't mind: If you're inheriting an interface that's acting like an interface, is it more technically proper to setup the naming of the replacement of the `IMvcRazorHost` as ... (with an `I`)
```c#
public class ICustomMvcRazorHost : IMvcRazorHost
```
... or ... (without an `I` like a normal class)
```c#
public class CustomMvcRazorHost : IMvcRazorHost
```
This falls into one of "Luke's dumb questions" category, but that's ok ... I've embarrassed myself many times on here. I don't think one time is going to matter! :smile:

**Comment by NTaylorMullen** [comment]
We only prefix interfaces with `I`. For implementations we've typically done the interface name minus the I (hence `MvcRazorHost`) OR we prefix `Default` to the name and remove the `I`. A great example of this is `IHtmlGenerator` => `DefaultHtmlGenerator`.

**Comment by GuardRex** [comment]
Ah ... thanks. I get it.
