### ISSUE TITLE
Make @addTagHelper, @removeTagHelper and @tagHelperPrefix optionally accept quotes around their values

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#636]
We made a change to the `addTagHelper`, `removeTagHelper` and `tagHelperPrefix` directives to disallow quotes around their values. This happens to really mess with tooling when using rc1 with rc2+ bits. Not to mention, it doesn't hurt to have quotes. We should allow them optionally like we did in RC1.

/cc @DamianEdwards

**Comment by Eilon** [comment]
1. Let's re-add support for quotes, but make it some kind of warning.
2. Open a bug for RTM to remove all support for quotes.

**Comment by DamianEdwards** [comment]
@NTaylorMullen pls ensure you work with tooling to ensure their RC2 release supports both quotes and without (if anything special is required at all).

**Comment by mikes-gh** [comment]
@NTaylorMullen Yes I noticed VS complains without quotes with squiggly red line after these changes

**Comment by pranavkm** [comment]
@DamianEdwards we haven't added warnings to the editor as part of this change (an API to send warnings isn't available as yet). We silently read and ignore quotes. Do you think this warrants a follow up work item?

**Comment by DamianEdwards** [comment]
I think we should just support both and be done with it. No need for warnings.

**Comment by pranavkm** [comment]
Great, that's how it behaves now.

**Comment by Eilon** [comment]
Do we need to close out any bug that says to remove/alter the warning behavior in the future?

**Comment by pranavkm** [comment]
Nope. All we need to do is delete this comment - https://github.com/aspnet/Razor/issues/636#issuecomment-164605202

**Comment by Eilon** [comment]
Ah ok cool (leave the comment there, just say we didn't do it.)
