### ISSUE TITLE
Microsoft.AspNet.Razor.Runtime.TagHelpers.RuntimeTypeInfoTest.Properties_ReturnsPublicPropertiesOfAdaptingType hangs on CoreCLR on Mac

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Razor#638]
Seeing hang on CI agent.

**Comment by pranavkm** [comment]
The Travis builds seem to be passing just fine: https://travis-ci.org/aspnet/Razor. Where are you seeing this?

**Comment by cesarbs** [comment]
In the CI. Look at the cancelled build in Mac-Universe-CoreCLR.

**Comment by cesarbs** [comment]
This is intermittent btw.

**Comment by NTaylorMullen** [comment]
Is this still an issue?

**Comment by NTaylorMullen** [comment]
I haven't seen this reproduce. Feel free to reopen if you do.
