### ISSUE TITLE
Allow VS to Precompile Razor

### ISSUE THREAD

**Issue by TonyValenti** [aspnet/Razor#641]
Good morning Microsoft!

Right now I have a few challenges with Razor:
1.  CSHTML files are not compiled at compile time.
*  This causes a performance hit the first time the page is accessed.
*  If I have a typo in my code, I have to wait till runtime to discover that.  For example, if I had: 
````
@Model.FirstNane @* <-- FirstName is misspelled*@
````
I have to wait until runtime to test this out and discover that I have an error.
* Refactoring a model's member does not refactor into the CSHTML file.  For example, renaming Model.Name to Model.FullName leaves me with a lot of broken views that I have to Find/Replace/Pray I got them all.

2.  There are a number of times when I've wanted to use Razor for different kinds of non-web content generation.  Email templates are an example.  To do this, I have to use a third-party tool like RazorEngine and deal with a lot of RazorEngine Overhead.  I have to do things like managing embedded resources, etc and it basically creates a lot of mess I have to work with.

3.  I would like to be able to do something like this instead:
````
@class MyApp.Templates.HelloTemplate
@model MyApp.Templates.HelloModel

Hello @Model.FirstName!
````

and then in my code do something like this:
````
var Template = new MyApp.Templates.HelloTemplate();
var Model = new MyApp.Templates.HelloModel { FirstName = "Robert" };
var Output = Template.Execute(Model);
````
and I believe that if Razor supposed precompilation / compile time compilation, that all three would be taken care of at once.

Thanks!

**Comment by mikeandersun** [comment]
I needs somethings like RazorEngine do.Specially:
Rendering an in memory View string, not finding for a file in a certain location.

**Comment by mikeandersun** [comment]
https://github.com/aspnet/Razor/issues/642

**Comment by IlyaKhD** [comment]
It seems to be a good UX improvement if errors and warnings are thrown on project been built.

It's very inconvenient to check all the views after a class been renamed or smth like.

**Comment by Eilon** [comment]
Rendering Razor to a string is tracked here: https://github.com/aspnet/Mvc/issues/3091

As far as pre-compilation goes, there's already support for that today, but we're looking at making improvements and changes in that area. Here's a post I found that shows how to do this: https://mjomaa.com/computer-science/frameworks/asp-net-mvc/158-how-to-enable-precompiled-razor-views-cshtml-in-asp-net-5
