### ISSUE TITLE
TemplateEngine

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Razor#642]
Is is possible to hame something like these template engines in ASP.NET 5 foundation?
http://twig.sensiolabs.org. The flexible, fast, and secure template engine for PHP.
http://freemarker.incubator.apache.org.  A Java library to generate text output (HTML web pages, e-mails, configuration files, source code, etc.) based on templates and changing data.

**Comment by dougbu** [comment]
@mikeandersun this sounds like a MVC question. Suggest moving the issue if it needs further discussion.

In any case, one approach is to create your own `IViewEngine` implementation and add it to `MvcViewOptions.ViewEngines` in a site's `Startup`.

**Comment by mikeandersun** [comment]
It is possible to move it by collaborator permission or i needs to create it in MVC repository?

**Comment by dougbu** [comment]
@mikeandersun just open a new issue in the MVC repo with any further question you have and close this one.

**Comment by mikeandersun** [comment]
move to https://github.com/aspnet/Mvc/issues/3753
