### ISSUE TITLE
Option to bypass GetContent HTML encoding in TagHelper

### ISSUE THREAD

**Issue by khalidabuhakmeh** [aspnet/Razor#643]
The current implementation of `TagHelperContent.GetContent` automatically HTML encodes when called from within the `TagHelper` implementation. Using [Dave Paquette's](http://www.davepaquette.com/archive/2015/11/02/markdown-in-your-mvc-6-razor-pages.aspx) implementation of Markdown `Taghelper`, I am able to reproduce the unexpected behavior of *premature encoding*.

### Implementation

```csharp
[HtmlTargetElement("p", Attributes = "markdown")]
[HtmlTargetElement("markdown")]
[OutputElementHint("p")]
public class MarkdownTagHelper : TagHelper
{
    public async override Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        if (output.TagName == "markdown")
        {
            output.TagName = "p";
        }
        var childContent = await context.GetChildContentAsync();

        // This call to get markdownContent is HTML encoded
        // prematurely and strips meaningful newline characters
        // necessary for the markdown output
        var markdownContent = childContent.GetContent();

        var markdown = new MarkdownSharp.Markdown();
        var htmlContent = markdown.Transform(markdownContent);
        output.Content.SetContentEncoded(htmlContent);
    }
}
```

### Input

```markdown
### Features\r\n\r\n* API namespace cleanup for tag helpers ([#578](https://github.com/aspnet/Razor/issues/578))\r\n* Refactor WriteAttribute API surface. ([#177](https://github.com/aspnet/Razor/issues/177))\r\n\r\n### Bugs Fixed\r\n\r\n* Multiple TagHelpers targeting same element cannot effectively communicate to children. ([#571](https://github.com/aspnet/Razor/issues/571))\r\n* Compilation error within tag attribute shows generated code instead of markup ([#569](https://github.com/aspnet/Razor/issues/569))\r\n* Specifying `RestrictChildren` and empty `HtmlTargetElement` results in an error ([#562](https://github.com/aspnet/Razor/issues/562))\r\n* `TreeStructureChanged` marked as `true` when whitespace is added to a page with `TagHelper`s ([#553](https://github.com/aspnet/Razor/issues/553))\r\n* Expose `FilePath` on `MappingLocation` to let Razor editor know mapping origination. ([#552](https://github.com/aspnet/Razor/issues/552))\r\n\r\n
```

### Expected

![](https://silvrback.s3.amazonaws.com/uploads/239d0f0d-49a3-4652-a8e9-d71993d66c9d/Releases_%C2%B7_aspnet_Razor_large.png)

### Actual

![](https://silvrback.s3.amazonaws.com/uploads/6d73ec35-6f9b-48e4-a4f4-08f9319289a7/Home_Page_-_Site_large.png)

### Proposed Solution

I expect to be able to pull the **exact** contents of the tag element, even if there is content that is *potentially* unsafe at runtime. The responsibility of HTML encoding should be left up to the `TagHelper` developer.

___

http://www.khalidabuhakmeh.com/asp-net-5-mvc-6-taghelpers-and-the-cake

**Comment by DamianEdwards** [comment]
Thanks for the write up. Here's a gist I did to demonstrate the issue too: https://gist.github.com/DamianEdwards/d57810d28d977058e702

**Comment by khalidabuhakmeh** [comment]
I did notice that this *"fixes"* the issue, like you suggested.

```html
<markdown>@(new HtmlString(release.Body))</markdown>
```

It just smells.

![](http://media0.giphy.com/media/mpxvACn6oda7e/giphy.gif)

**Comment by DamianEdwards** [comment]
Yeah this is a layering issue. The Razor parser is emitting code that always evaluates the content inside a Tag Helper as a Razor expression, and thus writes it out that way, which always HTML encodes. I think we need to either:
1. Allow for the Tag Helper to declare that it doesn't want the content encoded
2. Always capture the encoded and unencoded result of the expression then let the Tag Helper get at each via API

**Comment by dougbu** [comment]
@DamianEdwards suggestion 1 is similar to letting tag helpers declare authors should treat the element content like a bound `string` property. As such we'd need some new tooling support.

For suggestion 2, note one issue with concepts such as "encoded and unencoded result of the expression" is the mix of scopes in a `.cshtml` file. There is often no single expression. Even an attribute bound to a `string` property of a tag helper can contain more than just C#. Doubled HTML encoding won't be eradicated.

Separately, binding to a `string` property (instead of using the element body) is _almost_ a workaround for this issue. Except in `<text>` and similar corner cases, nothing is encoded before the tag helper gets it.

**Comment by DamianEdwards** [comment]
@dougbu why would suggestion 1 require tooling support? It's just changing the behavior of contained expressions, not literal content.

**Comment by dougbu** [comment]
> why would suggestion 1 require tooling support? It's just changing the behavior of contained expressions, not literal content.

Because users HTML encode literal content when they're typing in an HTML context.

**Comment by DamianEdwards** [comment]
Example?

**Comment by dougbu** [comment]
`<tagHelper>I love me some &lt;tagHelper&gt;.</TagHelper>`

**Comment by DamianEdwards** [comment]
@dougbu ah yes, of course. A tooling feature isn't a huge deal, and frankly we could ship a version without it. This will be applicable only to very particular Tag Helpers. Let's chat about it in person this week.

**Comment by NTaylorMullen** [comment]
@DamianEdwards and I worked through the implications of this issue and decided that in order to fix this we'll add an overload to `GetChildContentAsync` that takes an encoder. It's not ideal since you'll also have a `GetContent(HtmlEncoder)` overload; the idea behind it is that `TagHelper` rendering has two pieces:
1. Prepare the body to be rendered. This essentially builds out a buffer used to render final content, in cases like `@("<p>This should be encoded</p>")` it needs to execute the code and encode it when preparing. - `GetChildContentAsync`
1. Render the body with the specified encoder. - `GetContent`

Both parts need the encoder.

**Comment by dougbu** [comment]
@NTaylorMullen please loop in @Eilon on these conversations or talk to me about it tomorrow. What you're suggesting will be incorrect in at least some cases e.g. literal text between the start and end tags. Note as well that this approach assumes _all_ encoding is deferred until `GetContent(HtmlEncoder)` (ick) is called.

**Comment by NTaylorMullen** [comment]
@dougbu I think you misunderstood the suggestion.

> Note as well that this approach assumes all encoding is deferred until GetContent(HtmlEncoder) (ick) is called.

The suggested approach does not defer all encoding. Anything that is `@_____` (aka `RazorPage.WriteTo` where the value is not a `string` and not an `IHtmlContent` will be encoded with the encoder passed to `GetChildContentAsync`. Therefore, to get the "raw" value of the body users would be able to pass in no-op encoders into `GetChildContentAsync` and `GetContent` methods.

**Comment by dougbu** [comment]
> suggested approach does not defer all encoding

Huh? It assumes everything inside that `@` expression has not yet been encoded -- that's deferral.

The approach also assumes literal strings contain neither characters that are already encoded `&lt;tag&gt;` nor characters that need to be encoded `<tag>`, depending on how the `.cshtml` author _thought_ it would be handled.

**Comment by NTaylorMullen** [comment]
> Huh? It assumes everything inside that @ expression has not yet been encoded -- that's deferral.

Oh, I wouldn't consider that deferred. That's just how Razor has always worked. Anything after `@` is run through `WriteTo` which may or may not encode the value. In this new case, it'd just use a different encoder IF it decided a value should be encoded.



> The approach also assumes literal strings contain neither characters that are already encoded &lt;tag&gt; nor characters that need to be encoded <tag>, depending on how the .cshtml author thought it would be handled.

It's just Razor, it doesn't make any assumptions, I'm not seeing how this is different than classic Razor. If you want your stuff to not be encoded and its a string, wrap it in `@Html.Raw`.

**Comment by Eilon** [comment]
@dougbu please also add to this bug the final decisions that were made when you met with @DamianEdwards and @NTaylorMullen so that we can track those here.

**Comment by dougbu** [comment]
@DamianEdwards, @NTaylorMullen and I talked about this before the :snowman::gift:Days of Quietude:fireworks::tada:

As I remember it, we all recognize literal text in the element's body involves lots of odd cases e.g. when the `.cshtml` author types in `&lt;`. But @DamianEdwards wants to provide an escape hatch that disables _further_ encoding, with lots of warnings glowing around it.

So we'll go with what @NTaylorMullen described [above](https://github.com/aspnet/Razor/issues/643#issuecomment-164583274):
> an overload to `GetChildContentAsync` that takes an encoder

Ideally we'd also have Tooling support of some kind -- something to let the `.cshtml` author know they're not in a regular HTML context.

But I won't be doing the work this year and this extends the `ITagHelper` API. :ok: to do in January?

**Comment by Eilon** [comment]
I'm cool with this. @DamianEdwards please confirm.

**Comment by DamianEdwards** [comment]
:+1:

**Comment by dougbu** [comment]
- 37850b5
- aspnet/Mvc@2810858

**Comment by DFieldhouse** [comment]
The way to get the raw content is like this:

    var markdown = (await output.GetChildContentAsync(NullHtmlEncoder.Default)).GetContent(NullHtmlEncoder.Default);
