### ISSUE TITLE
Version 4.0.0-rc1-final doesn't work when targeting dnxcore50

### ISSUE THREAD

**Issue by lourian** [aspnet/Razor#644]
I am using Microsoft.AspNet.Razor to implement simple templating engine for my project.
I installed Microsoft.AspNet.Razor 4.0.0-rc1-final via NuGet.
I added dnxcore50 framework to "frameworks" section of my project.json.
Now I can't build project and I have an error:
"Type or namespace AspNet doesn't exist in namespace Microsoft"

**Comment by NTaylorMullen** [comment]
@lourian I created a pure `dnxcore50` project with rc1-final and it worked. Could you try the following:

1. Delete %UserProfile%/.dnx/packages
1. Delete %LocalAppData%/dnu/cache
1. At the root of your project run `dnu feeds list` and ensure you only have nuget.org as a feed
1. Remove all `project.lock.json` files from your project.

**Comment by pranavkm** [comment]
What version of DNX are you using? (`dnvm list`) should tell you this.

**Comment by NTaylorMullen** [comment]
In VisualStudio it's defined in your `global.json`, and if not there it's the `default` aliased DNX.
