### ISSUE TITLE
Breaking changes in FindPartialView rc1 to rc2

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Razor#645]
Given this working code in RC1

```
 public class HtmlViewRenderer
    {
        public string RenderViewToString(Controller controller, string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = controller.ActionContext.ActionDescriptor.Name;

            controller.ViewData.Model = model;

            using (StringWriter sw = new StringWriter())
            {
                var engine = controller.Resolver.GetService(typeof(ICompositeViewEngine))
                    as ICompositeViewEngine;
                ViewEngineResult viewResult = engine.FindPartialView(controller.ActionContext, viewName);

                ViewContext viewContext = new ViewContext(
                    controller.ActionContext,
                    viewResult.View,
                    controller.ViewData,
                    controller.TempData,
                    sw,
                    new HtmlHelperOptions() //Added this parameter in
                );

                //Everything is async now!
                var t = viewResult.View.RenderAsync(viewContext);
                t.Wait();

                return sw.GetStringBuilder().ToString();
            }
        }
    }
```

In RC2  1.0.0-*

FindPartilaView no longer exists
I guess we now use FindView which also has a last parameter IsMaster.= false ?

The Intelisense still says first parameter for FindView is an ActionContext but ActionContext seems to now removed from controller and we should use ControllerContext?  This works.  Maybe its just the itellisense is wrong.

Also in the above code controller.ActionContext needs to be replaced with controller.ControllerContext.

**Comment by dougbu** [comment]
The `ICompositeViewEngine` and `IViewEngine` interfaces changed significantly in RC2. We did not announce the MVC (note: not Razor) changes because we did not expect extensive use of this API. But please see issue aspnet/Mvc#3307 and PR aspnet/Mvc#3380, especially the PR to see the new usage pattern.

**Comment by mikes-gh** [comment]
OK as far as I know there is quite a few people using it to render html for emails and for html to pdf conversion (thats quite a popular space) so it may be worth telling people.

**Comment by Eilon** [comment]
@mikes-gh due to the limited audience for this change we decided to forego an announcement so as to avoid creating noise for most people.
