### ISSUE TITLE
TagHelpers doesn't run in script tag?

### ISSUE THREAD

**Issue by evorine** [aspnet/Razor#646]
I think TagHelpers are not working in `<script>` tags by default. I could not find any documentation about how to make them work.

So the problem is when using JsRender library, we define html templates in `<script type="text/x-jsrender"></script>` tags.
Something like:
```
<script id="foo" type="text/x-jsrender">
    {{if Type == 'foo'}}
    <span>foo</span>
    {{/if}}

    <translate>Hello</translate>
</script>
```
Here we need TagHelpers in `<script>` tag.

**Comment by NTaylorMullen** [comment]
If you change the script tag "type" to `text/html` then you will have `TagHelper`s working inside of `Script` tags. The reason why we don't enable them otherwise is because we don't want `TagHelper`s to inaccurately change JavaScript content.

**Comment by evorine** [comment]
Type `text/x-jsrender` is not declaring a JavaScript content so there will be no JavaScript in that tag like in type `text/html`. I think `text/x-jsrender` should be treated the same way as `html/text`.
And there are lot more types 

I just wanted to write my `<script>` tag in a proper way. If those types is not going to be added/supported, I will change them into `text/html` as you suggested.

**Comment by NTaylorMullen** [comment]
@evorine Sorry, adding an `x-*` exception to Razor would be too specific because we wanted know if the type allowed HTML or did not. As a work around try adding a TagHelper for the script tag under a different name:

```C#
[OutputElementHint("script")]
public class XJSScriptTagHelper : TagHelper
{
    public override void Process(...)
    {
        output.TagName = "script";
        output.Attributes["type"]="text/x-jsrender";
    }
}
```

Your code would then become:
```HTML
<xjs-script id="foo">
    {{if Type == 'foo'}}
    <span>foo</span>
    {{/if}}

    <translate>Hello</translate>
</xjs-script>
```

This approach should then make your design-time and runtime experience work :smile:

**Comment by evorine** [comment]
@NTaylorMullen Indeed, this is a great solution. ;)
