### ISSUE TITLE
No intellisense for TagHelpers

### ISSUE THREAD

**Issue by obryckim** [aspnet/Razor#654]
I am not getting any intellisense for tag helpers.  I have seen other issues regarding this and have ensured the following in my project:

project.json contains `"Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final"`
_ViewImports.cshtml contains `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"`

![intellisense screenshot](https://cloud.githubusercontent.com/assets/11857283/12148397/29943334-b46c-11e5-8bb3-af6aa42c15ad.png)

The tag helpers are working, though.  When I manually enter them, the text changes in the editor and the proper HTML is generated in the browser.
![intellisense screenshot 2](https://cloud.githubusercontent.com/assets/11857283/12148460/91b671e8-b46c-11e5-9bd6-09cc029e687d.png)

Here is my full project.json: [project.txt](https://github.com/aspnet/Razor/files/80104/project.txt)

My VisualStudio information: [VSInfo.txt](https://github.com/aspnet/Razor/files/80087/VSInfo.txt)

**Comment by NTaylorMullen** [comment]
Very interesting. Moving this over to aspnet/Tooling.

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Tooling#360
