### ISSUE TITLE
Usage in class libraries

### ISSUE THREAD

**Issue by gregbty** [aspnet/Razor#656]
There are issues https://github.com/aspnet/Mvc/issues/3199 and https://github.com/aspnet/Mvc/issues/3091, but these deal with rendering views while within the ASP.NET context. I want to be able to use Razor as a templating system external to ASP.NET.

I have used the same techniques as https://github.com/aspnet/Diagnostics/blob/dev/src/PageGenerator/Program.cs, but this only deals with generating a class file based on the Razor file. I also want to be able to compile and run the generated file and use it at runtime. Is this currently possible? Are there are any examples of this?

Also I seem to lose access to the model directive (at least the intellisense). Is this only available in an ASP.NET project, or is there a way to enable it for other project types?

**Comment by NTaylorMullen** [comment]
@ajaybhargavb I tried looking for your WIP sample. You could shed light here :smile:

**Comment by ajaybhargavb** [comment]
We are currently doing some work on this. But currently it does involve MVC so that the features like layouts, partials and tag helpers can still be supported when a view is rendered to a string even when no request is present. As for the 'Razor as a templating system' scenario, we are still discussing what kind of support we want to provide.

**Comment by gregbty** [comment]
If I only need to support for the bare minimum (i.e. strong typed html rendering) without any of the items you mentioned, is there any quick and dirty example I can look at?

**Comment by gregbty** [comment]
I was able to figure it out by looking more closely at the implementation detailed in the MVC project. Thanks.
