### ISSUE TITLE
Change to build to use dotnet

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Razor#657]
At a minimum, you have to upgrade a few scripts and project.json files just like here: aspnet/Configuration@9cfd22f

I think the interesting part is the view compilation here

**Comment by victorhurdugaci** [comment]
@pranavkm fixed?

**Comment by pranavkm** [comment]
Yup. Fixed in https://github.com/aspnet/Razor/commit/9c6e5f714a57754589b982519453c72a1647fb91
