### ISSUE TITLE
Razor fails to execute generic expression methods

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#66]
Ex in a Razor file:

```
@Component.Invoke<FooViewComponent>()
```

This fails because the parser believes that ```<FooViewComponent>``` is an html tag.

The fix for this definitely needs discussion because there could be cases where a user wants to do something like:

```
@SomeName<p>()</p>
```

**Comment by yishaigalatzer** [comment]
We are not planning to make a change here. And this is not a regression from Razor 3
