### ISSUE TITLE
@addTagHelper fails when attempting to reference an assembly from the GAC

### ISSUE THREAD

**Issue by rickandersen** [aspnet/Razor#681]
The @addTagHelper directive fails when attempting to reference an assembly that is in the Global Assembly Cache with the error message:

`Cannot resolve TagHelper containing assembly '<AssemblyName>'. Error: Could not load file or assembly '<AssemblyName>' or one of its dependencies. The system cannot find the file specified.
@addTagHelper "*, <AssemblyName>"`

**Comment by NTaylorMullen** [comment]
@rickandersen could you try and `Assembly.Load` the assembly in question in a console application? That's all `TagHelper` resolution is doing at its core.

**Comment by rickandersen** [comment]
The Assembly.Load works when I provide the full name of the assembly (ie <AseemblyName>, Version=1.0.0.0, Culture=neutral, PublicKeyToken=<PublicKeyToken>), but I am unable to specify the full name in the @addTagHelper directive as that throws a compilation error.

I am using the assembly in other areas of the app so I am sure it is referenced properly in the project.

**Comment by NTaylorMullen** [comment]
It does not work if you use the non fully qualified name though?

**Comment by rickandersen** [comment]
Correct.  Without the fully qualified name I receive this exception:

`An exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll but was not handled in user code`

**Comment by Eilon** [comment]
I don't think we intend to support loading tag helper assemblies from the GAC.
