### ISSUE TITLE
Hide attribute intellisense for a taghelper

### ISSUE THREAD

**Issue by alansangeeth** [aspnet/Razor#686]
what if i don't want to show attribute intellisenses for a taghelper eventhough i have set HtmlAttributeName attribute to the corresponding class properties?

For example:
``` c#
[HtmlAttributeName("testTag")]
public Class TestClass: TagHelper{

  [HtmlAttributeName("testProp")]
  public string testProp{get;set;}
}
```

Here for "testTag" element i don't want to show "testProp" atttribute and some more similar attributes.
The element tag only should present with

**Comment by NTaylorMullen** [comment]
If you want to hide HTML IntelliSense for a `TagHelper`s attribute or tag name you can decorate the corresponding `TagHelper` class/property with `[EditorBrowsable(EditorBrowsableState.Never)]`. Mvc does this for the `UrlResolutionTagHelper`.

**Comment by alansangeeth** [comment]
In my case, i have two tagHelper elements on same class. I don't want to show the properties as attributes for one taghelper element but for other taghelper element it should show the properties as attributes.

**Comment by NTaylorMullen** [comment]
You'd have to split that into two separate classes to get that effect.

**Comment by alansangeeth** [comment]
Now, i have created a separate class with multiple target element.. 

For instance lets take the below code example.
`
 [HtmlTargetElement("CustomTag1",ParentTag ="ParentTag"), 
HtmlTargetElement("CustomTag2", ParentTag ="ParentTag"),RestrictChildren(" "ChildCustomTag1",new string[] { "ChildCustomTag2" })]
public class TestCollection{

}

[HtmlTargetElement("ChildCustomTag2",ParentTag ="CustomTag2")]
public class ChildCustomTag2{

}

`

So in view page under "CusomTag1" element ,"ChildCustomTag2" is showing in intellisense..its wrong.. Actually the intellisense should not have shown since the parentTag of "ChildCustomTag2" is not "CustomTag2" or RestrictChildren attribute should be applicable for each target element instead of to the class/

**Comment by NTaylorMullen** [comment]
@alansangeeth In the example you provided the current tooling does not support the `ParentTag`/`RestrictChildren` hiding of IntelliSense. We do have fixes for these in RC2 however. Hopefully with the next release you'll see your scenario light up as you expect in IntelliSense.

**Comment by alansangeeth** [comment]
@NTaylorMullen  Thanks for the information. I need another clarification regarding implementing TagHelper in derived class. I have a derived class which is derived from another class, not an interface and now how to implement Taghelper to derived cass since we cannot inherit more than one class.

**Comment by dougbu** [comment]
@alansangeeth you can implement `ITagHelper` yourself. The `TagHelper` base is just for convenience.

**Comment by NTaylorMullen** [comment]
You can see how simple the TagHelper class is [here](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Runtime/TagHelpers/TagHelper.cs).

**Comment by Eilon** [comment]
Any further action required here or are the current questions answered?

**Comment by alansangeeth** [comment]
If i define TagHelper for a class with Multiple constructors, it throws exception as "Multiple constructors accepting all given argument types have been found". Is there a way to avoid this with multiple constructors?

**Comment by NTaylorMullen** [comment]
@alansangeeth Only way would be to make one private and create an alternative static method like `MyTagHelper.Create(x,y,z)` that delegated to a private ctor.
