### ISSUE TITLE
Unquoted TagHelper attribute values with `=` in their value cause Debug.Assert failure.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#698]
If we have a `TagHelper`.

```HTML
<myth name=something=value key="@value" />
```

You get a debug assert [here](https://github.com/aspnet/Razor/blob/5ca09d0b1020c0bef535d4121def9d3a48b463d0/src/Microsoft.AspNetCore.Razor/Parser/TagHelpers/TagHelperBlockRewriter.cs#L208).

**Comment by dougbu** [comment]
@NTaylorMullen your example is invalid. Is this about catching the HTML syntax violation earlier?

The [HTML 5 spec](https://www.w3.org/TR/html5/syntax.html#attributes-0) says unquoted attribute values:
> must not contain any literal space characters, any U+0022 QUOTATION MARK characters ("), U+0027 APOSTROPHE characters ('), "=" (U+003D) characters, "<" (U+003C) characters, ">" (U+003E) characters, or U+0060 GRAVE ACCENT characters (`), and must not be the empty string.

**Comment by NTaylorMullen** [comment]
@dougbu It's definitely invalid, however it shouldn't crash the parser :smile:. Instead of `Debug.Assert`ing we should be logging an error to the `ErrorSink`.

**Comment by dougbu** [comment]
Well, it won't crash the parser in release mode :smiling_imp:

Thanks for the clarification.
