### ISSUE TITLE
Razor Intellisense gets out of touch with reality

### ISSUE THREAD

**Issue by NoneGiven** [aspnet/Razor#700]
```
The type 'Expression<>' is defined in an assembly that is not referenced.
You must add a reference to assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

So says Visual Studio, and red squigglies appear over much of the C# code in my Razor view which is using lambdas in an HTML helper. And yet, everything builds just fine and there are no runtime errors when the helper is executed. This issue appeared out of the blue with no related to the view or the assemblies it thinks it can't find, and while it doesn't introduce build or runtime errors, it makes editing the view in question a pain because Intellisense including suggestions/auto-complete remains broken for those lines of code allegedly affected.

I am experiencing this in a large project with lots of dependencies and it's not unexpected for Intellisense to slow down and get confused along the way. The thing is, elsewhere in the project, Intellisense figures out when it's wrong eventually and stops painting red squigglies everywhere. Not so with Razor: it takes a complete solution delete and re-get from source control to make this issue go away.

So while I don't have any more info that could help reproduce this issue (again, very large project with lots of potential for crossed wires), my suggestion is, please audit whatever mechanisms the Intellisense is using to keep up-to-date with reality and find out where those two branches of the universe might diverge.

Or, add some kind of recovery mechanism whereby Razor's Intellisense will occasionally double-check to make sure its deeply rooted cache of information is actually correct, and spare me the trouble of having to wipe it all out and start over just to get rid of red squigglies.

**Comment by davidfowl** [comment]
What version of Razor is this? Is this ASP.NET Core? Or something else?

**Comment by NoneGiven** [comment]
It didn't occur to me look. Now I see it's v2.0.0.0. Whoops.
