### ISSUE TITLE
Allow multiple section with the same name to be defined

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Razor#702]
Lets say i would like to put all my scripts in the bottom of page and i have lot of view component. It will be nice if we can declare section "script" for example on each view component and it will be rendered on where RenderSection("script") called on layout page.

**Comment by Eilon** [comment]
View components cannot have section content that "bubbles up" to the calling page.

In this scenario I recommend building a data model of which script elements you wish to include (e.g. an array of strings), and each view component could add to that list, and then the layout page (or whatever) could read that list of script elements and render them out.

Would that work for you?

**Comment by andrew-vandenbrink** [comment]
@Eilon This is the dirty way to append to section
```
Microsoft.AspNet.Mvc.Razor.RenderAsyncDelegate x;
var debug = SectionWriters.TryGetValue("Navigation",out x);
x += (async xx =>
 {
        await Task.Run(() => xx.Write("xx"));
 });
SectionWriters["Navigation"] = x;
```

Which means I can also pass this SectionWriters object to the ViewComponent

My problem at this moment with this approach is that I losing all the tool support when writing script (intellisense,etc2)

Is there some way to have official api to add/append to section?
or make string inside c# code to have html/script tooling support?

**Comment by andrew-vandenbrink** [comment]
@Eilon Found the way

```
Func<dynamic,dynamic> b =
        @<strong>aaa
    </strong>;//Tooling support wohoo!
    
    SectionWriters["Navigation"] += (async xx =>
    {
        await Task.Run(() =>
        {
            b("").WriteTo(xx, Microsoft.Extensions.WebEncoders.HtmlEncoder.Default);
        });
    });
```

Is there any cleaner way than this?

**Comment by andrew-vandenbrink** [comment]
```
public static class PageExtension
    {
        public static void AppendSection(this IDictionary<string, RenderAsyncDelegate> args, string key, Func<dynamic, dynamic> text)
        {
            if (!args.ContainsKey(key))
            {
                args.Add(key, (async textWriter =>
                {
                    await Task.Run(() =>
                    {
                        text("").WriteTo(textWriter, Microsoft.Extensions.WebEncoders.HtmlEncoder.Default);
                    });
                }));
            }
            else {
                args[key] += (async textWriter =>
                 {
                     await Task.Run(() =>
                     {
                         text("").WriteTo(textWriter, Microsoft.Extensions.WebEncoders.HtmlEncoder.Default);
                     });
                 });
            }
        }
    }
```

```
 SectionWriters.AppendSection("Navigation",@<strong>
    bbb
</strong>);
```

looks good?

**Comment by Eilon** [comment]
Hmm the code you're showing there is not really supported. The SectionWriters dictionary should not be modified (or even observed) by anything except for the Razor page implementation using the DefineSection and similar APIs. I admit you've come up with some pretty clever tricks, though :smile:

**Comment by Eilon** [comment]
I'm putting this in the backlog for future consideration. We're trying to shut down on new features as much as possible right now. For this feature we'd want to carefully consider the scenarios as well as possible error cases (e.g. how do you order the multiple sections? what happens if there are zero sections with the name?)

**Comment by andrew-vandenbrink** [comment]
The order of sections just like queue, top to bottom

Above code may produce strange files due Task.Run and delegate is not so friendly with each other, 

this one more stable
```
 public static void AppendSection(this IDictionary<string, RenderAsyncDelegate> args, string key, Func<dynamic, dynamic> text)
        {
            if (!args.ContainsKey(key))
            {
                args.Add(key, (async textWriter =>
                {                    
                    await text("").WriteAction(textWriter);                  
                }));
            }
            else {
                args[key] += (async textWriter =>
                 {
                     await text("").WriteAction(textWriter);                    
                 });
            }
        }

        public static void AppendSection(this IDictionary<string, RenderAsyncDelegate> args, string key, Task<IHtmlContent> contentTask)
        {
            if (!args.ContainsKey(key))
            {
                args.Add(key, (async textWriter =>
                {
                    var content = await contentTask;
                    content.WriteTo(textWriter, Microsoft.Extensions.WebEncoders.HtmlEncoder.Default);                                       
                }));
            }
            else {
                args[key] += (async textWriter =>
                {
                    var content = await contentTask;
                    content.WriteTo(textWriter, Microsoft.Extensions.WebEncoders.HtmlEncoder.Default);                   
                });
            }
        }  
```

Usage
```

this.SectionWriters.AppendSection("sectionName",@<script>
</script>
);

SectionWriters.AppendSection("sectionName", Html.PartialAsync("PartialViewName"));


```

**Comment by rynowak** [comment]
We have no plans to do
