### ISSUE TITLE
Pre-allocate TagHelper attributes that are String typed, bound but not complex.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#704]
In issue #600 we did the work to pre-allocate unbound non-complex `TagHelper` attributes. We could do the same work for bound attributes that are of type `string` and are not complex. This would save us the extra `TagHelperAttribute` allocation's that are used to fill `TagHelperContext.AllItems`.

For instance, in our `BasicViews` performance scenario there's only a single unbound `TagHelper` attribute but there are tons of bound, string based attributes.

**Comment by NTaylorMullen** [comment]
@mnltejaswini @rynowak This is the issue we talked about briefly last week. After looking at what it'd take to accomplish this I'd rate it as a relatively small-medium change as far as line count goes. However, a medium-large change in terms of context needed.

Up to you if you want to take a stab at it (of course if you do i'd help with the context part).

**Comment by Eilon** [comment]
I'm moving to post-RTM.
