### ISSUE TITLE
Track TagHelperAttribute quotes

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#705]
This would enable `TagHelper` users to write things like `<input type=checkbox />` and have it output the identical code; whereas today we output `<input type="checkbox" />`.

This change would actually have a significant perf impact as well. Today in `TagHelperOutput` we have to [write an attribute to an intermediate writer](https://github.com/aspnet/Razor/blob/a3e92ab3f9656a6f2bd7504a94aa446918e62d50/src/Microsoft.AspNetCore.Razor.Runtime/TagHelpers/TagHelperOutput.cs#L316-L323) to potentially escape any double quotes in the case that a user wrote `<input type=' """" ' />` since we always output with double quotes.

This intermediate writing step in my tests have represented over 5% of allocations.

![image](https://cloud.githubusercontent.com/assets/2008729/13439271/936486fa-dfa1-11e5-99b6-d4d285865d96.png)

**Comment by Eilon** [comment]
Is preserving the non-quotes actually important?

Also, what happens if a Tag Helper modifies that attribute? Does it "gain" the quotes after it's modified? E.g. let's say in my Tag Helper I set `OutputTags["type"] = "this has spaces";` (or whatever the syntax is). Does it render `<input type=this has spaces />` or `<input type="this has spaces" />`?

**Comment by NTaylorMullen** [comment]
Actually, with the new immutability of `TagHelperAttribute`s the unquoted scenario isn't an issue. For instance, if a `TagHelper` author were to do `output.Attributes.SetAttribute("type", "...")` they'd be saying "create a new `TagHelperAttribute` with name `type` and value `...`" which would default to using a double quoted value. If they instead used the `string name, TagHelperAttribute attribute` overload they'd have the option of using their own quoting.

**Comment by NTaylorMullen** [comment]
e14f4b095d0bd4c5a5ae079f817f9a07217907af
https://github.com/aspnet/Mvc/pull/4587/commits/cfd58f17476df9bd296a3e50f519f570e0952877
