### ISSUE TITLE
Consider not tracking TagHelper bound attributes in Context.AllAttributes

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#706]
Today whenever a user has a `TagHelper` bound attribute we allocate a `TagHelperAttribute` for it and push it into `Context.AllAttributes`. We've yet to make use of their existence in `Context.AllAttributes` and in the case that a `TagHelper` author truly wants to know the value of an attribute added by another `TagHelper` they can also bind it to gain access to its value.

This would be a more impactful replacement for https://github.com/aspnet/Razor/issues/704 and is mutually exclusive.

**Comment by Eilon** [comment]
This is by design.
