### ISSUE TITLE
[Question] Which tags and Html attributes can write "~/"

### ISSUE THREAD

**Issue by John0King** [aspnet/Razor#708]
In Razor  :
 Which tags and attributes can write `"~/" ` ?  and when do we need to write `@Url.Content("~/")` ?
what are the rules?

**Comment by NTaylorMullen** [comment]
You can see the criteria in the `UrlResolutionTagHelper` [here](https://github.com/aspnet/Mvc/blob/e39cbf077c47d5ebc6bd705de547644eb3ddf5c8/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L24-L52).
