### ISSUE TITLE
Cannot resolve TagHelperDesignTimeDescriptors in CoreCLR

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#709]
The impact of this bug is not having `<summary>` IntelliSense in the Razor editor.

Problem: `RazorTooling` currently only compiles for CoreCLR/netstandard and Razor `ifdefs` the design time descriptor code to only run in net45 (how it used to run).

We need to find a way to locate XML locations for assemblies in CoreCLR to make this possible.

**Comment by Eilon** [comment]
Sorry, didn't feel like creating a new `taskbughancement` label :smile:

**Comment by ToddGrun** [comment]
Taylor, will this also fix the missing OutputElementHint info?

**Comment by NTaylorMullen** [comment]
Yes this will also fix that since it exists on the design time descriptor.

**Comment by NTaylorMullen** [comment]
3d0bf621f330ad5444a5892505dc4792aa14ad03
