### ISSUE TITLE
razor without temporary files

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Razor#711]
Please consider providing away to generate razor compiled templates without the need to generate temporary files; eg. take template - generate code - compile code - execute all from memory

it would also be good if the resulting generated code to accept a stream; so that when rendering large documents these can be output to a stream directly.

**Comment by davidfowl** [comment]
> Please consider providing away to generate razor compiled templates without the need to generate temporary files; eg. take template - generate code - compile code - execute all from memory

This is already possible with roslyn.

**Comment by grahamehorner** [comment]
oh, don't know that :D any examples of this, I'm trying to dynamically build emails without generating temporary files on disk

**Comment by Eilon** [comment]
@grahamehorner does this do what you want? https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

**Comment by Eilon** [comment]
Moving to Backlog because at this time we are not planning to change this. With the switch to .NET CLI, most things do require some disk access because that's where the C# compiler finds its source files, so this would be difficult to avoid.

**Comment by grahamehorner** [comment]
@Eilon I'll review and give feedback; I'm looking/hoping to be able to build/compile a RazorView template from a input stream (database or blob store) and output the compiled template to a stream (memory) without any use of temporary files/disk activity.

**Comment by Eilon** [comment]
@grahamehorner if you use Roslyn directly you could certainly do this without any temp files. Razor itself doesn't write anything to disk *ever*. It's just MVC's RazorViewEngine that needs to take the processed Razor and compile the C# into a DLL it can run, and today with .NET CLI that requires writing it to disk.

**Comment by Eilon** [comment]
Closing because this should already be the case with the above mentioned sample.
