### ISSUE TITLE
System.Threading.Tasks dep mismatch for Razor 

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Razor#718]
This might just be due to churn right now, but I mostly have one of my test apps working for `netcoreapp1.0` (standalone style), but I get this exception when requesting a View ...
```
Assembly 'Microsoft.AspNetCore.Mvc.Razor' with identity 'Microsoft.AspNetCore.Mvc.Razor, 
Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 
'System.Threading.Tasks, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 
which has a higher version than referenced assembly 'System.Threading.Tasks' with identity 
'System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
![capture](https://cloud.githubusercontent.com/assets/1622880/13905763/37e01774-ee86-11e5-98ce-47ec4460362a.PNG)

Resolved Razor: `"Microsoft.AspNetCore.Mvc.Razor/1.0.0-rc2-20270"`

```
.NET Command Line Tools (1.0.0-beta-001840)

Product Information:
 Version:     1.0.0-beta-001840
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

![capture1](https://cloud.githubusercontent.com/assets/1622880/13905801/54f3a046-ee87-11e5-95b8-9e099f930b7d.PNG)

```json
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
"runtimes": {
    "win8-x64": {},
    "win10-x64": {}
},
```
[EDIT] Explicitly adding ...
```json
"System.Threading.Tasks": "4.0.11-*"
```
to the app's `project.json` deps doesn't help.

**Comment by NTaylorMullen** [comment]
Hey @GuardRex could you provide a repro project for me to poke around in?

**Comment by GuardRex** [comment]
Sure ... I'll put one up in a few hours and ping u back. Thx.

**Comment by GuardRex** [comment]
@NTaylorMullen Almost there ... I've narrowed it down to some kind of problem with a NuGet package that I created and added to the main project. Here's the `project.json` for the package  ...
```json
{
    "authors": [ "GuardRex" ],
    "compilationOptions": {
        "preserveCompilationContext": true
    },
    "copyright": "Copyright 2016 GuardRex Corporation. All Rights Reserved.",
    "dependencies": {
        "NETStandard.Library": "1.0.0-*",
        "System.Net.Http": "4.0.1-*",
        "System.Net.Security": "4.0.0-*",
        "System.Net.Sockets": "4.1.0-*"
    },
    "description": "Email NuGet package",
    "frameworks": {
        "netcoreapp1.0": {
            "imports": [ "dnxcore50", "portable-net45+win8" ]
        }
    },
    "runtimes": {
        "win8-x64": {},
        "win10-x64": {}
    },
    "version": "1.0.0"
}
```
The lock file has no reference to `4.0.10` of `System.Threading.Tasks` ... and neither does the main project for that matter. Both lock files only contain references to `4.0.11-xxxx` versions. That's all I know thus far. I'll clarify what each is calling for tomorrow morning.

I'm still working on whittling the main project and the package down to the absolute minimum necessary to repro the issue, and I'll put both of them up tomorrow morning when I have the most minimal pair of projects. Standby ...

**Comment by GuardRex** [comment]
@NTaylorMullen I was able to narrow this down to a nice, small repro pair of the app and the package.

##### The Package `razor_issue_pkg`
```json
"dependencies": {
    "NETStandard.Library": "1.0.0-*",
    "System.Net.Http": "4.0.1-*"
},
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
"runtimes": {
    "win8-x64": {}
}
```
The `System.Net.Http` package must be present for the issue to repro.

##### The application `razor_issue_app`
```json
"dependencies": {
    "razor_issue_pkg": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.Razor": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "NETStandard.Library": "1.0.0-*"
},
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
"runtimes": {
    "win8-x64": {}
}
```
The `razor_issue_pkg` package must be present for the issue to repro.

This repros at `localhost` via Kestrel. The exception is ...
```
Assembly 'Microsoft.AspNetCore.Mvc.Razor' with identity 'Microsoft.AspNetCore.Mvc.Razor, 
Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 
'System.Threading.Tasks, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 
which has a higher version than referenced assembly 'System.Threading.Tasks' with identity 
'System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
There is **no** mention of `System.Threading.Tasks` version `4.0.10` in either lock file.

Package: https://github.com/GuardRex/razor_issue_pkg
Application: https://github.com/GuardRex/razor_issue_app

The feed for the package in the app is set to ...
```
<add key="LocalPkg" value="C:\_APPLICATIONS\razor_issue_pkg\bin\Release" />
```
... In `NuGet.config`.

My CLI is still ...
```
.NET Command Line Tools (1.0.0-beta-001840)

Product Information:
 Version:     1.0.0-beta-001840
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by Eilon** [comment]
@davidfowl I think this is what we were talking about, no?

**Comment by GuardRex** [comment]
This also repros with TFM's of ...

Package: `netsandard1.5`
Application: `netstandardapp1.5`

**Comment by GuardRex** [comment]
I can get normal behavior back if I revert to ...

##### Package
```json
"dependencies": {
    "NETStandard.Library": "1.0.0-rc2-23826",
    "System.Net.Http": "4.0.1-beta-23516"
},
"frameworks": {
    "netstandard1.5": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
"runtimes": {
    "win8-x64": {}
},
```

##### Application
```json
"dependencies": {
    "razor_issue_pkg": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-20114",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-20114",
    "Microsoft.AspNetCore.Mvc.Razor": "1.0.0-rc2-20114",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-20114",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-20114",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-20114",
    "NETStandard.Library": "1.0.0-rc2-23826"
},
"frameworks": {
    "netstandardapp1.5": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
"runtimes": {
    "win8-x64": {}
},
```
![capture](https://cloud.githubusercontent.com/assets/1622880/13938045/276aed9a-ef87-11e5-8676-d068d5c6e2ed.PNG)

**Comment by davidfowl** [comment]
It's likely the downgrade issue.

**Comment by GuardRex** [comment]
@ericstj Did your commit https://github.com/dotnet/corefx/commit/0f268ed1079c182d71cdf49cde3f339a01d67863 become available this morning (3/23/2016, Wed, 7:30am PST)? I did get a large number of new packages (99 pkgs I think) this morning for the repro package/app and upgraded my `dotnet cli` to -1937, but sadly :cry: I'm still getting the same result shown in my OP.

**Comment by ericstj** [comment]
You're using a mix of old and new CoreFx packages in this project.  ASP.NET would be referencing some newer packages then you are directly referencing an old NETStandard.Library: `1.0.0-rc2-23826`.

You need to get on latest for both.  You can double check the lock file to make sure you have a consistent set of packages referenced.

**Comment by GuardRex** [comment]
@ericstj I'm closing here. I opened this in the wrong spot, and I'm sorry for cross-discussing the same problem in https://github.com/aspnet/dnx/issues/3378.
