### ISSUE TITLE
Enable skipped code gen test on mono.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#726]
Currently skipping the CSS Required attribute selector test on mono due to [this](https://bugzilla.xamarin.com/show_bug.cgi?id=39951) issue.

Once the mono issue is fixed we can re-enable test disabled [here](https://github.com/aspnet/Razor/commit/d62343ade5de1d8bafdaba4f2d6716bed5555de1).

**Comment by Eilon** [comment]
Nope.

**Comment by NTaylorMullen** [comment]
Hmm? If we don't want to enable the skipped code gen test for mono why run the tests on mono at all?

**Comment by Eilon** [comment]
We won't 😄 We'll have tasks to remove the Mono tests.
