### ISSUE TITLE
HTML-style comments are still parsed for Razor escapes

### ISSUE THREAD

**Issue by jasoncavett** [aspnet/Razor#732]
I had a line like this in a CSHTML view (specifically, this was in a _Layout, but that does not seem to make a difference).

`<!--<li><a asp-controller="Home" asp-action="Index" asp-route-id=@Model.Id>A Link</a></li>-->`

However, I was receiving an exception that my Model did not have the property Id when I hit the page. After I changed the comment to:

`@*<li><a asp-controller="Home" asp-action="Index" asp-route-id=@Model.Id>A Link</a></li>*@`

then everything worked properly.

I am using `Microsoft.AspNet.Mvc 6.0.0-rc1-final` on OSX using the Mono runtime. I am serving the site locally on my dev machine through Kestrel. I don't have an additional machine to test it on.

**Comment by NTaylorMullen** [comment]
@jasoncavett this is working as intended. Razor somewhat understands HTML comment syntax but tries to be flexible when parsing it. In your case when it encounters the `<!--` it thinks, "alright i'm in an HTML comment, no HTML is really valid, try and find the end portion of this comment or any dynamic content (`@` anything). This is to support users having dynamic output in their comments if they please.

**Comment by jasoncavett** [comment]
Thanks for the quick response @NTaylorMullen! I hadn't considered the case of having dynamic data in comments. Much clearer. I'll close this out then.
