### ISSUE TITLE
Poll on file watch

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Razor#733]
cc @glennc @pranavkm 

@Eilon can I assume this is approved for RC2 as a transitive dependency of the polling file watcher?

**Comment by pranavkm** [comment]
The changes are in Mvc, not Razor itself.

**Comment by victorhurdugaci** [comment]
Move it to the right place :)

**Comment by Eilon** [comment]
BTW we should get @DamianEdwards to specifically approve/decline this feature for RC2. @victorhurdugaci can you send a mail on that?

**Comment by Eilon** [comment]
(This is technically somewhat orthogonal to the other file watched changes.)
