### ISSUE TITLE
Stop cross compiling Razor.Runtime for dnx451

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#734]
Shouldn't need this: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Runtime/project.json#L53

cc @NTaylorMullen

**Comment by Eilon** [comment]
@NTaylorMullen approved for RC2/release.

**Comment by Eilon** [comment]
Nevermind, @pranavkm has it.
