### ISSUE TITLE
Newline at the end of text tag should not be rendered when it is followed csharp

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#739]
Related to #485 

Example:

In this case,
```HTML
@using(...)
{
  <div>
...
  </div>
  <input />
}
```
The newline after `</div>` should be rendered and the newline after `<input/>` should not be rendered.

cc' @dougbu @NTaylorMullen

**Comment by ajaybhargavb** [comment]
Update: Nuking the newline at the end of all html tags that are followed by csharp breaks scenarios like nested `foreach` with `<ul>` and `<li>`. So doing this change only for `<text>` tags.

**Comment by dougbu** [comment]
> So doing this change only for `<text>` tags.

Sounds reasonable.
