### ISSUE TITLE
TagHelper directives don't work with optional quotes in non-import files

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#744]
`@addTagHelper *, Location` will work in any location, and `@addTagHelper "*, Location"` will work in an _ImportView.cshtml, but if you try to do `@addTagHelper "*, Location"` in for example Index.cshtml you'll get an error saying "The given assembly name or codebase was invalid"

To reproduce, create a new Web project, copy the `@addTagHelper` directive out of _ViewImports.cshtml into Index.cshtml and change it to `@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"`.

**Comment by Eilon** [comment]
@DamianEdwards FYI moving this to RTM.

**Comment by NTaylorMullen** [comment]
80ebb4a06838123599fa8132a850a141e9fc80b3
