### ISSUE TITLE
Generics and TagHelpers

### ISSUE THREAD

**Issue by Villason** [aspnet/Razor#745]
I am trying to build a generic TagHelper like this:

```
    [HtmlTargetElement("listing", Attributes = "asp-listing")]
    public class ListingTagHelper<TModel> : TagHelper
```
Unfortunately adding Generics makes the tag helper not to bind. Is there any "secret" parameter that triggers the binding?

**Comment by NTaylorMullen** [comment]
So you can't use generics but you can utilize the `ModelExpression` type to get information about the pages current `Model` and a provided property. `ModelExpression` is used by the MVC `TagHelper`s, aka `<input asp-for="FirstName />`

**Comment by Eilon** [comment]
Right, the only support for generic in tag helpers is for model-expressions (which perhaps might be exactly what you want to do).

For example, see the LabelTagHelper source code: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/LabelTagHelper.cs#L48
