### ISSUE TITLE
Investigate approaches to pooling TagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#746]
Whenever a TagHelper is constructed it's thrown away once it is done running. We should investigate alternatives to enable TagHelper instances to be pooled. This would limit the amount of service collection requests made when constructing and would limit allocations done for the vast number of TagHelpers on a page.

@mnltejaswini can provide perf numbers on this.

**Comment by Eilon** [comment]
I'm prospectively moving this to post-RTM.

**Comment by rynowak** [comment]
I think this should be post-RTM'ed again, we have bigger fish to fry for now.

**Comment by rynowak** [comment]
No plans to do this
