### ISSUE TITLE
Investigate pooling TagHelperContext.Items

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#747]
We currently construct a brand new items dictionary for every TagHelper instance. We investigate if we can pool these.

@mnltejaswini can provide perf numbers.

**Comment by Eilon** [comment]
I'm prospectively moving this to post-RTM.

**Comment by rynowak** [comment]
I think this should be post-RTM'ed again. We have bigger fish to fry.

**Comment by rynowak** [comment]
I don't think we can do this
