### ISSUE TITLE
CS1591 warning if xmlDoc enabled

### ISSUE THREAD

**Issue by martincostello** [aspnet/Razor#752]
If ```xmlDoc``` is set to true in ```project.json``` for an MVC application using ASP.NET Core 1.0 RC2, then a compiler warning is emitted for ```*.cshtml``` files when opened in Visual Studio. For example:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1591	Missing XML comment for publicly visible type or member '_Page_Views_Shared_Error_cshtml'	API..NETCoreApp,Version=v1.0	.\src\API\Views\Shared\Error.cshtml	1	Active

```

Issue found while migrating [a project](https://github.com/martincostello/api/tree/03e2dd99e566c685703592d7756ba44231201011) from RC1 to RC2 in Visual Studio 2015 Update 2 on Windows 10.

Apologies if this is the wrong repo, if this needs to be in Roslyn as it's compiler-related I'll move it.

**Comment by pranavkm** [comment]
Moving to Mvc which is where we perform the compilation. https://github.com/aspnet/Mvc/issues/4653
