### ISSUE TITLE
Intellisense missing for taghelper

### ISSUE THREAD

**Issue by alansangeeth** [aspnet/Razor#754]
When i create Nuget packages from source project and refer it in sample, custom tag helper working fine but intellisense alone not showing. 

If i connect my source project directly to my sample, then intellisense are working. If i create nuget package  by using command "dnu publish" and refer the nuget, now intellisense not working

I added my project namespace in ViewImports file

`@addTagHelper "*, TestProject"
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"`

Note: When i add taghelper TestProject default taghelpers like "environment" tag intellisense also not showing. I think there is some conflict but i could not figure out the cause.

**Comment by NTaylorMullen** [comment]
Can you ensure you have the following: https://github.com/aspnet/Tooling/issues/484#issuecomment-219807702

**Comment by alansangeeth** [comment]
I do have Razor tools referred. Im using rc1-final version and here is my project.json file


  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "TestProjecct": "156.45-rc1-final"
  },
  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  },
  "userSecretsId": "aspnet5-WebApplication25-83ff5279-290a-4cdd-aa00-7206904a5ccb",
  "version": "1.0.0-*"
}

**Comment by NTaylorMullen** [comment]
@alansangeeth Could you push your project to a GitHub repo so I could take a look?

**Comment by macgyver76** [comment]
Same problem here. I just created a new project from VS template. Everything related to tag helpers works fine except *Visual Studio* intellisense.

**Comment by NTaylorMullen** [comment]
@macgyver76 Are you trying to upgrade an existing application or does it fail for file => new web application?

**Comment by macgyver76** [comment]
@NTaylorMullen Both (_VS 2015 Enterprise_). I tried creating new application on my personal computer (_VS Community_) - same thing - no intellisense.

**Comment by NTaylorMullen** [comment]
@macgyver76 Can you make sure you have the following: https://github.com/aspnet/Tooling/issues/484#issuecomment-219807702

**Comment by macgyver76** [comment]
@NTaylorMullen I belive it's something else than unquoted `@addTagHelper` statements. Creating a new web application from template does not include quotes already. I applied your suggestions in [comment](https://github.com/aspnet/Tooling/issues/484#issuecomment-219807702) but it wouldn't help.

**Comment by NTaylorMullen** [comment]
@macgyver76 could you provide a repro project for me to take a look at?

**Comment by NTaylorMullen** [comment]
Ah, commented too early. If it even fails for file => new web application then the only thing that would make sense is that you're using a 32bit dotnet.exe. There was a [bug](https://github.com/aspnet/RazorTooling/issues/72) in RC2 about 32bit dotnet.exes/machines.

**Comment by macgyver76** [comment]
@NTaylorMullen [Sample](https://github.com/macgyver76/taghelper-no-intellisense-repro). 
`dotnet --info` output:
![image](https://cloud.githubusercontent.com/assets/9820004/15493510/bde7426c-2184-11e6-9265-391a8fe48d9e.png)

**Comment by NTaylorMullen** [comment]
@macgyver76 that doesn't state the bitness of the exe. Just the OS you're on. :smile:

**Comment by macgyver76** [comment]
@NTaylorMullen Hey, thanks for the hint :smile: 
Below is header for system type in polish language. 
![image](https://cloud.githubusercontent.com/assets/9820004/15493729/3a2b9d04-2186-11e6-8052-012297d009d5.png)

**Comment by NTaylorMullen** [comment]
Hmmm, the only thing I'm left with then is that your tooling install is bad. If you'd like to upload one of the projects that didn't have TagHelper IntelliSense light up I'll take a peak to see if it repros on my end (would help see if it was a project template issue on your box).

**Comment by macgyver76** [comment]
@NTaylorMullen Check [this](https://github.com/macgyver76/taghelper-no-intellisense-repro).

**Comment by NTaylorMullen** [comment]
@macgyver76 I had to remove the `WebApplication1.lib` reference because it wasn't included but after that and a build I was able to see TagHelper IntelliSense:

![image](https://cloud.githubusercontent.com/assets/2008729/15494086/313931a0-213d-11e6-8ec9-b6ff8c4173e9.png)

Soo, this makes me think you have a busted tool install. One last thing I thought of we could try is go to the command line in your rc2iis project and run the following command:

`dotnet razor-tooling resolve-taghelpers ./project.json Microsoft.AspNetCore.Mvc.TagHelpers`. If that returns a huge json blob then your tooling is busted, if not then it's something with your dotnet.exe install or the packages you have cached on your box.

**Comment by macgyver76** [comment]
@NTaylorMullen Magic command output:
### Command: 
`dotnet razor-tooling resolve-taghelpers ./project.json Microsoft.AspNetCore.Mvc.TagHelpers`
### Output:
`Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.`

**Comment by NTaylorMullen** [comment]
Delete your `%UserProfile%/.nuget/packages` folder. Re-restore your project once it's been deleted. Re-build. Then check the TagHelper IntelliSense.

**Comment by macgyver76** [comment]
@NTaylorMullen Intellisense is back! Thank you sir for your help.

**Comment by NTaylorMullen** [comment]
Hah, awesome! Glad we could figure it out @macgyver76.

**Comment by Eilon** [comment]
@NTaylorMullen safe to close this?

**Comment by NTaylorMullen** [comment]
@Eilon not quite. The original poster still hasn't posted their repro project. Granted its RC1.

**Comment by Eilon** [comment]
At this point the fix is to update to RC2 or newer.
