### ISSUE TITLE
Add ability for a TagHelper to ignore @tagHelperPrefix.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#756]
There's a class of `TagHelper`s that wants to run behind the scenes and make a developers life better. A great example of this is the `UrlResolutionTagHelper` in Mvc that enables `~/` resolution. 

The current issue with `UrlResolutionTagHelper` is that it hides its presence from the editor because it'd just be unneeded TagHelper highlighting; this in combination with `@tagHelperPrefix` result in an unfortunate scenario where all your `~/` pieces stop resolving because the tags that have those attribute values do not have the TagHelper prefix.

I propose adding a new property `IgnoreTagHelperPrefix` to `HtmlTargetElement` that allows you to specify the target should apply despite the presence of an `@tagHelperPrefix` directive.

The other option would have been to make `@tagHelperPrefix` specific to TagHelper assemblies but that gets really sticky when trying to have multiple TagHelper's run on a single element. IE would we handle it like `<th:th2:a ... ></a>`? It'd be too confusing.

Talked with @DamianEdwards and he feels that this should be done for RTM.

/cc @Eilon @danroth27

**Comment by Eilon** [comment]
Don't have time for RTM given the other work that we have. @DamianEdwards how important is this really? Do we expect many people to use `@tagHelperPrefix`?

**Comment by Eilon** [comment]
@DamianEdwards asked me to do a search on usage within GitHub repos, and if you exclude our actual source code, forks of it, or stuff written by our team, there are only maybe a dozen uses of it. Moving to post-v1.

**Comment by NTaylorMullen** [comment]
@danroth27 @Eilon it cool if I pick this one up?

**Comment by NTaylorMullen** [comment]
After many offline discussions we decided not to do any change to resolve this. Reasons: potential arms race and functional issues when multiple `TagHelper`s target the same element but one ignores and the other does not.

If you decide to use `@tagHelperPrefix` you will need to prefix even hidden `TagHelper`s on the page.
