### ISSUE TITLE
Cannot get ModelExpression assignment to work if model type is in another project file

### ISSUE THREAD

**Issue by ShamsulAmry** [aspnet/Razor#766]
When using a `TagHelper` that have a `ModelExpression` property, I can assign a model property to it if the model type is defined in the same project file. However once I moved the exact same type to a different project, I will get the following runtime error message:

> Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

**Comment by Eilon** [comment]
Looks like a dup of https://github.com/aspnet/Mvc/issues/4497.
