### ISSUE TITLE
HttpContext returns null for Httpcontextaccessor instance in RC2

### ISSUE THREAD

**Issue by alansangeeth** [aspnet/Razor#768]
In RC1 i used Httpcontextaccessor instance to get httpcontext in my class library. But it returns null when i migrated to RC2. Is there any other way to get Httpcontext in class library?

**Comment by khellang** [comment]
@alansangeeth That's because in RC2, `IHttpContextAccessor` isn't registered by default from RC2 onwards. You need to register it explicitly yourself, like this; https://github.com/aspnet/Mvc/blob/dd774366f6fb18af9382ca84c276e6eb73c66b3a/test/WebSites/BasicWebSite/Startup.cs#L23

**Comment by alansangeeth** [comment]
@khellang is there any other way to do this (without using startup.cs)? if I do it in startup.cs, then anyone uses my class library must do this(register IHttpContextAccessor) in their startup.cs file. i want to avoid this

**Comment by khellang** [comment]
If this is for a library, I think your options are

1. Create an extension method that does this and make your users call it, like all other frameworks do. I.e. `services.AddMvc ()`
2. Use the `IStartupFilter` interface to wire up your dependencies. I'might not really sure how those are hooked up/discovered though.

I'd give you a more comprehensive example, but I'm on the phone.

**Comment by khellang** [comment]
When I think about it, it sounds like you'really already hooking get some stuff up to the container.  How would you otherwise get the `IHttpContextAccessor` injected? I'd just do a `TryAddSingleton` together with the rest.

**Comment by mattman73** [comment]
Hi all
I need some help I have been working on a way to load a page from within the program.cs file but I can not work out how this is done I have look on the web to find the answer but for the life of me, I cannot find anything that will work.
What I'm looking to do is after a lookup I need to load the page again with an added searchstring, I have all the code doing the look up and cross-checking but I'm unable to get the code to redirect to the page again with the added searchstring.
I have tried to DI the Httpcontecxt but this keeps returning null.
any pointers would be great.
