### ISSUE TITLE
TagHelper with multiple attributes mapping to properties fail at runtime

### ISSUE THREAD

**Issue by mronnlun** [aspnet/Razor#769]
After upgrading from RC1 to RC2 Razor no longer identified the second of my custom attributes.

In my rc1 version I only had one attribute defined in the Attributes but both properties were still recognized both by Intellisense and at runtime. After upgrading to RC2 I get no Intellisense and at runtime I get the following exception

> 'DateTimeFormat' does not contain a definition for 'DateTimeFormat'
            <datetime asp-date-time="@DateTime.UtcNow" asp-date-time-format="DateTimeFormat.TimeWithSeconds" />

Here is the complete tag helper code

```C#
    [HtmlTargetElement("datetime", Attributes = DateTimeAttributeName + "," + DateTimeFormatAttributeName, TagStructure = TagStructure.WithoutEndTag)]
    public class DateTimeTagHelper : TagHelper
    {
        private const string DateTimeAttributeName = "asp-date-time";
        private const string DateTimeFormatAttributeName = "asp-date-time-format";

        [HtmlAttributeName(DateTimeAttributeName)]
        public DateTime DateTime { get; set; }

        [HtmlAttributeName(DateTimeFormatAttributeName)]
        public DateTimeFormat Format { get; set; }

        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            var date = this.DateTime;

            output.TagName = "";

            switch (this.Format)
            {
                case DateTimeFormat.Date:
                    output.Content.SetContent(date.ToString("dd.MM.yyyy"));
                    break;
                case DateTimeFormat.DateTime:
                    output.Content.SetContent(date.ToString("dd.MM.yyyy HH:mm"));
                    break;
                case DateTimeFormat.DateTimeWithSeconds:
                    output.Content.SetContent(date.ToString("dd.MM.yyyy HH:mm:ss"));
                    break;
                case DateTimeFormat.Time:
                    output.Content.SetContent(date.ToString("HH:mm"));
                    break;
                case DateTimeFormat.TimeWithSeconds:
                    output.Content.SetContent(date.ToString("HH:mm:ss"));
                    break;
                default:
                    output.Content.SetContent(date.ToString("dd.MM.yyyy HH:mm"));
                    break;
            }
        }
    }

    public enum DateTimeFormat
    {
        Date,
        DateTime,
        DateTimeWithSeconds,
        Time,
        TimeWithSeconds
    }
```

**Comment by NTaylorMullen** [comment]
@mronnlun To ensure you're getting IntelliSense ensure you've done the following: https://github.com/aspnet/Tooling/issues/484#issuecomment-219807702

As for your comment of 

> 'DateTimeFormat' does not contain a definition for 'DateTimeFormat'

That's due to the new TagHelper enum support. See the [announcement](https://github.com/aspnet/Announcements/issues/96) for more details.

I tried out your TagHelper and all worked well once the above was done:

Typing: 
![image](https://cloud.githubusercontent.com/assets/2008729/15686866/e9c0b18c-2726-11e6-8400-363a77fb93d6.png)  
Example typed out: 
![image](https://cloud.githubusercontent.com/assets/2008729/15686875/f386c738-2726-11e6-9ff9-3bc0f85b472a.png)

**Comment by mronnlun** [comment]
Ok. It's working now. I think the guides could be more clear that the Attributes field in the HtmlTargetElement attribute only relates to deciding if the tag helper applies to the tag or not and that input parameters like my asp-date-time comes directly from properties in the tag helper.

For me this is ok and you can close the issue.

Here is the working code for clarity if someone else stumbles on this.

`    [HtmlTargetElement("datetime", TagStructure = TagStructure.WithoutEndTag)]
    public class DateTimeTagHelper : TagHelper
    {
        private const string DateTimeAttributeName = "asp-date-time";
        private const string DateTimeFormatAttributeName = "asp-date-time-format";

        [HtmlAttributeName(DateTimeAttributeName)]
        public DateTime DateTime { get; set; }

        [HtmlAttributeName(DateTimeFormatAttributeName)]
        public DateTimeFormat Format { get; set; }

        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            var date = this.DateTime;

            output.TagName = "";

            switch (this.Format)
            {
                case DateTimeFormat.Date:
                    output.Content.SetContent(date.ToString("dd.MM.yyyy"));
                    break;
                case DateTimeFormat.DateTime:
                    output.Content.SetContent(date.ToString("dd.MM.yyyy HH:mm"));
                    break;
                case DateTimeFormat.DateTimeWithSeconds:
                    output.Content.SetContent(date.ToString("dd.MM.yyyy HH:mm:ss"));
                    break;
                case DateTimeFormat.Time:
                    output.Content.SetContent(date.ToString("HH:mm"));
                    break;
                case DateTimeFormat.TimeWithSeconds:
                    output.Content.SetContent(date.ToString("HH:mm:ss"));
                    break;
                default:
                    output.Content.SetContent(date.ToString("dd.MM.yyyy HH:mm"));
                    break;
            }
        }
    }

    public enum DateTimeFormat
    {
        None,
        Date,
        DateTime,
        DateTimeWithSeconds,
        Time,
        TimeWithSeconds
    }`

and usage is like, i.e. you shouldn't specify the name of the enum, DateTimeFormat.TimeWithSeconds -> TimeWithSeconds.

`<datetime asp-date-time="@DateTime.UtcNow" asp-date-time-format="TimeWithSeconds" />`
