### ISSUE TITLE
Generate nuget package for class library in RC2

### ISSUE THREAD

**Issue by alansangeeth** [aspnet/Razor#770]
Following is my project.json

`{
  "version": "Test-1.0.0",
  "authors": [ "Alan" ],
  "packOptions": {
    "tags": [ "Test", "Project" ]
  },

  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Hosting": "1.0.0-rc2-final",
    "Newtonsoft.Json": "8.0.3",
    "System.Collections": "4.0.11-rc2-24027",
    "System.Data.Common": "4.0.1-rc2-24027",
    "System.Linq": "4.1.0-rc2-24027",
    "System.Linq.Queryable": "4.0.1-rc2-24027",
    "System.Reflection.Emit": "4.0.1-rc2-24027",
    "System.Collections.NonGeneric": "4.0.1-rc2-24027"
  },
  "frameworks": {
    "netstandard1.5": {
      "imports": [
        "dnxcore50",
        "portable-net451+win81"
      ]
    }
  }
}
`

.net CLI command "dotnet pubish" does not create nuget package for my class library

**Comment by pranavkm** [comment]
You might need to use `dotnet pack` to generate nupkgs. That said, this would be a question for https://github.com/dotnet/cli
