### ISSUE TITLE
Since upgrading to RC2, I am unable to set a breakpoint in my Razor view.

### ISSUE THREAD

**Issue by 82dsoldier** [aspnet/Razor#772]
Title says it all.  When attempting to set a breakpoint in a Razor view, I get the message:

"The following breakpoint cannot be set:

At Index.cshtml, line 11 character 5
('Asp._Page_Views_Applications_Index_cshtml.ExecuteAsync()')

The breakpoint failed to bind."

**Comment by NTaylorMullen** [comment]
@Tratcher did you encounter anything like this when verifying Razor debugging?

**Comment by Tratcher** [comment]
No, it worked for me.

**Comment by NTaylorMullen** [comment]
@82dsoldier could you push a small repro project somewhere for me to take a look?

**Comment by 82dsoldier** [comment]
I'd love to, but I can't seem to reproduce it in a small project.  I have two major projects and it's broken in both, but I can't upload them anywhere due to security issues.  Anything I could look at to see what's causing the issue?

**Comment by NTaylorMullen** [comment]
@ToddGrun are there steps @82dsoldier can take to diagnose Razor breakpoint setting issues since he's unable to upload a repro project for us to peak at?

**Comment by ToddGrun** [comment]
Just to clarify, this isn't when setting the breakpoint at design time, but rather when binding the breakpoint when running the application, right? Is this for a .NET core web app, an MVC app or something else?

**Comment by Eilon** [comment]
@pranavkm could this be related to https://github.com/aspnet/Diagnostics/issues/293 ?

**Comment by 82dsoldier** [comment]
@ToddGrun correct, it is setting the breakpoint when running the app.  If I try to set the breakpoint before running the app, it sets correctly but is never hit.  It is for an MVC application.

**Comment by pranavkm** [comment]
I tried this on apps targeting both net451 and netcoreapp1.0 and I couldn't reproduce the issue:

![animation](https://cloud.githubusercontent.com/assets/174281/15951141/a130e734-2e6a-11e6-9a67-c2903f1f70a6.gif)

Could you let us know what the Symbol Status is in the Modules window (Debug -> Windows -> Modules). View assemblies have random file names so they'd be easy to spot.

**Comment by 82dsoldier** [comment]
For my app, the status is Symbols loaded.

**Comment by t0xicDen** [comment]
I have similar issue.
Reproduced on new project with default template.

![screenshot 2016-06-14 12 21 04 2](https://cloud.githubusercontent.com/assets/7147684/16037858/129c3ff4-322b-11e6-9638-37953bac1ce8.png)

![screenshot 2016-06-14 12 19 06](https://cloud.githubusercontent.com/assets/7147684/16037870/20e438c8-322b-11e6-9264-d561b39e61ee.png)

**Comment by pranavkm** [comment]
@t0xicDen could you push the app to a repo? Let me try it out to see if it's a code issue. In the meanwhile, I'd recommend trying to repair VS (via Programs & Features). I haven't been able to reproduce the error locally so it might be an installation issue.

@82dsoldier do your two projects contain any pre-RC references?

**Comment by 82dsoldier** [comment]
I don't see any pre-RC references.

Strange thing.  Due to another issue, I rebuilt my Index.cshtml page.  Now I can set breakpoints and they are actually hit, but when I attempt to do a quick watch on any variable I get the message that it isn't defined in the current scope.

**Comment by pranavkm** [comment]
cc @BillHiebert any guesses on what could be wrong here?

**Comment by t0xicDen** [comment]
@pranavkm [https://github.com/t0xicDen/RazorIssue772](https://github.com/t0xicDen/RazorIssue772) app repo

**Comment by pranavkm** [comment]
@t0xicDen I'm not seeing this issue. I tried this on different machines and it was working just fine. I'd recommend repairing or reinstalling VS. 

@82dsoldier, if you're still experiencing issues with the watch window, I'd recommend trying a VS repair. If you continue seeing it, please file a bug in the https://github.com/aspnet/Tooling repo.

**Comment by t0xicDen** [comment]
@pranavkm by the way, i am using VS 2015 Enterprise 2015 Version 14.0.25402.00 **Update 3 RC**

**Comment by hemantkd** [comment]
The new [Update for Microsoft Visual Studio 2015 Update 3 (KB3165756)](https://msdn.microsoft.com/en-us/library/mt752379.aspx) has fixed the breakpoint issue for me where I'm trying to inspect the local variables in C# code embedded in cshtml files in ASP.NET Core applications.
