### ISSUE TITLE
Unable to resolve "classlibrary" for ".NETStandard v1.5" 

### ISSUE THREAD

**Issue by alansangeeth** [aspnet/Razor#773]
I just created a new class library and without doing any modifications, I created Nuget package using dotnet cli "dotnet pack"

Then i created another class library. When i try to add my Nuget package created it throws error "Unable to resolve "classlibrary" for ".NETStandard v1.5"

My dotnet info
OS Name = Windows
OS Version = 6.3.9600
Os Platform = Windows
RID = win81-x64

And my Nuget Packager manager version is 3.4.3

**Comment by NTaylorMullen** [comment]
Did you add a local package source to your NuGet.config that contained your first class library?

**Comment by alansangeeth** [comment]
Got it!!!
Actually i was just simply moving the packages generated (dotnet pack) to /%userprofile%/.nuget/packages which was the cause of the problem.

Instead of it, after generating packages, I used following command to add nuget package and it worked :)
nuget add classLibrary.nupkg -source "%userprofile%\.nuget\packages "

**Comment by NTaylorMullen** [comment]
Glad you figured it out :smile:

**Comment by barbarosalp** [comment]
Hi @alansangeeth,

I am having the same issue here with my local nuget feed. I am not sure how should i resolve this issue. Do you have any idea?

**Info**
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

Nuget Package Manager 3.4.4

**Package Manager Output**

Installing NuGet package Solid.Common.Aws.DynamoDb.1.0.0.
Successfully installed 'Solid.Common.Aws.DynamoDb 1.0.0' to Solid.Disaster.Data
========== Finished ==========
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "D:\Projects\Solid.Disaster\Solid.Disaster\.vs\restore.dg"
log  : Restoring packages for D:\Projects\Solid.Disaster\Solid.Disaster\src\Solid.Disaster.Data\project.json...
**_warn : The folder 'D:\NuGetLocal\Solid.Common.Aws.DynamoDb\netstandard1.5' contains an invalid version._**
info :   GET https://api.nuget.org/v3-flatcontainer/digiturk.common.aws.dynamodb/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/digiturk.common.aws.dynamodb/index.json 496ms
error: Unable to resolve 'Solid.Common.Aws.DynamoDb (>= 1.0.0)' for '.NETStandard,Version=v1.5'.
info : Committing restore...
log  : Writing lock file to disk. Path: D:\Projects\Solid.Disaster\Solid.Disaster\src\Solid.Disaster.Data\project.lock.json
log  : D:\Projects\Solid.Disaster\Solid.Disaster\src\Solid.Disaster.Data\Solid.Disaster.Data.xproj
log  : Restore failed in 990ms.
Errors in D:\Projects\Solid.Disaster\Solid.Disaster\src\Solid.Disaster.Data\Solid.Disaster.Data.xproj
    Unable to resolve 'Solid.Common.Aws.DynamoDb (>= 1.0.0)' for '.NETStandard,Version=v1.5'.
NuGet Config files used:
    C:\Users\DTBALP\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
Feeds used:
    https://api.nuget.org/v3/index.json
    D:\NuGetLocal
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

**Comment by NTaylorMullen** [comment]
@barbarosalp it looks like you don't have a `Solid.Common.Aws.DynamoDb` package built for >= netstandard1.5.

**Comment by barbarosalp** [comment]
I think it's about .net 4.6.1 is not compatible with netstandard1.5. 
I guess i should downgrade all versions to netstandard1.4.

**Comment by barbarosalp** [comment]
This time i ran into a different problem which discussed here:
https://github.com/dotnet/corefx/issues/7274

I create nuget packages out of class libraries with the script postcompile.

**project.json**
```
{
  "version": "1.0.0.1",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027",
    "Newtonsoft.Json": "8.0.3"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  },
  "scripts": {
    "postcompile": [
      "dotnet pack --no-build --configuration %compile:Configuration%"
    ]
  }
}
```

I will download .net 4.6.2(preview) and try it again.

**Comment by barbarosalp** [comment]
This is the class library's project.json(Solid.Barb):
```
{
  "version": "1.0.0.1",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  },
  "scripts": {
    "postcompile": [
      "dotnet pack --no-build --configuration %compile:Configuration%"
    ]
  }
}
```

This is the other class library which I am trying to add reference for the above class library nuget package
```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Solid.Barb": "1.0.0.1",
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  }
}
```

What might be the problem here? 

Thanks.

**Comment by barbarosalp** [comment]
@alansangeeth Can you please help ? Thank you.

**Comment by alansangeeth** [comment]
@barbarosalp I had the same issue when i try to refer the nuget packages generated through "dotnet pack" command.

Delete all other files in nuget package generated folder and have only nupkg file alone. Now just add the nupkg file name with version in your project.json and use the following command to restore packages

`dotnet restore --source "nupkg file location"`
