### ISSUE TITLE
[WindowsServer2012][net451] mscorlib problem : Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?

### ISSUE THREAD

**Issue by dlaporte40** [aspnet/Razor#775]
Hi,
I got following problem when deploying my ASP.NET RC2 application compiled under Windows 7 to Windows Server 2012 (same problem with a sample directly from the VS template). Note that : The application target only "net451" (project.json) ; On my Windows server 2012 ".NET CORE framework" is not installed (i assume it is not needed since i target net451, and i have corporate restrictions which prevent me to easily install it) ; I had no such problem when deploying with RC1.

Error :
**## Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?

17.    public class _Views_Home_Index_cshtml : Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
Assembly 'Microsoft.AspNetCore.Mvc.Razor' with identity 'Microsoft.AspNetCore.Mvc.Razor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' which has a higher version than referenced assembly 'mscorlib' with identity 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'**

To reproduce :
- Create a new ASP.NET Core from template and target only "net451"
- Add a profile in LaunchSettings.json to run it under kestrel or WebListener 
 "RC2HostingDemo": {
      "commandName": "Project",
      "launchUrl": "http://localhost:60000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
- Test locally it works from command line or debugger
- Deploy to Windows Server 2012 with 4.5.1 .net framework installed (but no ".net core framework")
  => Got the error

Thanks a lot for any help on this issue.

**Comment by pranavkm** [comment]
@pakrym - would the dependency context resolve .NET 2.0 \ .NET 3.5 reference assemblies?

**Comment by pakrym** [comment]
@pranavkm, no, it only resolves things from `c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\`

**Comment by pranavkm** [comment]
@dlaporte40 - could you tell us the version of mscorlib.dll under the `refs` directory of your published output (via the Properties pane)? It seems like the view is using .Net 2.0 \ .Net 3.5 reference assemblies to compile.

**Comment by pompomJuice** [comment]
That's odd, this is the exact same problem I get when trying to run ASP.Net RC2 under linux while targeting net451. The problem is net451, but you can't develop anything under netcoreapp1.0+ because referenced assemblies just don't work. Take Nlog for example, says it supports netcoreapp but if you link it in id just gives errors.

You could probably solve your problem by copy & pasting the following [class](https://github.com/mono/mono/blob/d70777a3332af2d630d24adf620c2e548b92b56a/mcs/class/referencesource/System.Core/System/Runtime/CompilerServices/DynamicAttribute.cs
) into your project: 

https://github.com/aspnet/Razor/issues/774

**Comment by dlaporte40** [comment]
My mistake, to deploy i was using the output of the build instead of the output of "Publish". So when using "Publish" all is working fine on Windows server 2012.
Still don't understand why is was working locally on my Windows 7 desktop on not when user WS2012 using exactly the same binary and command line launch, but that's fine since i was not using the correct way to deploy.
@pranavkm : It was the 4.0 assembly in the refs.
Thanks all.

**Comment by pranavkm** [comment]
Thanks @dlaporte40. Not super sure on the Windows 7 desktop scenario - maybe you happened to have the publish binaries in the output directory?
