### ISSUE TITLE
 Non-Latin (non-ASCII?) characters are getting encoded.

### ISSUE THREAD

**Issue by lalibi** [aspnet/Razor#777]
If you include something like:
```
<p>@("Αυτό είναι ένα τεστ")</p>
```
in a Razor View, the rendered output is the following:
```
<p>&#x391;&#x3C5;&#x3C4;&#x3CC; &#x3B5;&#x3AF;&#x3BD;&#x3B1;&#x3B9; &#x3AD;&#x3BD;&#x3B1; &#x3C4;&#x3B5;&#x3C3;&#x3C4;</p>
```
Obviously, this happens to any text containing Greek characters (and I assume all non-Latin/ASCII ones). This is apparent only if you `View Source` and the page "works" ok, but it seems unnecessary, since the `.cshtml` file is UTF-8.

It can drive the file size up, too.

**Comment by pranavkm** [comment]
See https://github.com/aspnet/HttpAbstractions/issues/315
