### ISSUE TITLE
Remove unused classes

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#778]
Remove XmlHelper, CharUtils, EnumeratorExtensions, EnumUtil, BufferingTextReader, SourceSpan and TextBufferReader.

**Comment by pranavkm** [comment]
Also https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor/RazorDebugHelpers.cs which I think lets you remove some of the project dependencies in Razor.

**Comment by NTaylorMullen** [comment]
6e4f15bad4252fcf477c7b806ff459b558f77674
ccba161447f132d86e5714f90af8d49689c3eb9b
