### ISSUE TITLE
Mark EditorHints as obsolete, it's no longer used by tooling.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#780]

**Comment by Eilon** [comment]
You mean the `EditorBrowsable` stuff?

**Comment by Eilon** [comment]
Also what does "no longer used" mean? Was it ever?

**Comment by NTaylorMullen** [comment]
Nope, not `EditorBrowsable`, [this](https://github.com/aspnet/Razor/blob/3d0bf621f330ad5444a5892505dc4792aa14ad03/src/Microsoft.AspNetCore.Razor/Editor/EditorHints.cs). Talked to @anurse a while back and they were originally added to indicate if an attribute value was virtual; at which point Todd would detect that and provide appropriate `~/` IntelliSense. Thing is, Todds HTML editor is a bit more decoupled from the Razor side of things so he ended up taking his own stab at making that possible. End result, they were never used.

**Comment by dougbu** [comment]
So is this a suggestion to `[Obsolete]` the unread / unset `SpanEditHandler.EditorHints` property? Or do you want to treat that class as if it were `internal`?

**Comment by NTaylorMullen** [comment]
I'd prefer to treat it as if it was internal but that'd be a binary breaking change. I'm assuming that's a no go. Therefore, obsolete until we can remove it in a bigger release would suffice.

**Comment by Eilon** [comment]
Bug is approved as a breaking change. Please mark things obsolete (but remain compatible) in this bug, then log a new breaking-change bug for 2.0.0.

**Comment by Eilon** [comment]
Breaking change guidelines: https://github.com/aspnet/Home/wiki/Engineering-guidelines#breaking-changes

**Comment by NTaylorMullen** [comment]
fc4a61586e2773f4b9836c60d01a19229a290e3c
