### ISSUE TITLE
@addTagHelper fails because of strange issues with double quotes

### ISSUE THREAD

**Issue by pompomJuice** [aspnet/Razor#784]
When running razor under `net451` (backed by Mono) I get a strange issue where the `@addTagHelper` won't work because the assembly name contains a trailing **_"_**

Looking at the code it all comes down to a [line](https://github.com/aspnet/Razor/blob/3d0bf621f330ad5444a5892505dc4792aa14ad03/src/Microsoft.AspNetCore.Razor/Parser/CSharpCodeParser.Directives.cs#L348) that seems to be correctly coded but somehow still fails. Removing the quotes from the directive solves the problem for now.

@pranavkm

`Error @ (43:1,18)(18) - [Cannot resolve TagHelper containing assembly 'Osprey.Pro.FE.Web"'. Error: Could not load file or assembly 'Osprey.Pro.FE.Web"' or one of its dependencies] (1,18) Cannot resolve TagHelper containing assembly 'Osprey.Pro.FE.Web"'. Error: Could not load file or assembly 'Osprey.Pro.FE.Web"' or one of its dependencies`

The proof is in the `Error @` output. If you look closely at the 18, it should be 17. Somehow that quote gets in there. Adding just one " at the start or at the back triggers those validation code paths so I am at a loss how that code fails.

**Comment by NTaylorMullen** [comment]
This ended up being due to: https://github.com/aspnet/Razor/issues/744. Fixed in next release :smile: 

To work around it remove the quotes from your `@addTagHelper`

**Comment by Eilon** [comment]
@NTaylorMullen so this is a dup of https://github.com/aspnet/Razor/issues/744?

**Comment by NTaylorMullen** [comment]
Yup.
