### ISSUE TITLE
Razor on linux asp.net core is very slow

### ISSUE THREAD

**Issue by mytrash** [aspnet/Razor#790]
I created small asp.net core mvc project to test the speed of the asp.net application on the Linux (Ubuntu 16.04).

I created the CRUD controller that works with the "AspUser" class (stored in the PostgreSQL database). When I call the index method that shows the list of stored users the razor rendering is extremely slow. It takes 2 seconds to render the content (it is not the first call - the first call takes 8 seconds). There are 1000 users in the database. The database request is fast, but the rendering is slow.

The wrk utility wrk -c 256 -t 32 -d 10 http://localhost:5000/aspusers shows 2,6 request per second.

I made the same example in the nodejs the wrk utility shows 20 requests per second.

HW: Amd FX 8150 8 Core, 3.6 GHz, 8 GB RAM

View:

```
@model IEnumerable<PostgresTest.Models.AspUser>
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Age
                </td>
                <td>
                    @item.FirstName
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.CreatedAt
                </td>
                <td>
                    @item.UpdatedAt
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
```

Myth

**Comment by NTaylorMullen** [comment]
@SajayAntony / @mnltejaswini is this something we see in our cross plat benchmarks?

**Comment by Eilon** [comment]
@rynowak also.

@NTaylorMullen can you start an email thread on this?

**Comment by SajayAntony** [comment]
@mnltejaswini will be looking into this.

**Comment by mnltejaswini** [comment]
We are trying to repro in our lab. Will get back once I get some results.

**Comment by mnltejaswini** [comment]
I ran the scenario on Ubuntu 14.04, 4 Core , 4GB lab machine using wrk against the similar View with in memory database.

Here are the results 
Running 10s test @ http://10.194.217.139:5000/Home/TestIndexWithTagHelpers
  32 threads and 256 connections
Requests/sec:     21.09
Transfer/sec:     24.51MB

 We will look into the profiles to understand the behavior.

**Comment by pranavkm** [comment]
Could you check the console logs to verify that we aren't recompiling too often?

**Comment by mnltejaswini** [comment]
At least the profile doesn't indicate any compilation stuff. It includes processing of AnchotTagHelper like link generation.

**Comment by mnltejaswini** [comment]
Confirmed from the console logs that the Code generation and compilation happens only once.

**Comment by mnltejaswini** [comment]
We looked into the profiles and found that most of the cost is coming from link generation for the <a> tag helpers. We identified few optimizations to make it better and we are working on it.

**Comment by mytrash** [comment]
Hello friends,

I played with the source code and changed the index.cshtml like this:

```
@model IEnumerable<PostgresTest.Models.AspUser>
@{
	ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Age)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.FirstName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.LastName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.CreatedAt)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.UpdatedAt)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Age)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.FirstName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.LastName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.CreatedAt)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.UpdatedAt)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>
```

The Html.DisplayFor tag helper rapidly slows the page rendering down.

**Comment by rynowak** [comment]
This issue was moved to aspnet/Mvc#6111
