### ISSUE TITLE
Where did ViewLocationFormats go?

### ISSUE THREAD

**Issue by BrianVallelunga** [aspnet/Razor#794]
I'm not sure if this is ASP.NET, Razor, or Razor Tooling, but with RC1 and RC2 we were overriding ViewLocationFormats of the RazorViewEngine to serve views from custom locations. This appears to be gone now with RTM. How can I go about getting this behavior back? I check the Announcements section and didn't see any listing of a breaking change.

**Comment by NTaylorMullen** [comment]
@BrianVallelunga could you move this issue over to aspnet/Mvc?
