### ISSUE TITLE
This extension method fails in RC2 - worked in RC1 - could use some help..

### ISSUE THREAD

**Issue by dazinator** [aspnet/Razor#795]
The following extension method is a simplified version of the one we actually use, to demonstrate the issue. 

```

     public static HtmlString AddResource(this IHtmlHelper htmlHelper, Func<object, HelperResult> template)
        {       
                
                using (var writer = new StringWriter(CultureInfo.InvariantCulture))
                {
                    var content = template(null);
                    content.WriteTo(writer, HtmlEncoder.Default);
                    hash = writer.ToString().GetHashCode();
                }     

               // TODO: do some stuff with the content           

                return new HtmlString(String.Empty);
        }

```

In RC1 - I could use this within a razor view, such a a view for a ViewComponent, like so:

```

@Html.AddResource(
    @<script type="text/javascript">
        require(['jquery'], function (jquery) {           

            jquery(document).ready(function() {
               // do some stuff
            });

        });
    </script>
)

```

However in RC2, this line now throws a null ref exception:

```

 content.WriteTo(writer, HtmlEncoder.Default);

```

I'm really not sure how this all sits together to begin with, any ideas what changed and how I can fix this method to work in RC2?

**Comment by NTaylorMullen** [comment]
Your sample works fine for me. I copy and pasted your code directly. Just had to remove the `hash = writer.ToString().GetHashCode();` line because hash was never created.

**Comment by dazinator** [comment]
@NTaylorMullen how odd! I will see if I can put together a repro..

**Comment by NTaylorMullen** [comment]
Note: I did try this with the latest released RTM bits.

**Comment by dazinator** [comment]
Ah, I'm testing after just upgrading to RC2! I'll try upgrading to RTM and see if it persists.

**Comment by dazinator** [comment]
I'm hoping that the upgrade from RC1 to RC2 is going to be seemless and automatic like Microsoft promised.

**Comment by Eilon** [comment]
@dazinator there are relatively few changes between RC2 and RTM, and even fewer breaking changes. The migration should be relatively easy.

**Comment by dazinator** [comment]
Ok managed to upgrade to RTM, and I now get a much better exception message (kudos):-

![image](https://cloud.githubusercontent.com/assets/3176632/16567849/31b3d8ca-421b-11e6-94b2-91de1059b5ad.png)

So the problem was actually the razor script itself, and its much easier to see that now. Cheers.

**Comment by dazinator** [comment]
The underlying problem turned out to be that the razor script was binding against a null model. It didn't used to be null, but the `ViewComponent` that creates it is now being passed a null argument, i.e ThemeSwitcherDisplayOptions is now null:

```
 public IViewComponentResult Invoke(ThemeSwitcherDisplayOptions options)
        {
            //  _themeService.LoadCustomerThemes = !useStandardThemes;
            var allThemes = _themeService.GetThemes();
            var currentTheme = _themeService.GetCurrentTheme();
            var viewModel = new ThemeSwitcherViewModel() { CurrentThemeName = currentTheme.Name, Themes = allThemes, CookieName = _themeService.CookieName, Options = options };
            return View("Selector", viewModel);
        }

```

This is obviously because of the breaking changes in that area, 
Still, I am surprised that when you `@Component.InvokeAsync` passing arguments, that MVC will casually wire that up to an Invoke method that also accepts an argument, but passes in null for them becuase it can't match them up. Would be better to through an arguments mismatch exception imho. I know there is a lot of discussion re view components at present so I'll leave this alone for the present.
