### ISSUE TITLE
Customizing the RazorEngineHost used by Visual Studio's .cshtml editor

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Razor#801]
Title says it all.

How can this be done using ASP.NET Core? I've got my `CSharpDesignTimeCodeVisitor`, I've got `AutoCompleteEditHandler`s... I just don't know how to get the editor to pick them up.

**Comment by NTaylorMullen** [comment]
/cc @ToddGrun

Adding Todd here because the only way to do this would be to do a Visual Studio Extension ofsome sort. He can add more context.

**Comment by tuespetre** [comment]
I've found the implementation of `IRazorCodeGeneratorProvider` in `Microsoft.VisualStudio.Web.Editors.Razor.4_0.dll`. The `ShimRazorEditorParserImpl` class (buried down a couple of calls) is hard-coded to use a type that derives from `MvcRazorHost`. 

This used to be done with a `web.config` setting. Perhaps as the MSBuild tooling comes to fruition, MSBuild properties could be used to specify a type of `RazorEngineHost` to use for a certain pattern, with a fallback to the `MvcRazorHost`.

Something like this:

```
<ItemGroup>
    <RazorTemplate Include="./NonMvcTemplates/*.cshtml">
        <Host>My.Fully.Qualified.RazorEngineHost</Host>
    </RazorTemplate>
</ItemGroup>
```

**Comment by rynowak** [comment]
We're going to do something like this someday, but not for preview 1.

**Comment by NTaylorMullen** [comment]
Closing this since the functionality ask is abstractly covered in #854/#855.
