### ISSUE TITLE
Remove EditorHints.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#806]
EditorHints is no longer used by VisualStudio tooling and is not populated during Razor parse time. This feature was marked [obsolete in 1.1.0](https://github.com/aspnet/Razor/issues/780).

**Comment by rynowak** [comment]
@NTaylorMullen - it looks like this was never ported forward to the new codebase. Close?

**Comment by rynowak** [comment]
Talked to @NTaylorMullen - this is gone.
