### ISSUE TITLE
mvc razor：Chinese charset auto converted to NCR code, I need to turn this feature off

### ISSUE THREAD

**Issue by kzwr** [aspnet/Razor#807]
mvc razor：Chinese charset auto converted to NCR code, I want to turn this feature off
` <h2><a href="./article/173349" target="_blank">W3C&#x5021;&#x5BFC;&#x8BBE;&#x7ACB;&#x6807;&#x51C6;&#x5316;&#x65E0;&#x5BC6;&#x7801;&#x767B;&#x5F55;&#x7CFB;&#x7EDF;&#xFF1A;FIDO&#x662F;&#x57FA;&#x77F3;</a></h2>`

**Comment by Eilon** [comment]
@blowdart care to comment?

@kzwr the encoders used in ASP.NET are customizable. Can you share info on why you want to turn this off? (I know it looks ugly, but it is correct, and typically more secure - I just want to know if there's anything other than that.)

**Comment by kzwr** [comment]
@Eilon 
 I worry Baidu.Com does not support NCR coding for Seo unfriendly

**Comment by blowdart** [comment]
You can configure the encoders so they safelist Unicode codepages (it's not languages though, some languages are scattered over multiple code pages. so you need to figure out which ones you need)

The HtmlEncoder constructor appears to take settings which should enable this, so I _presume_ (that is to say I haven't tried it), that you could construct one during your app startup, then replace the one we have in DI against IHtmlEncoder which your new one.

This would be a question for the MVC folks on how to swap it out :)

**Comment by kichalla** [comment]
@kzwr Following is something you can do:

```
services.AddSingleton(
    typeof(HtmlEncoder),
    HtmlEncoder.Create(allowedRanges: new[] { UnicodeRanges.BasicLatin, UnicodeRanges.CjkUnifiedIdeographs }));
```
You can specify a list of allowed ranges as shown above. I included the `BasicLatin` range as its the default range used by the [default encoder](https://github.com/dotnet/corefx/blob/v1.0.0/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/HtmlEncoder.cs#L51) and so that you don't encode English characters (but you are free to remove it if you need to).

**Comment by kichalla** [comment]
Closing this issue now. Feel free to re-open this issue if the above solution does not work for you.

**Comment by blowdart** [comment]
Note this is now documented -https://docs.asp.net/en/latest/security/cross-site-scripting.html#customizing-the-encoders
