### ISSUE TITLE
External functions in razor view

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Razor#809]
At this moment I have to put the functions in the **TOP** of the razor cshtml

```
 Func<Dictionary<string, string>, IHtmlContent> Example = @<text>@{
<div>@item.["FirstName"]</div>
}</text>;
```

Hopefully in future we can create something like

```
 Func<(firstName, lastName), IHtmlContent> Example = @<text>@{
<div>@item.firstName</div>
}</text>;
```

It will be nice for the maximum re usability that we can include this kind of functions

**Comment by NTaylorMullen** [comment]
@andrew-vandenbrink I'm not entirely sure I follow. You're able to put that at the end of a Razor file as well (or any other location):

![image](https://cloud.githubusercontent.com/assets/2008729/17222798/d76dd946-54ae-11e6-9263-3269247f4831.png)

**Comment by Eilon** [comment]
@NTaylorMullen there's also a new syntax being proposed, I think: `Func<(firstName, lastName), IHtmlContent>`.

**Comment by andrew-vandenbrink** [comment]
@NTaylorMullen You can put it on the bottom, but it won't be callable from the top.
@Eilon the future syntax hopefully automatically supported by c# 7 tuple

The use case is I have lot of templates that is specific to one cshtml, instead creating lot of partials, i decide to use this kind of templates. Problem is that the template takes thousand lines of code and I need to scroll down to see the actual content of cshtml

The solution to this problem:
- @include xxx.cshtml
This will merge cshtml files (compile time) and process it as one
I can put that large templates as external cshtml file

- @<text> not supported inside @functions ? if this works, it will also solve my issue...
```
//I just realize this is also not working
@functions{
        Func<Dictionary<string, string>, IHtmlContent> Example= @<text>@{
<div>@item.["FirstName"]</div>
```


I'm also looking for a way to make javascript template to be processed in server side, will be nice if razor can support that scenario.

**Comment by NTaylorMullen** [comment]
> You can put it on the bottom, but it won't be callable from the top.

Sadly Razor generates C# and is therefore restricted by what C# can do. Since what you're writing is essentially a local variable it can only be used after it is declared.


> The use case is I have lot of templates that is specific to one cshtml, instead creating lot of partials, i decide to use this kind of templates

If you're looking to have complex logic within your template [ViewComponents](https://docs.asp.net/en/latest/mvc/views/view-components.html)s are a good choice. Non-complex logic but lots of Razor should work well with [partial views](https://docs.asp.net/en/latest/mvc/views/partial.html) (I know you tried this route, but this may be the best choice). 

For truly simple HTML snippets TagHelpers or HtmlHelpers may also be a better fit.

**Comment by andrew-vandenbrink** [comment]
ViewComponent is bad in RTM, its forcing things as async even I don't really have async thing on it.
Partial View files are too much due I have to create one file per template.

In the end, 
I create the html template in the top (bit bloated but no other option at this moment)
Then use nodejs to process the template and data.

**Comment by dougbu** [comment]
> Partial View files are too much due I have to create one file per template.

Partial views can be referenced using their full path from the content root. Or use a simple name and it will be searched for in locations such as `Views/Shared`. What about this prevents reuse across your templates?

**Comment by andrew-vandenbrink** [comment]
@dougbu I get it but still I want to scope the template only to this view, partial view doesn't have intellisense anyway

Luckily in visual studio I can collapse the Func, but as you can see its already take 100++ lines in the top of my .cshtml **It will be nice if there's a way to put this somewhere else** but still having the intellisense support.

![image](https://cloud.githubusercontent.com/assets/12871379/17355190/0cd23920-594f-11e6-8586-75c0644a90ca.png)

This is how I use the template
![image](https://cloud.githubusercontent.com/assets/12871379/17355293/ca870d9c-594f-11e6-89b7-462dd2de6e19.png)

**Comment by andrew-vandenbrink** [comment]
@NTaylorMullen with local function, i can put the function now in the bottom, but razor only support c# 6 at this moment, do I need to wait the release of razor version 2 for c# 7 support?

**Comment by pranavkm** [comment]
@andrew-vandenbrink - yes. We just recently updated Razor and Mvc to target C# 7.0.

**Comment by andrew-vandenbrink** [comment]
@pranavkm thanks, I will wait... bit surprising that razor not released in sync with other product...

**Comment by rynowak** [comment]
We have no plans to do the things posted in the original bug
