### ISSUE TITLE
Razor Intellisense doesnt show up in some destructive cases

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#81]
**_Steps to reproduce:**_

**Scenario 1:** Going backward with selection and hitting . (dot)
1. User types razor keyword like `@await Html.Password`
2. Then sees error in the error list that this is not async method, realizes mistake
3. Selects text with string Password and . (dot) (backward selection ctrl+shift+back arrow button)
4. Tries to type .(dot) again and now intellisense shows “Parsing document” and after few seconds gets nothing.

_Workaround:_ User need to select and type . (dot) again to get correct intellisense.

**Scenario 2:** Slight variation of scenario 1 but in step 4 when user sees parsing document, hit ctrl+ J and user will see html tag intellisense.

**_Expected Behavior:**_ Proper intellisense

**Comment by Eilon** [comment]
@NTaylorMullen can you check if this is already fixed?

**Comment by rynowak** [comment]
@NTaylorMullen ping

**Comment by NTaylorMullen** [comment]
This is still an issue.

**Comment by rynowak** [comment]
Punting this forever unless we get strong feedback
