### ISSUE TITLE
Can't send POST-request via json in script 

### ISSUE THREAD

**Issue by deeplydippy** [aspnet/Razor#811]
I want to send to API Controller POST-request using json.  But something going wrong.
Here is my script in CSHTML:
```
<script>
$.post("/api/Push/PushParticipantSubscription", { presid: "test", idcookies: "4", agreement: true });
</script>
```
Here is my API Controller:
```
    [Produces("application/json")]
    [Route("api/Push")]
    public class PushController : Controller
    {

        private readonly ApplicationDbContext _context;
        public PushController(ApplicationDbContext context)
        {
            _context = context;
        }

        // POST api/Push/PushParticipantSubscription/
        [HttpPost]
        [Route("PushParticipantSubscription/")]
        public async Task<IActionResult> PushParticipantSubscription(string presid, string idcookies, bool agreement)
        {
            PushParticipantSubscription subs = new PushParticipantSubscription();
            subs.OneSignalUserId = idcookies;
            subs.PresentationId = presid;
            subs.PushAgreement = agreement;
            try
            {
                subs.ApplicationUser = _context.ApplicationUser.SingleOrDefault(p => p.UserName == User.Identity.Name);
            }
            catch
            {
                subs.ApplicationUser = null;
            }
            _context.Add(subs);
            await _context.SaveChangesAsync();
            return NoContent();
        }
    }
```
But in table from DB nothing changes.Thank you for any help!

**Comment by pranavkm** [comment]
Could you file this bug in https://github.com/aspnet/Mvc? Doesn't look like there's a Razor specific issue here.

**Comment by Eilon** [comment]
@deeplydippy can you provide more information about what doesn't work? Can you attach a debugger and catch all exceptions to see what's going on? Are you sure your action is executing?

**Comment by deeplydippy** [comment]
Sorry for the incomplete description of the problem. I place POST-request in About.cshtml page, and on VS i can see this events:
![image](https://cloud.githubusercontent.com/assets/18574364/17358470/a7365c4c-5951-11e6-8589-2e2597aaac88.png)
My POST request isn't executing, right?

**Comment by pranavkm** [comment]
Does your the Network tag in the browser debug console say anything useful about this?

**Comment by Eilon** [comment]
@deeplydippy yes, it looks like the browser isn't even sending the request to the server. It looks like you'll need to debug this using your browser's JavaScript debugging tools. It doesn't look like there's an ASP.NET or MVC issue here.
