### ISSUE TITLE
Disabling client validation breaks TH validation

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Razor#812]
From customer DISQUS comment:
https://docs.asp.net/en/latest/tutorials/first-mvc-app/validation.html

If I disable Client Validation using services.AddMvc().
```
AddViewOptions(options =>
{
options.HtmlHelperOptions.ClientValidationEnabled = false;
});
```

Server validation errors are not display with Tag Helper validation. Switching to HTML Helper validation,  errors are displayed.

**Comment by NTaylorMullen** [comment]
@Rick-Anderson could you please file this issue in Mvc? Doesn't seem to be a Razor related issue since the MVC TagHelpers are the ones responsible for dealing with validation logic.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#5102
