### ISSUE TITLE
Razor editor does not respect automatic brace completion setting

### ISSUE THREAD

**Issue by miloush** [aspnet/Razor#818]
1. Create a new or open existing cshtml file (can be isolated or in project).
2. Ensure _Automatic brace completion_ is disabled in Options > Editor > HTML/C# > General.
3. Type `@{` and hit Enter.

**Version used:** 15.0.25148.1
**Actual:** `}` is automatically inserted
**Expected:** no brace inserted as per the setting

This breaks the typing flow when users are used to manually enter the closing brace (as it works for `@for` etc.).

**Comment by Eilon** [comment]
@NTaylorMullen @ToddGrun any idea where this bug ultimately goes?

**Comment by NTaylorMullen** [comment]
Definitely on the tooling side. I'll move it.

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Tooling#712

**Comment by miloush** [comment]
Thanks @Elion and @NTaylorMullen, I was wondering whether it belongs here or to the tooling.
