### ISSUE TITLE
Escaped @ symbols are improperly handled at beginning of non-string TagHelper attributes

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#819]
This seems to be an edge case that wasn't fixed in https://github.com/aspnet/Razor/issues/436.

If you have the following TagHelper: `<myth non-string="@@@DateTime.Now" />` you end up having the 3rd `@` be handled as the transition character and the initial 2 @ symbols written to markup. Functionally there's no problem with this; however, in the editor you see the 3rd `@` symbol highlighted instead of the first which should have been fixed by 436.

Suppper edge casey and not high priority :+1:

**Comment by Eilon** [comment]
Why would it be an error for the 3rd `@` to be highlighted? Isn't that exactly correct?

**Comment by NTaylorMullen** [comment]
@Eilon in normal HTML, yes. In TagHelper land, no. In #436 we modified TagHelper attributes to allow a single `@` symbol at the beginning of your non-string TagHelper attribute if you wanted to be explicit in showing what was code and what wasn't. This means the first `@` symbol is escaped/ignored and the other `@` symbols are pure C# `@` symbols. The sample code `@@@DateTime.Now` would be a CSharp compilation error:

```C#
var th = new MyTH();
th.NonString = @@DateTime.Now;
```

**Comment by Eilon** [comment]
O I C. Totally not confusing at all 😄

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by rynowak** [comment]
Closing unless we get strong feedback
