### ISSUE TITLE
Creating a new fresh instance of  TagHelperExecutionContext for each TagHelper instance

### ISSUE THREAD

**Issue by frankabbruzzese** [aspnet/Razor#831]
At moment all instances of a specific tag within a `View`instance share the same instance of `TagHelperExecutionContext`,. The instance is just reinitialized(by calling its `ReInitialize`method) each time a new instance of the same tag is processed This works with the constraint that each tag processes its child content as soon it is called, otherwise it ends up working with  the `TagHelperExecutionContext`settings of another instance.
So if one encloses  `await output.GetChildContentAsync()` within a lambda for later execution the tag doesnt work properly. 
When designing complex tag helpers it might be useful to collect information from all children tag helpers and then processing everything in the appropriate order.  Thus, enclosing `await output.GetChildContentAsync()` wihin a lambda for later execution might be very useful. Let think for instance to a "column template" that needs to be executed several time on different rows.

Is there a way to prevent `TagHelperExecutionContext` recycling and forcing the creation of a new fresh  instance on a specific tag,?
Are the memory advantages of having just one `TagHelperExecutionContext` for all instances of the same tag within a View instance worth all constraints and rsks of sharing the same instance?

**Comment by NTaylorMullen** [comment]
@frankabbruzzese we also re-use `TagHelperOutput`s so I'd recommend not capturing the `output` in any way 😄 .

We've definitely considered adding an opt-out functionality to the `TagHelperOutput`/`TagHelperExecutionContext` pooling in the past. Maybe it wouldn't be so bad.

**Comment by frankabbruzzese** [comment]
In my opinion another interesting option would be to split `TagHelperExecutionContext `into two classes: 1) one storing the `_startTagHelperWritingScope `and `_endTagHelperWritingScope `functions that may continue being shared through several instances of each tag  since these two functions don't depend on the specific tag instance, and 2) another class  containing everything else, i.e, everything is reset when the Reinitialize methof is called. 
Everything but class 1) might be created again for each tag instance (included `TagHelperOutput `and `TagHelperContext`), since time and space saved by recycling these classes appears negligible when compared with the data structures they contain and that must be created again anyway for each instance(_allAttributes, Items, Output.Attributes,..).

**Comment by Eilon** [comment]
@frankabbruzzese can you provide more info on what your scenario is? We generally recommend buffering output because the execution of tag helpers is designed to be essentially sequential, meaning you can't delay the execution of components.

**Comment by frankabbruzzese** [comment]
Hi @Eilon,
When designing complex controls like a grid this sequentiality constraint creates problems. In fact  one needst o put all settingsin children TagHelpers, and some of them may be custom column templates.
I'll do an example with a grid TagHelper I implemented.
Simplest case grid without children tags:
```
<grid asp-for="Products.Data"
              type="Immediate"
              all-properties="true"
              mvc-controller="typeof(GridTestController)"
              operations="x => Functionalities.FullInLine"
              class="table table-condensed table-bordered"/>
```
In this case all columns are rendered with default templates..**.  Obviously no pronlem with sequentiality constraint**.
Now suppose I want to declare a certain colum contain an external key to be selected by user with a `<select>`. I need To add a child tag helper to specify this setting:
```
<grid asp-for="Products.Data"
              type="Immediate"
              all-properties="true"
              mvc-controller="typeof(GridTestController)"
              operations="x => Functionalities.FullInLine"
              class="table table-condensed table-bordered">
            <column asp-for="Products.Data.Element().TypeId">
                <external-key-static display-property="Products.Data.Element().TypeName"
                    items-selector="@getTasks"
                    items-value-property="Value"
                    items-display-property="Display"
                     />
            </column> />
        </grid>
```
Settings specified in children tag helpers are read only once and then used to render all grid rows....**Again no problems with sequentiality constraint**, since children taghelper are executed immediately just to read their settings: then settings are put in a data strucure and this data structure is re-used for each row rendered.

**Problems arise if one would like to specify a custom in-line template for another column**:

```
<grid asp-for="Products.Data"
              type="Immediate"
              all-properties="true"
              mvc-controller="typeof(GridTestController)"
              operations="x => Functionalities.FullInLine"
              class="table table-condensed table-bordered">
            <column asp-for="Products.Data.Element().TypeId">
                <external-key-static display-property="Products.Data.Element().TypeName"
                    items-selector="@getTasks"
                    items-value-property="Value"
                    items-display-property="Display"
                     />
            </column> />
            <column asp-for="Products.Data.Element().Description">
               <asp-template type="Edit">
                    @{ {
                       var Model = Html.Item<string>();
                    <div class="form-group col-xs-12">
                        <label asp-for="@Model" ></label>
                       <textarea class="form-control" asp-for="@Model"></textarea>
                       <span asp-validation-for="@Model" class="text-danger"></span>
                    </div>
                 } }
             </asp-template>
       </column>
</grid>
```

In fact, in this case the content of the `asp-template` tag needs to be executed one time for each row rendered so I need to put its `await output.GetChildContentAsync()` call within a lambda to be executed for each row rendered. Actually, with just one in-line template defined everything works fine since the `asp-template`  tag helper data structures are not shared with any other instance of the same tag. Confusion arise with at least two in line templates defined within the same grid....Data structure are shared among the so both columns are rendered with the template defined in the last` asp-template` tag.

**Comment by frankabbruzzese** [comment]
One might think to re-execute all grid tag children  once for each row rendered, to conform to the sequentiality constraint. However, not only  this is very unefficient and forces "unclean code", but also it is not possible in general, since the grid tag might contain also children  tags describing toolbars, and alteranate row templates (alternate sets of  column specifications, to be selected on a per item basis).

**Comment by frankabbruzzese** [comment]
One might enable a specific TagHelpers to get a "private" copy of its TagHelperOutput, so that taghelper needing to delay execution might require it. Something like: output.export() -> private TagHelperOutput.
This private copy shoud have a `GetChildContentAsync` frozen at the moment output.export() was called.

**Comment by Eilon** [comment]
@NTaylorMullen @DamianEdwards @rynowak any further thoughts on this? Would we implement anything for this in vNext?

**Comment by DamianEdwards** [comment]
My initial thoughts are this isn't the "right fix" for the scenario here. [Templated Tag Helpers](https://github.com/aspnet/Razor/issues/788) are something we want to support and would be a more appropriate solution here I think. Anything that encourages executing Tag Helper contents as they are today out of order with the normal sequence of events is bad IMO. Doing so suggests concurrency and thus, potentially, thread safety, which we **definitely** do not guarantee (page rendering and indeed request processing in generaly is inherently not thread safe).

Ultimately, Tag Helpers are not a DOM-based approach to rendering, but rather a forward-only, sequential system. Without proper support for Razor templating (and templated Tag Helpers in turn) it's difficult to achieve the types of scenarios above.

**Comment by Eilon** [comment]
Makes sense to me, so closing this.

**Comment by frankabbruzzese** [comment]
[Templated Tag Helpers](https://github.com/aspnet/Razor/issues/788) implementation would be simply perfect!

**Comment by Eilon** [comment]
@frankabbruzzese yup, that's the direction we want to go in!

**Comment by rynowak** [comment]
We should look into making the 'context' optional in any future endeavors in this area. This is big part of the cost of executing taghelpers today.
