### ISSUE TITLE
MVC6 Razor views are not compiled at runtime. Console application project.

### ISSUE THREAD

**Issue by rusanov-vladimir** [aspnet/Razor#834]
I have problem similar with [Cannot use types from class libraries (csproj) in razor views ](https://github.com/aspnet/Razor/issues/755). When some MVC Razor View is requested at runtime no reference is found:
![Image](http://content.screencast.com/users/E1f/folders/Jing/media/1215d6f6-5be5-42d2-b397-89cbbbd7dc5c/2016-10-21_1750.png)
Workaround with context.Compilation works for me, but it still a workaround and I'm looking for a real solution. The main difference in my approach is I'm not using .NET CORE SDK to create MVC6 app, but installed all required packages in a simple Console application project. Not using project.json, but packages.config. Building from command line with MsBuild 14.

Any thoughts on this?

If neccessary I can upload repro project.

**Comment by rusanov-vladimir** [comment]
Thanks, so instead of adding all the references in compilation callback I'm adding additional references to the AdditionalCompilationReferences collection and it works just fine:

    services.AddMvc()
        .AddRazorOptions(
            options
                => {
                var assemblies = AppDomain.CurrentDomain.GetAssemblies().ToList();
                assemblies.Add(typeof(Microsoft.CSharp.RuntimeBinder.Binder).Assembly);
                var refs = assemblies
                    .Where(x => !x.IsDynamic && !string.IsNullOrWhiteSpace(x.Location))
                    .Select(x => MetadataReference.CreateFromFile(x.Location))
                    .ToList();
                foreach (var portableExecutableReference in refs) {
                    options.AdditionalCompilationReferences.Add(portableExecutableReference);
                }
            });


But I'm still wondering if it's a workaround or the intended behavior?... Seems strange, that I have to explicitly specify to RazorEngine to load even mscorlib.dll, not talking about some 3rd party library.

**Comment by NTaylorMullen** [comment]
@rusanov-vladimir You should only need to add assemblies that aren't referenced by your project. Do you have `"preserveCompilationContext": true` in your `buildOptions`?

**Comment by rusanov-vladimir** [comment]
@NTaylorMullen  `preserveCompilationContex`t Is a build option of `project.json`. Since I'm not installing .NET Core SDK (project constraint - web-site should be built on client's machine where it's not available), I'm unable to set that option, because there is no `project.json`, just regular .csproj. Is there a way to set this option via code? Doubt that MsBuild could have some option for it...

**Comment by NTaylorMullen** [comment]
@rusanov-vladimir this is our detection logic in MVC: https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/AssemblyPart.cs#L48

**Comment by rusanov-vladimir** [comment]
@NTaylorMullen Pardon my ignorance, but I don't understand how this information could help me. As I understand MVC is relying on `.deps.json` file, that is generated by `cli` during the build. Since there is no `.deps.json` generated in my case ` DependencyContext.Load` returns null and GetReferencePaths() returns assembly itself, which is not enough for RazorCompiler to succeed. Currently I'm feeding all the assemblies in my output directory to the Razor Compilation, but I susspect at least 2 issues with this:
1. performance - I'm loading unneeded stuff
2. GAC references - If a reference is not copied to output, like GAC references, it's not considered during Razor Compilation.
I'm not sure if I could generate `.deps.json` without 'project.json', but I don't needed it, it's enough to know which references should be included for Razor Compilation.

**Comment by rusanov-vladimir** [comment]
@pranavkm Thank you for details! I will check if I could adapt the solution with MsBuild. Regarding the issues I've mentioned: 
1. Great, didn't think of it!
2. Here I have some doubts: In my snippet you could notice, that I'm adding explicitly Microsoft.Csharp.dll. The reason is that without it on a clean machine(only .NET 4.5.2 installed) I'm getting following error during Razor Compilation:
![csharpdll](https://cloud.githubusercontent.com/assets/3341799/19716919/d10fe842-9b66-11e6-9ee9-ffc1a1642f4a.png)
It's hardly reproduced on my development machine. I thought that the reason for this to happen is that Microsoft.Csharp.dll is referenced from GAC and not copied in output. Adding Microsoft.Csharp.dll to the list of libraries fixes the issue, but I'm worried if there would be no other lib that might be missing.

**Comment by pranavkm** [comment]
The `Microsoft.CSharp` scenario is interesting. Mvc references the package (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/project.json#L47), so using `DependencyContext` \ `preserveCompilationContext` in a project.json world would've added this reference to your project. 

One way to ensure you're not missing these binaries might be to restore a `net4x` targeting project.json- based class library that has `Microsoft.AspNetCore.Mvc` as a solitary reference. The `project.lock.json` that gets produced as part of restore should include the closure of binaries that you would have picked up transitively as a result of referencing Mvc.

**Comment by rusanov-vladimir** [comment]
@pranavkm  Finally I've tried your suggestion. The result is not exactly as I've expected. First of all, I've noticed that when building a project.json-world solution without any reference at all, there are 4 compile referencies in -compile.deps.json. I'm not sure if it's related to my issue and it's enough just to add them to `AdditionalCompilationReferences`.

**project.json:**

		{
		  "dependencies": {
			/*"Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final"*/
		  },

		  "tools": {
		  
		  },

		  "frameworks": {
			"net452": {}
		  },

		  "buildOptions": {
			"emitEntryPoint": true,
			"preserveCompilationContext": true
		  },

		  "publishOptions": {
			"include": [
			  "wwwroot",
			  "web.config"
			]
		  },

		  "scripts": {
			"postpublish": [
			  "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
			]
		  }
		}

**-compile.deps.json**

		{
		  "runtimeTarget": {
			"name": ".NETFramework,Version=v4.5.2/",
			"signature": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
		  },
		  "compilationOptions": {
			"defines": [
			  "DEBUG",
			  "TRACE",
			  "NET452"
			],
			"platform": "x64",
			"optimize": false,
			"emitEntryPoint": true
		  },
		  "targets": {
			".NETFramework,Version=v4.5.2": {
			  "MvcCoreApp/1.0.0": {
				"compile": {
				  "MvcCoreApp.exe": {}
				}
			  },
			  "mscorlib/4.0.0.0": {
				"compile": {
				  ".NETFramework/v4.5.2/mscorlib.dll": {}
				}
			  },
			  "System/4.0.0.0": {
				"compile": {
				  ".NETFramework/v4.5.2/System.dll": {}
				}
			  },
			  "System.Core/4.0.0.0": {
				"compile": {
				  ".NETFramework/v4.5.2/System.Core.dll": {}
				}
			  },
			  "Microsoft.CSharp/4.0.0.0": {
				"compile": {
				  ".NETFramework/v4.5.2/Microsoft.CSharp.dll": {}
				}
			  }
			},
			".NETFramework,Version=v4.5.2/": {
			  "MvcCoreApp/1.0.0": {
				"runtime": {
				  "MvcCoreApp.exe": {}
				}
			  },
			  "mscorlib/4.0.0.0": {},
			  "System/4.0.0.0": {},
			  "System.Core/4.0.0.0": {},
			  "Microsoft.CSharp/4.0.0.0": {}
			}
		  },
		  "libraries": {
			"MvcCoreApp/1.0.0": {
			  "type": "project",
			  "serviceable": false,
			  "sha512": ""
			},
			"mscorlib/4.0.0.0": {
			  "type": "referenceassembly",
			  "serviceable": false,
			  "sha512": ""
			},
			"System/4.0.0.0": {
			  "type": "referenceassembly",
			  "serviceable": false,
			  "sha512": ""
			},
			"System.Core/4.0.0.0": {
			  "type": "referenceassembly",
			  "serviceable": false,
			  "sha512": ""
			},
			"Microsoft.CSharp/4.0.0.0": {
			  "type": "referenceassembly",
			  "serviceable": false,
			  "sha512": ""
			}
		  }
		}

In case I'm adding  `"dependencies": {"Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final" }`, I'm getting a long project.lock.json. Analyzing it I've noticed that there are quite a lot `"runtime"` dependencies. So I suppose that you meant to extract all "runtime" dll's in a list and supply that list to Razor's `AdditionalCompilationReferences`? But the problem is again with Microsoft.CSharp package:

      "Microsoft.CSharp/4.3.0-preview1-24530-04": {
        "type": "package",
        "frameworkAssemblies": [
          "Microsoft.CSharp"
        ],
        "compile": {
          "ref/net45/_._": {}
        },
        "runtime": {
          "lib/net45/_._": {}
        }
      },

There is no dll specified for this case. Maybe it's because in my case library is available from GAC?

**Comment by pranavkm** [comment]
I guess for desktop you might have to additionally look at `frameworkAssemblies` which is the set of assemblies that come from the GAC. You should be able to `Assembly.Load` those by name and add it to `AdditionalCompilationReferences`. 

> In case I'm adding "dependencies": {"Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final" }, I'm getting a long project.lock.json.

As part of the 1.1.0 milestone, we switched to adding `NETStandard.Library` to all our projects. (https://github.com/aspnet/WebListener/issues/268 has some discussion about our rationale for this). Consequently you end up with a whole slew of references as a result of referencing Mvc.

**Comment by rusanov-vladimir** [comment]
@pranavkm  Thank you a lot for looking into this. For me things are getting too complicated now to continue this way.
1. For `Microsoft.AspNetCore.Mvc` project I could theoretically gather all the "runtime" and "frameworkAssemblies" assemblies that are indicated in project.lock.json, but what if I'll add some other nuget package later, that add some other dlls transitively? I would be restricted to perform such routine on every package change.
2. Loading assemblies from GAC using Assembly.Load by name indicated in "frameworkAssemblies" isn't working, because I have to specifify fully qualified name, but I get something like "Microsoft.CSharp". I could use something like [this](http://stackoverflow.com/a/6131116/5246145) but I'm unsure that it worth it.
3. Another point of concern is that cshtml files should be compiled with the rest of solution(I want to know at compile time about all possible errors, not on runtime). That is another thing I would have to struggle with.

I was hoping that there is was some "standard way" of dealing with all these problems when using MVC6 in csproj projects, but seems not and such "standard way" is coming with new version of msbuild.  

I think we can close this for now.

**Comment by pranavkm** [comment]
1 / 2. Unfortunately the choice of using a .csproj until MsBuild based tooling is available is going to cause a bunch of friction. 
3. We released a CLI based tool (https://github.com/aspnet/MvcPrecompilation, https://www.nuget.org/packages?q=Microsoft.AspNetCore.Mvc.Razor.Precompilation) as part of the 1.1.0 preview release. That might help with performing build time compilation.
