### ISSUE TITLE
Its possible use Razor like a "Run-Time Text Generation"?

### ISSUE THREAD

**Issue by juniorgasparotto** [aspnet/Razor#841]
Hi,

It's possible use the Razor engine like "Run-Time Text Generation" (file.tt)?

If not, I suggest the following change:
Replace the files ".tt" by Razor, after all, the syntax is better known and very much easy

[]s.

**Comment by Eilon** [comment]
Yes, absolutely. Check out what we do in https://github.com/aspnet/Diagnostics/tree/dev/src/Microsoft.AspNetCore.Diagnostics with the various CSHTML files. We use the Razor parser to generate the C# code, then we compile that C# code into the assembly. Then at runtime we run that C# to generate HTML.

And we also have another sample showing how to use Razor to render to a string: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

**Comment by juniorgasparotto** [comment]
Glad to know that.

Just two questions.

1) Is Visual Studio already prepared to edit "cshtml" files in non-WEB projects? I tried it and it does not seem to recognize some syntax like: @model.

2) Finally, if the Razor is capable of generating several types of files, should the "file.cs**html**" extension not change to something more generic like "file.razor"?

Thank you

**Comment by Eilon** [comment]
For question 1, there's some discussion here: https://github.com/aspnet/RazorTooling/issues/91. The short answer is that there isn't good support for this yet.

For question 2, I defer to @NTaylorMullen as to how Razor works with files of other extensions. I'm guessing it doesn't matter a whole lot because it's usually something like a view engine that reads files and passes it to the Razor parser.

**Comment by NTaylorMullen** [comment]
@juniorgasparotto We've discussed changing Razor's extensions but doing that results in a lot of fall out from Visual Studio editor support. On the other hand, you could absolutely make that work at runtime.

**Comment by pranavkm** [comment]
Just a note, some features like `@model` and the choice of the file extension are behaviors \ features that Mvc builds on top of the Razor parser.
