### ISSUE TITLE
Add RazorProject - an abstraction for working with Razor files in a project

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#842]
Based on the type here - https://github.com/aspnet/RazorPages/blob/master/src/Microsoft.AspNetCore.Mvc.RazorPages/Razevolution/RazorProject.cs#L12. We have the need to look up Razor files and navigate the project hierarchy in a specific order to get at files that are relevant when parsing other files. The goal here is to create an abstraction for this.

**Comment by toddams** [comment]
Hello there,
What if I want to create my own RazorProject that works with embedded resources? Seems like this abstraction is tightly coupled with files, as there are such properties as FilePath, PhysicalPath etc.
Is it even possible to utilize this classes, or this abstraction for MVC needs only?
Thanks

**Comment by pranavkm** [comment]
@toddams - Mvc has a adapter for this from `IFileProvider` which includes `EmbeddedFileProvider`: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/FileProviderRazorProject.cs#L15. That said, I'd recommend starting a new issue to discuss this further rather than used this closed work item.
