### ISSUE TITLE
Allow await to be invoked inside of HelperResult bodies

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#85]
The body of `Templates`\ `HelperResult` is synchronous which disallows calling await inside of it. We need to start generating async lambdas for these types. In addition, since `HelperResult` represents a deferred write operation, we additionally need to modify the code generated from `@await` calls to be awaitable rather than awaiting inside of it:

e.g. `C# @await Foo() ` is generated as `Write(await Foo());` but should instead be generated as `await WriteAsync(Foo());`

**Comment by pranavkm** [comment]
Based on https://github.com/aspnet/Razor/issues/281, we're currently removing `@helpers` from Razor until we have a better design.
