### ISSUE TITLE
Tooling Standalone: Define Razor lanuage service

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#852]
We want to define a Razor language service that is host independent. This will be used by VS but not tied to VS

**Comment by NTaylorMullen** [comment]
@rynowak I'm envisioning this bit as what I'm currently working on. Let me know if I'm misreading the purpose of this issue 😄

**Comment by rynowak** [comment]
We should come up with smaller items here and close this, it's *TOO BIG TO TRACK*

**Comment by NTaylorMullen** [comment]
Closing this since this is more-or-less a super-meta-issue
