### ISSUE TITLE
Could I make Razor Engine as precompiled templates as a cache?

### ISSUE THREAD

**Issue by alexsandro-xpt** [aspnet/Razor#866]
When I worked with PHP, I remeber the `Smarty PHP Template Engine` this was very good at that time.

I remember a feature called Caching http://www.smarty.net/docsv2/en/caching.tpl I could set some cache lifetime for template and the a complied template file was writed on the disk making quick access and request instead every time connect to database and others external dependences.

I would like to know, we have some feature like that in ASP Net Core Razor? And why not?

Thanks

**Comment by saitolabs** [comment]
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response

**Comment by alexsandro-xpt** [comment]
@saitolabs I'm not looking for HTTP cache feature, I looking for a precompiled templates managed by my own lifetime.

**Comment by pranavkm** [comment]
The `CacheTagHelper` might be somewhat analogous. Here's a pretty detailed article about what it is and how it works - http://www.davepaquette.com/archive/2015/06/03/mvc-6-cache-tag-helper.aspx

**Comment by alexsandro-xpt** [comment]
Right @pranavkm, but the `CacheTagHelper` is not enogth, it's should have an API to ask if a template is in cache lifetime before I instanciate and build my `viewmodel` because my `viewmodel` could have hight cost like query slow database, request a remote API and something else.

**Comment by Eilon** [comment]
@alexsandro-xpt can you give a pseudo-code example of how you might like to use such a feature? I think I get the gist of it, but I'd like to see what you have in mind. Thanks!

**Comment by alexsandro-xpt** [comment]
Ok @Eilon, a quick sample bellow, this feature could be work like this:

```
public class HomeController : Controller
{
    ...
    public IActionResult Index([FromServices]IMemoryCache cache)
    {
        //Caching could be cofigured at Startup.cs as InMemory, Tmp Local File or Redis as prefer.
        this.ViewEngine.EnableCaching(true);
        var templateView = "Index";

        var dbChangesFlag = _servicesHomePage.CountItens()

        var cacheId = "MyHomePage" + dbChangesFlag; //MyHomePage5

        if(!this.IsCachedView(templateView, cacheId,/*Optional lifetime*/))
        {
            var someItens = _servicesHomePage.GetSlowAllItens();
            //some hard work....
        }

        return View(templateView, cacheId);
    }

    ...
}

```
Another implementation could work with ViewComponents or child Views.

Thank you.

**Comment by alexsandro-xpt** [comment]
Another way to do that is with `Microsoft.Extensions.Caching.Memory`:

public class HomeController : Controller
{
    public IActionResult Index([FromServices]IMemoryCache cache)
    {

        var dbChangesFlag = _servicesHomePage.CountItens()
        var cacheId = "MyHomePage" + dbChangesFlag;

        var html = cache.GetOrCreate<string>(cacheId, context =>
            {
                context.SetAbsoluteExpiration(TimeSpan.FromSeconds(20));
                context.SetPriority(CacheItemPriority.High);


                var someItens = _servicesHomePage.GetSlowAllItens();
                //some hard work....
                var calc = _servicesHomePage.Calc();

                var viewBag = new { Calc = calc }
                var viewModel = someItens;
                return this.RenderView(templateView, viewModel, viewBag); // I don't know if Rasor have a method like that, it's useful...
            });

        return Cotent(html);
    }
    ...
}

**Comment by alexsandro-xpt** [comment]
Looking for on-demand Template Engine, I found it http://antaris.github.io/RazorEngine/ may I could cache compiled HTML.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this type of caching as part of the system. From the code you have it looks like you've been able to build this out for your app, so we recommend sticking with that.

**Comment by alexsandro-xpt** [comment]
@Eilon This code is only example of how it could work. By the way, this no exist yet.

**Comment by Eilon** [comment]
@alexsandro-xpt yep, I understand that, I'm just recommending that if you need this feature that your current code should be a good start.

**Comment by alexsandro-xpt** [comment]
Allright!
