### ISSUE TITLE
Javascript formating not work with c# code without quotas

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/Razor#871]
For example some time need insert value to javascript code in cshtml files:
```
<script>
var value = @ViewBag.Id;
</script>
```
but formatting not working until add quotas:
```
<script>
var value = '@ViewBag.Id';
</script>
```

**Comment by dougbu** [comment]
@mojtabakaviani what are your expectations exactly?

`@ViewBag.Id` inserts the current value into the generated HTML / JavaScript. So, unless that value happened to be a valid literal, I'd expect JavaScript errors in the first example.

**Comment by mojtabakaviani** [comment]
No any error, just in the first example formatting not working. can not inserts numerical or code without literals.

**Comment by dougbu** [comment]
Sounds like the system is working as-expected. Or, what special-casing were you requesting here?

Suggest looking at the generated HTML and confirming.

**Comment by mojtabakaviani** [comment]
I think formatting not support this scenario and must add this feature.

**Comment by Eilon** [comment]
@doug the quotes are needed only for certain data types, e.g. strings. If the id is a numeric type the quotes would be incorrect.

I am able to reproduce the problem in VS2015 U3:

1. Create new ASP.NET Core app
2. In a Razor file, add this snippet:
```html
<script>
    var value   =   @ViewBag.Id;
</script>
```
(Note all the extraneous spaces around the `=` sign.)
3. Press <kbd>Ctrl</kbd>+<kbd>K</kbd>, <kbd>Ctrl</kbd>+<kbd>D</kbd> to Format Document

Expected: The JavaScript code should be better-formatted by trimming the extraneous spaces around the `=` sign.

Result: No formatting takes place.

However, if you wrap the `@ViewBag.Id` in quotes, i.e. `'@ViewBag.Id'`, then repeat, it all works great.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Tooling#913
