### ISSUE TITLE
Support adding attributes to `IDictionary<string, TValue>` properties

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#89]
It will look something like this:

```C#
public class MyTagHelper : TagHelper
{
    public Dictionary<string, string> route { get; set; } // Can be <string, T>
    
    [AttributeName("something-")]
    public IEnumerable<KeyValuePair<string, int>> something { get; set; }
    
    public override Process(.....
}
```

This will then enable us to do things like:

```HTML
<mytaghelper routeFoo="hello" routeBar="world" something-foo="Hi" something-bar="earth" />
```

Which will then populate route with:
```
{
    "Foo": "hello",
    "Bar: "world"
}
```

And would populate 'something' with:
```
{
    "foo": "Hi",
    "bar: "earth"
}
```

**Comment by NTaylorMullen** [comment]
Talked in person, can be re-triaged doesn't need to happen now.

**Comment by dougbu** [comment]
@Eilon @danroth27 suggest we should try and get this done early in Beta5.  right now it's languishing in the Backlog.  but it feels more urgent than for example #182.

@DamianEdwards the system could enable authors to differentiate properties that should be bound to a single dictionary expression from ones that should be bound to zero or more attributes. it could also special-case attributes with the exact name (to be dictionary-valued) or ignore such attributes.  i.e. `<a route-aaa="bbb" route="@myDictionary"/>` might be up to the tag helper author, legal, or illegal.  which do you prefer?

**Comment by Eilon** [comment]
Moving out of backlog so we'll revisit in triage.

**Comment by dougbu** [comment]
renamed to "Support adding attributes to `IDictionary<string, TValue>` properties"

**Comment by dougbu** [comment]
- aspnet/Common@aae8e6e
- aspnet/Mvc@61b76fd
- 7dc0508
- 94f2f90
- 60c47c8
- aspnet/Mvc@517c013
