### ISSUE TITLE
Razor generates class names that violate code style guidelines

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#896]
![image](https://cloud.githubusercontent.com/assets/2008729/21153052/c015ed0c-c11d-11e6-94e1-0aee2f482a56.png)

**Comment by Eilon** [comment]
This is a very obnoxious rule, is it on by default in VS2017?

We could presumably mark these types as compiler-generated, which would hopefully quite these rules down, but I think that's somewhat beside the point.

cc @DamianEdwards

**Comment by Eilon** [comment]
Ok looks like maybe it's on by default... The rule's code is here: https://github.com/dotnet/roslyn

But I'm not sure who decides whether it's on by default or not.

**Comment by DamianEdwards** [comment]
I think the meta-issue here is that those rules shouldn't be applying to anything in a non-projected part of the language editor buffer. We should log that issue with Roslyn.

**Comment by Eilon** [comment]
I personally thing this rule shouldn't be on by default at all. But I agree we ought to make things better for those who choose to have this rule enabled.

**Comment by NTaylorMullen** [comment]
Looks like Roslyn will fix this after all https://github.com/dotnet/roslyn/issues/15903 👍 .
