### ISSUE TITLE
Attributes with statements (@if, @do etc.) do not accurately represent source.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#897]
One of the draw backs of the attributes not representing source is that instrumentation breaks down resulting in inaccurate indexes when mapping runtime code to source code.

You can see this [here](https://github.com/aspnet/Razor/blob/1b3863044dec1d9edfb53ef9c9506ca07ec0e3fc/test/Microsoft.AspNetCore.Razor.Evolution.Test/Legacy/TagHelperBlockRewriterTest.cs#L1476-L1479). There should be a space represented but there's not.

**Comment by rynowak** [comment]
Note that the new parser codebase enforces an invariant that spans must be contiguous, and all parsed text must be a member of a span. This causes several test failures that we're skipping for now.

**Comment by ajaybhargavb** [comment]
8bba757703475c0f5abc8d003ff678d1210cf3cd
