### ISSUE TITLE
Small mistake in 'CSharpLanguageCharacteristics'

### ISSUE THREAD

**Issue by Yves57** [aspnet/Razor#924]
Is there a small mistake in [Right Shift Assign](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Evolution/Legacy/CSharpLanguageCharacteristics.cs#L61) (`>>>` instead of `>>=`)?

**Comment by NTaylorMullen** [comment]
Totally is. Good find. Thankfully we don't special case it anywhere. This might impact other users who tried to extend the Razor parsing system though (unlikely, but possible).

**Comment by Yves57** [comment]
OK. I close it, I suppose?
