### ISSUE TITLE
Razor shows "The name <objname> does not exists in the current context"

### ISSUE THREAD

**Issue by wh1sp3r** [aspnet/Razor#928]
Hi,
I am using console application with full .NET framework with AspNetCore libraries to host webpages.
Everything is working fine ( Compiling, Running ), but any object like var,await, inject, model, etc are underlined with error I specified on the title. It's kind of **cosmetic problem**, becuase I can run it and all Views are rendered correctly.
If i use class library based on .NET Core .. Views are fine.

I created a small project. If you open Index.cshtml from AspNetCoreRazorTest ( full .NET class library ), @model is underlined. if you open Index.cshtml from AspNetCoreRazorTest_Core ( .NET core class library ), it's without any problem.

[https://1drv.ms/u/s!AjM4CQ0E6R2rkaRzOj1PtS_LiN7YgA](https://1drv.ms/u/s!AjM4CQ0E6R2rkaRzOj1PtS_LiN7YgA)

I would like to ask, what should I do ? Thank you very much for your help.

**Comment by Eilon** [comment]
@pranavkm is this the same as the general issue of Razor editor experience not working in class libs?

**Comment by pranavkm** [comment]
I'll have a look.

**Comment by pranavkm** [comment]
@wh1sp3r what version of VS are you using? The csproj format you have looks like it came from VS 2015 (or lower). I'm not entirely sure if tooling is wired up at all to work with AspNetCore Razor based applications in this scenario.

Might I recommend trying out VS 2017 (https://www.visualstudio.com/downloads) and using the .NET Core Class library project template? There's a separate issue that causes intellisense in these class library projects from not showing up, but it can be easily remedied - https://github.com/aspnet/Mvc/issues/5975#issuecomment-287095173

**Comment by svallis** [comment]
@pranavkm You say it can be easily remedied, but unless I'm missing something the "fix" breaks project compilation. As I reported in the issue you linked to, it seems you currently have to chose between either having intellisense (with Microsoft.NET.Sdk.Web` specified), or being able to build your project (with `Microsoft.NET.Sdk` specified).

**Comment by pranavkm** [comment]
@svallis guess we could close this since https://github.com/aspnet/Mvc/issues/5975 is resolved?

**Comment by svallis** [comment]
Sure @pranavkm - I only posted here as I figured your comment that it was easily remedied either meant you hadn't seen that the fix broke things for me or there was an easy fix for the fix. Glad it was the latter.
