### ISSUE TITLE
Add errors for multiple tagHelperPrefix directives in the same file

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#942]
Currently Razor will use the (lexical) first `@tagHelperPrefix` in each file and will report an error for each subsequent one. This allows views to override an imported `@tagHelperPrefix` but not to specify it multiple times in the same file.

After some discussion, it's likely that this semantic should be applied to more of our directives or at least applied at a different layer than it is today. I'm logging this issue to follow up with implementing this validation since we're temporarily adding support for the taghelper directives without preserving the current behavior.

**Comment by NTaylorMullen** [comment]
05cc4123a75150dd84a352bebde7f805b2f9ae97
