### ISSUE TITLE
Add keyword safe list for editor identifier replacements

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#949]
Today if you type `@B` and autocomplete it with a `.` to `@base.` you will not get IntelliSense because Razor picks up the change as a replacement that resulted in a CSharp keyword. We can special case specific keywords that wont require full re-parses (will provide IntelliSense).

The list that comes to mind is:

```
"this",
"base",
"true",
"false",
"byte",
"short",
"ushort",
"float",
"uint",
"double",
"object",
"sbyte",
"decimal",
"string",
"ulong",
"bool",
"char",
"long",
"int",
```

**Comment by rynowak** [comment]
@NTaylorMullen - what's the relative priority of this?

**Comment by NTaylorMullen** [comment]
@rynowak Not game changing but should be done once we have time for polish. Users don't typically type one of these reserved keywords and auto-complete them with a dot.

**Comment by rynowak** [comment]
I'm parking this in the backlog then until we have a good reason to do it.

**Comment by rynowak** [comment]
Closing until we get a complaint
