### ISSUE TITLE
Need a way to opt-out of tag helper at pre-compile time.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#95]
If an HTML element is a tag helper it will be code genned as a tag helper no matter what.  We need to add a way for a tag helper to provide a way to "opt-out" of tag helperifying an html element at compile time.

**Comment by yishaigalatzer** [comment]
my 2c this can happen post RTM.

**Comment by NTaylorMullen** [comment]
This item is not possible until we have more concrete support in the DTH for `TagHelper`s/executing user code.

**Comment by yishaigalatzer** [comment]
We shouldn't rely on user code in dth. Lets talk

-----Original Message-----

**Comment by NTaylorMullen** [comment]
Pinging this because we still need to talk :smile:

**Comment by NTaylorMullen** [comment]
Talked in person, I think we can skip this for now.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
