### ISSUE TITLE
Bound Attributes are lowered to IR as html instead of expressions

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#963]
Given this document:
```
@addTagHelper TestTagHelper, TestAssembly
<p foo="17">
```

And a matching taghelper where `foo` is bound to an `int`, this will appear in the IR as an HTML node, where we should be able to clearly know that it's C#.

**Comment by rynowak** [comment]
When this is fixed, look to `ModelExpressionPass` in MVC for some cleanup.

**Comment by ajaybhargavb** [comment]
7bd13061b5aee380a0acdbdc1d1a58e8d2da9445
