### ISSUE TITLE
CSharpStatementIRNode shouldn't have Content property

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#964]
We use the statement node for `@{ ... }` blocks as well as things like `@functions { ... }`. We shouldn't just put a content property on it, we should have it use tokens. That way we can compose multiple tokens into a complex statement, while maintaining a line mapping for part of it. An example of where we need this is for `@inject`

**Comment by ajaybhargavb** [comment]
@rynowak, are you saying we should make this identical to `CSharpExpressionIRNode`?

**Comment by rynowak** [comment]
Yes and no. It needs to be its own distinct type because the difference between statement and expression is semantically meaningful.

But yes, it should follow the same pattern as expressions.
