### ISSUE TITLE
Replace RazorError with RazorDiagnostic in public API

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#972]
As part of the MVC migration, I had to make RazorError public and use it in a few places in MVC. We need to make it internal again and use `RazorDiagnostic` in all public API.

**Comment by rynowak** [comment]
There's a WIP commit here https://github.com/aspnet/Razor/tree/rynowak/diagnostics

We should make sure we do this throughout the public API, and then make `RazorError` and `ErrorSink` internal again. 

This will require a reaction PR is MVC and possibly also entropy.

**Comment by ajaybhargavb** [comment]
ed9068cef4b4a73fe01814025476d066ee0ef1b7 and aspnet/Mvc@0f5d5ff3b5f74d0b475c8a6edfcd81bdacad6fe7
