### ISSUE TITLE
Update Razor to use new ServiceHubServiceBase ctor

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#976]
See: https://github.com/dotnet/roslyn/pull/16943

We will need to update our shim to follow the recommended pattern once these bits are available.

**Comment by rynowak** [comment]
As of today the Roslyn bits have marked the old ctor as obsolete, but the servicehub does not yet work with the new ctor

**Comment by rynowak** [comment]
The work item here is to try this on a new build of VS and see which constructor gets used by servicehub. Then we'll know if we can remove the obsolete one.

**Comment by NTaylorMullen** [comment]
Waiting on VS to take newer Roslyn bits to make this possible.

**Comment by NTaylorMullen** [comment]
870b2640395a9986230cdf131a6be271d74f21f9
