### ISSUE TITLE
Make conditional attributes work for data- attributes

### ISSUE THREAD

**Issue by leo-ridgewood** [aspnet/Razor#978]
Conditional attributes were introduced in MVC4 whereby if an attribute is set to a null value then the entire attribute was omitted. This isn't covered in the release notes, but is referred to [here](https://weblogs.asp.net/jongalloway/asp-net-4-beta-released). Here is an example:

`<div class="@(null)">`  ->  `<div>`

Presumably for backwards compatibility with some code that was confusing blank and null, this does not work for data- attributes. This behaviour is unexpected, hard to work around and not documented anywhere except in the source. Until you realise that it is data- attribute specific it is also very hard to find references to it. Example:

`<div data-anything="@(null)">`  ->  `<div data-anything="">`

It is a very simple code change, but the question is whether compatibility issues are still a concern?

I see that other long-standing issues in MVC that had (presumably) not previously been fixed for backwards compatibility reasons have now been fixed in MVC Core, for example calling Html.Partial with a null model used to pass the callers model (without a nasty workaround) but now works as expected. 

References (only really discoverable once you realise it is data- specific):
[http://stackoverflow.com/questions/17545045/weird-behavior-with-conditional-data-attributes](http://stackoverflow.com/questions/17545045/weird-behavior-with-conditional-data-attributes)
[http://stackoverflow.com/questions/13267619/razor-conditional-attribute-not-working](http://stackoverflow.com/questions/13267619/razor-conditional-attribute-not-working)

**Comment by NTaylorMullen** [comment]
@leo-ridgewood `data-` attributes by spec are intended to be used on the client which is why we don't enable conditional attributes on them (server functionality). This is also true with TagHelper bound attributes; they cannot use `HtmlAttributeName` to specify a `data-` attribute.

**Comment by pranavkm** [comment]
To expand on @NTaylorMullen's comment, the presence of an empty `data-` attribute might be used to make a decision on the client. (e.g. `document.querySelectorAll('[data-anything]')`). Removing this would be a breaking behavior which is why Razor specifically chooses to ignore these.

**Comment by HarveyWilliams** [comment]
I just discovered this issue too.

@pranavkm It's fair to say that someone may try to query for an element based on its data attributes, but surely someone could also query for other attributes too?

For example:

CSHTML

```
@{
    string title= null;
}
<a href="https://github.com/aspnet/Razor/issues/978" title="@(title)">Link</a>
```

JS

```
... document.querySelectorAll('[title]') ...
```

Also, the `title` attribute is surely a purely client side attribute, so it should show even if empty?

**Comment by HarveyWilliams** [comment]
However, I get that if this is just gonna cause more issues for people who upgrade and you don't want to introduce unnecessary breaking changes, that makes sense.

**Comment by pranavkm** [comment]
@HarveyWilliams that's entirely true - most attributes, with the exception of the ones processed by TagHelpers, are meant for the client and could be used as a source of making decisions on the client (either JS or CSS). That said, using the presence of presentation \ informational attributes to make decisions on the client doesn't seem like idiomatic JS to me. That said, if you require these values to be rendered, you could always use empty strings (`string title = ""` or title="@(title ?? "")".

**Comment by Eilon** [comment]
For the reasons @pranavkm and @NTaylorMullen mention, we are not planning to change this behavior.
