### ISSUE TITLE
Discuss removing DisposableAction to discourage bad use.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#98]
https://github.com/aspnet/Razor/pull/86#discussion_r16626731

**Comment by Eilon** [comment]
It looks like in Razor Evolution this type moved into a Legacy parser folder: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Evolution/Legacy/DisposableAction.cs

Does that mean this issue will be resolved when we switch to Evolution?

**Comment by NTaylorMullen** [comment]
Nope, still an "issue". If/when we re-do the parser this issue will go away. I'd close it since the only time we'd move away from it is on a parser re-write.
