### ISSUE TITLE
DirectiveDescriptorBuild should throw for directives that wouldn't be parsed correctly

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#981]
For instance `DirectiveDescriptorBuilder.Create("my-directive").Build()` works correctly, but the parser requires an identifier token to be a descriptor name.

**Comment by rynowak** [comment]
Wouldn't this parse as `@my-directive`? This seems totally legal and reasonable to me.

**Comment by NTaylorMullen** [comment]
It could, but that's not what we've allowed in Razor in the past. We should enforce a convention. Up till today we've followed the camel case convention for Razor directives, i.e. `@addTagHelper` not `@add-tag-helper`

**Comment by pranavkm** [comment]
I think it parsed it as two separate tokens when I tried this in a test. We should either support it in the parser or throw ahead of time. I assumed we were camel casers, hence the work item.

**Comment by pranavkm** [comment]
tl,dr: 🐫 > 🐍

**Comment by rynowak** [comment]
Ah I see. We should define the set of characters that are allowed in directives and validate that. Conventions are just conventions, not rules.

**Comment by rynowak** [comment]
For now I'm only going to allow letters here. If someone comes up with a killer use case later we can make it full c# identifiers.

**Comment by rynowak** [comment]
b17e506ce83007bddd7838e9a71958bc002f7660
