### ISSUE TITLE
Figure out a way to build the VSIX project from VS

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#986]
Building the VSIX from VS often fails with 

```
Microsoft.VisualStudio.RazorExtension -> E:\Razor\Razor-dev\tooling\Microsoft.VisualStudio.RazorExtension\bin\Debug\Microsoft.VisualStudio.RazorExtension.dll
Microsoft.VSSDK.BuildTools.15.0.25901-RC\tools\VSSDK\Microsoft.VsSDK.targets(945,5): error : CreatePkgDef : error : ProvideBindingRedirectionAttribute: Invalid value specified for NewVersion.
```

One cause might be that the VSIX targets net46 while the other projects target net451. We could try targeting net46 in other projects to make this issue go away.

**Comment by rynowak** [comment]
We resolved this by adding a net46 target to the projects that we ship in VS.
