### ISSUE TITLE
DefaultDirectiveIRPass removes @model nodes from Mvc

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#989]
Mvc visits the document multiple times to infer the model. With the model gone, it's only available the first time Mvc queries for it.

**Comment by pranavkm** [comment]
Super hacky workaround in Mvc that needs to be removed once I figure out how this needs to be fixed: https://github.com/aspnet/Mvc/commit/bc3a741eee40e39425016943a2253c39fc887d17#diff-514dda9b9f77b844575a122166854526R45

**Comment by rynowak** [comment]
@ajaybhargavb - removal of directives is a lowering concern, it needs to be in the last set of IR passes.

**Comment by ajaybhargavb** [comment]
@rynowak, yes I am aware of this. I have the fix for this locally and generated code (in this PR https://github.com/aspnet/Mvc/pull/5776) and it works fine. I'll send a PR.

**Comment by ajaybhargavb** [comment]
On a related note, calling `GetModelType()` here https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Host/InjectDirective.cs#L33 actually invokes `ModelDirectivePass` before we intend it to run or at least it runs twice. We should probably fix it so that it is only called once.

**Comment by pranavkm** [comment]
Isn't it running the visitor, not the pass?

**Comment by ajaybhargavb** [comment]
@pranavkm, yes. I take that back.

**Comment by rynowak** [comment]
@ajaybhargavb is this fixed?

**Comment by ajaybhargavb** [comment]
This will be fixed as part of https://github.com/aspnet/Razor/pull/996

**Comment by ajaybhargavb** [comment]
8ac5468714ca68cc69cbf801b85e5f32d8d53b23
