### ISSUE TITLE
Create a separate package for the Razor integration testing infrastructure

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#991]
From https://github.com/aspnet/Mvc/pull/5776#discussion_r100618230, we want to re-use some of the integration testing infrastructure like `LineMappingSerializer` in Mvc.

**Comment by NTaylorMullen** [comment]
Already have one: https://github.com/aspnet/Razor/tree/dev/shared

**Comment by rynowak** [comment]
207f40f92de9e51ba0df561872ec180927eb10d1
