### ISSUE TITLE
Split IRazorIRPhase into multiple Phases

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#993]
Currently `IRazorIRPhase` contains all passes that do three distinct things as mentioned here https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Evolution/RazorIRPass.cs#L27. We instead want to have them run as their own phase.

**Comment by rynowak** [comment]
yes we do 👍

**Comment by ajaybhargavb** [comment]
8ac5468714ca68cc69cbf801b85e5f32d8d53b23 and aspnet/Mvc@38e1e7d14ea2375ebf8427d8764e54a73d213a47
