### ISSUE TITLE
what's failing kestrel to run on heroku 

### ISSUE THREAD

**Issue by halter73** [aspnet/Razor#994]
_From @AbhimanyuAryan on February 10, 2017 23:12_

I have created an new asp.net core project and it runs on locally but fails when deployed to heroku. Please see this issue and help me understand this problem. What's causing this [issue](https://github.com/friism/dotnet-buildpack/issues/4) 

_Copied from original issue: aspnet/KestrelHttpServer#1357_

**Comment by ajaybhargavb** [comment]
@AbhimanyuAryan, could you post both the project.json contents here? Or better yet if possible could you upload both projects to Github and share the link?

**Comment by AbhimanyuAryan** [comment]
@ajaybhargavb link to repo 

repo generated by yeoman: https://github.com/AbhimanyuAryan/ivdstudios
repo generated by dotnet: https://github.com/ivdstudios/DotNetCoreMVC-LinuxMint

**Comment by pranavkm** [comment]
@AbhimanyuAryan, by default, the CLI uses the folder name as the output assembly name. When deploying the Heroku, it looks like it's checking out the application in a randomly named directory: `log  : Restoring packages for /tmp/tmp.d4Qf6iTUHZ/app/project.json...`

Try specifying the `outputName` in your `project.json`:

```
{
  "buildOptions": {
    "outputName": "ivdstudios"
     ...
  }
```

**Comment by Eilon** [comment]
@AbhimanyuAryan can you let us know if this worked for you? Thanks!

**Comment by pranavkm** [comment]
To add to this, updating to the csproj should also solve this issue. The default value for the project name is inferred from the project file name (`MyApp.csproj`) and not the directory. You have the ability to change this value using `AssemblyName`, but where project is checked out shouldn't affect your output binary name.

**Comment by AbhimanyuAryan** [comment]
@Eilon no I still can't figure out. @pranavkm I'm have a .csproj project. What do you think should I add here? 

```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.1" />
  </ItemGroup>
  
  
</Project>
```

**Comment by Eilon** [comment]
@AbhimanyuAryan can you share your full updated app on GitHub, plus also what current error(s) or behavior(s) you're getting?

**Comment by pranavkm** [comment]
@AbhimanyuAryan feel free to reopen this work item once you have a repro we could try somewhere. It's difficult to determine much from the details you've provided.
