### ISSUE TITLE
Prevent LOH allocations when constructing Razor source documents

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#997]
Today we Create our Razor documents one way. We should inspect the size of the stream we're reading and buffer it incrementally to avoid LOH allocations. This is similar to what Roslyn does: https://github.com/dotnet/roslyn/blob/4799250ab7adf1e8ca39d79961fcd4cbcb96fa1f/src/Compilers/Core/Portable/Text/SourceText.cs#L127-L131

**Comment by rynowak** [comment]
Fixed by dee8d86. Thanks again @Yves57
