### ISSUE TITLE
Add an equivalent of RazorTemplateEngine

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#999]
We need a simple to use, customizable facade for codegen. This is the equivalent of `RazorTemplateEngine` in the old Razor codebase. 

This should combine the `RazorEngine` and `RazorProject` abstractions.

Once this is built we should use it everywhere Razor is used.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Razor/commit/a6d611aecd6ab9d2603dd63009595bc502fe1850.

Follow up to remove reference: https://github.com/aspnet/Razor/pull/1034.
Spoke to @prafullbhosale about Scaffolding's use of Razor 1.0.4. and we decided to wait a bit before touching that.
